### ISSUE TITLE
希望能消除一些命令的歧义

### ISSUE THREAD

**Issue by Hexhu** [Chuyu-Team/Dism-Multi-language#1]
解密微软在线提供ESD文件
    ’在线提供‘是修饰“ESD文件”吗？我的理解：解密微软在网上提供的ESD文件
为映像重新添加引导。
    添加的是‘引导文件’咩？是的话我就翻成‘add entry to bootloader’之类的

**Comment by mingkuang-Chuyu** [comment]
解密微软在线提供ESD文件 确实错了， 正确的是    解密微软在线提供的ESD文件

另外 为映像重新添加引导  ，添加的是‘引导文件’ 。这个表达大众是可以理解的，反正现在的人都是误解的，说的太专业 大家反而看不懂了。

**Comment by mingkuang-Chuyu** [comment]
感谢支持，已经修正中文问题，将在下个版本中推送所有的Dism++用户。感谢支持
