### ISSUE TITLE
使用Dism清理后把TIMQQ所有的图片都删了

### ISSUE THREAD

**Issue by w371987114** [Chuyu-Team/Dism-Multi-language#100]
所有之前的聊天记录图片都被删了，文字记录还在
望解决

**Comment by mingkuang-Chuyu** [comment]
抱歉…… 但是 能否告知Dism++版本号?

**Comment by w371987114** [comment]
由于每次打开Dism都会自动更新，所以我已经不记得是哪个版本了
但是我从我QQ上看到的现有的聊天图片最早的是5月11日的，应该就是在5月11日的前两天打开Dism更新的那个版本

**Comment by mingkuang-Chuyu** [comment]
Hi，我没发现此问题啊。Dism++并不清理聊天记录之类的。你是不是还用了CCleaner清理？
Dism++就清理一些 %AppData%里面的AndroidAssist、AndroidServer、Logs、TXSSO以及WinTemp。
而聊天记录有关的貌似都在我的文档里面。但是Dism++并没有相关规则……

**Comment by w371987114** [comment]
不好意思误会了，我刚刚看了一下
我电脑用的火绒安全的垃圾清理功能确实会扫描出TIM的聊天图片，如果我用它清理了的话可能会导致这个问题
我提错issue了

**Comment by mingkuang-Chuyu** [comment]
没关系，发现问题就好
