### ISSUE TITLE
网站没啦？

### ISSUE THREAD

**Issue by nlzq** [Chuyu-Team/Dism-Multi-language#1007]
官方没了么？
![image](https://user-images.githubusercontent.com/95120835/177282646-dec508a6-09bc-4f3c-8163-c8abcc9aa77b.png)

想看看文档来着，GitHub 上面没找到

**Comment by jieran233** [comment]
> 后记
由于不可抗力因素 chuyu.me 网站的备案掉了，因此无法访问。
由于不可抗力因素 Dism++ D 群被封，于是创建了 Dism++ E 群，群号为 361689191
如果不希望在 QQ 群内进行讨论，也可以加入 Telegram 频道了解相关信息，链接为 https://t.me/dismplus

<from [https://github.com/Chuyu-Team/Dism-Multi-language/releases/tag/v10.1.1002.1](https://github.com/Chuyu-Team/Dism-Multi-language/releases/tag/v10.1.1002.1)>

**Comment by Sunbangyan233** [comment]
没了，你可以在[Github](https://github.com/Chuyu-Team/Dism-Multi-language/tree/master/www.chuyu.me/zh-Hans/library)上找到源文档。
这是时光机保存的页面，也可以用。[帮助文档](https://web.archive.org/web/20210923014728/https://www.chuyu.me/zh-Hans/Document.html?file=start.md)
