### ISSUE TITLE
更改更新设置后会出现这个

### ISSUE THREAD

**Issue by Sense25** [Chuyu-Team/Dism-Multi-language#102]
![screenshot_18](https://cloud.githubusercontent.com/assets/28778394/26501171/5590e674-426b-11e7-849a-2e7293f9a46d.jpg)
可不可以顺道把这个也隐藏了

**Comment by mingkuang-Chuyu** [comment]
能上图吗？

**Comment by mingkuang-Chuyu** [comment]
终于看到了…… 原来是这个 啊。这个是无解的，设置了策略后就会这样。  无解……
