### ISSUE TITLE
？

### ISSUE THREAD

**Issue by VMwareEFI** [Chuyu-Team/Dism-Multi-language#1036]
我试图查看帮助文档
不过.......
我怀疑是不是跑了：（
![image](https://user-images.githubusercontent.com/109196429/210927864-345ba748-6dcb-42db-b59f-8a43f0e1b28b.png)
![image](https://user-images.githubusercontent.com/109196429/210927894-00691c89-0a09-4f9c-83ff-e20cb8fa923e.png)

**Comment by Sakura-wcs** [comment]
软件都没有收费的项目……何来跑了一说？

**Comment by zevlaoxie2010** [comment]
dism.cf

**Comment by zevlaoxie2010** [comment]
网站被搞了

**Comment by VMwareEFI** [comment]
感谢回复：）
