### ISSUE TITLE
请问Debian使用DD装windows提示无引导是什么原因

### ISSUE THREAD

**Issue by laoshuge** [Chuyu-Team/Dism-Multi-language#1039]
![QQ截图20230118215738](https://user-images.githubusercontent.com/123370853/214025221-20b8aa36-b3c7-4263-8107-7df41cdf0ecb.png)

请问Debian使用DD装windows提示无引导是什么原因

**Comment by haotian2004** [comment]
6

**Comment by haotian2004** [comment]
你太会了

**Comment by haotian2004** [comment]
用dd安装windows

**Comment by mingkuang-Chuyu** [comment]
听不懂。
