### ISSUE TITLE
10.1.1002.2版本扫描更新出错

### ISSUE THREAD

**Issue by RatinCN** [Chuyu-Team/Dism-Multi-language#1056]
![image](https://user-images.githubusercontent.com/55521781/233112748-1b08e625-146f-4c23-97dd-4bd39725f0ec.png)

10.1.1002.2版本 “更新管理” - “扫描” 功能出错，如上图，提示“系统找不到指定的文件”。
操作系统为Windows 11 22h2 x64，同个环境下使用上一版本10.1.1002.1工作正常。

**Comment by RatinCN** [comment]
跟了下，是找不到Config\wsusscn3.cab文件导致，将上一版本程序检测更新时自动下载的wsusscn3.cab复制过来即可

**Comment by mingkuang-Chuyu** [comment]
wsusscn3.cab 暂时已经停止更新，具体何时恢复没有预期，此类问题暂不处理。
