### ISSUE TITLE
Integrated ВСD boot menu Error 

### ISSUE THREAD

**Issue by AANNOONNIIMM** [Chuyu-Team/Dism-Multi-language#1057]
Can't create system  bootloader ,changed disks increased the size of disks does not help Nothing.
Thank you.

![Configuring Windows RE    error](https://user-images.githubusercontent.com/132037890/235056431-72563f8f-2a63-4f58-b6c8-b0b0b7591dcc.PNG)
![error Dism](https://user-images.githubusercontent.com/132037890/235056443-249dd53c-3a64-4e61-8a81-3453aabf7b0b.PNG)

**Comment by mingkuang-Chuyu** [comment]
winre.wim has been lost.
