### ISSUE TITLE
sutwizard标准模式的没有使用说明，用一些集成的运行库包用快速模式制作的安装脚本会导致在部署系统时出现错误

### ISSUE THREAD

**Issue by wxs2011** [Chuyu-Team/Dism-Multi-language#1058]
如题，当我想制作定制系统时，使用Sut制作安装脚本，制作单独的运行库如VC++2015 x86安装脚本，然后添加到wim中后再安装系统是不会有问题，当制作VC++集成包的安装脚本后，制作成WIM安装系统时就会出现错误，导致系统部署失败；制作大型点的软件安装脚本也是如此；想尝试一下sut脚本制作标准模式，但是不知道标准模式的使用方法，或者解决快速模式制作问题，谢谢

**Comment by mingkuang-Chuyu** [comment]
没有，这个功能太复杂了。说明也很难去解释。 索性就直接废除了。
