### ISSUE TITLE
清理 被取代winsxs组件出错

### ISSUE THREAD

**Issue by clfsoft** [Chuyu-Team/Dism-Multi-language#109]
环境:windows 7 sp1 
Dism++.log
Dism++	成功启动，程序版本: 10.1.27.1，CBS抽象层: 10.1.27.1，Host版本：6.1.7601.23796
操作:空间回收 ,清理 被取代winsxs组件
        扫描的显示有8.7g,然后按下清理.
问题: UI显示出错.然后log文件里头啥都没有

**Comment by clfsoft** [comment]
画面截图
![clean](https://cloud.githubusercontent.com/assets/1608414/26710459/ff9376e0-4794-11e7-9d93-ca87484d8974.png)
![scan](https://cloud.githubusercontent.com/assets/1608414/26710460/ff9c1c3c-4794-11e7-9461-4dad5347a8a0.png)

**Comment by mingkuang-Chuyu** [comment]
请提供具体错误信息，谢谢…… 提示错误后 点击错误项目即可

**Comment by clfsoft** [comment]
![error2](https://cloud.githubusercontent.com/assets/1608414/26770018/64d0cef8-49ee-11e7-93e6-9a5e236d5451.png)

**Comment by mingkuang-Chuyu** [comment]
Hi,此功能只有原版系统才能使用…… 一些精简版系统无法使用此功能……
请确保使用了原版Windows 7操作系统

谢谢

**Comment by clfsoft** [comment]
使用的是原版系统,用msdn版本安装的.

**Comment by mingkuang-Chuyu** [comment]
可以加我QQ 343183163 谢谢 我需要远程看看环境……

**Comment by clfsoft** [comment]
进一步检查发现系统的添加windows组件出现白页面.重新升级安装了系统,一切正常了.
多谢了.
