### ISSUE TITLE
建议添加清理条目 Nvidia Geforce Experience 下载及安装缓存

### ISSUE THREAD

**Issue by Ailick** [Chuyu-Team/Dism-Multi-language#11]
使用Nvidia Geforce Experience更新自身或驱动程序时会在下列位置产生缓存，并不会自行清理

当前操作系统路径 %PROGRAMDATA%\NVIDIA Corporation\Downloader\

绝对路径（仅当操作磁盘符为C时） C:\ProgramData\NVIDIA Corporation\Downloader\

经多次测试，删除此文件夹下所有内容后不存在任何异常问题

**Comment by mingkuang-Chuyu** [comment]
谢谢 提供，已经添加此规则，请耐心等待 新的数据库推送
    <Item Name="#英伟达驱动安装包（by Ailick）" Level="1">
      
      <Description>#Nvidia Geforce Experience更新程序时产生的安装包。</Description>
      <Group>#临时文件</Group>
      <Scan>
        <Applicable>
          <FileExist FilePath="%PROGRAMDATA%\NVIDIA Corporation\Downloader"/>
        </Applicable>
        <Activate>
          <General RootPath="%PROGRAMDATA%\NVIDIA Corporation\Downloader"/>
        </Activate>
      </Scan>
    </Item>
