### ISSUE TITLE
如何更改 Dism++ 的 dism 位置（例如 ADK）？

### ISSUE THREAD

**Issue by TK50P** [Chuyu-Team/Dism-Multi-language#1102]
你好，我有一个问题
我在 Windows 7 上下载并安装了 ADK，如何更改 dism++ 的 dism 位置？
我不想在 system32/syswow64 上替换较新版本的 dism。

**Comment by MouriNaruto** [comment]
DISM++ 不依赖 DISM，而是直接使用 CBS，DISM 也是基于 CBS 实现的

毛利

**Comment by TK50P** [comment]
那么清理WinSxS的功能是用CBS而不是用Dism来实现这一点吗？

**Comment by mingkuang-Chuyu** [comment]
> 那么清理WinSxS的功能是用CBS而不是用Dism来实现这一点吗？

是的，Dism++不依赖Dism组件，而是跟Dism一样直接基于CBS构建。使用Dism++时不需要去关注Dism是否是新版本。
