### ISSUE TITLE
Windows 10 1703扫描不出最新累计更新

### ISSUE THREAD

**Issue by Roger-WIN** [Chuyu-Team/Dism-Multi-language#111]
用GImageX装载映像，然后用Dism++进行编辑。在当前系统为最新的情况下，对挂载的映像检查更新，会检查不到更新或者显示不全。如，当前系统为最新的10.0.15063.332，挂载的映像为10.0.15063.0，检查更新时只能检测出Adobe Flash Player的安全更新甚至什么都检测不出。

**Comment by mingkuang-Chuyu** [comment]
应该不存在此问题，建议你详细说明系统信息

另外最好能远程看看环境……

**Comment by mingkuang-Chuyu** [comment]
谢谢 确实存在此问题，只是不是你说的问题，而是Windows 10最新补丁扫描不出来……

**Comment by mingkuang-Chuyu** [comment]
反正者 +丶预谋

**Comment by mingkuang-Chuyu** [comment]
已经确认，Windows 10采用双分支方案，当用户未启用测试分支时，将扫描不出更新。

**Comment by Roger-WIN** [comment]
我这边是只能扫描出Flash Player的补丁，扫描不出Windows 10累积更新的补丁。有时连Flash Player的补丁都扫描不出来。

来自 Outlook for Android 客户端

________________________________

**Comment by Roger-WIN** [comment]
对了，在测试1607的家庭中文版时，发现一个补丁都扫描不出来。🙃

**Comment by Roger-WIN** [comment]
测试分支？那要怎么启用？

**Comment by mingkuang-Chuyu** [comment]
Dism++ Beta 10.1.2000.30
已经修复此问题

**Comment by mingkuang-Chuyu** [comment]
正式版 10.1.1000.0也已经修复此问题，关闭这个问题
