### ISSUE TITLE
语言文件打包之后发现不好改了

### ISSUE THREAD

**Issue by suwakowww** [Chuyu-Team/Dism-Multi-language#112]
做 #110 的时候发现的
现在添加（或者说加回来）的**语言选择**貌似只针对**压缩的语言包**（即 .zip 文件，里面只包含所选择语言的 xml 文件）生效，对**解压后的语言包**（即之前未压缩的 .xml 文件）不生效，不过可以使用 zip 压缩软件“自行制作”语言选项出来。
![1](https://user-images.githubusercontent.com/6368936/27004336-3056c29a-4e3a-11e7-945b-41eaa36c74ca.PNG)
这个是**仅存在 .xml 文件**的情况
![2](https://user-images.githubusercontent.com/6368936/27004346-59510368-4e3a-11e7-9b98-48800777b59f.PNG)
这个是**含有 .zip 文件**的情况，当然 .zip 文件使用 7-zip 生成的，就简单地打了个包

**Comment by mingkuang-Chuyu** [comment]
Hi, 这个不是问题，而是因为xml已经不再支持……现在开始将慢慢迁徙到.zip
不过考虑到……大伙测试翻译是否正常。xml支持可以添加

**Comment by mingkuang-Chuyu** [comment]
确认，10.1.2001.30解决此问题。另外以后只有Beta分支Dism++支持原有xml格式，方便大家修改配置，正式版将完全移除xml支持。
