### ISSUE TITLE
空间回收功能，勾选项扫描后消失

### ISSUE THREAD

**Issue by OrcaIsDolphins** [Chuyu-Team/Dism-Multi-language#1120]
使用的版本 Dism++10.1.1002.1B
Windows 11 家庭中文版  22631.4317

空间回收功能中，我勾选“酷狗音乐老版本备份”，然后点扫描，在扫描结果里面，这个选项被隐藏了，需要点一次刷新才能显示，但刷新之后扫描结果会被重置。其他勾选项没测试过，不确定其他选项是否会出现这个问题
![image](https://github.com/user-attachments/assets/160e94a0-b83a-4c0b-8083-aaa9b26c46c7)
![image](https://github.com/user-attachments/assets/e5e34787-2d88-4935-9e3e-52e9a930b382)

**Comment by CrazyKDM** [comment]
一般某个项目没有可清理的内容时会在扫描后隐藏
