### ISSUE TITLE
建议也不要添加.exe

### ISSUE THREAD

**Issue by Sense25** [Chuyu-Team/Dism-Multi-language#113]
![1](https://user-images.githubusercontent.com/28778394/27005014-7d87a50e-4e47-11e7-805e-62d38d9408ad.png)

**Comment by suwakowww** [comment]
估计不行，本来这些优化项算是注册表调整的
正常来说生成的是“文件名 - 快捷方式”的，感觉这个跟显示所有扩展名有关

**Comment by Sense25** [comment]
那么这个功能比较鸡肋啊，还是要手动删除.exe
话说程序猿都是这么晚不睡的吗？😀

**Comment by suwakowww** [comment]
刚好在测文本，隔壁那个就是
已经测试了要配合文件夹选项的“不显示已知文件名的扩展名”使用，自己取舍下吧

**Comment by mingkuang-Chuyu** [comment]
你说错的功能无法实现，因为微软先天不支持你说的功能……

关闭此问题
