### ISSUE TITLE
右键新建崩溃问题

### ISSUE THREAD

**Issue by Sense25** [Chuyu-Team/Dism-Multi-language#114]
实测更改右键设置后取消也无法修正这个问题，系统还原也没办法。Dism貌似也没有重置所有设置选项<a href="https://ibb.co/kNzU55"><img src="https://image.ibb.co/g0ekdQ/2017_06_17_11_39_29.gif" alt="2017_06_17_11_39_29" border="0"></a>

**Comment by mingkuang-Chuyu** [comment]
冒昧的问下  这个问题跟Dism++有什么关系？

**Comment by mingkuang-Chuyu** [comment]
用户自己安装的其他软件不兼容Windows 10所致，关闭这个问题。如需解决可以卸载相关应用程序 或者使用一些右键菜单管理工具取消所有非系统默认的新建文件Shell。
