### ISSUE TITLE
冒昧的问一句，能不能添加一个禁用掉Alt热键的功能，如果可以的话十分感谢

### ISSUE THREAD

**Issue by KobayshiMari** [Chuyu-Team/Dism-Multi-language#117]
额，比如在Ps Ae 或者CSP这种软件（以及绝大多数软件包括office）里面，都会有这样的一个问题。（以Adobe Photoshop举例）当你按下一次Alt键的时候（比如使用了Alt+左键，或者Alt+滚轮）菜单栏会被激活。然后当你下一次按其他键的时候（比如按E切换到橡皮）就会激活菜单“编辑(E)”，而不是激活橡皮。所以这个就很麻烦。Ps有专用的辅助型软件来解决这个问题，但是其他的软件（比如Clip Studio Paint）就没有这种插件（而且那种插件的原理是检测到Alt按下之后再按一下以取消这个状态）。但是我不太了解Windows系统热键的原理（我感觉是系统热键把），所以很希望你们能够稍微……如果不忙的话，稍微研究一下。无论成果如何，我都非常感谢你们这个项目和团队。谢谢

**Comment by mingkuang-Chuyu** [comment]
不可以谢谢，如果真的要解决这都需要写注入插件。目前没有空去维护其他项目
