### ISSUE TITLE
更新管理扫描时，提示“该进程不处于后台模式”

### ISSUE THREAD

**Issue by elfkidwtf** [Chuyu-Team/Dism-Multi-language#118]
最新版本，更新管理，点击扫描，弹出对话框“该进程不处于后台模式”

**Comment by mingkuang-Chuyu** [comment]
Hi，其他用户已经反馈了此问题，https://github.com/Chuyu-Team/Dism-Multi-language/issues/92
这是无法下载库文件所致。
请暂时通过www.chuyu.me，手动下载wsuscab2.cab解决此问题（保存到 Conifg\wsuscab2.cab即可）

谢谢
