### ISSUE TITLE
ESD->ISO可以做一个根据版本号自动生成文件名的选项么

### ISSUE THREAD

**Issue by yyjdelete** [Chuyu-Team/Dism-Multi-language#12]
主要是因为强迫症和懒吧, 不然还要去百度一下这个版本的名字是什么, 然后填上去...

**Comment by mingkuang-Chuyu** [comment]
Hi，此功能无法做，因为发布的ESD一般都是不公开原始文件名的（除了极少数几个版本）

那个外国的那个转换工具基本都是自己瞎猜写的，微软实际并为公布对应ISO的文件名

**Comment by yyjdelete** [comment]
其实某种意义上说, 不标准还是比没有强点的。
就算只能精确到15002pro.iso， 比如最近懒得写名字都叫的xx1,xx2,最后看到一堆iso都不知道哪个是哪个。
另外名字也是一个很好的检查esd是否下载正确的方式，昨天下esd的时候下错了，一直安装到最后一步才发现是企业版。。。

**Comment by mingkuang-Chuyu** [comment]
谢谢，你说的也确实有道理…… 这样吧 未来版本程序加个自动名称产生，但是名称仅供参考，并非一定是微软官方的称呼
