### ISSUE TITLE
[建议]增加windows服务优化功能,不常用的服务一件关闭

### ISSUE THREAD

**Issue by lzpong** [Chuyu-Team/Dism-Multi-language#120]
建议增加windows服务优化功能,不常用的服务一件关闭
也可以根据使用率, 开启/关闭存量来建议

**Comment by suwakowww** [comment]
“不优化是最好的优化”
作为服务项，肯定有其设计出来的理由。
只能这样说

**Comment by lzpong** [comment]
但是有很多服务, 其实在工作,生活当中一年可能就用不到一两次, 甚至从来没有用到过的都有,  要其占资源干嘛, win10 启动都占用一两G的内存,一百多进程......

**Comment by mingkuang-Chuyu** [comment]
这个功能可以考虑增加……

**Comment by mingkuang-Chuyu** [comment]
系统优化中已经提供了常用可以安全优化的服务。而服务管理，主要是为了高级应用。如果需要友好使用，可以考虑使用系统优化。
