### ISSUE TITLE
GUI 建議

### ISSUE THREAD

**Issue by kulaLin** [Chuyu-Team/Dism-Multi-language#121]
文字顯示為藍底黑字辨識性稍差，應該為跟TAB一樣的藍底白字。

Dialog window 字體別再用遠古時期的襯線體(Serif)，應採用Vista以上用的UI字體Segoe UI

**Comment by mingkuang-Chuyu** [comment]
Dui字体部分已经更改，至于微软通用窗口相关字体就这样吧。毕竟是微软默认值。

**Comment by kulaLin** [comment]
![sshot-2017-06-26- 16](https://user-images.githubusercontent.com/17091825/27531226-70d30418-5a8e-11e7-8504-83084c392c0d.png)
側邊欄藍底黑字亦是辨識性稍差
