### ISSUE TITLE
win7 空间回收会删除硬链接

### ISSUE THREAD

**Issue by quegfeng** [Chuyu-Team/Dism-Multi-language#122]
不知道是否个案。win7用mklink创建的硬链接会被删除（Programdata目录映射到d盘自建的Programdata）但并未在空间回收项目中看见有关删除硬链接或无效快捷键的控制开关，请作者确定。我回去试试windows10看看会不会再反馈。程序版本为10.1；貌似旧版本也一样。

**Comment by mingkuang-Chuyu** [comment]
此问题我需要确认下 谢谢

**Comment by mingkuang-Chuyu** [comment]
已经确认，Dism++并不会删除符号链接。可能是其他程序导致了此问题。关闭此问题，如果你觉得是Dism++的问题可以重新打开此问题。到时我需要看环境了了解一些详细信息。谢谢支持
