### ISSUE TITLE
GUI 藍底黑字

### ISSUE THREAD

**Issue by kulaLin** [Chuyu-Team/Dism-Multi-language#123]
左側邊欄及停留該項目藍底黑字辨識性不好，傷眼
![sshot-2017-06-26- 16](https://user-images.githubusercontent.com/17091825/27531311-b00adba6-5a8e-11e7-8773-6d7120ef741b.png)
![sshot-2017-06-26- 36](https://user-images.githubusercontent.com/17091825/27543480-dcb2c532-5abc-11e7-9a3c-338747384bb2.png)

**Comment by mingkuang-Chuyu** [comment]
嗯 到时可以统一更改下，你在找找其他地方

**Comment by mingkuang-Chuyu** [comment]
可以简单改的地方都已经改了。其他地方需要编写代码。实现，就暂时不改了。
Dism++Beta 10.1.2001.41以及更改版本生效
