### ISSUE TITLE
GUI 閃爍

### ISSUE THREAD

**Issue by kulaLin** [Chuyu-Team/Dism-Multi-language#125]
懸停在該項目上會閃爍，請修復

![honeycam 2017-06-26 22-12-42](https://user-images.githubusercontent.com/17091825/27543582-29ff4b12-5abd-11e7-8da2-5074f3effb6c.gif)

**Comment by mingkuang-Chuyu** [comment]
我知道这个问题，但是这个问题不修了，Dui本身框架限制，不然等多少 ms后 悬浮框 就会消失。
我觉得消失反而更加影响体验。至于UI方面暂时不会再有框架调整。
