### ISSUE TITLE
空间回收后桌面图标排序混乱/移位

### ISSUE THREAD

**Issue by NeROTor** [Chuyu-Team/Dism-Multi-language#126]
win10 家庭版，26/27两天使用空间回收功能后，桌面图标会跑动，而且没有办法直接拖回原位。

**Comment by mingkuang-Chuyu** [comment]
Hi，你不清理图标缓存相关项目即可。

**Comment by NeROTor** [comment]
谢谢，下次清理我会注意的
发自网易邮箱大师
在2017年06月27日 09:42，mingkuang 写道： Hi，你不清理图标缓存相关项目即可。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Chuyu-Team/Dism-Multi-language","title":"Chuyu-Team/Dism-Multi-language","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Chuyu-Team/Dism-Multi-language"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mingkuang-Chuyu in #126: Hi，你不清理图标缓存相关项目即可。"}],"action":{"name":"View Issue","url":"https://github.com/Chuyu-Team/Dism-Multi-language/issues/126#issuecomment-311228780"}}}
