### ISSUE TITLE
建议控制面板-驱动管理显示每个驱动的占用空间，还能排序找最占空间的驱动

### ISSUE THREAD

**Issue by cafrew** [Chuyu-Team/Dism-Multi-language#127]
如题，谢谢大神开发了这个软件，我是普通用户，经常用，感觉清理空间很方便。
这次大胆地提出建议，如果有不现实的地方请大神们多包涵:-P

**Comment by mingkuang-Chuyu** [comment]
你说的都很好做，主要是……做了有什么意义，有怎么样的使用场景？

如果说你想删除不需要的驱动，Dism++本身就有过期驱动清理……一键即可清除……

**Comment by mingkuang-Chuyu** [comment]
用户长时间无应答，关闭比问题。如有需要可以重新打开此问题。谢谢
