### ISSUE TITLE
不支持部分ISO

### ISSUE THREAD

**Issue by Lyqqt** [Chuyu-Team/Dism-Multi-language#132]
1.使用Dsim++的系统还原插件：选择微PE工具箱导出的ISO文件，会提示“试图加载格式不正确的程序”
2.若提取出WIM选择，则提示“数据无效”
//微PE工具箱官方要求使用UltraISO进行操作（即还原整个分区，不能像Dism++仅还原某一分区），所以可能导致Dism++无法读取这种ISO
以上纯属意淫，引起关注，靠各位技术大佬深入摸索

**Comment by mingkuang-Chuyu** [comment]
Hi，Dism++所支持的ISO文件只能是跟微软官方形式一致的ISO文件。
其他第三方自定义标准，程序也不可能去做兼容…… 不然兼容都是没完没了的。说难听点，他们怎么不兼容微软原版的ISO……
