### ISSUE TITLE
备份系统时提示指定的环境无效

### ISSUE THREAD

**Issue by RichardWinters** [Chuyu-Team/Dism-Multi-language#133]
系统环境：       
  Operating System: Windows 10 专业版 64-bit (10.0, Build 15063) (15063.rs2_release.170317-1834)
                 Language: Chinese (Simplified) (Regional Setting: Chinese (Simplified))
      System Manufacturer: LENOVO
             System Model: INVALID
                     BIOS: J1ET37WW (1.16 )
                Processor: Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz (4 CPUs), ~2.5GHz
                   Memory: 8192MB RAM
      Available OS Memory: 8094MB RAM
                Page File: 5210MB used, 4163MB available
              Windows Dir: C:\Windows
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: Using System DPI
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Supported
           DxDiag Version: 10.00.15063.0000 64bit Unicode

问题截图：
![qq 20170708202419](https://user-images.githubusercontent.com/11906517/27985329-73b8e35a-641b-11e7-91fe-2f79b068d98a.jpg)

日志：2017-07-08 20:17:02, Info	PID=4268 TID=1472, Dism++	成功启动，程序版本: 10.1.1000.1，CBS抽象层: 10.1.1000.0，Host版本：10.0.15063.0  （真没了……）

# **求大佬解答，感激不尽~**

**Comment by mingkuang-Chuyu** [comment]
Hi,希望能加我QQ，我看看谢谢（343183163）

**Comment by SeptimusX** [comment]
存在类似情况。

Windows 10 1703，安装了Ubuntu Subsystem后出现，怀疑与此相关。

**Comment by RichardWinters** [comment]
@SeptimusX 我不觉得是这个Ubuntu的问题，我电脑上也安装了Ubuntu子系统，一直以来备份都没问题，这是近几天才出现的。而我电脑并没有新安装什么软件……

**Comment by RichardWinters** [comment]
@mingkuang-Chuyu 已发送好友请求，请通过~

**Comment by mingkuang-Chuyu** [comment]
Linux子系统使用过程中  会创建一些奇葩的文件，这将导致程序无法访问那些文件，而导致备份失败。

这个是wimgapi的已知问题。

另外 我没收到好友请求啊，如果你加了我 建议喊我下。 谢谢

**Comment by mingkuang-Chuyu** [comment]
用户长时间未加我好友，等加我好友后可以重新打开此问题。同时这个问题很可能是Windows Linux子系统问题，因此暂时关闭此问题。

**Comment by lzghzr** [comment]
1709 有同样问题，需排除
> Users\\*\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc
