### ISSUE TITLE
Dism++调整语言疑似错误

### ISSUE THREAD

**Issue by mingkuang-Chuyu** [Chuyu-Team/Dism-Multi-language#135]
反馈者：8511010
en_windows_10_enterprise_2016_ltsb_n_x64_dvd_9057894，挂载后调整为中文依然显示英文。

临时解决方案：暂时使用Dism命令或者直接下载zh-CN ISO。

**Comment by mingkuang-Chuyu** [comment]
未能重现问题……  可能是用户本身操作问题

**Comment by suwakowww** [comment]
说起来这个...之前下了个15063 s版（cloud版）想加个中文语言进去，用dism++加语言包很顺利，然后再调了语言后把这个wim放回去镜像里面做安装盘镜像，再然后...用刚制作的安装程序装完才发现进去还是英文的（oobe，桌面等），不过中文语言包是倒是装上了，直接换语言就行

**Comment by mingkuang-Chuyu** [comment]
@suwakowww  这是因为还需要修改配置文件

ISO\sources\lang.ini
以及boot.wim@2\sources\lang.ini

[Available UI Languages]
zh-CN = 3
[Fallback Languages]
zh-CN = en-us

**Comment by mingkuang-Chuyu** [comment]
关闭此问题，用户无法远程同时本地无法复现
