### ISSUE TITLE
DISM++批量增加驱动（可能包含未签名驱动）打包好的Wim，在启动时会蓝屏

### ISSUE THREAD

**Issue by Cyclonekid** [Chuyu-Team/Dism-Multi-language#136]
想做个集合万能驱动的Boot.wim，然后方面网络部署安装Windows，使用Dism++集合万能驱动到Boot.wim内（可能包含未签名驱动），然后使用该Boot.wim为引导镜像会直接导致系统蓝屏，但是使用Windows自带的Dism，打包同样的驱动进去（增加驱动时使用了ForceUnsigned参数），制作好的Wim启动一切正常·············

**Comment by mingkuang-Chuyu** [comment]
已经确认，在兼容模式下启动Dism++会导致此问题。

临时解决方案，启动Dism++直接启动即可。不要在设置勾选什么兼容模式。

**Comment by verdy-p** [comment]
could you provide basic translation to English in these bugs ? Chinese is notoriously known to be difficult to parse an interpret,  even automatic translators have problems (lot of confusion between terms, and confusion in grammar, creating too many non-sense sentence).

Please make an effort, even if your English is not perfect it will ALWAYS be better than automatic translators. Provide at least a summary sentence: very few people using Dism actually can read Chinese thanks!

Note: this should also be done in change logs. Not all translations are needed, but English should be easier to interpret or retranslate to other languages.

**Comment by mingkuang-Chuyu** [comment]
@verdy-p Yes~~

**Comment by mingkuang-Chuyu** [comment]
暂时开打此问题吧，以免我忘记修复了。

**Comment by mingkuang-Chuyu** [comment]
Beta版已经添加兼容模式检测
