### ISSUE TITLE
Using DISM++ in scripts

### ISSUE THREAD

**Issue by Slavah80** [Chuyu-Team/Dism-Multi-language#137]
Hi,
Looking for a way to run this application as a part of script in order to get some cleanings on the multiple machines. Can not find any details about this feature. Sorry if incorrect place selected to place my question.

Thank you for the support.

**Comment by mingkuang-Chuyu** [comment]
Could  you used C/C++? If you can, Dism++have Dism++ API，you could used Dism++ API do your work.

**Comment by Slavah80** [comment]
Hi,
Nope, in my case I am using the application (dism++) which is already compiled to executable format. Have no knowledge in application development, to be honest. That's why looking for a way to use your application if this possible thorough.;))

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mingkuang-Chuyu** [comment]
关闭此问题，这个不是Dism++ BUG
