### ISSUE TITLE
挂载 Win7 映像后，检测更新扫描不出新的 .NET Framework

### ISSUE THREAD

**Issue by Roger-WIN** [Chuyu-Team/Dism-Multi-language#138]
挂载 Win8.1 的映像，可以扫描出 .NET Framework 4.5.2 和 4.7，因此可以直接安装。
但是 Win7 就没有扫描出来。只有部署之后直接在 Win7 桌面环境下检测才能扫描出。

**Comment by mingkuang-Chuyu** [comment]
此问题不是问题，因为  Windows 7根本就不支持离线集成4.7

**Comment by Roger-WIN** [comment]
那么，.NET Framework 4.5.2/4.6.1/4.6.2 呢？这些总归没太多问题的吧？为什么也没有？是不支持离线集成吗？

来自 Outlook for Android 客户端

________________________________

**Comment by mingkuang-Chuyu** [comment]
Windows  7是不支持离线集成 4.X的   你不用吧4.X家族所有成员 都来问一遍支持不支持

**Comment by Roger-WIN** [comment]
那好吧，我明白了，谢谢了。

来自 Outlook for Android 客户端

________________________________
