### ISSUE TITLE
最近一直更新失败

### ISSUE THREAD

**Issue by beginWith** [Chuyu-Team/Dism-Multi-language#139]
最近一直更新失败 正版的win10 打开提示有更新 点击确定 会提示"更新出错"

**Comment by mingkuang-Chuyu** [comment]
能给个截图吗？ 我不明白是程序更新 还是数据更新……
还有 Dism++跟正版Windows 10有什么关系？

**Comment by beginWith** [comment]
![2017-07-16_182646](https://user-images.githubusercontent.com/15656166/28246775-71519492-6a54-11e7-96e0-6619fc12088f.png)

**Comment by beginWith** [comment]
以前也有这样的情况 后来我手动下载最新的 自动更新就没出错了 现在自动更新又开始出错了

**Comment by mingkuang-Chuyu** [comment]
麻烦加我QQ 343183163 应该是服务器访问问题

**Comment by beginWith** [comment]
又可以了...什么情况 你们服务器修复了bug?

**Comment by mingkuang-Chuyu** [comment]
可能是近期转移域名到国内的关系吧，，，，那就暂时关闭吧。以后有问题再重新打开
