### ISSUE TITLE
全選功能消失了

### ISSUE THREAD

**Issue by kulaLin** [Chuyu-Team/Dism-Multi-language#140]
以前舊版本是有全選功能，不知為何現今版本將此功能移除
請將此功能回歸
![sshot-2017-07-14- 01-05-28](https://user-images.githubusercontent.com/17091825/28178318-9e88e346-6830-11e7-9593-35187a0c6df0.png)

**Comment by mingkuang-Chuyu** [comment]
这是因为  很多人不动脑筋，想都不想就是个全选。

所以新版本只有全不选 跟默认值，二种，这是希望没个用户都自己选择过去，免得到时又说不知道。另外程序有记忆功能，也就只是第一次需要这样，以后会自动记忆上次使用情况。

**Comment by kulaLin** [comment]
其實可以放在專家模式
這樣不就解決了嗎？

**Comment by mingkuang-Chuyu** [comment]
不能，专家也很多都是伪专家，另外一个个项目选址过去 也不用几秒钟。另外程序的意图是希望大家别不动脑筋就全选，这个才是初衷。不可能为了用户能方便全选 就添加此功能。

**Comment by kulaLin** [comment]
好吧。
我只想要"預覽"全選情況下，會節省多少空間而已。
所以能否推出像是"預覽掃描"的功能
