### ISSUE TITLE
可以吧系统优化加一个配置项吗 保存自己的设置项

### ISSUE THREAD

**Issue by yuehun** [Chuyu-Team/Dism-Multi-language#141]
win10预览版每次都是用Dism进行优化，但是每次都要一个一个设置，可不可以加一个导入上次保存的项，以后直接导入上次的配置

**Comment by mingkuang-Chuyu** [comment]
可以考虑……

**Comment by 2810676203** [comment]
我也是这么想的每次重装系统都要重新设置一次很麻烦-.-有时候真的想保存上一次的设置然后一键操作

**Comment by Roger-WIN** [comment]
对，这个确实很有必要，把自定义配置导出为文件，以后直接导入就行。

**Comment by justwho** [comment]
很需要这个功能！方便每一次重装系统或者做系统定制。

**Comment by MouriNaruto** [comment]
Archived, #707
