### ISSUE TITLE
希望加入windows激活备份和office激活备份

### ISSUE THREAD

**Issue by SaxonLee372324** [Chuyu-Team/Dism-Multi-language#146]
rt，虽然有很多途径来备份，但是dism++直接包括了不是省了好多找其他软件或方法的时间。还请开发者加入此功能。

**Comment by suwakowww** [comment]
好像因为 #39 给砍掉这功能了，估计10.1.1000.1（不含这个版本）以前的版本还有

**Comment by mingkuang-Chuyu** [comment]
主要是windows 10激活还原太麻烦了。Win10跟其他系统不同，有显性版本跟隐性版本。如果备份了直接覆盖容易导致系统激活功能挂掉。再加Windows 10现在貌似也没有太大必要备份激活吧？微软不是直接在线备份么

**Comment by mingkuang-Chuyu** [comment]
用户长时间未回应，关闭此建议，如果有需要  可以重新打开。
