### ISSUE TITLE
备份系统时提示“指定的环境无效”

### ISSUE THREAD

**Issue by BurningRaptor** [Chuyu-Team/Dism-Multi-language#147]
查询log之后发现报错如下：
> 2017-07-21 03:01:06, Info	PID=9668 TID=9960, Wimgapi	\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy6\Users\Administrator\AppData\Local\lxss\rootfs\lib\xtables\libip6t_HL.so 0x0000011A
2017-07-21 03:01:06, Info	PID=9668 TID=9960, Wimgapi	\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy6\Users\Burning\AppData\Local\lxss\rootfs\lib\xtables\libip6t_hl.so 0x0000011A
2017-07-21 03:01:06, Error	PID=9668 TID=9960, Wimgapi	\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy6\Users\Burning\AppData\Local\lxss\rootfs\lib\xtables\libip6t_hl.so 0x0000070D
>
查询得知这个是win10 bash的相关文件，不知道为何会引起报错
Dism++ 版本：10.1.1000.1
Windows 版本：Windows 10 Enterprise 14393.1480

**Comment by BurningRaptor** [comment]
猜测这个和Linux文件名区分大小写而windows不区分有关？
Bash in Windows 里面出现了
> libip6t_hl.so
> libip6t_HL.so
>
但是windows应该不支持这样的命名两个文件的啊

**Comment by mingkuang-Chuyu** [comment]
Windows支持，但是Win32不支持。目前微软的wimgapi会有这样的问题。建议你反馈给微软。

**Comment by dfc643** [comment]
同样的问题，更新 dism++ 之前正常，更新之后报错。
磁盘文件没有变更。

**Comment by BackTrackCRoot** [comment]
是的 早先版本使用正常 新版的备份有问题

**Comment by dfc643** [comment]
之前的版本是 10.1.23.2
日志和一楼一样的，换成旧版后日志冲洗掉了。
旧版备份的 WIM 可以正常恢复使用，
而且 WIM 里面也存在 libip6t_HL.so 和 libip6t_hl.so 都可以解压出来。

**Comment by mingkuang-Chuyu** [comment]
libip6t_HL.so 和 libip6t_hl.so的文件也同时正常恢复？

**Comment by dfc643** [comment]
@mingkuang-Chuyu 刚刚仔细对比了一下，WIM 里面确实存在两个文件，但恢复出来文件内容都变成了libip6t_HL.so，也就是备份错误。

不过希望新版能加一个忽略错误，至少可以备份完成，这点问题（Windows Bash）其实有时候比较无所谓的。

**Comment by BackTrackCRoot** [comment]
对的 感觉Linux子系统 备份不备份 无所谓 重要的Windows系统能备份下来就行

**Comment by mingkuang-Chuyu** [comment]
Users\*\AppData\Local\lxss\

**Comment by BurningRaptor** [comment]
谢谢！

**Comment by dfc643** [comment]
谢谢~

**Comment by BackTrackCRoot** [comment]
谢谢。

**Comment by CNife** [comment]
谢谢，我说怎么突然备份不成功了。

**Comment by mingkuang-Chuyu** [comment]
10.1.1000.31已经修复，默认规则中已经过滤   Users\\*\\AppData\\Local\\lxss

**Comment by JamesLiAndroid** [comment]
我的win10系统保存路径如下：
Users\*\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc

来自win10 专业版1709
