### ISSUE TITLE
删除可选功能后无法进入

### ISSUE THREAD

**Issue by Caiws** [Chuyu-Team/Dism-Multi-language#148]
系统版本：Windows 10 64位；
版本号：1703，OS内部版本15063.483；
机型：联想V470；
CPU：i5-2430M；
问题描述：
1、使用Dism++x6410.0.1000.1 UEFI Firmware专家模式；2、打开可选功能；3、其中功能存在一个"Fix for KB2839636"的功能，大小为0字节；4、删除；5、重启，系统显示正在配置更新；6、再次进入卡在Win标处无限自动重启。

**Comment by mingkuang-Chuyu** [comment]
Fix for KB2839636 是系统的语言包……

按常理，语言包只有一个时也会直接失败。应该是微软新出了什么BUG

建议你反馈给微软。谢谢

**Comment by mingkuang-Chuyu** [comment]
Dism++暂时先临时做个屏蔽……

**Comment by mingkuang-Chuyu** [comment]
确认，15063存在BUG，语言包可以被直接卸载。

Dism++ Beta 10.1.2001.10已经临时屏蔽 Fix for KB2839636。

谢谢反馈，今晚会发布新的正式版，来解决此问题
