### ISSUE TITLE
Drive cleanup errors, clean up virtual devices "NVIDIA Miracast Audio"

### ISSUE THREAD

**Issue by zerozerone** [Chuyu-Team/Dism-Multi-language#149]
20170725
Windows 7 Ultimate SP1 X64 patched 1707
dism++10.1.2000.90 BETA
384.94-desktop-win8-win7-64bit-international-whql-g
nvvadarm.inf_amd64_neutral_7916f6e4193c063d

Drive cleanup errors, clean up virtual devices "NVIDIA Miracast Audio"

**Comment by mingkuang-Chuyu** [comment]
已经修复此问题，针对虚拟设备。Dism++加入了硬件数量统计功能，硬件支持数量<=1时则屏蔽此类驱动。避免虚拟驱动被清理问题。

生效版本：10.1.2001.20
