### ISSUE TITLE
dism++ 驱动管理，列表为空，但是dism /get-drivers却有。

### ISSUE THREAD

**Issue by kokutoukiritsugu** [Chuyu-Team/Dism-Multi-language#150]
![snipaste20170725_203850](https://user-images.githubusercontent.com/5471433/28572441-a095ac6c-7179-11e7-935e-efdf2ba47416.png)
![snipaste20170725_204607](https://user-images.githubusercontent.com/5471433/28572610-5277a476-717a-11e7-8a1e-f2e003bf2d9d.png)

用dism++添加驱动，然后用easysysprep4封装系统，第一第二阶段封装完毕后，用dism++空间回收。
这时候再进驱动管理，列表就是空的。
这个时候把系统拿去安装是不正常的，集成的驱动就跟没集成一样，万能驱动v7在pe下，也不能再次注入。
只能 dism /image:c:\1 /Remove-Driver /driver:xxx 一下，才能重新注入。

感觉是哪里被破坏掉了。

能不能加个检测到这个，并提示删除这些驱动的功能？

**Comment by kokutoukiritsugu** [comment]
另外，原版镜像，这里面是会有这2个驱动的，
列表里面也没有了。
![snipaste20170725_210017](https://user-images.githubusercontent.com/5471433/28573186-600bd65a-717c-11e7-956f-8aa527cef536.png)

**Comment by verdy-p** [comment]
Not an bug in my opinion. You've not checked the box at the bottom, this means that only drivers that are not part of Windows itself are listed.

If you check the box, you'll see drivers installed with Windows itself (from Windows Update if needed), which are not necessarily the latest one, but just WHQL drivers (frequently outdated and not offering the best performance: you should install replacement drivers at least for the audio/video and system bus from nVidia, AMD, and Intel).

Your system just has no supplementary drivers installed (coming from OEM installers, such as those from nVidia or AMD Radeon, of from Intel for audio, video, bus or storage, or Logitech mouse/keyboard, or printer drivers, HD audio, or some suplementary Wifi USB adapters, or custom codec drivers)

Drivers for mouse/keyboard are generally not needed except for additional config panels (showing battery status or allowing custom configuration such as keyboard accelerators and macros or integration with games to dynamically optimize the settings depending on the software you use).

But drivers for RAID controlers are generally needed (Windows itself does not support many of them natively, and some of them may even be needed to boot your system and get access to the storage where the OS is installed and allow boting from it).

Drivers for Ethernet adapters are most often not needed; only some Wifi adapters require their own driver, but you just need the system drivers and not their additional control panels.

Some security tools also require their own drivers for booting and securing the system at boot. But you don't need to backup them: it's just safer to download a recent installer to get the last version from their support website. But you may need them if you need to repair your system and these drivers have encrypted the storage.

Most printer drivers don't need to be backup: those coming with Windows generally work fine (for wellknown manufacturers) and OEM drivers are frequently built only for older versions of Windows (newer versions of Windows are supported directly by WHQL drivers from Windows Update). But you may need them from some advanced panels (such as displaying the status of ink cartridge or better selection of paper formats an special mounting options, or presentation options not built natively in basic Windows drivers).

Other OEM drivers you may see in this panel are those for Android and Apple mobile devices or GPS devices when you connect them on the PC, or special filesystem drivers for synchronization with online storage services on a cloud.

**Comment by mingkuang-Chuyu** [comment]
这部分Dism++跟微软实现不一致，主要是Dism++要改进对精简系统的支持。所以是通过遍历inf文件夹实现的。你的问题应该是你用的封装工具，强行删除了inf文件夹的东西。建议你不用封装工具，单纯用Dism++验证下，应该就没这个问题了。如果情况属实，那么就反馈给你的封装工具吧。让它通过api的方式移除驱动，不要直接删inf。

**Comment by kokutoukiritsugu** [comment]
![snipaste20170727_190026](https://user-images.githubusercontent.com/5471433/28667491-523098da-72fe-11e7-9733-f6689703a2d9.png)

inf是存在的，只是不在列表里面显示了。
而且下面打勾后， 也不在内置列表里。

同样的封装配置，同样的操作。却无法重现了。。。
只是之前的镜像是原版镜像安装-进系统后打补丁，然后做后续封装操作。不知道是从什么时候开始，列表就空了。
这次是挂载 install.wim，dism++打补丁，然后做后续封装操作。注入的驱动，列表里面却都有。

**Comment by kokutoukiritsugu** [comment]
同样的封装配置，同样的操作。却无法重现了。。。
只是之前的是 install.wim 安装，进系统后打补丁，然后做后续封装操作。不知道是从什么时候开始，第三方驱动列表就空了。

这次是挂载 install.wim，dism++打补丁，然后再安装，再然后后续封装操作。注入的驱动，列表里面却都有。

**Comment by mingkuang-Chuyu** [comment]
我是说inf文件夹里没有对应的inf.
Windows/inf/oem*.inf

**Comment by mingkuang-Chuyu** [comment]
有什么软件直接干掉了oem*.inf，导致Dism++不能正常解析驱动。

**Comment by mingkuang-Chuyu** [comment]
另外你的截图水平太高了，刚好不截标题。我都不知道你的Dism++版本号。如果是Dism++ Beta分支，最近更改了一次驱动清理逻辑。不过后来想想也不可能，你都是在封装怎么可能会去用驱动清理

**Comment by mingkuang-Chuyu** [comment]
暂时关闭此问题。如果Dism++真的有问题在重新打开此问题。

谢谢支持
