### ISSUE TITLE
"更新管理"功能增强建议

### ISSUE THREAD

**Issue by watano** [Chuyu-Team/Dism-Multi-language#153]
实在受不了windows自带的更新功能了,能否丰富下更新管理的功能, 完全替换windows自带的? 以下是我的一些小意见,仅供参考:
1. 更新时能否增加insider的fast/slow版本切换? 现在这个功能必须绑定windows live帐号登陆, 这个又关联到windows帐号的UWP, 而我又经常把所有应用都删除,导致不能正常更新.
1. 更新时可以手动选择更新哪一项, windows经常会自动把我的驱动也更新了,结果intel的集成显卡驱动又是一坨翔.
1. 更多功能可以参考 [Windows Update MiniTool](http://forum.ru-board.com/topic.cgi?forum=5&topic=48142#2)

**Comment by mingkuang-Chuyu** [comment]
谢谢支持，但是Dism++使用的是catalog的数据，并非微软在线的Windows Update。
目前微软没有发布insider的数据，因此是无法支持的。

2.更新时可以手动选择更新哪一项：这个能力Dism++本身不是支持吗？Dism++并未强制更新。

**Comment by Roger-WIN** [comment]
我觉得可以把查找功能再强化一下，比如查找某个列表里没有的补丁A，而列表里有取代这个补丁的补丁B，就可以选中补丁B，并弹出提示信息：补丁A已被B取代。

**Comment by mingkuang-Chuyu** [comment]
这个就太蛋疼了，自己去微软catalog查吧……

**Comment by mogu1121** [comment]
@mingkuang-Chuyu 更新有点慢， Windows Update有更新了 catalog也有，wsusscn2.cab 也是新的 但是idsm++ 扫描结果还是说没有更新

**Comment by mingkuang-Chuyu** [comment]
Dism++是每个星期的双休时发布更新。因为微软发布更新是非常频繁的。基本每个星期都有几次。甚至，同一天也可能出现多次。所以 不会紧跟随微软立马发库。

**Comment by mingkuang-Chuyu** [comment]
关闭此建议，用户长期无回应，并不能知道真真用户需求。如果有需要可以重新打开此问题
