### ISSUE TITLE
dism++ 更新到最新版以后全部蓝屏，所有的机子中招！

### ISSUE THREAD

**Issue by zensin123** [Chuyu-Team/Dism-Multi-language#156]
系统 win10 15063版本  64位  
dism++ 版本 10.1.1000.11
如果不用dism++  机子完好
但是一旦用了就会出现蓝屏的问题，而且用dism++引导修复也不行
只能重装系统，之前没有出现这样的问题！ 连我家里的15063版本的系统也中招！
备注：空间回收里面5个大的框框都选择了 相当于全选 然后扫描  然后清理  重启以后就蓝屏了！

系统终止代码：0*c000007b
系统错误代码：0*c0000001

**Comment by mingkuang-Chuyu** [comment]
Hi,  请问 dism++清理压缩 是什么意思？ 你的意思是说 用了Dism++的CompactOS？还是其他什么。

能大概说下   用了哪些清理项目吗？


谢谢

**Comment by mingkuang-Chuyu** [comment]
如果你确实用了CompactOS，那么可以在恢复功能里 进行撤销Compact。

**Comment by zensin123** [comment]
空间回收里面5个大的框框都选择了 相当于全选 然后扫描 然后清理 重启以后就蓝屏了！

**Comment by mingkuang-Chuyu** [comment]
话说5个大框框是什么，能否告知大概清理了什么？
特别是CompactOS有没有使用？

**Comment by mingkuang-Chuyu** [comment]
应该是驱动清理导致的，已经有其他用户反馈。驱动清理后蓝屏无法启动。

但是驱动清理本身就非常危险，非常容易导致电脑无法启动。

如果确定是驱动清理导致的问题，那么我需要看环境……。找到特征值后才能解决问题。

谢谢

**Comment by zensin123** [comment]
CompactOS当然有，就是空间回收里面所有的选项都打勾了！至于驱动清理，之前一直有过，但是从来没有出现蓝屏问题，这次出现就奇葩了！！！
系统 win10 15063版本 64位
dism++ 版本 10.1.1000.11
系统终止代码：0c000007b
系统错误代码：0c0000001

**Comment by zensin123** [comment]
15063版本打完8月补丁，然后用驱动人生更新驱动，所有更新完之后开始清理垃圾，结果用dism++清理完之后 蓝屏了，用dism++修复引导也不行，必须重装系统！！！  再次说明：空间回收里面所有的选项都打勾了！系统 是win10   创业者更新版15063  补丁更新到这个月8月份！用驱动人生更新驱动的！ 
dism++ 版本 10.1.1000.11  !!!

**Comment by zensin123** [comment]
我这边在公司给别人弄机子也出现蓝屏的问题，当时我就郁闷了，结果一查是dism++清理后出现的问题，可是之前并没有出现这样的问题哦！

**Comment by zensin123** [comment]
系统是64位创业者更新版！

**Comment by mingkuang-Chuyu** [comment]
如果你在意稳定性不要使用专家模式…… 专家模式某些功能本来就是极其危险的……

这个跟Dism++版本也没有任何关系，只是刚好踩到一个坑。而至于如何解决或者说规避这个坑，只有用户配合。找到出问题是项目，最终找到原因。

麻烦你再多做做测试，帮忙找确认下那个项目有问题。

一般就CompactOS 跟 过期驱动清理 会导致蓝屏，麻烦你先确认是哪个功能引起的，几个大功能挨个试过去（也可以用2分排除法快速定位，听不懂我说话就用最原始的挨个试吧）。然后联系我，到时我需要远程看看具体环境。

谢谢

CompactOS蓝屏解决办法很简单，撤销CompactOS就可以了。

驱动清理恢复略微麻烦点，把被清理的驱动重新添加回去就能恢复正常。

**Comment by zensin123** [comment]
我下载dism++的时候没有提示 哪个是专家模式哪个不是    至于我是不是用专家模式 ，我表示一脸懵逼，完全不懂，反正看到空间回收选项 我就把里面的所有框框全部打√   然后扫描 清理 就是这样 一直以来都是这样  也没出现过大的问题(*^▽^*)

**Comment by mingkuang-Chuyu** [comment]
话说 那你怎么说 CompactOS 当然有…… 现在 CompactOS 都是专家模式特有的功能。我也开始懵了

**Comment by mingkuang-Chuyu** [comment]
Hi,请问有什么新的发现，谢谢

**Comment by zensin123** [comment]
已经确认是15063版本系统自己的问题  ，没有用dism++的情况下，打完补丁（8月8号补丁）然后用驱动人生更新完驱动 至少重启两次就会发生蓝屏的问题，于是乎，退回win8.1 64位系统，不打补丁  但是还没试过在win8.1  64位系统下 用dism++最新版本 来压缩和清理驱动是否也会有蓝屏的问题？  还没试过！按理说应该没有问题。建议大家还是用win10 14393版本比较好 ，而15063这个版本的系统无论是使用投影仪 （字体模糊问题还没解决好）还是打补丁都会出现问题，等秋季版win10 发布再看

**Comment by zensin123** [comment]
微软已经正式宣布推出旨在满足高级用户在苛刻和关键任务情况下部署的 Windows 10 Pro for Workstation 版本，此 Windows 10 Pro for Workstation 将作为 Fall Creators Update 的一部分提供，将在今年秋季可用
dism++ 的开发者和维护者请跟进！

**Comment by zensin123** [comment]
Windows 10 Pro for Workstation 具有以下特点：

ReFS（弹性文件系统）：ReFS 可以为容错存储空间的数据提供云级别的弹性，并轻松管理非常大的容量。ReFS 对数据损坏具有弹性处理能力，可优化处理大数据量和自动更正等功能。它可以在你的镜像存储空间上使用完整性流来保护数据，使用 ReFS 完整性流可以检测数据在其中一个镜像驱动器上的损坏情况，并在其他驱动器上使用健康的数据副本来更正和保护用户的宝贵数据。
持久内存：Windows 10 Pro for Workstations 通过非易失性内存模块（NVDIMM-N）硬件提供最苛刻的应用程序和数据保护。NVDIMM-N 使得用户能够以最快的速度读/写文件，即计算机主内存的速度。由于 NVDIMM-N 是非易失性存储器，所以即使关闭工作站，文件仍然存在。
更快的文件共享：Windows 10 Pro for Workstation 支持 Windows Server 都有的 SMB Direct 的功能特性，它支持具有远程直接内存访问（RDMA）功能的网卡。RDMA 网卡支持低 CPU 使用率和超低延迟状态全速运行，对于在远程 SMB 文件共享上访问大型数据集的应用程序，此功能可以实现：
提高吞吐量：利用高速网络的全部吞吐量，其中网络适配器以线速协调大量数据的传输。
低延迟：对网络请求提供极快的响应，让使远程文件存储就像是直接连接的存储一样。
低 CPU 占用率：在网络传输数据时只占用较少的 CPU 周期，从而使系统上运行的其他应用程序可以获得更好的性能。
扩展硬件支持：Windows Insiders 用户表达最大的痛点之一就在于利用 PC 原始硬件性能的限制。因此，微软正在扩展 Windows 10 Pro for Workstation 中的硬件支持。用户现在可以在具有高性能配置的设备上运行 Windows 10 Pro for Workstation，包括支持最多 4 颗 CPU 服务器级别的 Intel Xeon 或 AMD Opteron 处理器并可增加高达 6TB 的大容量内存支持。（目前仅支持最多 2 颗 CPU 和最大 2TB 内存）

**Comment by zensin123** [comment]
Windows 10 Pro for Workstations属于Windows 10专业版系统的最顶级版本，专为高端PC打造、拥有服务器级别的硬件支持，专为高负载场景设计

**Comment by zensin123** [comment]
所以已经确认是15063版本系统自己的问题 ，在没有用dism++的情况下，打完补丁（8月8号补丁）然后用驱动人生更新完驱动 至少重启两次就会发生蓝屏的问题，于是乎，退回win8.1 64位系统，不打补丁 但是还没试过在win8.1 64位系统下 用dism++最新版本 来压缩和清理驱动是否也会有蓝屏的问题？ 还没试过！按理说应该没有问题。建议大家还是用win10 14393版本比较好 ，而15063这个版本的系统无论是使用投影仪 （字体模糊问题还没解决好）还是打补丁都会出现问题，等秋季版win10 发布再看

**Comment by zensin123** [comment]
另外无论是新机6代酷睿  还是老机三代酷睿 装15063版本系统 打完补丁 然后用驱动人生更新完驱动就会蓝屏  初步怀疑要么是补丁要么是驱动问题！

**Comment by suwakowww** [comment]
走一遍常规的更新看下吧，一般情况下windows update会连驱动也扫出来的。

**Comment by zensin123** [comment]
补丁包我是事先从第三方网站下载好的，并非通过dism++去打补丁

**Comment by zensin123** [comment]
至今为止  貌似其他人15063版本系统蓝屏的概率不大，即使打完这个月的补丁   也很少蓝屏的  那就是驱动的问题了

**Comment by mingkuang-Chuyu** [comment]
我觉得，根据你的描述也很有可能是驱动人生打驱动的问题。Win10有致命设计缺陷，程序行为会被模拟成win8。如果你要打驱动我建议你使用系统自带，或者跟Dism++一样明确的声明了Windows 10兼容性清单的程序。

**Comment by mingkuang-Chuyu** [comment]
否则打驱动时很可能给你打上到Win8节点去了

**Comment by mingkuang-Chuyu** [comment]
用户已经确认 不是Dism++问题。关闭此问题……
