### ISSUE TITLE
创建系统备份失败

### ISSUE THREAD

**Issue by ndy000** [Chuyu-Team/Dism-Multi-language#159]
最新版version 10.1.1000.11，用于系统备份，无论怎么设置文件名称总是提示：句柄无效。

**Comment by mingkuang-Chuyu** [comment]
hi, 建议你提供下Dism++日志，Config/Dism++.log

提示失败时，立马保存日志然后给我。

谢谢

我猜测是硬盘文件受损，一些文件无法正常访问所致。

**Comment by mingkuang-Chuyu** [comment]
已经解决，腾讯相关文件无法访问所致， 删除就可以了。
