### ISSUE TITLE
为能更新加上编号吗？或者显示更新总数是多少？

### ISSUE THREAD

**Issue by spirit3001** [Chuyu-Team/Dism-Multi-language#177]

**Comment by verdy-p** [comment]
"Is it possible to update the number? Or show the total number of updates?"
No more details? Do you speak about the detection of Windows Updates available, and the list of descriptions articles (KB numbers ?) on the Microsoft site ?

**Comment by mingkuang-Chuyu** [comment]
DIsm++ 类别会显示 总数量，只是需要心算下。一共也就是5个类别左右。心算也可以接受吧。另外提供总数也不是什么刚需。

**Comment by mingkuang-Chuyu** [comment]
用户不在回复…… 暂时关闭此问题。如有需要可以重新打开此问题。
