### ISSUE TITLE
6.1.7601 64bit系统打开32bit系统会话时提示“试图加载格式不正确的程序”

### ISSUE THREAD

**Issue by yunzy** [Chuyu-Team/Dism-Multi-language#18]
6.1.7601 64bit系统中使用64位Dism，因为是双系统（版本号一致），所以Dism能检测到另外一个32bit系统，在打开32bit系统会话时提示“试图加载格式不正确的程序”。这是何故呢？

**Comment by mingkuang-Chuyu** [comment]
Hi,首先要确保另一个系统处于关机状态，而不是休眠状态

如果你确认你的系统已经处于真正的关机状态，那么可以加我QQ 343183163，我需要远程看看环境。谢谢

**Comment by yunzy** [comment]
已加。用TeamViewe吧，QQ远程稳定性和流畅性不如TeamViewe。

**Comment by yunzy** [comment]
已加。用TeamViewe吧，QQ远程稳定性和流畅性不如TeamViewe。

**Comment by mingkuang-Chuyu** [comment]
已经确认此问题，未考虑到另一个系统刚好是Boot分区的情况
下个Beta修正

**Comment by mingkuang-Chuyu** [comment]
新版本已经发布解决了此问题

**Comment by yunzy** [comment]
好的。
