### ISSUE TITLE
Suggestion to add

### ISSUE THREAD

**Issue by Jhovany200** [Chuyu-Team/Dism-Multi-language#180]
You could add the function to "find duplicate files" in the section "常用工具" or "Utilities". With that function it would be more complete Dism++.

It's just a suggestion.

**Comment by mingkuang-Chuyu** [comment]
Hi Dism++ Support "Hand Link Merge"  in Cleaner.

It will used handlink Merge your files.

Thanks

**Comment by verdy-p** [comment]
Typo: this is "Hard Link" not "Hand Link"
