### ISSUE TITLE
启动项管理-服务项 列表无法操作，点击按钮无反应

### ISSUE THREAD

**Issue by irexer** [Chuyu-Team/Dism-Multi-language#185]
启动项管理-服务项 列表无法操作，点击按钮无反应

_via **Dism++ x64 10.1.1000.11UEFI** on Windows 10_

**Comment by mingkuang-Chuyu** [comment]
这个不是BUG，而是只有专家模式才能调整……

如果需要调整 请切换到专家模式，否则只有看。
