### ISSUE TITLE
 Problem updating page translation

### ISSUE THREAD

**Issue by Jhovany200** [Chuyu-Team/Dism-Multi-language#187]
You can solve the problem of updating the page translation:
https://www.chuyu.me/es/index.html
Or it is probably a general problem of updating the translation of the other pages as well.

Oleada1 si tu podrias expresarles a los programadores que si pueden corregir el problema de la actualización de la traducción en la pagina, por que sigue con los cambios de hace un tiempo atras.

**Comment by Oleada1** [comment]
Te voy a poner dos comentarios, por si lo quieres cambiar y te quedará mejor la traducción, ya ves que te pongo comentarios, no pido que modifiquen nada, para que veas la diferencia.

wsusscn2.cab es la base de datos para Windows Update. Puede usarlo sobrescribiendo en la ruta "Config\wsusscn2.cab".
por:
wsusscn2.cab es la base de datos para Windows Update. Puede usarlo escribiendo la ruta "Config\wsusscn2.cab".
-----------------------------------------------
¡El código abierto no es sólo la virtud, sino también un símbolo de fuerza!.  Haga clic aquí para ver Github del equipo de Chuyu.
por:
¡El código abierto no es sólo una virtud, sino también un símbolo de fortaleza!. Clic aquí para ver el equipo de Chuyu en Github.
--------------------------------------
Si lo quieres cambiar lo cambias, y si lo quieres dejar como está, lo dejas. Es un comentario. Yo no voy a cambiar nada, si te gusta lo cambias,. Ya ves que el significado cambia notablamente.

**Comment by Oleada1** [comment]
No cambies nada de la traducción, sin que me lo comentes antes, les he enviado una nueva traducción, tanto del es.xml, como del Update es.xml.
Había frases entrecortadas, y las he tenido que retocar, así como otras correcciones mal hechas, he reparado todas las comillas simples y dobles, para que estén en el formato correcto. ¿De acuerdo?.
Una vez hayan actualizado la versión que les he enviado, ya miraremos lo que comentas.

**Comment by Jhovany200** [comment]
me expresare lo mejor que pueda, es que al momento de buscar ejemplo: Dism++, entra primero a: https://www.chuyu.me/ y despues redirecciona a: https://www.chuyu.me/es/index.html  esta bien.
El problemas es que ya no cambia o se actualiza la pagina, ya mire en el respositorio que ya cambio pero en la pagina tovia no.

**Comment by verdy-p** [comment]
The live HTML page on the site is generated from base.html and the XML translation file after validating it. It is not visible immediately. There are good reasons for not publishing it immediately on the website. The Github repository is there to track changes that may be reverted before importing them to the site.

**Comment by Jhovany200** [comment]
Ok, thanks for answering my question.

**Comment by Jhovany200** [comment]
No me entediste Oleada1 yo tampoco quiero mas peleas, pero ya resolvieron mi duda, gracias.

**Comment by Oleada1** [comment]
Si te entendí, lo que pasa que he aprovechado para hacerte el comentario, me he tirado más de dos horas corrigiendo los archivos, ya que había frases entrecortadas, comillas sin el formato correcto, que entre todos hemos mandado a tomar por saco la traducción (digo hemos, porque también me incluyo), por eso  te he hecho el comentario, no pienso perder más tiempo.
Respecto a la pregunta, tienes que tener paciencia, a veces me envían las nuevas actualizaciones que hay para traducir, yo se las paso al momento y como tienen que pasar por el resto de compañeros de otros países, tardan al igual una semana, o varios días en aplicar esa actualización. Al igual que cuando les envío una traducción nueva o actualización, no lo hacen al momento, tardan unos días. Debes pensar que no vivimos de esto, y cada uno tiene sus propias responsabilidades y puede que tarden en actualizarlo.

**Comment by mingkuang-Chuyu** [comment]
Hi, html update is not immediately effective, if there is no important thing, I generally update once a week.

Thanks for your support
