### ISSUE TITLE
可否在系统优化中增加“设置开机自动开启NumLock数字锁定键”？

### ISSUE THREAD

**Issue by justwho** [Chuyu-Team/Dism-Multi-language#192]
最近在使用台式电脑和带小键盘的笔记本时经常遇到得开启数字锁定后才可以输入数字的麻烦，想着如果在Dism++里集成此设置项，会很方便日常使用。
如下为注册表实现方法：
Windows Registry Editor Version 5.00

[HKEY_USERS\.DEFAULT\Control Panel\Keyboard]
"InitialKeyboardIndicators"="2"

如果将其值改为0，表示开机不打开NumLock(即还原windows默认设置)
Windows Registry Editor Version 5.00

[HKEY_USERS\.DEFAULT\Control Panel\Keyboard]
"InitialKeyboardIndicators"="0"

**Comment by mingkuang-Chuyu** [comment]
谢谢你的意见……
下次规则库更新时 添加此规则

**Comment by mingkuang-Chuyu** [comment]
突然发现Dism++明明有这个规则……

在其他 ：
登陆界面默认打开小键盘

**Comment by justwho** [comment]
我也发现了!!!哈哈
