### ISSUE TITLE
Correciones Oleada1

### ISSUE THREAD

**Issue by Jhovany200** [Chuyu-Team/Dism-Multi-language#193]
Languages/es.xml
Línea N° 61: Link="Nunca compactar"/>
te comiste la c
www.chuyu.me/es.xml
Línea N° 16: Dst="Limpieza de WinSxS"
"Limpiar WinSxS" enmarca una acción, mientras que "Limpieza de WinSxS" emarca una característica que es lo correcto
Línea N° 19: Dst="Hay una reducción del 33% del espacio utilizado, sin racionalizar la imagen del SO"/>
Línea N° 26: Dst="Totalmente seguro"/>
Green--->hase referencia a lo limpio, verde y seguro. Y no solo colocar portable
Línea N° 27: Dst="Gratuito, portable, seguro y sin anuncios."/>
Línea N° 37: Dst="Registro de cambios"/>
Ya estaba bien
Línea N° 38: Podrias volver a colocar las comillas para remarcar entre comillas: "wsusscn2.cab" al igual que al final
&quot al igual que al final pero con: wsusscn2.cab

**Comment by mingkuang-Chuyu** [comment]
@Oleada
