### ISSUE TITLE
希望在备份还原中增加“完成后自动关机”

### ISSUE THREAD

**Issue by kkocdko** [Chuyu-Team/Dism-Multi-language#195]
真的很需要，非常需要，有时候晚上要挂机备份
另外还原里边希望也能加上，有时候帮别人装系统，没有自动重启。。只好去用nt安装器，感觉还是dism++比较好看。。

**Comment by mingkuang-Chuyu** [comment]
Hi, Dism++有这个功能，

选项  -  操作完成后   关机/重启

谢谢你的支持

**Comment by mingkuang-Chuyu** [comment]
关闭此问题，如果你有什么其他疑问可以重新打开。谢谢
