### ISSUE TITLE
Appx卸载后在进行sysprep，计算器等应用变成英文

### ISSUE THREAD

**Issue by mingkuang-Chuyu** [Chuyu-Team/Dism-Multi-language#20]
反馈者：
guoyin618@qq.com

先用Dism++的User Appx的卸载功能在线删除了不想要的APP后，sysprep后，在PE里运用 Dism++的WinSxS清理后就某些应用变成英文，可能是User Appx删除的原因

正在验证

**Comment by MouriNaruto** [comment]
这个问题，我也碰到过
曾经在Store把App X升级到最新版本，sysperp后应用全部变成英文（如果把InfusedApps目录删除，则sysperp后所有非系统级AppX消失）

**Comment by mingkuang-Chuyu** [comment]
@MouriNaruto  我也在怀疑是你说的问题，因为我无论怎么测试 都测不出来。

**Comment by mingkuang-Chuyu** [comment]
此问题应该是系统自身的问题，用户也没有后续反馈，暂时关闭此问题。
