### ISSUE TITLE
在 Windows 10 (1703) x64 使用"硬链接合并"功能导致Win10通用应用无法打开(闪退)

### ISSUE THREAD

**Issue by ZhLong-473811012** [Chuyu-Team/Dism-Multi-language#201]
空间回收 硬链接合并 。虽然有说明说 可能会导致错误。
但我已经测试了差不多两个月、重装了三遍Win10。
发现在应用商店下载安装了一些应用，过了一段时间(比如一个星期)，使用Dism++的硬链接合并功能后重启系统，直接会导致所有的Win10通用应用闪退。这两个月我都找不到合适的方法解决，只能重装系统。

如果没有到应用商店下载安装应用就先使用Dism++的硬链接合并功能，并没有发现一些错误。但过了一段时间(比如一个星期)，到应用商店下载安装应用可能会发生错误 0x80070005。这时重新启动系统又是直接无法打开，闪退。目前我找不到合适的方法解决，只能重装系统。

包括 计算器、照片、相机、闹钟、应用商店 等的通用应用，打开都会闪退。而且还无法卸载应用，点击一个应用→卸载，虽然可以立即看到这个应用的磁贴消失了，但是重新登录(重新启动)之后又会在"所有应用"显示出来，并且有些应用如果有后台通知还是照常通知的 (现在我应用商店一直在通知"某某应用安装失败"…)。
![image](https://user-images.githubusercontent.com/20869871/29740059-69dcbac4-8a80-11e7-8b12-e4176f5af1f6.png)

**Comment by mingkuang-Chuyu** [comment]
那么奇葩……

**Comment by vladislays** [comment]
Please update the update database for windows 10

**Comment by powerxing04** [comment]
我还真没遇到过，不过我都是按以下顺序分开执行的：
1、清理WinSxS等垃圾
2、硬链接合并
3、CompactOS

**Comment by kxsclu** [comment]
会不会是因为系统对链接操作会同时影响两个文件？（我瞎猜的）
