### ISSUE TITLE
选项 - 详细设置-开启 整合引导菜单 失败，显示“系统找不到指定的文件”

### ISSUE THREAD

**Issue by epsgerry02** [Chuyu-Team/Dism-Multi-language#204]
= =请问还需要安装什么软件吗？

**Comment by mingkuang-Chuyu** [comment]
是你的系统缺少了RE，一般是被精简了。

你可以用原版ISO提取原版RE文件，或者直接就用第三方PE。

如果你打算恢复RE，那么重原版ISO中 提取 "Windows\\System32\\Recovery" 里面的二个文件，覆盖到当前系统即可。
