### ISSUE TITLE
新增功能

### ISSUE THREAD

**Issue by kkkgo** [Chuyu-Team/Dism-Multi-language#207]
增加/Set-Edition和/Get-TargetEditions；
ISO生成器限制32字节；

**Comment by lixuy** [comment]
还有/Set-ProductKey

**Comment by lixuy** [comment]
ISO生成器支持多线程；

**Comment by mingkuang-Chuyu** [comment]
ISO生成器支持多线程，应该没必要，因为ISO都是不压缩的。单纯的数据复制操作，没有这种必要上多线程。

**Comment by lixuy** [comment]
不是，我是说iso生成器没办法多开几个，或者在用iso生成器的时候其他镜像不能操作

**Comment by lixuy** [comment]
其实我觉得工具箱的部分功能可以独立出来，放在顶部菜单栏

**Comment by mingkuang-Chuyu** [comment]
大叔  那叫多实例……

**Comment by lixuy** [comment]
嗯嗯是我打错了

**Comment by mingkuang-Chuyu** [comment]
ISO生成器限制32字节 以及 多实例已经完成。
