### ISSUE TITLE
能否增加可以變動『使用者』檔案及程式安裝位置的設定

### ISSUE THREAD

**Issue by kenmen** [Chuyu-Team/Dism-Multi-language#209]
掛載映象檔對映象檔進行優化時，能否增加對使用者目錄及程式安裝位置的變更設定？

**Comment by suwakowww** [comment]
要是从注册表上改，改了可能会不稳定，比如会出现“没有注册类”，然后所有经过uac的都打不开，等等。
要是改倒建议在oobe阶段使用命令提示符进行修改：
```batch
robocopy <源路径> <目标路径> /e /copyall /xj
cd /d <路径>
ren <原文件夹名> <目标文件夹名>
mklink /j <源路径> <目标路径>
```
命令提示符可以使用shift+f10打开
再或者，可以写个预应答批处理来改

**Comment by kenmen** [comment]
看來只能用這個方法了！
沒法像之前XP那樣，直接修改原始的映象檔了～

**Comment by mingkuang-Chuyu** [comment]
没听懂在说什么…… 另外挂载的wim设置这种东西又有什么意义……

**Comment by mingkuang-Chuyu** [comment]
关闭此问题，因为wim修改此类设置并没有太大意义。另外修改后也容易导致系统异常
