### ISSUE TITLE
备份系统时显示错误

### ISSUE THREAD

**Issue by johnbitcn** [Chuyu-Team/Dism-Multi-language#216]
输入保存路径选择确定后弹出错误 “0x80042301”
不管是64位和32位，甚至RE启动也会出现这样的错误。
DISM版本 10.1.1000.31
系统 Win10

**Comment by mingkuang-Chuyu** [comment]
0x80042301 是VSS 错误。
不过RE中应该不会吧，难道 你在备份RE？

**Comment by mingkuang-Chuyu** [comment]
备份时  一定要写上你备份的分区，RE里面别傻傻的去备份  X:

**Comment by mingkuang-Chuyu** [comment]
用户长时间没有回复，暂时关闭此问题。
