### ISSUE TITLE
希望增加：在资源管理器空白处双击后，返回到上级目录

### ISSUE THREAD

**Issue by bloosmgh** [Chuyu-Team/Dism-Multi-language#217]
希望增加：在资源管理器空白处双击后，返回到上级目录；clover有这个功能，但是想让微软原生资源管理器实现这个功能

**Comment by mingkuang-Chuyu** [comment]
Hi,   这个需要微软本身支持，另外需要你提供对应实现规则。

谢谢支持

**Comment by mingkuang-Chuyu** [comment]
关闭此问题，如果需要可以重新打开此问题。
