### ISSUE TITLE
建议增加一个任务栏时间“显示到秒”的功能

### ISSUE THREAD

**Issue by Luupw3d** [Chuyu-Team/Dism-Multi-language#220]
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"ShowSecondsInSystemClock"=dword:00000001

这是reg内容，望采纳。添加注册表项难度应该不大。

**Comment by Luupw3d** [comment]
还建议深度挖掘一下HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced 这个项下面的可玩性。

**Comment by mingkuang-Chuyu** [comment]
谢谢支持……

**Comment by mingkuang-Chuyu** [comment]
10.1.1000.40已经新增此功能。请耐心等待推送
