### ISSUE TITLE
win10备份时报“拒绝访问”错误，请问是什么原因

### ISSUE THREAD

**Issue by deanning007** [Chuyu-Team/Dism-Multi-language#221]
win10备份时报“拒绝访问”错误，请问是什么原因

**Comment by mingkuang-Chuyu** [comment]
应该是有其他软件拦截了Dism++文件读取操作。
具体错误可以参考Dism++日志  Config/Dism++.log.

谢谢

**Comment by mingkuang-Chuyu** [comment]
长时间没有回复。暂时关闭此问题，如果有需要可以重新打开

**Comment by MRNIAN** [comment]
win10备份系统出现“拒绝访问“，查看日志也未显示什么问题，请问是怎么回事

**Comment by MRNIAN** [comment]
自己操作的问题已经解决了，

**Comment by LJJJPPP** [comment]
win10备份时报“拒绝访问”错误，查看日志没有发现问题，请问如何解决

**Comment by mingkuang-Chuyu** [comment]
> win10备份时报“拒绝访问”错误，查看日志没有发现问题，请问如何解决

  提供一些信息，比如说 你保存到哪里了……提供一些截图 最好了
