### ISSUE TITLE
能否忽略特定更新？

### ISSUE THREAD

**Issue by IzualYang** [Chuyu-Team/Dism-Multi-language#222]
之前我就一直打不上KB30000850，用dism++容易误操作。
就算不能忽略显示，至少提供“默认不勾选”的选项吧。

**Comment by mingkuang-Chuyu** [comment]
这个功能后期将会上线，另外已经有此反馈。因此关闭此问题
相关问题：
https://github.com/Chuyu-Team/Dism-Multi-language/issues/151
