### ISSUE TITLE
"Apps and Features" sorting order

### ISSUE THREAD

**Issue by Viaxl** [Chuyu-Team/Dism-Multi-language#225]
It's near impossible to find the entry I want to remove in Applications tab because the sorting method is chaos. It's neither sorted by alphabetic or time.

**Comment by mingkuang-Chuyu** [comment]
Thanks, I know.

**Comment by mingkuang-Chuyu** [comment]
Change set 1547, Done~

Please wait.

Thanks for your support.

mingkuang
