### ISSUE TITLE
<dism++文件夹>\config\config.ini异常

### ISSUE THREAD

**Issue by suwakowww** [Chuyu-Team/Dism-Multi-language#23]
不清楚是不是非unicode编码的问题，这个配置文件的字符被替换了，但奇怪的是，即使配置文档是异常，还是能正常加载
![qq 20170122124411](https://cloud.githubusercontent.com/assets/6368936/22180080/cec32386-e0a0-11e6-8edd-e5cf632af774.png)
拿其他电脑看了下，这个文件似乎是**GB**编码的，但自用那台笔记本默认用的是**iso8859-1**编码，不过修不修随便吧，估计国外的没几个看配置文件的

**Comment by mingkuang-Chuyu** [comment]
OK 谢谢反馈 将在下个版本中修正

**Comment by mingkuang-Chuyu** [comment]
已经修复，请耐心等待下个测试版 或者新的正式版
