### ISSUE TITLE
更新管理下载有些补丁老是下载失败，总是重试几次才下得下来。

### ISSUE THREAD

**Issue by welldong2017** [Chuyu-Team/Dism-Multi-language#230]
个别补丁还要安装两次才能装上。例如一个ondrive的KB..8707的补丁。

**Comment by mingkuang-Chuyu** [comment]
Hi，Dism++使用的是微软的服务器下载地址。而微软服务器质量并非想象中的好。所以可能需要多尝试几次。另外具体原因会在Config/Dism++.log中输出。
