### ISSUE TITLE
系统优化里面的禁用“共享”右键菜单，现在是没用的

### ISSUE THREAD

**Issue by yuehun** [Chuyu-Team/Dism-Multi-language#233]
顺便提供一下自己找到的删除方法
[-HKEY_LOCAL_MACHINE\SOFTWARE\Classes\*\shellex\ContextMenuHandlers\ModernSharing]

**Comment by kaweizz** [comment]
主要体现在16299上

**Comment by mingkuang-Chuyu** [comment]
谢谢大家

**Comment by mingkuang-Chuyu** [comment]
话说共享 菜单怎么打开 ，我安装16299后 都找不到 共享菜单在哪里了

**Comment by mingkuang-Chuyu** [comment]
测试了下没问题啊……

**Comment by mingkuang-Chuyu** [comment]
建议提供截图，以及相关操作说明。

**Comment by yuehun** [comment]
这怎么上传图片

**Comment by yuehun** [comment]
http://i1.bvimg.com/9427/814530ec043fbbf2.png
这个 共享禁用或者不禁用都没用 右键菜单都有会

**Comment by yuehun** [comment]
http://i1.bvimg.com/9427/814530ec043fbbf2.png
这个 共享禁用或者不禁用都没用 右键菜单都有会

**Comment by mingkuang-Chuyu** [comment]
OK 了解了，这完全是另一个项目……跟 “共享” 不同

**Comment by mingkuang-Chuyu** [comment]
已经添加至Data.xml中，请耐心等待新版本推送。暂时先推送到Beta版。
