### ISSUE TITLE
Add as collaborator

### ISSUE THREAD

**Issue by Jhovany200** [Chuyu-Team/Dism-Multi-language#234]
with the permission of the project manager of Chuyu-Team.

My question is if you can add me in "collaborators" to make the changes directly. And not be requesting all the time by sending "pull requests".

I will only cooperate in the Spanish language.

Thanks for your reply.

**Comment by suwakowww** [comment]
maybe you are already contributor...
try to commit to Chuyu-Team/Dism-Multi-language directly

**Comment by Jhovany200** [comment]
he said for the most part he modifies or corrects the incorrect parts in the online translations.
Or have write access.
