### ISSUE TITLE
建议增加“系统失败自动重启选项”规则

### ISSUE THREAD

**Issue by szoliver** [Chuyu-Team/Dism-Multi-language#235]
“蓝屏重启"规则不是这个选项的设置

![default](https://user-images.githubusercontent.com/16750254/31339890-efe84da8-ad36-11e7-8823-60410e23af6a.png)

**Comment by mingkuang-Chuyu** [comment]
此规则已经存在……

“蓝屏时自动重启（by 原罪）”
