### ISSUE TITLE
“系统优化”中的“收起资源管理器功能区”项为什么是“收起”而不是“展开”？

### ISSUE THREAD

**Issue by Roger-WIN** [Chuyu-Team/Dism-Multi-language#237]
在当前用户下，此项的开闭是有效的。
对于离线挂载的映像，该项是默认关闭的。可即使将此项开启再关闭，部署后也发现功能区依然没有展开。
所以我想能不能将此项改为“展开资源管理器功能区”，这样开启之后可以确保展开。

**Comment by mingkuang-Chuyu** [comment]
可能是规则执行有误……

**Comment by mingkuang-Chuyu** [comment]
问题已经解决……今天晚上会发布新规则解决此问题
Data.xml  ver 2017-10-12
