### ISSUE TITLE
add to translate

### ISSUE THREAD

**Issue by Jhovany200** [Chuyu-Team/Dism-Multi-language#242]
I was wondering if they can add, to translate the marked parts with red.
As no other language changes, you can add these parts in the languages ​​to translate.

also for other languages, and so translate the rest of their respective languages.

![imagen](https://user-images.githubusercontent.com/30766228/31462423-bd7aaae0-ae9a-11e7-8b22-da7e3955b8ba.jpg)

"there is no reference on the 2 parts marked with red".

**Comment by verdy-p** [comment]
This is not new, I had requested it months ago. Apparentlmy they are hardcoded in code without using the internal translation API to convert them. Or I have not been able to locate the Chinese source text that would be used on Chinese version of Windows (where no translation package is needed as the source equals the target of translation).

**Comment by Jhovany200** [comment]
Thanks for your answer.

**Comment by mingkuang-Chuyu** [comment]
I'll Update Data.xml, Thanks

**Comment by mingkuang-Chuyu** [comment]
Done~

<String q="" Target="User Appx" Link="User Appx"/>
<String q="" Target="Provisioned Appx" Link="Provisioned Appx"/>

and use new default.ui.zip (Config/default.ui.zip)

[default.ui.zip](https://github.com/Chuyu-Team/Dism-Multi-language/files/1377781/default.ui.zip)
