### ISSUE TITLE
new add to translate

### ISSUE THREAD

**Issue by Jhovany200** [Chuyu-Team/Dism-Multi-language#244]
I was wondering if they can add, to translate the marked parts with red.
As no other language changes, you can add these part in the languages ​​to translate.

also for other languages, and so translate the rest of their respective languages.

![imagen1](https://user-images.githubusercontent.com/30766228/31479459-6cbf1582-aee5-11e7-9f7a-08f41853b574.jpg)

"there is no reference on the part marked with red".

**Comment by mingkuang-Chuyu** [comment]
“Explorer”has been added in Data.xml.

You can add
      <String Target="Explorer" Link="????????"/>

in es.xml

Thanks
