### ISSUE TITLE
试图加载格式不正确的程序

### ISSUE THREAD

**Issue by MarkMoXs** [Chuyu-Team/Dism-Multi-language#245]
挂载Windows 10 企业版 install.wim  提示：  试图加载格式不正确的程序  怎么解决？还是我打开的方式不对，还请告知一下 非常感谢。

**Comment by mingkuang-Chuyu** [comment]
esd不支持挂载，请先转换到wim然后继续。

你不要觉得我说的文不对题……你的install.wim其实是个esd……

**Comment by MarkMoXs** [comment]
谢谢，一语道破梦中人，搜了很多都没收获 只好来这里求助，你这么一说 全懂了 就好比MP4视频后辍改成wmv 其实它还是MP4，真的非常感谢。
