### ISSUE TITLE
关于语言

### ISSUE THREAD

**Issue by JohnsonSYK** [Chuyu-Team/Dism-Multi-language#25]
请问一下能不能在设置里添加一个语言选项
我用的是英文系统默认语言是英文而且没法改，能选中文就好了
谢谢~！

**Comment by suwakowww** [comment]
给个临时解决方法你：
<dism++目录>\config\languages
这里有语言文件，之前貌似说过可以把里面的文件删掉还是剩下cn.xml就变中文了

**Comment by JohnsonSYK** [comment]
谢谢~我之前就是这么解决的，但是每次打开软件就会提示更新（版本号一样），然后就把xml文件“更新“回英文了 QAQ

**Comment by mingkuang-Chuyu** [comment]
在 系统格式 里调整为中文即可

程序是不会提供自定义语言的，这是为了保证最近体验。因为程序如果不跟随系统格式的设置会导致 字体显示发虚，或者字形显示错误
