### ISSUE TITLE
规则无效：Windows Media Player 不显示首次使用对话框

### ISSUE THREAD

**Issue by Roger-WIN** [Chuyu-Team/Dism-Multi-language#251]
该规则开启后，在当前用户和离线映像下均无效。测试系统：Windows 10 Build 15063、16299.15。

**Comment by mingkuang-Chuyu** [comment]
此问题建议你反馈给微软…… 用的是策略规则。

Windows组件- Windows Media Player-不显示首次使用对话框

**Comment by mingkuang-Chuyu** [comment]
在gpedit中
