### ISSUE TITLE
提交规则：重建图标缓存/重建缩略图缓存

### ISSUE THREAD

**Issue by Arnaud-Github** [Chuyu-Team/Dism-Multi-language#252]
重建图标缓存
-----------------------------------------------------
cd /d %userprofile%\AppData\Local\Microsoft\Windows\Explorer
taskkill /f /im explorer.exe
attrib -h iconcache_*.db
del iconcache_*.db /a
start explorer
-----------------------------------------------------

重建缩略图缓存
-----------------------------------------------------
cd /d %userprofile%\AppData\Local\Microsoft\Windows\Explorer
taskkill /f /im explorer.exe
attrib -h thumbcache_*.db
del thumbcache_*.db /a
start explorer
-----------------------------------------------------

**Comment by mingkuang-Chuyu** [comment]
@MouriNaruto  你怎么看？合并到现有 缩略图缓存 规则？

**Comment by MouriNaruto** [comment]
DISM++内置的缩略图清理规则与你提供的两条规则加起来是等价的
` <Item Name="#缩略图缓存" Level="2">
      <Group>#缓存文件</Group>
      <ScanCollection>
        <Scan Type="Custom">
          <Name>#缩略图缓存(需重启explorer)</Name>
          <Description>#缩略图缓存（当前用户）</Description>
          <Applicable>
            <ImageFlags>1</ImageFlags>
          </Applicable>
          <Activate Restart="Explorer">
            <General RootPath="%LocalAppData%">
              <Query>Microsoft\Windows\Explorer\*</Query>
              <Query>IconCache.db</Query>
            </General>
            <ExplorerNotify Type="AssocChanged"/>
          </Activate>
        </Scan>
        <Scan>
          <Description>#缩略图缓存（所有用户）</Description>
          <Activate>
            <General RootPath="%SystemDrive%\Users\*\AppData\Local">
              <Query>Microsoft\Windows\Explorer\*</Query>
              <Query>IconCache.db</Query>
            </General>
          </Activate>
        </Scan>
      </ScanCollection>
    </Item>`
