### ISSUE TITLE
提交规则：关闭休眠、关闭快速启动、自定义chkdsk等待时间

### ISSUE THREAD

**Issue by powerxing04** [Chuyu-Team/Dism-Multi-language#255]
Windows Registry Editor Version 5.00

;关闭休眠
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Power]
"HibernateEnabled"=dword:00000000

;关闭快速启动
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Power]
"HiberbootEnabled"=dword:00000000

;开机自动chkdsk等待时间改为3秒，可以自定义时长（单位：秒）
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager]
"AutoChkTimeout"=dword:00000003

**Comment by mingkuang-Chuyu** [comment]
谢谢支持，未来版本会添加此类设置。

**Comment by mingkuang-Chuyu** [comment]
Hi， 关闭快速启动 此条目已经存在

开机自动chkdsk等待时间改为3秒，可以自定义时长。
这个就不考虑了，因为只在硬盘受损时才会出现。

关闭休眠功能 已经添加。请耐心等待新版本推送

**Comment by powerxing04** [comment]
谢谢采纳
