### ISSUE TITLE
建议增加：Microsoft Edge——禁止Adobe Flash的即点即用

### ISSUE THREAD

**Issue by PaTTeeL** [Chuyu-Team/Dism-Multi-language#256]
建议在 “控制面板——系统优化——Microsoft Edge”中增加项目，禁止Adobe Flash的即点即用

参见 组策略中 “Edge浏览器"——配置“Adobe Flash 即点即用”设置
![default](https://user-images.githubusercontent.com/9150277/31677614-f7a00c1c-b39d-11e7-9d07-48aa65ab82c8.png)

**Comment by mingkuang-Chuyu** [comment]
Hi，我想知道这样做的意义…… 似乎更多人喜欢 “即点即用” ？

**Comment by PaTTeeL** [comment]
好问题，更多人喜欢，也就是说有人不喜欢， 增加个选项让不喜欢的人有选择不是更好吗？
其次，edge的即点即用不是所有时候都生效的，某些flash页面并不会跳出即点即用，怎么刷新也没用，也就无法启用flash。
另外，部分win7的机器升级之后，edge替代了ie11，如果能去掉即点即用，既能迁移浏览器到edge，又避免了win7升级到win10的不适应，所以希望能有选项让edge更接近于ie的体验，当然你们可以做个提示这样会降低浏览器的安全性，会加载所有flash的网页使机器变慢等等。

**Comment by mingkuang-Chuyu** [comment]
好 下次添加

**Comment by mingkuang-Chuyu** [comment]
id b23e10a7，已经加入此功能支持。
