### ISSUE TITLE
建议修改：【系统优化】-【任务栏相关设置】-【任务栏时钟精确到秒】设置变动时新增重启explorer.exe操作

### ISSUE THREAD

**Issue by AnnAngela** [Chuyu-Team/Dism-Multi-language#258]
RT，我的系统是 Windows 10 Pro Version 1709 (10.0.16299.15) ，如果不重启explorer则不会应用这个设置的变动。

**Comment by mingkuang-Chuyu** [comment]
谢谢支持……Data.xml已经修正。请耐心等待新版本
