### ISSUE TITLE
希望添加功能:关闭JPEG壁纸质量压缩功能

### ISSUE THREAD

**Issue by Luupw3d** [Chuyu-Team/Dism-Multi-language#259]
原帖地址于 https://www.ithome.com/html/win10/218197.htm

在HKEY_CURRENT_USER\Control Panel\Desktop新建DWORD（32位）值，命名为JPEGImportQuality，把数值数据调整为100（可调整范围是60至100, “100”即“100%”，意为无压缩），重启explorer即可。

望考虑！谢谢

**Comment by mingkuang-Chuyu** [comment]
已经扩充至Data.xml，请耐心等待新规则更新。谢谢支持
