### ISSUE TITLE
NET3.5 Error message...

### ISSUE THREAD

**Issue by man0000** [Chuyu-Team/Dism-Multi-language#26]
Hi,

Since Build 15014 and now 15019 I get this Error message when try to Restore Health :

Dism++ can not find the installation source, if you need to enable
NET3.5 Please mount the ISO and then continue. If you need to fix
Windows, please try th options - to set the detailed local source. if that
fails, it is recommended that you use a repair installation.

This has never before appeared.
Am I doing anything wrong?.

MANY THANKS...

**Comment by mingkuang-Chuyu** [comment]
Please ignore this issue, which is Microsoft's problems. "Restore Health" couldn't fix your system.
