### ISSUE TITLE
在原有*.wim文件下，进行系统备份是增量的么，

### ISSUE THREAD

**Issue by wangqunsen** [Chuyu-Team/Dism-Multi-language#266]
在原有*.wim文件下，进行系统备份是增量的么，因为第一次备份60G，费时挺长，请问更改升级更新原有备份的时长

**Comment by mingkuang-Chuyu** [comment]
是 增量，具体时间不知道，要看具体硬件以及实际数据量。唯一能确定的就是时间比全量少
