### ISSUE TITLE
使用之后所有uwp都出现异常

### ISSUE THREAD

**Issue by 92lovehtc** [Chuyu-Team/Dism-Multi-language#268]
edge无法保存配置，微信无法打开，图片无法打开，基本都无法打开

**Comment by mingkuang-Chuyu** [comment]
Hi，建议你说明下详细情况。比如用了哪些功能，用了哪些清理项目。
具体报错什么错？
操作系统？

一般Dism++都不会引发这样的问题，除非是使用了`过期Appx清理`，但是这个项目属于专家模式专属。一般人也不会看到。

建议你先重启电脑然后在试试。另外请补充完整信息，谢谢。不然问题无法追踪

**Comment by guanglin1994** [comment]
他这个问题跟我那个类似   系统任务栏或者uwp应用快捷到任务栏的 左键单击无效
