### ISSUE TITLE
“更新管理”页面 中 “查找”按钮一定情况下不起作用

### ISSUE THREAD

**Issue by Dt8333** [Chuyu-Team/Dism-Multi-language#27]
有一个小问题，导致使用不太方便。
尝试通过查找补丁号(KB*******)来打某一个不推荐的（红色的）补丁，但打开查找页面输入补丁号并点击查找后却没有选中该补丁（实质是没有变色，还是红色，也没有任何提示）。
查找一个不存在的补丁，也没有诸如“找不到***”的提示。
查找一个列表中的，但在屏幕外的一个补丁，列表不滚动，也没有选中。
问题记录文件将发送到你们的邮箱。（Github竟无法上传zip？！）
       mingkuang@live.com 
希望下一版能处理这些问题。

**Comment by mingkuang-Chuyu** [comment]
谢谢，我明白了，我尽快修复此问题
