### ISSUE TITLE
问题反馈：进入主程序后即使不执行任务也会提示“正在执行任务，是否退出？”

### ISSUE THREAD

**Issue by WanJJ123** [Chuyu-Team/Dism-Multi-language#273]

**Comment by mingkuang-Chuyu** [comment]
Hi，应该是卡在网络请求了。

Dism++为了加速程序启动，网络检查新版本以及程序启动是并行的。

同样的，当程序退出时需要等待网络检查新版本完成才能退出。

建议加我QQ 343183163，让我看看是否真的网络卡住导致的。
谢谢

**Comment by mingkuang-Chuyu** [comment]
此文已经确认，就是网络迟迟无响应，导致卡在了自动更新检测上。

**Comment by mingkuang-Chuyu** [comment]
感谢 反馈，变更集 1546已经解决此问题。

新版本中，Dism++采用3小时间隔机制。不在每次都请求元数据。其次，将网络会话等待时间从30秒减少到了5秒。未来新版本应该将大幅度改进这方面的体验。

谢谢反馈
