### ISSUE TITLE
windows 10 唤醒 蓝屏是不是Dism++引起的?

### ISSUE THREAD

**Issue by masktao** [Chuyu-Team/Dism-Multi-language#274]
没怎么设置过系统,秋季创意更新升级安装,之前sleep后唤醒还没事的,貌似最近就用了Dism++弄过系统
一般只用空间回收
对了,用了撤回Compact功能
很奇怪,根本没用使用过compact功能,为啥之前C盘会提示compact, 最后一次使用撤回了compact,
然后现在sleep唤醒就蓝屏.按照网上文章扫描系统升级显卡驱动没用
![image](https://user-images.githubusercontent.com/13614353/32159634-4479f404-bd89-11e7-916e-e13e8f777023.png)

**Comment by powerxing04** [comment]
个人感觉是秋季版的bug或者与显卡驱动的兼容性

**Comment by mingkuang-Chuyu** [comment]
一般是你的硬盘控制器驱动问题

**Comment by masktao** [comment]
没有升级秋季版是没问题的,显卡也特意更新到最新,故障依旧

**Comment by masktao** [comment]
想起来了,升级秋季版后,有一次启动Dism后,系统盘显示Compact,但自己从来没有压缩过,于是就使用恢复功能里面的撤销Compact. 会不会因为这样引起的?
没有用过compact为什么会变成compact?

**Comment by masktao** [comment]
@mingkuang-Chuyu 显然并不是,刚升级完秋季版是可以从休眠唤醒一点问题没有的,自己也没做什么系统设置修改,唯一使用的就是Dism清理空间的功能,实在想不出其他原因造成

**Comment by masktao** [comment]
对了,没升级秋季版之前我关闭了系统的休眠功能,C盘根目录的休眠文件清除了,关机菜单只有sleep. 使用正常.
升级秋季版后记得又有了休眠问题,又使用命令关闭了根目录休眠文件.sys.
不确定是不是这样造成,因为以前没有这样蓝屏过,一直都用sleep

**Comment by mingkuang-Chuyu** [comment]
听你的描述 也可能是主板固件不兼容Windows 8，建议你看看你的主板提供商有没有新固件提供Win8特性支持。建议你先吧固件先升级到最新版，然后在试试。

也有可能是硬盘控制器不兼容你的系统，这个问题常见于Intel。

**Comment by mingkuang-Chuyu** [comment]
不过 你说一开始是可以使用，那么基本排除 硬盘控制器不 不兼容问题。不过你也要注意下，Windows 10会自动升级驱动……可能刚好给你升级到了不兼容的版本。

**Comment by mingkuang-Chuyu** [comment]
CompactOS系统本身也会使用……

**Comment by masktao** [comment]
感觉升级安装隐患多啊,还是得全新安装. 等明年春RS4出来重装算了,现在凑合用

**Comment by mingkuang-Chuyu** [comment]
暂时关闭此问题……目前也没有收到其他类似的反馈。如有需要可以重新打开此问题
