### ISSUE TITLE
Chrome全部无标题

### ISSUE THREAD

**Issue by JoJoJun** [Chuyu-Team/Dism-Multi-language#276]
使用之后chrome全部无标题，甚至打不开设置页面。重装之后默认打开的是正确的，但是打开快捷方式依然全是无标题

**Comment by mingkuang-Chuyu** [comment]
Hi，能否截个图，方便我验证问题？
另外能否告知 使用了那些功能?

**Comment by mingkuang-Chuyu** [comment]
此问题已经解决，是重启Explorer所致。重启电脑就能解决。另外新版本Dism++也解决了此文，也不再会导致此问题。
