### ISSUE TITLE
关于使用dism++的一些建议

### ISSUE THREAD

**Issue by scccboom** [Chuyu-Team/Dism-Multi-language#277]
官网
===
管网的背景颜色稍微有点刺眼。不知道是不是我显示器亮度的问题:)。

工具
===
1. UI线程普遍有阻塞现象。
2. 更新管理，建议参照360漏洞修复模块的设计：
   - 能先下载所有更新包再执行更新
   - 能在后台执行更新工作不影响其他模块的使用
   - 能将下载地址导出到文本文件，每行一个地址，便于使用其他下载工具批量下载

**Comment by mingkuang-Chuyu** [comment]
官网是这样亮的，不过目前也懒得改了。还没找到适合的颜色。

# 能先下载所有更新包再执行更新
安装更新会占用CBS接口，这将导致Dism++其他大部分功能被阻塞。所以
能在后台执行更新工作不影响其他模块的使用，这个也没什么意义，另外Dism++设计也是如此，一个系统是一个回话，而一个回话只能做一件任务，否则就被阻塞。

# 能先下载所有更新包再执行更新
这个功能没什么意义，先下载更新在装，还是边下边安装没有什么本质区别。另外一般来说边下边安装往往速度更快。

# 能将下载地址导出到文本文件，每行一个地址，便于使用其他下载工具批量下载
这个功能本来就是支持的
