### ISSUE TITLE
Win 8和Vista的更新管理

### ISSUE THREAD

**Issue by xdriftdoll** [Chuyu-Team/Dism-Multi-language#278]
我之前拿原盤Win 8和Vista SP2，DISM都會說系統已安裝最新的修正檔，這個問題有解嗎？先謝謝了。

**Comment by mingkuang-Chuyu** [comment]
Hi，这没有问题。因为Dism++数据库中并没有加入 Win8 Vista系统的数据，因为他们的用户量太少了。已经放弃支持。可以考虑升级到Win7或者 8.1
