### ISSUE TITLE
系统时间戳报错

### ISSUE THREAD

**Issue by cybing2008** [Chuyu-Team/Dism-Multi-language#28]
win10中挂载win7的install.wim，dism++报错"根据当前系统时间或签名文件中的时间戳验证时要求的证书不在有效期内。"且直接退出，无法挂载。
win7中挂载同一win7的install.wim，没有任何问题。

将系统时间调整到2017年以前，则没有任何问题。

**Comment by mingkuang-Chuyu** [comment]
Hi，建议你使用微软自带的Dism命令试试
Dism /Mount-Wim /WimFile:C:\test\images\myimage.wim /index:1 /MountDir:C:\test\offline /ReadOnly

如果微软的没问题，咋们在QQ联系
我的QQ是 343183163
谢谢

**Comment by mingkuang-Chuyu** [comment]
用户长时间无应答 也为加我QQ，暂时关闭此问题。如果在后来回复后在重新打开此问题
