### ISSUE TITLE
dism++备份win10显示句柄失效，备份失败

### ISSUE THREAD

**Issue by ljl9919** [Chuyu-Team/Dism-Multi-language#284]
之前是用dism++做备份，系统有问题就用dism++恢复了。打完补丁之后再备份就提示句柄无效。
另外dism++恢复系统后开机时间明显增加。

**Comment by mingkuang-Chuyu** [comment]
Hi，这样的错误一般都是硬盘文件受损所致。
具体可以参考日志，Config/Dism++.log。会输出具体无法读取的文件。

**Comment by ljl9919** [comment]
GLOBALROOT\Device\HarddiskVolumeShadowCopy1\Program Files\Lenovo\SettingsDependency\IntelligentSense\setup.exe 0x00000006
这个错误。

**Comment by verdy-p** [comment]
**Dism++ backup on Win10 display handle failure, backup failed (rough translation)

Before using Dism++ backup, the system has been using Dism++ recovery.
After the patch after the backup prompts the handle is invalid.
In addition, Dism ++ recovery system significantly increased boot time.

**Comment by mingkuang-Chuyu** [comment]
建议你手动复制这个文件试试
C:\Program Files\Lenovo\SettingsDependency\IntelligentSense\setup.exe 

我猜测 此文件已经损坏。

如果手动可以复制这个文件，那么还请加我QQ 343183163。咋们方便联系。

谢谢

**Comment by mingkuang-Chuyu** [comment]
用户没有新回复，如果有更多信息可用，那么可以重新打开此问题。

**Comment by 1523789353** [comment]
2020-12-05 00:24:45, Error	PID=13212 TID=6648, Wimgapi	\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy1\Program Files\Microsoft Office\Updates\Download\PackageFiles\E026FBC2-6244-49DB-AFB1-304FC600F441\root\Office16\CHAKRACORE.DLL 0x00000006

**Comment by 1523789353** [comment]
同样是"句柄失效"错误,但奇怪的是在WinRe下可以备份

**Comment by 1523789353** [comment]
最近给C盘加了个Bitlocker
WinRe下Dism++读不出盘
所以进WinRe备份的方法也失效了

**Comment by 1523789353** [comment]
正在尝试chkdsk C: /f /x后备份...

**Comment by 1523789353** [comment]
chkdsk不管用,C盘没有任何错误...
但是瞧瞧我发现了什么...我在网上找不到任何相关资料...
![屏幕截图 2020-12-05 145149](https://user-images.githubusercontent.com/39769643/101236136-8cb77a00-3709-11eb-9c34-c31d03b8296e.png)

**Comment by 1523789353** [comment]
问题解决了,删了整个C:\Program Files\Microsoft Office\Updates\Download文件夹

之前尝试只删CHAKRACORE.DLL但仍有问题，索性直接删了整个目录
