### ISSUE TITLE
希望增加自定义规则

### ISSUE THREAD

**Issue by thomasmolover** [Chuyu-Team/Dism-Multi-language#288]
能自己命名一些注册表的规则, 不必提交的, 这样就可以在装机的时候进行调整了

**Comment by verdy-p** [comment]
**Hope to add custom rules**
Can name some registry rules, do not have to submit, so that you can adjust when installed.

**Comment by mingkuang-Chuyu** [comment]
Hi，支持此功能
你可以把自己的规则打包为 Custom**XXXX**.zip，再放Config目录即可。XXXX任意即可，只需要保证Custom开头，并且 zip打包即可。
