### ISSUE TITLE
Missing translation items

### ISSUE THREAD

**Issue by verdy-p** [Chuyu-Team/Dism-Multi-language#289]
The following items (in the Paameters panel) are shown only in Chinese, please add them in English in all translation resource files (with q="" for marking them as fuzzy for all languages other than English). We cannot locate them in the any resource bundles.

Please consider that these strings in Chinese are extremely difficult to enter in text editors to update them if we are not native Chinese readers and don't know how to use a Chinese IME. and impossible to translate using external search tools, so almost all users (except in China) absolutely don't know what to do with them and what are their impact.

**So as a general rule, NEVER publish any new Chinese text in Dism++ without publishing at least an English translation that can then be translated.**

**Suggestions:**
* allow all texts in these panels to be selectable with the mouse and copied, so we can use external translation tools to know what they mean: this is important for all languages, as the UI may be partially understood and the UI may still be partially translated.**
* if a text is truncated on display, hovering it with the mouse should popup an help bubble containing the full text.

**The current missing translations are:**

* Windows themes (1 item, "??? (by IThome)"):
* Startup and Windows experience (1 item, "??? by (powerxing04)"):
![dism chinese options1](https://user-images.githubusercontent.com/1387035/33171093-37baea0a-d04b-11e7-90b9-18b8d4007cc4.png)

* Context menus (2 items, "??? (by choyri)"):
* Microsoft Edge (1 item, "??? Adobe Flash ???"):
![dism chinese options2](https://user-images.githubusercontent.com/1387035/33171097-3925e1ce-d04b-11e7-9914-84f0d614f310.png)

* Others (2 items, "??? (by powerxing04)"):
![dism chinese options3](https://user-images.githubusercontent.com/1387035/33171099-3a44ba08-d04b-11e7-90ae-8923e542120a.png)

**Comment by mingkuang-Chuyu** [comment]
Please wait~

**Comment by mingkuang-Chuyu** [comment]
ef755115, pushd now~~
you can search for q=\“\”.

: )

best

mingkuang

**Comment by masx200** [comment]
下列项目（在Paameters面板中）仅以中文显示，请在所有翻译资源文件中以英文添加（用q =“”表示对于除英语以外的所有语言都是模糊的）。我们无法在任何资源包中找到它们。

如果我们不是中国本土读者，也不知道如何使用中文输入法，请认为这些中文字符串非常难以进入文本编辑器进行更新。而且不可能使用外部搜索工具进行翻译，所以几乎所有的用户（中国除外）都完全不知道如何处理它们以及它们的影响。

所以作为一般规则，不要在Dism ++中发布任何新的中文文本，至少不要发布可以翻译的英文翻译。

建议：

允许这些面板中的所有文本都可以用鼠标进行选择并进行复制，因此我们可以使用外部翻译工具来了解它们的含义：这对于所有语言都很重要，因为可能会部分理解UI，并且仍然可能会部分翻译UI **
如果文本被截断显示，用鼠标悬停它应该弹出包含全文的帮助气泡。
目前缺少的翻译是：

Windows主题（1项，“???（IThome）”）：

启动和Windows体验（1项，“??? by（powerxing04）”）：
dism中文options1

上下文菜单（2项，“???（by choyri）”）：

Microsoft Edge（1项，“Adobe Flash ???”）：
dism中文options2

其他（2项，“???（by powerxing04）”）：
dism中文options3

**Comment by mingkuang-Chuyu** [comment]
Done~
