### ISSUE TITLE
win10安装更新kb3213986会出现“参数错误的”提示

### ISSUE THREAD

**Issue by wikilike7** [Chuyu-Team/Dism-Multi-language#29]
win10安装更新kb3213986会出现“参数错误的”提示，尝试了好几次一直是这个错误

**Comment by mingkuang-Chuyu** [comment]
此问题是微软自身的堆栈问题，可以自己下载KB3213986 然后安装，会发现一样的错误
建议你将此问题反馈给微软。这个问题已经有2个月了，可能这个补丁日就修复了。

我暂时先关闭了问题，如果你发现手动安装更新成功了，你可以再次打开此问题，谢谢
