### ISSUE TITLE
Backup files of Opera browser old version - by Jhovany200

### ISSUE THREAD

**Issue by Jhovany200** [Chuyu-Team/Dism-Multi-language#291]
[Backup files of Opera Web Browser old version.txt](https://github.com/Chuyu-Team/Dism-Multi-language/files/1502692/Backup.files.of.Opera.Web.Browser.old.version.txt)
=======================================================
I was wondering if they can add to clean the old version of the Opera browser.
The whole process is based on Google Chrome.
""My goal is only to collaborate"".

""Please correct if something is wrong"".

**Comment by mingkuang-Chuyu** [comment]
Thanks~~ ：)

**Comment by mingkuang-Chuyu** [comment]
f30456f8, add this rul now.

Best
