### ISSUE TITLE
Dism++无法转换高版本UUP esd 问题

### ISSUE THREAD

**Issue by mingkuang-Chuyu** [Chuyu-Team/Dism-Multi-language#292]
反馈者：初生之鸟

Host：17040

**Comment by masx200** [comment]
我也遇到这个问题啊

**Comment by mingkuang-Chuyu** [comment]
此问题已经发现根源所在，并且已经解决。
当选择ActionList.xml转ISO时不会有问题，但是选择Professional_zh-cn.esd这样的转换就会触发问题。

根源是新的Windows 10已经改变了加载方式，改成了从路径加载。

今天会发送新的Beta。谢谢，请耐心等待推送。
