### ISSUE TITLE
Windows 8 and Cleanup of Replaced WinSxS assemblies

### ISSUE THREAD

**Issue by Slavah80** [Chuyu-Team/Dism-Multi-language#295]
Hi there,

Trying to get some extra space by cleaning Replaced WinSxS assemblies in Windows 8 64bit embedded edition, but it fails with error in the log file:
2017-09-02 23:55:17, Debug	PID=10812 TID=15900, Dism++消息循环	消息循环已经退出！
and
2017-11-27 21:34:18, Info	PID=3784 TID=3788, Dism++	成功启动，程序版本: 10.1.1000.51，CBS抽象层: 10.1.1000.50，Host版本：6.2.9200.22254
2017-11-27 21:34:39, Info	PID=3784 TID=3788, 空间回收	正在进行扫描或清理

However, if Scan selected for this option it correctly shows how much space can be freed - 5+ Gb.
So, wonder if this can be considered to be fixed out, since this just for Thin Clients where just 15 Gb of HDD space available for Windows and applications. Can also upload reference WIM file for this to test out ~ 900 Mb.
This neither working with the reference image downloaded from Microsoft, not with updated image where all possible hotfixes\updates installed. Already was trying to repair image with DISM and DISM++, no luck.

Would be appreciate for your help with this - really needed:)

Thanks

**Comment by Slavah80** [comment]
Enclosing CBS.log
[OfflineCbs.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/1505178/OfflineCbs.log)

**Comment by Slavah80** [comment]
Sorry closed one accidentally...

**Comment by mingkuang-Chuyu** [comment]
Please Update to Windows  8.1, this feature does not fully support Win8.
