### ISSUE TITLE
在需要输入镜像路径的对话框中手动输入路径导致频繁提示参数错误

### ISSUE THREAD

**Issue by keeeeymann** [Chuyu-Team/Dism-Multi-language#297]
在挂载镜像、释放镜像等等需要输入镜像路径的对话框中，如果手动输入镜像路径，则程序在**每一层目录输入完后**（反斜杠结束后）都会自动跳出一次“参数错误”的对话框。虽然除此之外没有任何功能上的问题，但会造成极大不便，望修复。
![snipaste_2017-11-28_16-12-52](https://user-images.githubusercontent.com/22412315/33308839-0e02c2a4-d457-11e7-880e-c2e1e04c8ff6.png)

**Comment by mingkuang-Chuyu** [comment]
谢谢反馈，确实考虑不妥

**Comment by mingkuang-Chuyu** [comment]
此问题已经解决，请耐心等待新版本推送。
解决变更集：1545
