### ISSUE TITLE
我清理完C盘显卡驱动总共14G 为什么C盘就多了3G

### ISSUE THREAD

**Issue by voynich-chen** [Chuyu-Team/Dism-Multi-language#299]
那11G内存去哪了  正在找  疯了

**Comment by zlx42** [comment]
重启一下试试，我记得以前我清理图片缓存是重启一下机器才行。还有我有一次在re环境用dism++的文件管理器删除文件，但是空间也没回来，回收站也没有记录。后来在空间回收里重新扫描了一遍才清理出空间。还有你确定你清除了？在驱动管理里看看显示设配器里是不是只有一版的驱动，有多的话说明在driverstore里还没清除。

**Comment by voynich-chen** [comment]
的确清除了我去c盘那个文件夹去看了 的确少了14G 只是C盘显示只多了3G  ， 只剩下一个驱动了  重启了三次了 就是找不到剩下的11G 


------------------ 原始邮件 ------------------
发件人: "zlx42";<notifications@github.com>;
发送时间: 2017年11月30日(星期四) 中午12:36
收件人: "Chuyu-Team/Dism-Multi-language"<Dism-Multi-language@noreply.github.com>;
抄送: "✎﹏尘馨｡◕‿◕｡"<2277952561@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Chuyu-Team/Dism-Multi-language] 我清理完C盘显卡驱动总共14G 为什么C盘就多了3G (#299)




重启一下试试，我记得以前我清理图片缓存是重启一下机器才行。还有我有一次在re环境用dism++的文件管理器删除文件，但是空间也没回来，回收站也没有记录。后来在空间回收里重新扫描了一遍才清理出空间。还有你确定你清除了？在驱动管理里看看显示设配器里是不是只有一版的驱动，有多的话说明在driverstore里还没清除。

**Comment by zlx42** [comment]
你用的是空间回收还是驱动管理删除的？
驱动管理手动删除的应该不会有问题，空间回收的话记得勾选windows缓存啊，下载缓存之类的，还有winsxs临时文件。
反正就是默认的再多加 过期驱动，windows下载缓存，英伟达驱动安装源缓存，英伟达驱动安装包，临时文件。
上次我在re里删除就是靠这样恢复了10G的空间，但是当时没太注意是那个选项占了空间，但是我一般都是这样选然后清除系统垃圾的。你可以试试看

**Comment by mingkuang-Chuyu** [comment]
无视即可…… 因为某些功能只计算文件大小，并不计算硬盘真实占用。
