### ISSUE TITLE
可以考虑添加去掉文件夹右上角蓝色双箭头选项

### ISSUE THREAD

**Issue by dfc643** [Chuyu-Team/Dism-Multi-language#3]
感觉工具命令挺多的，基本上可以替代常用的系统 Tweaker 类工具了。
可以考虑添加隐藏 NTFS 压缩文件右上角的蓝色双箭头标志，对强迫症有帮助  : )

http://www.ithome.com/html/win10/197657.htm

**Comment by EMLVIRUS** [comment]
个人来说不希望这样以便于区分

**Comment by mingkuang-Chuyu** [comment]
感谢 已经添加到Beta版库中……
