### ISSUE TITLE
安装更新失败

### ISSUE THREAD

**Issue by kt1024** [Chuyu-Team/Dism-Multi-language#30]
安装KB3213986失败。之前用DISM成功装过几次更新的，如下图：
![image](https://cloud.githubusercontent.com/assets/12657496/23004030/3fba79bc-f42f-11e6-92ff-9c9ff7a0b688.png)
![image](https://cloud.githubusercontent.com/assets/12657496/23004032/428d1258-f42f-11e6-8eac-082c7bdbcd4e.png)
谢谢。

**Comment by mingkuang-Chuyu** [comment]
谢谢 反馈，还请加我QQ 343183163，我需要看点现场环境，来确定具体问题

**Comment by wikilike7** [comment]
还是kb3213986的问题嘛，和我反馈的一模一样，windows 10的补丁真是够水的

**Comment by mingkuang-Chuyu** [comment]
@wikilike7  @kt1024  感谢支持，在远程协助下，一句找到了问题。是差异传输引擎的快速模式存在一处代码缺陷，某些环境中无法感知到源文件目录。

可以在设置  详细设置  差异传输引擎调整为 完整 或者 关闭 即可

**Comment by mingkuang-Chuyu** [comment]
@wikilike7 能否加QQ 让我确认下你们是否是同一个问题？

**Comment by mingkuang-Chuyu** [comment]
此问题微软系统多个补丁暂存时处理BUG才是根本原因，暂时关闭此问题   如果有需要以后在重新打开此问题。
