### ISSUE TITLE
Temporary files of "IDM" or "Internet Download Manager"

### ISSUE THREAD

**Issue by Jhovany200** [Chuyu-Team/Dism-Multi-language#300]
"IDM" is acronym in English, in the "Description" shows the full name so that it is better understood.

[Temporary files IDM.txt](https://github.com/Chuyu-Team/Dism-Multi-language/files/1523464/Temporary.files.IDM.txt)
==================================================================

""If I'm wrong I can correct it"".
""My goal is only to collaborate"".

**Comment by mingkuang-Chuyu** [comment]
5d147d43, done~ Thanks
