### ISSUE TITLE
无法删除非当前系统的appx，提示不支持此接口，windows 10 pro 10.0. 17025.1000 x64

### ISSUE THREAD

**Issue by masx200** [Chuyu-Team/Dism-Multi-language#301]
无法删除非当前系统的appx，提示不支持此接口，windows  10 pro 10.0. 17025.1000 x64
希望能解决这个问题

**Comment by mingkuang-Chuyu** [comment]
这个问题应该不是问题，你的系统应该已经经过OOBE，所以导致Dism++无法移除。

离线删除Appx，必须是全新系统。没有进入过桌面的系统。
