### ISSUE TITLE
esd转iso功能目前不能转换Windows 10 统一更新平台（UUP），强行转换会报错，例如Windows-Insider-Windows-10-Insider-Preview-17046.1000-(rs-prerelease)-[x64]-Chinese-(Simplified)-Professional

### ISSUE THREAD

**Issue by masx200** [Chuyu-Team/Dism-Multi-language#303]
esd转iso功能目前不能转换Windows 10 统一更新平台（UUP），强行转换会报错，例如Windows-Insider-Windows-10-Insider-Preview-17046.1000-(rs-prerelease)-[x64]-Chinese-(Simplified)-Professional

**Comment by masx200** [comment]
amd64fre_Client_zh-cn_lp.esd
Microsoft-OneCore-ApplicationModel-Sync-Desktop-FOD-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-Client-Features-Package.ESD
Microsoft-Windows-Client-Features-WOW64-Package.ESD
Microsoft-Windows-EditionPack-Professional-Package.ESD
Microsoft-Windows-EditionPack-Professional-WOW64-Package.ESD
Microsoft-Windows-EditionSpecific-Professional-Package.ESD
Microsoft-Windows-EditionSpecific-Professional-WOW64-Package.ESD
Microsoft-Windows-Foundation-Package.ESD
Microsoft-Windows-Hello-Face-Resource-A-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-Hello-Face-Resource-B-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-Hello-Face-Resource-C-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-Holographic-Desktop-Analog-Package.ESD
Microsoft-Windows-Holographic-Desktop-Merged-Package.ESD
Microsoft-Windows-Holographic-Desktop-Merged-WOW64-Package.ESD
Microsoft-Windows-InternetExplorer-Optional-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-LanguageFeatures-Basic-zh-cn-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-LanguageFeatures-Handwriting-zh-cn-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-LanguageFeatures-OCR-zh-cn-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-LanguageFeatures-Speech-zh-cn-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-LanguageFeatures-TextToSpeech-zh-cn-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-MediaPlayer-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-QuickAssist-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-RegulatedPackages-Package.ESD
Microsoft-Windows-RegulatedPackages-WOW64-Package.ESD
Microsoft.ModernApps.Client.All.esd
Microsoft.ModernApps.Client.professional.esd
Professional_zh-cn.esd

**Comment by masx200** [comment]
> 
amd64fre_Client_zh-cn_lp.esd
Microsoft-OneCore-ApplicationModel-Sync-Desktop-FOD-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-Client-Features-Package.ESD
Microsoft-Windows-Client-Features-WOW64-Package.ESD
Microsoft-Windows-EditionPack-Professional-Package.ESD
Microsoft-Windows-EditionPack-Professional-WOW64-Package.ESD
Microsoft-Windows-EditionSpecific-Professional-Package.ESD
Microsoft-Windows-EditionSpecific-Professional-WOW64-Package.ESD
Microsoft-Windows-Foundation-Package.ESD
Microsoft-Windows-Hello-Face-Resource-A-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-Hello-Face-Resource-B-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-Hello-Face-Resource-C-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-Holographic-Desktop-Analog-Package.ESD
Microsoft-Windows-Holographic-Desktop-Merged-Package.ESD
Microsoft-Windows-Holographic-Desktop-Merged-WOW64-Package.ESD
Microsoft-Windows-InternetExplorer-Optional-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-LanguageFeatures-Basic-zh-cn-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-LanguageFeatures-Handwriting-zh-cn-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-LanguageFeatures-OCR-zh-cn-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-LanguageFeatures-Speech-zh-cn-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-LanguageFeatures-TextToSpeech-zh-cn-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-MediaPlayer-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-QuickAssist-Package~31bf3856ad364e35~amd64~~.cab
Microsoft-Windows-RegulatedPackages-Package.ESD
Microsoft-Windows-RegulatedPackages-WOW64-Package.ESD
Microsoft.ModernApps.Client.All.esd
Microsoft.ModernApps.Client.professional.esd
Professional_zh-cn.esd

**Comment by mingkuang-Chuyu** [comment]
感谢反馈，此问题已经修复，Beta已经推送。
相关BUG：
https://github.com/Chuyu-Team/Dism-Multi-language/issues/292
