### ISSUE TITLE
Windows 7 使用Dism++清理缩略图缓存之后Chrome浏览器打不开任何网页

### ISSUE THREAD

**Issue by SpDChen** [Chuyu-Team/Dism-Multi-language#304]
系统：Windows 7 旗舰版 SP1 x64
Google Chrome 版本号： 63.0.3239.84 (64位)
当我清理缩略图缓存之后，Chrome就显示无标题，打开任何网页都是无标题，设置界面都是无标题。希望Dism++能尽快修复此问题。

影响等级：
中等

临时解决方案：
重启电脑或者手动重启explorer自动恢复。

影响范围：
所有Dism++需要重启explorer相关规则均受影响。（Dism++/Dism++ Beta）

**Comment by mingkuang-Chuyu** [comment]
我去尝试下，不过最好提供Chrome版本号。因为如果你不提供 我将使用最新版 Chrome。

**Comment by SpDChen** [comment]
去Chrome官网下载的最新版Chrome

**Comment by SpDChen** [comment]
系统是Windows 7 旗舰版 64位 SP1

**Comment by sumver** [comment]
我也遇到了，清理了导致chrome打不开任何页面包括chrome://命令。同时扩展都被删除，chrome提示扩展崩溃。望排查。
相关信息：
win7 sp1专业版，Chrome版本号：63.0.3239.84(64位)

**Comment by SpDChen** [comment]
+1，希望Dism++尽快检查这个问题

**Comment by mingkuang-Chuyu** [comment]
已经确认~

**Comment by mingkuang-Chuyu** [comment]
@MouriNaruto  本地完美复现，确认是 `缩略图缓存（需重启Explorer） `这个项目

**Comment by mingkuang-Chuyu** [comment]
已经更新临时解决方案，此问题并非误杀导致。

**Comment by mingkuang-Chuyu** [comment]
Dism++ Beta 10.1.2002.43已经解决此问题
