### ISSUE TITLE
Win10 64位系统驱动管理清理功能缺失。

### ISSUE THREAD

**Issue by HowquaX** [Chuyu-Team/Dism-Multi-language#31]
驱动管理模块没有删除的功能。只有导入导出……
![default](https://cloud.githubusercontent.com/assets/18021450/23069488/9bd12be0-f562-11e6-8b89-02088f7351ce.jpg)

**Comment by MouriNaruto** [comment]
Dism++只有在专家模式下才有删除驱动的功能
![1](https://cloud.githubusercontent.com/assets/10867563/23090359/cb2718f8-f5d7-11e6-851f-5441304b63e5.png)
![2](https://cloud.githubusercontent.com/assets/10867563/23090361/cb4d17a6-f5d7-11e6-8a33-cadb032611f8.png)
![3](https://cloud.githubusercontent.com/assets/10867563/23090358/cb25ef64-f5d7-11e6-88ff-6b3139e8f3e7.png)
![4](https://cloud.githubusercontent.com/assets/10867563/23090360/cb2fda42-f5d7-11e6-96f3-794032d822c9.png)
