### ISSUE TITLE
关于右键菜单去除“NVIDIA控制面板”改进建议

### ISSUE THREAD

**Issue by sumver** [Chuyu-Team/Dism-Multi-language#310]
由于我电脑的右键菜单里，NVIDIA选项和集显选项都集中在“用图形处理器运行”一级菜单下，Dism++的“禁用桌面的英特尔集显”和“禁用NVIDIA控制面板”不生效。
[点此查看图片](https://pan.baidu.com/s/1dE22Oq1)

**Comment by mingkuang-Chuyu** [comment]
建议你提供相关规则……谢谢。因为我本机没有这玩意。我不知道该处理什么注册表。或者给我远程看看。谢谢

**Comment by mingkuang-Chuyu** [comment]
用户长期无回复 关闭此问题。如果有更多信息可用，则可以重新打开此问题。
