### ISSUE TITLE
建议增加通过企业内网wsus服务器更新wim镜像包的系统补丁

### ISSUE THREAD

**Issue by iampp7511** [Chuyu-Team/Dism-Multi-language#314]
现有“更新管理”功能，似乎是通过软件调用配置文件夹下的“wsusscn2.cab”文件，而后做相关处理的，相关补丁还需要连接外网去下载，比较费时费力。
建议如技术上可行的话，能否在相关配置文件中增加企业内网wsus服务器的相关选项，这样就能直接下载企业内网已经部署审批好的系统及Office等相应微软产品的补丁了。
非常感谢各位编写了这款软件，能简化系统管理员的不少工作。

**Comment by mingkuang-Chuyu** [comment]
虽然Dism++可以做到，建议你直接使用Windows Update。反正都能满足你的要求。
