### ISSUE TITLE
关于账户管理功能的建议

### ISSUE THREAD

**Issue by 2810676203** [Chuyu-Team/Dism-Multi-language#317]
可否添加一个 查看和修改用户密码的功能
还有 添加用户 和 更改用户名 的功能

**Comment by mingkuang-Chuyu** [comment]
请问 这些功能 有什么意义？

这个功能的初衷是为了解决开机密码忘记的人，所以主要功能就是清空密码。

另外，就算做了添加用户功能，OOBE后也并不能使用。所以我都不明白这些功能有什么意义？你有的意图是什么？

**Comment by mingkuang-Chuyu** [comment]
长时间没有回复，暂时关闭。 如果有什么问题可以重新打开此问题
