### ISSUE TITLE
最近几个版本,根本没办法清理了

### ISSUE THREAD

**Issue by ugksoft** [Chuyu-Team/Dism-Multi-language#32]
1.
在升上去的,从网上下的压缩包.都一样,都不能清理了

空间回收->除"Windows更新历史记录"外,我一般是全选的
扫描,可以看到WinSxs过期文件,临时文件,有好几百MB,全部垃圾加起来,超过1G
但是,清理后,可能只显示删了xxMB,重新扫描后,垃圾还在(占用大小显示上判断,而不是实际文件,因为不清楚有哪些文件,没办法实际去硬盘上看是不是误检测)

2.添加添加delphi7或其它版本的历史删除功能
HKEY_CURRENT_USER\Software\Borland\Delphi\7.0\Closed Files
HKEY_CURRENT_USER\Software\Borland\Delphi\7.0\Closed Projects

3.QQ群多少号啊, 这里都不能发图的...
 软件上的帮助->QQ群  哪个傻x想出来的?  这只有在完整安装qq,并且是IE时,才能调用QQ的COM组件的
 直接写在上面关于里,或是网站上,不好吗?

4.对话框,能不能改成可以拖大小啊!!,列表里多了,只能最大化窗口来看

我的系统是Win64

**Comment by mingkuang-Chuyu** [comment]
1: Dism++无法删除某些被占用的文件，因此 临时目录删除不干净都是正常的……

2：delphi7历史文件功能，我会转告青蛙

3：你能问这个问题，我不是说你，你也是神，首先 不说程序启动后 UI立马会显示 QQ群号码，网站的关于里面也写了QQ群号。你居然还能问 QQ群号码是多少…… 

4： Dism++本来就是可以拖动大小

最后 我有疑问了，你确定用的是Dism++吗？

**Comment by ugksoft** [comment]
关于3
http://www.chuyu.me/zh-Hans/index.html的关于里,没有QQ群号 ,根本没的点击的"关于"
查了一下,是在"帮助"里有QQ群号


关于4:拖动大小,哦,是我错了,拖时,鼠标可能点的位置不准,加班加点的,眼花了




不知道图片是否能显示,你那破回复地址,看似一个邮箱地址


=>


扫描完


=>清理




清理完后,重新扫描,


感觉是在清理过程中发生了意外,没有继续清下去似的
以前还提示清理出多少空间,想给你截图,但是居然没有弹出清理了xxMB的对话框了,....
以前explorer的图标缓存,也是没办法清理的,有上百MB,这次截图不知道为什么,只有2M了,但去看实际文件,有11M












在 2017-02-21 18:27:32，"mingkuang" <notifications@github.com> 写道：


1: Dism++无法删除某些被占用的文件，因此 临时目录删除不干净都是正常的……

2：delphi7历史文件功能，我会转告青蛙

3：你能问这个问题，我不是说你，你也是神，首先 不说程序启动后 UI立马会显示 QQ群号码，网站的关于里面也写了QQ群号。你居然还能问 QQ群号码是多少……

4： Dism++本来就是可以拖动大小

最后 我有疑问了，你确定用的是Dism++吗？

**Comment by ugksoft** [comment]
1.
 dism以前,是可以非常干净的清理,winsis或其它可以清查的非常干净
  explorer的缓冲图标,也删干净的,explore是被杀后再删的,所以不存在占用问题
 总体感觉是,某个清理过程出了意外,害的后面步骤没有进行下去

如果有其它有问题,我会qq群里说

2. 
  ok
3.qq群号是在帮助里,不在关于里,"关于"都不能点的
  
4,是可以拖动,可能我太累了
  ok.是可以的,我真的太累了,

**Comment by mingkuang-Chuyu** [comment]
1： explorer的缓冲图标 只是一部分，这个确实会杀掉explorer，不会有占用问题。但是还有其他Temp……以及一些缓存，怎么可能不存在占用的情况，除非你把所有的程序都关闭了
3： QQ群号，明明在程序主界面就有，你居然还没发现 说在 帮助里……

我建议你多休息……不好好休息 怎么好好使用程序呢

**Comment by ugksoft** [comment]
sorry ,我也是做开发的,还是做底层算法的,加班加点的,已经职业病了,一跟筋了,想到这些,就到关于之类的地方找, 而软件本身界面操作之类,自己不关注的,眼睛就不会往那些地方瞄.  QQ群我加了,还是从网站的帮助里找到的(前面内容说帮助,关于,都是说网页里,而不是软件上,压跟儿没注意,你把qq群号与在软件主界面中央)
qq群我加了,里面的人都是在东拉西扯,不淡技术的,闲扯,所以我又退了,

**Comment by ugksoft** [comment]
关于不能删除的几些文件,我查了,确实有几个文件没"SYSTEM"锁定了,你应该加个提示,说部分文件因占用,没能删,愿意就列个清单,不愿意就只提示下次启动删或是下次扫描时再删等
现在什么也不提示,甚至扫描完,都不提示清理了多少空间(可能一个文件都没删掉,所以不提示吧),
会让人误会是出错了,或是软件作者代码上条理混乱等

**Comment by mingkuang-Chuyu** [comment]
当程序清理出空间时，程序会提示 清理了多少，当没有清理出空间时 程序不会提示。此外 删除失败的 会统一写入日志，不对UI提示。删除失败都是很正常的， Config/Dism++.log 记录了详细删除失败原因

另外QQ群也不是谈技术的，而是 反馈问题的，没问题时自然他们也会扯淡

**Comment by ugksoft** [comment]
en.那推荐改进一下吧,log文件放在config里,也真够变态的
没删文件,就什么也不提示,也太不符合常规做法了

改成,不管是否成功,都提示, 

--提示-------------------------
总共删掉多少文件,几个文件因占用,未能删除, 
总共清理多少空间, 未清理多少...
详见:
  Dism++/Dism++.log
---------------OK----------------


我不是强制的意思,只是推荐, dism确实不错,清理了微软变态的sxs文件,估计这种做法是阿三想出来的,阿三都已经控制很多科技类公司了,搞的最近几年软件类公司中,逻辑上和技术上等都超级的差,

**Comment by ugksoft** [comment]
扫描时,根据系统情况,自动隐藏不需要清理的项目,这种做法也是有点问题的
在清理时,因为速度不同,有些隐藏的慢,有的隐藏的快,给人的感觉是,这个列表框显示的不够稳定
可能存在代码问题,列表错误等,
你这样动态的隐藏, 有点画蛇贴足

可能你没看过UI心理的书(这类书,在10多年前有,现在没有这类书了),也编程时间不长
这个应该是先不删除,扫描到哪条,就哪条高亮或其它进度的意思,.如果没找到垃圾,就显示 0
全部扫描完后,继续显示不需要清理的项目,或是再去把不需要的隐掉(速度快)

引导修复的那个,建议提示一下原理,比如写盘512B的MBR,还是调用哪个程序来处理等
毕竟是危险操作,你不写清楚,懂的人,会不敢往下点的

顶部系统版本,那里,不知道别人如何,但我这里只显示"版本\nC:\本地硬盘\n\准备就绪"
占了四行, 右边空白,这太高地方了吧, 如果你想这样大点,那么右边放个logo,或是放点硬盘smartdrv之类的信息


----------------
**实在不好意思,白用你的程序,还挑毛病,**

**Comment by mingkuang-Chuyu** [comment]
谢谢你的意见，但是日志以及提示哪里还是算了。因为那些错误顶多是一些文件占用而无法删除。用户不需要去关注那些小错误，何况大部分用户也没有能力关注…… 如果用户每一个小错误都要去关注，我感觉 他会累死……

第二，至于UI 隐藏逻辑，你说的挺有道理的，我可以在下个版本调整下显示逻辑

第三，至于引导修复这个，其实也没啥危险，除非用户是混合系统（比如Linux+Windows）可能会导致Linux无法启动，但是话说回来，用Linux的人难道还会不知道这种简单的事情…… 另外某些模拟固件的盗版系统 激活会挂掉，这个也重新激活就可以了，并不会导致致命问题。

第四，顶部确实 空白了一点…… 本来打算是放张图片的，一直没做……

最后还是感谢你的支持

**Comment by ugksoft** [comment]
en,也不是说所有信息都提示,只是提示一下有一小部分文件因占用而没能清理,或是系统干净的,什么文件也没删时,也至少显示一下"清理完成"

结贴吧,忙的很,平常一干活就几天不睡的,一睡就睡好几天,也没有什么精力来折腾这贴子

**Comment by mingkuang-Chuyu** [comment]
重新打开 等 UI显示逻辑 以及 delphi7 历史记录添加后 在关闭此问题

**Comment by mingkuang-Chuyu** [comment]
空间回收，清理/扫描 UI展现模式已经调整。

delphi7注册表项目，将在未来的注册表清理规则化中添加。

**Comment by banyan772** [comment]
看你们俩聊得好欢乐，我真的是好羡慕啊~~

**Comment by kt1024** [comment]
是不是作者欠了楼主几百万．．．语气这么冲
