### ISSUE TITLE
关于通用安装脚本——sut的导入问题

### ISSUE THREAD

**Issue by yellowbest** [Chuyu-Team/Dism-Multi-language#320]
帮助文档里只有生成sut的教程，但在dism++却不知道如何导入！ 有点郁闷，请问一下，生成这个脚本之后我应该如何封装到wim里面呢？

有哪位大大帮忙解答一下么，不胜感激！ 在这个问题上纠结了好久了！

**Comment by mingkuang-Chuyu** [comment]
Hi, 离线模式中，点击程序和功能。Dism++会显示导入按钮的。 谢谢

**Comment by hqq718685** [comment]
请问如何进入离线模式

**Comment by mingkuang-Chuyu** [comment]
在另一个系统中处理你想处理的系统就是离线模式，比如说在PE里处理，或者当前系统挂载处理wim。
