### ISSUE TITLE
英文版中仍然出现中文

### ISSUE THREAD

**Issue by macgg** [Chuyu-Team/Dism-Multi-language#322]
**问题1:** 在Appx中, 每次删除appx, 会先出现一遍英文的提示,然后过几秒又出现中文的提示再让确认一遍.

<img width="956" alt="screen shot 2017-12-19 at 1 39 32 am" src="https://user-images.githubusercontent.com/16809241/34150722-0ab6b95e-e45e-11e7-9cb3-4d7651a85f9c.png">
<img width="978" alt="screen shot 2017-12-19 at 1 39 46 am" src="https://user-images.githubusercontent.com/16809241/34150721-0aa28876-e45e-11e7-910d-5b1b683dfb2a.png">

**问题2:** 系统优化中, 不少中文字没有被英化
<img width="755" alt="screen shot 2017-12-19 at 1 41 31 am" src="https://user-images.githubusercontent.com/16809241/34150716-0a38fa3c-e45e-11e7-9d54-ba43c8bd7dc3.png">
<img width="753" alt="screen shot 2017-12-19 at 1 41 08 am" src="https://user-images.githubusercontent.com/16809241/34150717-0a4ef490-e45e-11e7-8086-45cf0f6f9e1f.png">
<img width="766" alt="screen shot 2017-12-19 at 1 41 02 am" src="https://user-images.githubusercontent.com/16809241/34150718-0a6433d2-e45e-11e7-951d-71da4e4d6778.png">
<img width="742" alt="screen shot 2017-12-19 at 1 40 44 am" src="https://user-images.githubusercontent.com/16809241/34150719-0a7a3af6-e45e-11e7-9bf9-b09ed6265b1d.png">
<img width="682" alt="screen shot 2017-12-19 at 1 40 35 am" src="https://user-images.githubusercontent.com/16809241/34150720-0a8ee28a-e45e-11e7-96c7-376ee1be138e.png">

**Comment by suwakowww** [comment]
等更新吧，估计还没把语言包同步过去

**Comment by mingkuang-Chuyu** [comment]
等待更新即可。目前还尚未发布语言更新，相关翻译已经完成。
