### ISSUE TITLE
Windows Update Not Integrated wim

### ISSUE THREAD

**Issue by rulman** [Chuyu-Team/Dism-Multi-language#323]
> IE-Win7.CAB
> IE11-Windows6.1-KB4052978-x64.cab
> Windows6.1-KB2545698-x64.cab
> Windows6.1-KB2547666-x64.cab
> Windows6.1-KB2592687-x64.cab
> Windows6.1-KB2667402-v2-x64.cab
> Windows6.1-KB2670838-x64.cab
> Windows6.1-KB2685811-x64.cab
> Windows6.1-KB2685813-x64.cab
> Windows6.1-KB2698365-x64.cab
> Windows6.1-KB2729094-v2-x64.cab
> Windows6.1-KB2750841-x64.cab
> Windows6.1-KB2834140-v2-x64.cab
> Windows6.1-KB2841134-x64.cab
> Windows6.1-KB2862330-v2-x64.cab
> Windows6.1-KB2894844-x64.cab
> Windows6.1-KB2900986-x64.cab
> Windows6.1-KB2912390-x64.cab
> Windows6.1-KB2952664-v23-x64.cab
> Windows6.1-KB2970228-x64.cab
> Windows6.1-KB2984972-x64.cab
> Windows6.1-KB3000483-x64.cab
> Windows6.1-KB3006137-x64.cab
> Windows6.1-KB3020369-x64.cab
> Windows6.1-KB3020388-x64.cab
> Windows6.1-KB3021917-x64.cab
> Windows6.1-KB3035126-x64.cab
> Windows6.1-KB3046269-x64.cab
> Windows6.1-KB3059317-x64.cab
> Windows6.1-KB3068708-x64.cab
> Windows6.1-KB3075226-x64.cab
> Windows6.1-KB3078601-x64.cab
> Windows6.1-KB3080149-x64.cab
> Windows6.1-KB3110329-x64.cab
> Windows6.1-KB3118401-x64.cab
> Windows6.1-KB3123479-x64.cab
> Windows6.1-KB3125574-v4-x64.cab
> Windows6.1-KB3138612-x64.cab
> Windows6.1-KB3150220-x64.cab
> Windows6.1-KB3150513-x64.cab
> Windows6.1-KB3156016-x64.cab
> Windows6.1-KB3156019-x64.cab
> Windows6.1-KB3159398-x64.cab
> Windows6.1-KB3161102-x64.cab
> Windows6.1-KB3161949-x64.cab
> Windows6.1-KB3161958-x64.cab
> Windows6.1-KB3172605-x64.cab
> Windows6.1-KB3177467-x64.cab
> Windows6.1-KB4014596-x64.cab
> Windows6.1-KB4019990-x64.cab
> Windows6.1-KB4033996-x64.cab
> Windows6.1-KB4040980-x64.cab
> Windows6.1-KB4041686-x64.cab
> Windows6.1-KB4048960-x64.cab
> Windows6.1-KB4049068-x64.cab
> Windows6.1-KB4051956-x64.cab
> Windows6.1-KB4054521-x64.cab
> Windows6.1-KB971033-x64.cab

windows_7_ultimate_with_sp1_x64_dvd_u_677404 

Replaces Update List "KB3125574"
> Windows6.1-KB2574819-v2-x64.cab
> Windows6.1-KB2574819-v2-x86.cab
> Windows6.1-KB2603229-x64.cab
> Windows6.1-KB2676562-x64.cab
> Windows6.1-KB2676562-x86.cab
> Windows6.1-KB2732059-v5-x64.cab
> Windows6.1-KB2732059-v5-x86.cab
> Windows6.1-KB2761217-x64.cab
> Windows6.1-KB2761217-x86.cab
> Windows6.1-KB2773072-x64.cab
> Windows6.1-KB2773072-x86.cab
> Windows6.1-KB2813347-x64.cab
> Windows6.1-KB2813347-x86.cab
> Windows6.1-KB2830477-x64.cab
> Windows6.1-KB2830477-x86.cab
> Windows6.1-KB2919469-x64.cab
> Windows6.1-KB2919469-x86.cab
> Windows6.1-KB2923545-x64.cab
> Windows6.1-KB2923545-x86.cab
> Windows6.1-KB3102429-v2-x64.cab
> Windows6.1-KB3102429-v2-x86.cab

**Comment by mingkuang-Chuyu** [comment]
What?

**Comment by mingkuang-Chuyu** [comment]
no reply.
