### ISSUE TITLE
Opera Kill

### ISSUE THREAD

**Issue by grompes** [Chuyu-Team/Dism-Multi-language#327]
[RUssia]
После отметки "анализ Opera" программа зависает.. и Opera больше нормально не загружается. Сайты не открываются. Дополнения (аддоны) не загружаются. Стартовая страница (speeddial) не загружается !!
Установка браузера поверх старой Opera - непомогает.
 Помогает только ПОЛНОЕ удаление Opera, выключая дополнения, и все все все папки связанные с ней.
Удалите нахрен этот пункт из программы!!

[Google translate]
After marking "Opera analysis" the program hangs .. and Opera does not load normally anymore. Sites do not open. Add-ons (addons) are not loaded. The start page (speeddial) does not load !!
Installing the browser over the old Opera is unavailable.
It is only the COMED removal of Opera that helps, turning off the add-ons, and all the folders associated with it.
Remove fuck this item from the program !!

**Comment by Jhovany200** [comment]
@mingkuang-Chuyu 
the possible solution would be to change to "Launcher.exe".
`<Excluded>?GetFileVersion(%Root%Launcher.exe)</Excluded>`

**Comment by mingkuang-Chuyu** [comment]
2f0f69aa, done~
I'm sorry to hear that.  I'll update Data.xml.

mingkuang
