### ISSUE TITLE
Windows10 Pro识别成企业版

### ISSUE THREAD

**Issue by Whuihuan** [Chuyu-Team/Dism-Multi-language#329]
![image](https://user-images.githubusercontent.com/6679148/34378654-f3ad1868-eb31-11e7-9768-e5bdad396537.png)
![image](https://user-images.githubusercontent.com/6679148/34378669-02bf907e-eb32-11e7-9e00-2ad0e1697e4d.png)

**Comment by mingkuang-Chuyu** [comment]
谢谢~~反馈

**Comment by mingkuang-Chuyu** [comment]
从 Cloud 中获取到了相关文件，已经确认是系统结构更改所致。Beta已经修正，请等待新版本发布
