### ISSUE TITLE
既然有的文件不能删，那为什么不把这些文件移动到别的文件夹呢？

### ISSUE THREAD

**Issue by w371987114** [Chuyu-Team/Dism-Multi-language#33]
部分文件用途有限，直接删除又怕影响电脑以后的使用；那何不把这些文件移动到其它盘呢？
腾讯电脑管家就有这个功能，它可以直接在大文件处设置一个指向其它路径的快捷方式；只是我嫌腾讯电脑管家不清净，所以一直没用它
如果不能移动，那备份到其它盘；等到用的时候再还原不也可行吗？（我觉得添加这个功能至少也比看着C盘那些不知道什么时候才用的文件空占地方好）

**Comment by mingkuang-Chuyu** [comment]
这样移动是会有问题的…… 会导致某些软件无法正常使用。真的移动也就是桌面 之类的可以改位置，而这些……对容量没什么太大的意义  反正你都知道他们的用途
