### ISSUE TITLE
提交规则：显示幽灵硬件

### ISSUE THREAD

**Issue by powerxing04** [Chuyu-Team/Dism-Multi-language#331]
Windows 设备管理器通常只会显示已经连接至计算机的设备，不会显示未连接至计算机的设备。如果我们希望显示那些以前曾经连接过、但目前没有连接至计算机的历史硬件设备，在系统变量里新建一个变量名为DEVMGR_SHOW_NONPRESENT_DEVICES变量值为1，对应的注册表方式为：

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Session Manager\Environment]
"DEVMGR_SHOW_NONPRESENT_DEVICES"="1"

**Comment by mingkuang-Chuyu** [comment]
设备管理器本身就有选项    查看 - > 显示隐藏的设备

**Comment by mingkuang-Chuyu** [comment]
关闭此问题
