### ISSUE TITLE
16299ESD转换出错 ClassFactory 无法供应请求的类

### ISSUE THREAD

**Issue by Whuihuan** [Chuyu-Team/Dism-Multi-language#333]
宿主机：WIN10 Pro X64 17063
![image](https://user-images.githubusercontent.com/6679148/34452800-71e8d13e-ed82-11e7-8c1f-e3b1d0ba9601.png)

**Comment by mingkuang-Chuyu** [comment]
Hi， 这个问题是你系统的image API不正常……

**Comment by mingkuang-Chuyu** [comment]
微软预览版系统本身BUG，关闭此问题
