### ISSUE TITLE
清理旧驱动不干净

### ISSUE THREAD

**Issue by daiaji** [Chuyu-Team/Dism-Multi-language#335]
![default](https://user-images.githubusercontent.com/25875791/34454088-f439f83c-ed9d-11e7-9c3e-69dac7c81148.gif)
佷明显这是旧驱动
然后能不能给提供一个选项在正常卸载无效时直接删除C:\Windows\System32\DriverStore\FileRepository下对应的文件夹？(比如按住Control再按删除驱动就直接删文件夹了

然后图片是rar格式的图种 里面有没清理掉的旧驱动

**Comment by mingkuang-Chuyu** [comment]
Hi，Dism++为了安全性会自动过滤启动关键驱动。防止清理后系统无法启动。
因此这个不是BUG，而是设计如此。

另外强制删除驱动 不妨你自己删吧。因为强制删除后会导致系统驱动管理相关API异常，比如会发生USB驱动无法识别，无法遍历驱动等问题。  因此如果你有强制删除的需要，不妨你自己删吧……

谢谢支持
