### ISSUE TITLE
请加个删除文件到回收站的选项

### ISSUE THREAD

**Issue by U140** [Chuyu-Team/Dism-Multi-language#337]
用了这个软件以后，在D盘上删除东西每次都是直接删除的。虽然快捷但不习惯，希望添加个选项功能让用户自己选择删除文件要不要删除到回收站里

**Comment by mingkuang-Chuyu** [comment]
Hi，这个是不行的…… 因为很80%左右的清理能力都是虚拟的，无法实际移动到回收站。

另外能移动到回收站的项目 一般也是一些临时文件，直接还原反而可能导致程序出现潜在风险。
