### ISSUE TITLE
系统优化中的开始菜单及Windows体验某些选项会禁用Windows聚焦

### ISSUE THREAD

**Issue by gesla** [Chuyu-Team/Dism-Multi-language#338]
具体是哪个我没有查，排除关闭锁屏时的Windows聚焦推广，这个选项在rs3上是默认开启的，很可能是关闭商店应用推广和禁止自动安装推荐的应用程序这2个，或者第2、5、6项。Windows聚焦锁屏壁纸很好用，不要误禁。

**Comment by mingkuang-Chuyu** [comment]
Hi,  Windows聚焦 也是 商店应用推广 的一部分，因此 只要启用这个功能。 Windows聚焦的图片广告也会消失。

**Comment by gesla** [comment]
经过我的仔细检查，发现是我关闭了隐私设置里的“允许应用在后台运行”这个选项，导致Windows聚焦无法使用。至于关闭应用商店推广会不会导致Windows聚焦不可用还有待核实，反正我现在这几项都是开着的，没见像以前给我自动安装应用，也许是我把除商店以外的应用都删除了的原因？

**Comment by mingkuang-Chuyu** [comment]
可能Windows聚焦 有2个等级…… 微软有个设置，关闭 Windows聚焦屏中推送广告。Dism++关闭的也就是它。
