### ISSUE TITLE
升级1709--17063.1000版之后，任务栏更透明失效了

### ISSUE THREAD

**Issue by 369418257** [Chuyu-Team/Dism-Multi-language#339]
快速预览升级到1709--17063.1000版之后，任务栏更透明失效了，可以优化一下吗?强迫症患者呀

**Comment by suwakowww** [comment]
好像17063的任务栏改了下，不知道是不是因为这个导致

**Comment by HowieXS** [comment]
网上有修改注册表的方法，在17063的时候任务栏改高斯模糊了，修改了注册表会好些，如果是17063之前，我这个方法全透明

**Comment by 369418257** [comment]
我试试。搞成透明显示歌词用。
