### ISSUE TITLE
硬链接合并导致WindowsApps文件夹中合并后的文件权限中的Users的“读取和执行”访问控制项损坏

### ISSUE THREAD

**Issue by magsom** [Chuyu-Team/Dism-Multi-language#34]
比如WindowsApps里有一个D3DX9_43.dll文件，SysWOW64中也有一个D3DX9_43.dll，执行硬链接合并后，这两个文件的安全属性中的Users的“读取和执行”权限都被破坏。
该问题会导致桌面应用无法读取并执行权限损坏的文件，商店应用仍然正常。

**Comment by mingkuang-Chuyu** [comment]
感谢支持，我看了WindowsApps中的dll本身就有读取跟执行权限，你说的问题应该不会发生……
因为吃功能是创建硬链接，所以文件应该跟另一个文件属性完全都一样才是……
是不是你的WindowsApps目录本身的权限被篡改了，导致dll没有读取跟执行？

**Comment by magsom** [comment]
执行硬链接合并前WindowsApps目录的权限没有变过。
硬链接合并后的文件权限确实无法分开设置。
Users的读取和执行权限被修改成带这两个条件：(Exists WIN://PKG)以及(WIN://SYSAPPID Contains "包名")。系统只显示这2个权限条目损坏，但所有的权限条目都无法使用系统自带的高级安全选项面板修改了，删除按钮变成灰色。我还没尝试过使用icacls能否来修改那些文件的权限。
因为商店应用使用的是ALL APPLICATION PACKAGES的权限来读取和执行文件的，所以没问题。但是桌面应用都使用Users的权限。
我使用的是Windows 15042，不知道这是不是预览版的Bug。

**Comment by mingkuang-Chuyu** [comment]
谢谢，确认……我看了15031的文件，原本系统WindowsApps里面的二进制文件确实没有读取与执行……
但是 10586系统相关文件有读取与执行
看来我只能排除WindowsApps目录了……

**Comment by mingkuang-Chuyu** [comment]
已经屏蔽 此文件夹 的扫描
开始生效版本：10.1.24.8（Beta），10.1.23.3（正式）
还请耐心等待，最后感谢你的支持
