### ISSUE TITLE
It is unclear whether or not the program has hung or even perhaps whether it is doing anything

### ISSUE THREAD

**Issue by CottonEaster** [Chuyu-Team/Dism-Multi-language#342]
I am using the wonderful Dism++, and I wonder whether it has hung. It's been like this (some 20% CPU, with an operation seemingly in progress) for 15 minutes:

![screenshot 269](https://user-images.githubusercontent.com/9998846/34633176-50c73bb8-f272-11e7-8823-4d1a7092438f.png)

EDIT: I should add that the progress bars (on the taskbar, and in the program window) do not seem to move. FURTHER EDIT: ah, I did not see that '50%' (in small, black type!) Still, I do not think that that figure is changing either. I worry whether it would be safe to abort the operation . . FINAL EDIT: It completed - it had not hung. Suggestion: make it more obvious when the program is working and perhaps add a 'may take a while' warning.

I am sorry if this problem has been submitted before, in a language I cannot read.

**Comment by Jhovany200** [comment]
I'm not sure but it seems that it is because of all the processes that you have open, because you must close them. Which is recommended with either Dism ++ or other cleaning programs.

**Comment by CottonEaster** [comment]
Well, I had Firefox and Sublime Text open, and some background programs - but none of those running processes were doing very much, at least to my knowledge . .

**Comment by Jhovany200** [comment]
Well, it's just an opinion to see if it works for you. I think it helps you in your problem @mingkuang-Chuyu

**Comment by CottonEaster** [comment]
Well, perhaps you are right; and thank you for the advice. Yet, I do think that a more prominent indication that the program has not hung would be a good idea.

**Comment by mingkuang-Chuyu** [comment]
Please wait ... It takes a long time.
