### ISSUE TITLE
每次清理完后 左键出问题

### ISSUE THREAD

**Issue by guanglin1994** [Chuyu-Team/Dism-Multi-language#343]
清理垃圾后  开始和声音以及网络蓝牙wifi 等系统自带的 图标 左键点击 只有沙漏 但是打不开

**Comment by guanglin1994** [comment]
安装的软件 没问题 就是系统自带功能 左击无反应

**Comment by mingkuang-Chuyu** [comment]
Hi，删除Intel显卡右键菜单试试……

**Comment by mingkuang-Chuyu** [comment]
另外 不要使用MacType这种插件

**Comment by guanglin1994** [comment]
AMD的  清理无用 貌似官方都没出方案

**Comment by mingkuang-Chuyu** [comment]
重启电脑就正常了吗？如果是这样的话 那应该就是重启Explorer出了问题。

加我QQ 343183163 让我远程看看吧

**Comment by guanglin1994** [comment]
重启无用 网上的方法基本都试过了 什么重启资源管理器 启用服务组 运行sfc/scan 磁贴 什么的 都没用 我只好重装的备份 官方出了个  startmenu.diagcab 检测提示 所需应用程序未正确安装 Microsoft.Windows.shellExperienceHost和
Cortana（被我删了）  前面那个我没动过 是否存在 360和dism++同时清理导致

**Comment by guanglin1994** [comment]
QQ 1003184954 学校断网了  系统用的 Dism++ 一直备份 还原了远程也找不到问题所在  但是一直存在这个问题  很多次都是 运行360和dism++清理 就出现此问题 还有就是 电脑一直装不了 微软很多更新  360做的大更也不行  运行sfc/scan 到51% 就提示 权限受限 网上的所有解决办法又不行  应该不是管理员权限问题 一直用的win10专业版  版本10.0.10240  大一备份到大四
