### ISSUE TITLE
扫描“被取代的WinSxS组件”时失败

### ISSUE THREAD

**Issue by sciei** [Chuyu-Team/Dism-Multi-language#346]
扫描“被取代的WinSxS组件”时失败，7G多不能删除

**Comment by sciei** [comment]
扫描“被取代的WinSxS组件”时找到7G多，但是不能删除，出错

**Comment by mingkuang-Chuyu** [comment]
请说明下 具体什么错误…… 点击出错的项目 程序会显示详细错误信息。

另外 精简系统无法正常使用此功能。

**Comment by powerxing04** [comment]
我猜你有更新被挂起，你是扫描失败还是清理失败，是Win7x86还是Win10x64

**Comment by mingkuang-Chuyu** [comment]
长期无回复，如果有问题请重新打开此问题。另外方便的话QQ 343183163联系我，我们直接远程吧
