### ISSUE TITLE
更新版本至10.1.23.2 更新失败，Dism++x64.exe下载出错

### ISSUE THREAD

**Issue by a150808** [Chuyu-Team/Dism-Multi-language#35]
更新版本至10.1.23.2 更新失败，Dism++x64.exe下载出错，提示提示信息如下：
[Window Title]
Dism++更新程序
[Main Instruction]
更新文件过程中遇到错误，Orz……
[Content]
Dism++x64.exe

**Comment by lee853761** [comment]
相同问题

**Comment by mingkuang-Chuyu** [comment]
此问题应该 可能是DNS问题，还请提供QQ号，方便排除谢谢

**Comment by mingkuang-Chuyu** [comment]
为提供联系方式，无法继续处理。暂时关闭
