### ISSUE TITLE
ClassFactory无法供应请求的类

### ISSUE THREAD

**Issue by Silver-Fang** [Chuyu-Team/Dism-Multi-language#351]
在17063上用ActionList.xml制作做17074的ISO，进行一段时间后提示ClassFactory无法供应请求的类。制作失败。WIM可以正常。

**Comment by Silver-Fang** [comment]
系统升到17074以后再做，还是一样的问题

**Comment by mingkuang-Chuyu** [comment]
这个是系统的 ImageAPI 无法获取 导致ISO制作功能异常。方便远程的话加我QQ 343183163 我打下日志看看具体是那个申请失败了。如果真的是系统本身异常，那么需要反馈给微软。

**Comment by Silver-Fang** [comment]
@mingkuang-Chuyu 应该不是微软的问题，因为我另找了一个工具做就成功了，而且还成功用那个ISO给同学装了系统……

**Comment by mingkuang-Chuyu** [comment]
你说的另一个工具 它不使用 ImageAPI，而是直接调用微软的oscdimg。而oscdimg自身独立实现ISO生成功能。另外我也说了，具体需要你联系我，输出下日志。看看具体是那个行为时产生了错误。

**Comment by mingkuang-Chuyu** [comment]
@333 跟此问题是同一个问题，统一在 @333 里面跟踪吧
