### ISSUE TITLE
更新管理用不了

### ISSUE THREAD

**Issue by T1M77** [Chuyu-Team/Dism-Multi-language#352]
点击扫描后会弹出错误提示
![qq 20180114133315](https://user-images.githubusercontent.com/35415045/34913148-1594bb78-f930-11e7-8c9b-5bf934797b09.png)

**Comment by mingkuang-Chuyu** [comment]
Hi，某些网络中Dism++可能无法正常下载数据库。这个问题还在跟踪。
临时解决方案：
http://cdn.chuyu.me/files/wsusscn2_094748943bafddfc0755ad30e7a482f8.cab

下载到Dism++的Config/wsusscn2.cab即可
然后再点击扫描。

**Comment by mingkuang-Chuyu** [comment]
另外如果可以帮我跑测试程序的话 可以加我QQ好友 343183163
谢谢

**Comment by mingkuang-Chuyu** [comment]
已经修复，Beta版已经修复此问题，请耐心等待正式版推送。
