### ISSUE TITLE
imageX不能直接把一个wim文件里的映像移到另一个wim文件里吗？

### ISSUE THREAD

**Issue by Silver-Fang** [Chuyu-Team/Dism-Multi-language#353]
我现在有A.wim和B.wim，两个文件里各有3个映像，我现在要把A文件里的一个映像转移到B文件里，应该怎么转移？我想是先打开A导出映像，然后再打开B添加映像？结果B添加映像的时候让我选文件夹？不能选刚刚导出的映像文件？

**Comment by mingkuang-Chuyu** [comment]
你可以使用导出功能
打开 A.wim，选择你需要导出的index（按住Ctrl支持多选），然后点击导出  在选择 B.wim即可
