### ISSUE TITLE
windows update设置

### ISSUE THREAD

**Issue by MMM497206549** [Chuyu-Team/Dism-Multi-language#356]
在Dism++10.1.1000.52这个版本中，挂载windows 7的wim映像文件windows update设置为“从不检查更新（不推荐）”保存映像，实际封装成ISO文件装机后，查看修改的选项中目前只有更新设置不起作用，仍然是“自动安装更新（推荐）”。

**Comment by mingkuang-Chuyu** [comment]
某些设置会被OOBE重置，因此你还需要自定义OOBE，不要去重置Windows Update相关设置。具体可以考虑使用应答文件。
