### ISSUE TITLE
硬链接合并怎么回滚啊？

### ISSUE THREAD

**Issue by pcj1997** [Chuyu-Team/Dism-Multi-language#357]
软件里面我也没找到回滚的选项啊，另外你们的群满了啊

**Comment by mingkuang-Chuyu** [comment]
没有回滚按钮 只能自己在PE里面手动恢复文件 原始文件在在HardLinkBackup中。

**Comment by pcj1997** [comment]
请问具体的操作步骤是什么啊，把HardLinkBackup中的文件直接复制粘贴到C盘根目录吗
