### ISSUE TITLE
能不能加一个注册表清理功能？

### ISSUE THREAD

**Issue by jnrfalcon** [Chuyu-Team/Dism-Multi-language#359]
RT 不知道好不好做 只是提个建议

**Comment by MouriNaruto** [comment]
请开启专家模式

**Comment by jnrfalcon** [comment]
就没用过其他模式... 在哪呢...？

**Comment by MouriNaruto** [comment]
在DISM++设置窗口开启专家模式后应该就能看到这个功能了

**Comment by jnrfalcon** [comment]
常用工具：空间回收，启动项管理，appx管理，工具箱
控制面板：系统优化，驱动管理，程序和功能，可选功能，更新管理
部署功能：文件关联，预应答
就这些啊... 空间回收里没有注册表清理，工具箱里也没...

**Comment by MouriNaruto** [comment]
那估计是在Beta版里面了

**Comment by mingkuang-Chuyu** [comment]
Dism++ Beta有的专家模式，但是目前并不打算增强注册表清理。

**Comment by MouriNaruto** [comment]
参见 https://github.com/Chuyu-Team/Dism-Multi-language/issues/579
