### ISSUE TITLE
DISM++ not work

### ISSUE THREAD

**Issue by AligSeB** [Chuyu-Team/Dism-Multi-language#36]
Hello everybody. I write here because I do not know where to write. Installed Windows 10 ltsb. There is a good DISM ++ program. On all previous windows works fine, if you know what to do. In Windows 10, ltsb x64 does not work for me, Windows is incorrectly defined. Written Windows NT local disk is ready for use and only one item is displayed in addition. I can not figure out what the problem is, I tried everything. Can what that service need to include? I will be very grateful for the help. Thank you
[https://drive.google.com/file/d/0B46WzGqdZqa6bnpLU3dkX0xQMFE/view?usp=sharing](url)

**Comment by mingkuang-Chuyu** [comment]
Thanks for your support,Please delete reg 
"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\WinPE"
and " HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\WinPE"

: )
