### ISSUE TITLE
windows 10 x64 系统，系统还原以后，开始菜单的磁贴出现问题

### ISSUE THREAD

**Issue by eforlina** [Chuyu-Team/Dism-Multi-language#360]
还原成功，
首次重启以后，开始菜单里的磁贴都无法打开，且图标和显示名称都有问题：每一个磁贴的图标为空白，显示的名称为w～【程序路径】，磁贴位置没变;
再次重启以后，磁贴都能打开了，然而磁贴位置错乱。

**Comment by mingkuang-Chuyu** [comment]
重复反馈，此问题已经修复，默认过滤列表中过滤Explorer缓存所致，请耐心等待Data.xml更新。
