### ISSUE TITLE
使用空间回收功能清理完后，资源管理器打开很慢

### ISSUE THREAD

**Issue by TypicalSEE** [Chuyu-Team/Dism-Multi-language#37]
桌面上右键单击反应也很慢

**Comment by mingkuang-Chuyu** [comment]
此问题是Intel显卡驱动存在一些问题。跟微软的Resetbase有冲突。

这个问题 只需要禁用 Intel的桌面右键菜单就可以了。（具体 参考 系统优化 -  菜单管理）

也可以禁用Intel显卡驱动相关服务来解决此问题。
