### ISSUE TITLE
Bug反馈：系统优化中的“删除右键新建联系人”

### ISSUE THREAD

**Issue by zfaway** [Chuyu-Team/Dism-Multi-language#370]
启用了系统优化中的“删除右键新建联系人”，正常情况应当删除注册表中的“HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.contact\ShellNew”，实际上程序除了删除此键外，会另外建立多余的注册表键“HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.contact\-ShellNew”；
当手动删除多余的“HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.contact\-ShellNew”键后，系统优化中的相关选项消失不见。
系统：Win10 RS3 1709 x64 (16299.192)

**Comment by mingkuang-Chuyu** [comment]
没叫你去删Dism++的备份……这是自己作孽
