### ISSUE TITLE
建议增加配置导入导出功能

### ISSUE THREAD

**Issue by yellowEST** [Chuyu-Team/Dism-Multi-language#373]
在控制面板的系统优化一栏，设置的一些选项建议增加导入导出的功能，那样下次就不会挨个再点一遍了，因为可优化的东西越来越多啦。

**Comment by MouriNaruto** [comment]
请转到 https://github.com/Chuyu-Team/Dism-Multi-language/issues/578 讨论

**Comment by MouriNaruto** [comment]
Archived, #707
