### ISSUE TITLE
希望加入关闭UAC的选项

### ISSUE THREAD

**Issue by zxqwe** [Chuyu-Team/Dism-Multi-language#374]
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
"EnableLUA"=dword:00000000

EnableLUA：用户帐户控制: 以管理员批准模式运行所有管理员

dword:00000000是关闭，dword:00000001是开启

Win10 家庭版没有组策略，只能靠注册表来关闭。

这个选项很危险，应该加上相应提示。

**Comment by Carlos920** [comment]
win10家庭版是有办法开启组策略的https://www.zhihu.com/question/53834660 这边有方法

**Comment by Carlos920** [comment]
win10家庭版是有办法开启组策略的https://www.zhihu.com/question/53834660 这边有方法

**Comment by mingkuang-Chuyu** [comment]
此功能一直都有…… 在系统优化中
