### ISSUE TITLE
希望在执行任务的时候在此程序上进行其他操作

### ISSUE THREAD

**Issue by HowieXS** [Chuyu-Team/Dism-Multi-language#376]
每次执行任务的时候什么都不能点（除左上角四个工具栏按钮），很浪费时间的。希望能改进。

**Comment by mingkuang-Chuyu** [comment]
这是故意的，因为一旦在进行任务 就不能执行其他操作。

比如你在备份系统，然后你另一边又清理垃圾。这算什么……

如果你觉得耗时长，你可以取消任务。
