### ISSUE TITLE
执行操作时速度慢

### ISSUE THREAD

**Issue by HowieXS** [Chuyu-Team/Dism-Multi-language#377]
执行操作的时候，就打个比方，系统备份超级慢的，一小时40%，连空间清理也挺慢的

**Comment by HowieXS** [comment]
空间回收的被取代的winsxs组件最慢

**Comment by mingkuang-Chuyu** [comment]
备份慢 建议你关闭微软自带杀毒…… 这个开着会导致程序性能只有 1/20左右。
