### ISSUE TITLE
状态栏的“预览”失效。

### ISSUE THREAD

**Issue by gdmec07150607** [Chuyu-Team/Dism-Multi-language#38]
就是鼠标移动过去没有任何的反应。点击可以跳转到桌面，就是预览不行。听说跟系统优化有关，但是在本机的高级设置里边我明明点开了预览，组策略也开启了。一定是被什么阻止了。

**Comment by mingkuang-Chuyu** [comment]
预览 ? 任务栏 的 界面预览吗？

**Comment by mingkuang-Chuyu** [comment]
这个问题应该是  Explorer缓存被清理所致，建议你 在清理一次 Explorer，然后 手动重启下 Explorer试试。

**Comment by mingkuang-Chuyu** [comment]
用户长时间无应答，另外NCleaner缓存处理逻辑也已经调整，未来版本应该能避免此问题了。
