### ISSUE TITLE
Windows Update数据库更新问题

### ISSUE THREAD

**Issue by Aaron0083** [Chuyu-Team/Dism-Multi-language#384]
开发者你好，我现在使用的是win10的64位系统，版本号为1709，OS内部号为16299.125，在用Dism进行更新时，提醒我Windows 数据库已存在新版本，但是在无法更新成功，并出现错误提示“未指定的错误”，我在重新下载软件、重装系统后仍然无法改变，想问问这是为啥，如果是bug，希望修复一下，谢谢啦

**Comment by mingkuang-Chuyu** [comment]
Hi，此问题在Beta版已经修复。还请耐心等待新版本发布。

**Comment by Aaron0083** [comment]
谢谢，多问一句，怎么获取Beta版啊？

2018-03-06 19:30 GMT+08:00 mingkuang <notifications@github.com>:
