### ISSUE TITLE
win10备份提示出错

### ISSUE THREAD

**Issue by 7878k** [Chuyu-Team/Dism-Multi-language#385]
win10备份提示出错
![untitled](https://user-images.githubusercontent.com/9486163/37044688-2091f9f8-2132-11e8-9918-6020db06c187.png)

**Comment by mingkuang-Chuyu** [comment]
关闭Linux子系统即可。或者排除Linux子系统的文件，你可以把日志贴上来。我在Dism++的规则里默认排除下。

**Comment by mingkuang-Chuyu** [comment]
已经解决，已经过滤Linux子系统
