### ISSUE TITLE
hosts编辑器存在的一个BUG

### ISSUE THREAD

**Issue by huangsijun17** [Chuyu-Team/Dism-Multi-language#386]
由于某些未知原因，本机不存在c:\windows\system32\drivers\etc\hosts文件，但却存在c:\windows\system32\drivers\etc\hosts.ics。该文件可以替代hosts进行自定义解析。
但在通过本软件的hosts编辑器尝试编辑时，反而会提示是否新建该文件，截图如下：
![default](https://user-images.githubusercontent.com/31504595/37070426-6600f8a2-21f2-11e8-9600-2ff20cca93cf.PNG)

**Comment by huangsijun17** [comment]
还有一个问题，DISM是支持在Windows下甚至RamOS、WTG下对其他路线系统操作的，包括安装驱动、补丁等。（我曾经拿DISM手动给Win7离线安装USB3.1和NVMe驱动）
DISM++下我未找到对于离线系统的支持。

**Comment by mingkuang-Chuyu** [comment]
谢谢你的支持，我会通知青蛙修复这个 hosts问题。

另外Dism++也能添加驱动补丁等……支持离线（包括PE下 你也能处理其他系统）。

**Comment by mingkuang-Chuyu** [comment]
@FogDai

**Comment by mingkuang-Chuyu** [comment]
已经修复
