### ISSUE TITLE
激活备份无法识别Office 2016零售版

### ISSUE THREAD

**Issue by mingkuang-Chuyu** [Chuyu-Team/Dism-Multi-language#39]
反馈者：左岸

影响，为备份备份硬件激活信息。这可能导致还原激活后依然无法激活。

临时解决办法：
自行输入激活密钥，然后在点击还原激活。

**Comment by Roger-WIN** [comment]
Office 2016 的零售版不是绑定微软账户的吗？

**Comment by mingkuang-Chuyu** [comment]
是的，所以无法备份……

**Comment by Roger-WIN** [comment]
那这就不算是问题了吧。

**Comment by mingkuang-Chuyu** [comment]
Dism++10.1.1000.0 已经删除了此功能。因为Windows 10后时代微软会自动云备份密钥。
