### ISSUE TITLE
[Add to Windows Update section of System Optimizer] Allow downloading of all updates

### ISSUE THREAD

**Issue by Zero3K** [Chuyu-Team/Dism-Multi-language#390]
Here's the registry key for it to add/remove:

Key: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\QualityCompat
REG_DWORD: cadca5fe-87d3-4b96-b7fb-a231484277cc
Value: 0

**Comment by mingkuang-Chuyu** [comment]
The new wsusscn2.cab will skip this rul.
