### ISSUE TITLE
为什么用过清理之后windows目录就变成已共享了？

### ISSUE THREAD

**Issue by 8035258** [Chuyu-Team/Dism-Multi-language#41]
如题，win10企业版.   重装了几次，发现每次一用dism++之后windows目录就变成已共享了！

**Comment by mingkuang-Chuyu** [comment]
程序并没有去处理Windows目录的共享状态。建议你 先 杀毒 确认是否 中毒了，谢谢……

**Comment by mingkuang-Chuyu** [comment]
用户 长时间无应答，而且手动使用Dism++清理并未发现此问题。暂时关闭

**Comment by 8035258** [comment]
![image](https://cloud.githubusercontent.com/assets/25729512/24278484/0f8728b4-107f-11e7-8f40-66d127552043.png)
 你好，我说的是图中左下角显示的状态.  刚重装完这里没有显示已共享.
 虽然我对这个共享的意义似乎也不太明白.  但确实使用过dism++之后就显示已共享了...
已经重装过好多次了，系统来自msdn，使用了GPT分区切全盘格式化了，未使用第三方PE.

**Comment by mingkuang-Chuyu** [comment]
Hi，我还是那句话。Dism++并不会调整文件夹共享状态。这个文件夹共享一般是用在多用户共享文件用的。如果不知不觉就变成了共享状态，中毒的概率更高一些。

**Comment by mingkuang-Chuyu** [comment]
Hi，发现系统默认 缺少有个Windows目录的共享（ADMIN$），但是这个是系统默认就有的共享。但是系统默认并不会显示它。你是不是调整了什么共享相关的设置？

**Comment by mingkuang-Chuyu** [comment]
我希望能远程具体看看此问题  谢谢

**Comment by 8035258** [comment]
@mingkuang-Chuyu   非常感谢您耐心的回复! 因为电脑只有自己一个人使用..做系统的时候把（ADMIN$）和其他共享都关闭了，并且禁用了Server服务. 文件夹选项里面有个“使用共享向导（推荐）”我也取消掉了.
似乎win10的UAC机制较之前有所改变，也许我自己的设置（也可能是dism++的某项功能）被重定向了.
 印象中我以前装过LTSB版，直接使用Administrator账户就一切正常!

**Comment by 8035258** [comment]
@mingkuang-Chuyu    我找到原因了.  之前使用dism++优化时，喜欢关闭Server服务.
  经测试，手动禁用Server服务，windows目录也会显示已共享...   总之，非常抱歉！

**Comment by mingkuang-Chuyu** [comment]
没关系， 能找到问题就好。那我就关闭这个问题了  谢谢支持
