### ISSUE TITLE
Dism++ 界面优化建议。。。

### ISSUE THREAD

**Issue by kokutoukiritsugu** [Chuyu-Team/Dism-Multi-language#410]
上下两部分这样的一些界面，
其实下面的一部分不是特别需要关注，能不能搞成灰色字体呢？
这样可读性能大大提升。。。

ps的效果：
![snipaste_2018-03-15_20-53-37](https://user-images.githubusercontent.com/5471433/37464665-006a6296-2894-11e8-8833-d8e82bf4a5ba.png)
  
1
1
1

![snipaste_2018-03-15_20-58-24](https://user-images.githubusercontent.com/5471433/37464666-00fcab42-2894-11e8-85b3-86adde180f26.png)

**Comment by kokutoukiritsugu** [comment]
其实名称后面的版本号都不是很重要。
做个选项和透明度放到设置里？

![snipaste_2018-03-15_21-03-18](https://user-images.githubusercontent.com/5471433/37464866-a31a5ed8-2894-11e8-807f-08e301e65ecc.png)

**Comment by mingkuang-Chuyu** [comment]
就像微软这样吧，做的简单点。改改配置就行。Beta已经更新
