### ISSUE TITLE
OEM win10家庭中文版没有策略组问题

### ISSUE THREAD

**Issue by 917591230** [Chuyu-Team/Dism-Multi-language#412]
[策略组.txt](https://github.com/Chuyu-Team/Dism-Multi-language/files/1819230/default.txt)

把这个脚本后缀名改为cmd,以管理员身份运行,会自动下载策略组所需组件.
有一个bug,不能从控制面板打开策略组,需要在命令行运行gpedit.msc打开
本人能力有限,希望有帅哥可以完善一下.

**Comment by mingkuang-Chuyu** [comment]
既然系统本身没有策略，其实暂时我也不想加。因为这个会破坏更新的父子关系。暂时留着，以后观望观望吧

**Comment by Threonine-Animist** [comment]
我试了一下，虽然gpedit.msc打得开，但是似乎在里面调整的设置不会起作用
