### ISSUE TITLE
新版本里还有“删除被代替的MSP软件更新”这个功能吗

### ISSUE THREAD

**Issue by carsonasia** [Chuyu-Team/Dism-Multi-language#413]
![image](https://user-images.githubusercontent.com/37445682/37523337-8edc1268-2961-11e8-92a3-aa63575383b1.png)
问下这个版本里面的“删除被代替的MSP软件更新”功能，在dism++里面还有吗？一直没找到。

群满员了加不进去，所以就来这里问下，非常感谢。

**Comment by mingkuang-Chuyu** [comment]
有 但是在专家模式，谢谢。
