### ISSUE TITLE
许可协议第二条存在对盲人的错误认识和描述，建议修改

### ISSUE THREAD

**Issue by qt06** [Chuyu-Team/Dism-Multi-language#418]
在Dism++用户协议的第一部分“Dism++许可”的第二条是这样写的：
```
    2、使用Dism++前，您必须认真阅读Dism++帮助文档。除非您无法正常阅读简体中文，比如盲人、海外用户等。
```

这里对于无法正常阅读简体中文做了举例说明，提到了盲人。
我觉得这一说法存在偏差，与实际情况不一致。
现在的盲人可以借助于读屏软件来阅读电脑上的文本，并且可以操作电脑。
比如我就是使用读屏软件看到的 Dism++ 的许可，并且我知道现在有不少的盲人在使用 Dism++。
现在，我也是使用读屏软件在写这篇反馈。
这一描述从某种角度说可能已经涉嫌对盲人的歧视，可能给 Dism++ 带来不必要的麻烦和困扰。
我建议 Dism++ 团队可以修改许可协议的第二条，吧对于盲人的错误认识和描述去掉。

**Comment by mingkuang-Chuyu** [comment]
谢谢你的支持，对应一些争议性信息 将在下个版本中删除。

mingkuang

**Comment by mingkuang-Chuyu** [comment]
服务器中我已经签入。请耐心等待下个版本。

谢谢支持

**Comment by qt06** [comment]
非常感谢。

**Comment by veg-xiaobo** [comment]
赞美 Dism++ 团队的即时响应。

**Comment by man0528** [comment]
如果可以，希望Dism++优化一下无障碍体验。由于某些对象不具有tab焦点，导致屏幕阅读器无法正常使用该程序的某些功能。例如“释放空间”功能的选择清理项，屏幕阅读器无法正常操作，只有通过修改配置文件来改变默认选中项。

**Comment by MouriNaruto** [comment]
@man0528 

https://github.com/Chuyu-Team/Dism-Multi-language/issues/422

**Comment by man0528** [comment]
@MouriNaruto 期待中，感谢。

**Comment by MouriNaruto** [comment]
Archived, #707
