### ISSUE TITLE
常用工具->空间回收->描述栏 不能左右拖动宽度大小

### ISSUE THREAD

**Issue by ZenChang** [Chuyu-Team/Dism-Multi-language#419]
我想查看右侧描述栏中的文件路径信息，但是文件路径信息太多，建议可以让宽度可以设置为动态更改，用户体验更加

**Comment by mingkuang-Chuyu** [comment]
文件信息没什么软用。只是作为参考而已。实际上，软件也只是显示前200个条目而已。
