### ISSUE TITLE
更新补丁提示无法连接服务器

### ISSUE THREAD

**Issue by mrxhliu** [Chuyu-Team/Dism-Multi-language#420]
不管是给本地系统或挂载的映像，更新补丁界面点扫描后提示无法连接服务器

![default](https://user-images.githubusercontent.com/28480827/37697604-ae464320-2d18-11e8-8695-957eb9765146.PNG)

**Comment by mingkuang-Chuyu** [comment]
建议加我QQ 343183163，我猜测了应该是小运营商所致。

**Comment by mingkuang-Chuyu** [comment]
已经确认，共享IP问题。过一段时间尝试即可。
