### ISSUE TITLE
无障碍问题 UI无法使用NVDA等屏幕阅读软件操作

### ISSUE THREAD

**Issue by jiangtiandao** [Chuyu-Team/Dism-Multi-language#422]

**Comment by MouriNaruto** [comment]
首先，我得说声抱歉

Dism++不支持屏幕阅读软件是一个历史性问题，主要是因为Dism++使用了不支持UI自动化的DirectUI框架导致的。
曾经， @mingkuang-Chuyu （鸭子）在我曾经反馈相同的问题后，也提过早在很久前就有人反馈过。
其实每个参与Dism++开发的人都希望让Dism++支持屏幕阅读器
据说鸭子在自制一个新的UI框架，屏幕阅读器必然会支持的。

毛利

**Comment by jiangtiandao** [comment]
多谢解答

**Comment by MouriNaruto** [comment]
Archived, #707
