### ISSUE TITLE
DISM++无法自己更新，系统补丁数据库也无法更新

### ISSUE THREAD

**Issue by wbchly** [Chuyu-Team/Dism-Multi-language#423]
![tim 20180329105620](https://user-images.githubusercontent.com/37889754/38067733-6897a8e0-3340-11e8-8422-f9906f510bba.jpg)
![tim 20180329105631](https://user-images.githubusercontent.com/37889754/38067738-6bbba850-3340-11e8-8eb5-6a28ea21ba6e.jpg)
如标题所示，这个问题如何解决？

**Comment by mingkuang-Chuyu** [comment]
共享IP问题，过一段时间重新尝试即可。
