### ISSUE TITLE
Windows10（1803）始终显示企业版

### ISSUE THREAD

**Issue by lovezhiqi123** [Chuyu-Team/Dism-Multi-language#426]
1803版本用dism++精简 在dism++中专业版会显示成企业版 实际还是专业版

**Comment by mingkuang-Chuyu** [comment]
此问题确实存在，但是发现未启动时。系统内核内部数据结构确实为企业版。暂时先观望一段时间。

影响范围：低（仅影响UI显示）

**Comment by mingkuang-Chuyu** [comment]
解决方案：
Dism++Beta 10.1.2002.91已经修正了此问题

**Comment by kaweizz** [comment]
虽然识别修正了， 手动安装系统为专业版,增加应答文件 就自动变成了企业版 ... 应答没有添加<key>项
不知道为什么会产生这么诡异的问题 ......
