### ISSUE TITLE
2008 x86系统无驱动管理功能

### ISSUE THREAD

**Issue by spirit3001** [Chuyu-Team/Dism-Multi-language#427]
win7x86系统有“驱动管理”功能，同样的win7核心的2008 x86却没有“驱动管理”功能，是什么原因？

**Comment by MouriNaruto** [comment]
Win7对应的是只有x64的2008 R2

Vista与其对应的2008不支持驱动管理

**Comment by mingkuang-Chuyu** [comment]
同上，主要是Vista框架跟Win7以及以后版本略微不同……用户量少就不支持了。
