### ISSUE TITLE
[Suggestion] Autounattend graphically configure.

### ISSUE THREAD

**Issue by Jhovany200** [Chuyu-Team/Dism-Multi-language#428]
If there could be a section to graphically configure the "Autounattend.xml" for the "ISO image".
Example:
"true" or "false" for the selection that only has those options.
"And a space to write" in the sections that are mandatory to write, such as the installation serial.

As a suggestion of the idea of ​​this page for the "Autounattend.xml": 
http://windowsafg.no-ip.org/

Conclusion: So that it is easier to configure "Autounattend" and understand.
"Please take the idea into account".

**Comment by mingkuang-Chuyu** [comment]
Thanks ,But Dism++ doesn't plan to add new features. I'm busy with other things.

**Comment by MouriNaruto** [comment]
Archived, #707
