### ISSUE TITLE
不能挂载wepe win10  64位2.0版本的wepe64.wim文件

### ISSUE THREAD

**Issue by wwliuyi** [Chuyu-Team/Dism-Multi-language#430]
电脑是戴尔台式xps8930，内有16g英特尔傲腾闪存和1t的机械硬盘，安装完系统后找了wepe win10  64位2.0版本来做系统维护，制作好U盘启动pe后，不能识别硬盘。用网上介绍的方法是用dism++注入驱动，在挂载wepe64.wim文件时，提示数据无效。

**Comment by mingkuang-Chuyu** [comment]
建议你用微软的Dism试试，八成是wim文件本身问题。

**Comment by mingkuang-Chuyu** [comment]
关闭此问题。用户长时间未回复
