### ISSUE TITLE
update禁止驱动更新出错

### ISSUE THREAD

**Issue by wsdixin** [Chuyu-Team/Dism-Multi-language#44]
经常性自动归位。希望能添加控制面板-设备和打印机-更改设备安装设置-否
这种按钮
按钮需要在控制面板中搜索设备两个字
规则不知道。希望能添加。不然老是自动归位

**Comment by mingkuang-Chuyu** [comment]
这种功能需要微软本身提供支持…… 另外 经常性自动归位 是什么意思 可以发截图来看看么

**Comment by wsdixin** [comment]
就是说。我在UPDATE里面关掉了
windows驱动更新不包括驱动文件。然后他自己按钮又还原了。不知道是不是杀毒的问题

**Comment by mingkuang-Chuyu** [comment]
谢谢  可能是WIndows Update自己的逻辑……

另外 在Windows 10 14393里面正常啊，请问你是什么系统 你能提供截图吗？你在哪里看的设置

**Comment by mingkuang-Chuyu** [comment]
暂时关闭，用户长时间无应答，同时本地测试正常。如果有疑问，可以重新打开此问题。
