### ISSUE TITLE
新手刚学习用dism++给个小建议

### ISSUE THREAD

**Issue by youngerzhong** [Chuyu-Team/Dism-Multi-language#442]
在挂截映像时，我用的是中文路径，然后等待了好久好久好久之后加截完了，才提示要用英文路径不然会有未知的错误，所以我建议在挂载映像框底下做个灰色的提示给大家，谢谢

**Comment by mingkuang-Chuyu** [comment]
用中文路径不会有问题，Dism++这样提示只是为了防范未然。
