### ISSUE TITLE
win10无法扫描到更新

### ISSUE THREAD

**Issue by scccboom** [Chuyu-Team/Dism-Multi-language#443]
请问dism++用于更新扫描的wsusscn2.cab是否与微软同步，最近能在windows10自带的更新中更新，但dism++扫描不到更新，删除cab重新下载也不行。
如果可以的话是否可以提供dism++的源码fork，或CBS模块的头文件、API等信息。

**Comment by MouriNaruto** [comment]
由于我作为Dism++的开发者之一，可以告诉你Dism++用的数据库文件和ms的有些区别（考虑到大部分人的硬件配置）
Dism++的核心部分是不会开源的，当你拿到Dism++代码的时候，我想你的目的就不会这么单纯了
Dism++的作者曾经也很单纯，也分享过最早的清理工具的实现；但世界上总有目的不纯的人，作者当时一气之下改名……

我说话有些直，但还是说了，希望理解

毛利
