### ISSUE TITLE
Windows 10 1803 OneDrive导致备份出错提示无效句柄（invalid handler）

### ISSUE THREAD

**Issue by 1and1get2** [Chuyu-Team/Dism-Multi-language#444]
win版本 Microsoft Windows [Version 10.0.17133.73]
试过 online 和offline 两个环境

**Comment by 1and1get2** [comment]
dism ++ 版本 10.1.1000.62

**Comment by 1and1get2** [comment]
[Dism++.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/1913881/Dism.log)

**Comment by mingkuang-Chuyu** [comment]
手动打开这个文件看看
C:\Users\1and1\OneDrive\Copy_changes_based_on_UX_v2.7.xlsx

**Comment by 1and1get2** [comment]
我格式化了分区重新安装了
我也怀疑过硬盘文件损坏 跑过chkdsk （有错）和坏道扫描 （无错）

全新安装的系统跟新.70版本 目前还没问题

**Comment by mingkuang-Chuyu** [comment]
OneDrive将导致Dism++无法备份

**Comment by mingkuang-Chuyu** [comment]
### 备份成功之后的wim 文件打不开 提示invalid data
这个问题最新版已经修复了此问题，这个属于历史问题。不再受理。

**Comment by mingkuang-Chuyu** [comment]
#3ec67bd0

**Comment by mingkuang-Chuyu** [comment]
已经发布新规则解决
