### ISSUE TITLE
 如何将当前的优化方案导出为配置文件

### ISSUE THREAD

**Issue by omaidb** [Chuyu-Team/Dism-Multi-language#447]
已经在本地优化好系统，对当前方案比较满意，想分享给其他用户使用当前优化方案，能否将当前配置导出为配置文件呢。分享给其他用户后，直接导入配置就可以执行当前优化。

**Comment by MouriNaruto** [comment]
现在还不支持

**Comment by mingkuang-Chuyu** [comment]
不支持此功能，配置文件只能自己编写
