### ISSUE TITLE
Windows10 17134.1 系统备份，提示句柄无效

### ISSUE THREAD

**Issue by clongfly8023** [Chuyu-Team/Dism-Multi-language#451]
如题，17133.1和17133.73都尝试过，均有句柄无效的错误提示，无法备份。
刚开始是可以看到在备份的，几分钟后会出现句柄无效的提示，我装了Linux子系统，Ubuntu。
![default](https://user-images.githubusercontent.com/29867903/39309550-dbf35ad0-499a-11e8-8e11-acb37cb03f34.png)
log日志在下面，不过我看了一下，貌似没有今天的……
[dism.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/1951412/dism.log)

**Comment by MouriNaruto** [comment]
含有 Linux 子系统的映像无法使用基于 wimgapi 的 ImageX, DISM 和 Dism++ 进行备份

因为在 Windows 子系统之上的 wimgapi 不支持区分大小写（虽然 Windows 的内核与文件系统皆支持区分大小写，但是 Windows 子系统不支持不区分大小写）

毛利
