### ISSUE TITLE
是否考虑在"空间回收"面板添加"自定义扫描项"的选项?

### ISSUE THREAD

**Issue by ZhLong-473811012** [Chuyu-Team/Dism-Multi-language#455]
比如我想删掉几百MB的Chrome Cache，%AppData%\Local\Google\Chrome\User Data\Default\Cache，只能手动去删掉…

**Comment by MouriNaruto** [comment]
扫描项可以自己编辑
把 config 目录的 data.zip解压得到 data.xml 就能自定义了
