### ISSUE TITLE
贡献规则:Win10-1803 内核隔离_内存完整性选项

### ISSUE THREAD

**Issue by Luupw3d** [Chuyu-Team/Dism-Multi-language#459]
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\HypervisorEnforcedCodeIntegrity

Enabled项，0为关1为开

原帖来自:
https://zhuanlan.zhihu.com/p/36295152

**Comment by MouriNaruto** [comment]
收到

**Comment by mingkuang-Chuyu** [comment]
话说这个有什么用途？比如？

**Comment by Luupw3d** [comment]
有些用户在射中中误打开此选项后，设置中就无法关闭了。
至于这个选项的功能，大概和“熔断”“幽灵”两个漏洞相关？使用一些更激进的预防性措施去规避问题吧，不过可能影响性能而默认关闭了……

**Comment by mingkuang-Chuyu** [comment]
那就没什么用了……毕竟用户又看不懂这是什么，乱调整反而可能会出问题。真有需要的人可以直接自行修改注册表。
