### ISSUE TITLE
WIN10_64使用Dism++10.1.25.1后Clear Type设置失效

### ISSUE THREAD

**Issue by mc315** [Chuyu-Team/Dism-Multi-language#46]
本人在临安初语一夜落红QQ里很久了，这两年木时间聊天在夜以继日攻读法学，希望做一名律师，去QQ里很少了，这个QQ群里，俺加进去，不就又被踢出来，所以只能在此留言了：使用Dism++10.1.25.1对WIN10_64空间回收后，启动好的Clear Type设置在重启电脑后就失效，当然最近刚好赶上这个系统升级，不知到底是使用Dism++10.1.25.1空间回收功能，还是系统升级惹的祸。

**Comment by mingkuang-Chuyu** [comment]
感谢你的支持，祝你早日实现愿望。

另外 Clear Type设置 重启就失效，这个问题我需要跟踪下，等双休日时，我会处理此问题，谢谢。

**Comment by mingkuang-Chuyu** [comment]
并未发现此问题，你能说说 你的系统具体版本么？
我测试的是Windows 10 10586

**Comment by ugksoft** [comment]
我跑过来打个补丁
 在主界面,右边空白区,贴个二维码吧, 让大家捐款.虽然超小比例,但多少能收到几个油条大饼钱
(当然,事先说一下,我是不给的,)

**Comment by Hexhu** [comment]
win下Clear type 的设定在大版本更新后的确会改变。

为了能更好地确定你的情况，麻烦提供你现在的系统版本号（先用ctrl+R调出“运行”，再运行“msinfo32” ，版本号在右侧表格里）

**Comment by mingkuang-Chuyu** [comment]
用户长时间无应答，同时本地无法复现此类问题，暂时关闭。如果后续过程依然有问题，可以重新打开此问题

**Comment by mc315** [comment]
您好，问题已解决。方法是：对于win10_64的1703之OS版本15063.250从微软主站下载更新了一下原系统，原设置都没有改变，问题解决了。然后用最新版Dism++再次回收空间，一切正常了。非常感谢你们的努力和热忱！由于很忙，很少来这里，所以回复晚了，请海涵!

在 2017-04-09 12:56:18，mingkuang <notifications@github.com> 写道：


Closed #46.

**Comment by mc315** [comment]
您好，问题已解决。方法是：对于win10_64的1703之OS版本15063.250从微软主站下载更新了一下原系统，原设置都没有改变，问题解决了。然后用最新版Dism++再次回收空间，一切正常了。非常感谢你们的努力和热忱！由于很忙，很少来这里，所以回复晚了，请海涵!

在 2017-04-09 12:56:18，mingkuang <notifications@github.com> 写道：


用户长时间无应答，同时本地无法复现此类问题，暂时关闭。如果后续过程依然有问题，可以重新打开此问题

**Comment by mc315** [comment]
您好，问题已解决。方法是：对于win10_64的1703之OS版本15063.250从微软主站下载更新了一下原系统，原设置都没有改变，问题解决了。然后用最新版Dism++再次回收空间，一切正常了。非常感谢你们的努力和热忱！由于很忙，很少来这里，所以回复晚了，请海涵!

在 2017-04-08 19:05:51，Hexhu <notifications@github.com> 写道：


win下Clear type 的设定在大版本更新后的确会改变。

为了能更好地确定你的情况，麻烦提供你现在的系统版本号（先用ctrl+R调出“运行”，再运行“msinfo32” ，版本号在右侧表格里）

**Comment by mc315** [comment]
您好，问题已解决。方法是：对于win10_64的1703之OS版本15063.250从微软主站下载更新了一下原系统，原设置都没有改变，问题解决了。然后用最新版Dism++再次回收空间，一切正常了。非常感谢你们的努力和热忱！由于很忙，很少来这里，所以回复晚了，请海涵!

在 2017-03-26 19:58:30，mingkuang <notifications@github.com> 写道：


并未发现此问题，你能说说 你的系统具体版本么？
我测试的是Windows 10 10586

**Comment by mc315** [comment]
您好，问题已解决。方法是：对于win10_64的1703之OS版本15063.250从微软主站下载更新了一下原系统，原设置都没有改变，问题解决了。然后用最新版Dism++再次回收空间，一切正常了。非常感谢你们的努力和热忱！由于很忙，很少来这里，所以回复晚了，请海涵!

在 2017-03-21 16:43:57，mingkuang <notifications@github.com> 写道：


感谢你的支持，祝你早日实现愿望。

另外 Clear Type设置 重启就失效，这个问题我需要跟踪下，等双休日时，我会处理此问题，谢谢。

**Comment by mingkuang-Chuyu** [comment]
谢谢支持，能找到问题就好……
