### ISSUE TITLE
桌面快捷方式经常会边空白，只有这一款软件才会，其他软件不会！

### ISSUE THREAD

**Issue by hhchaobin** [Chuyu-Team/Dism-Multi-language#460]
如题，而且经常是一开始解压打开不回，等打开一两次桌面快捷方式就变成白色，并且清除图标缓存无用！

**Comment by MouriNaruto** [comment]
你是否选择了图标缓存清理项

**Comment by hhchaobin** [comment]
没有清理过。每次用iso格盘重装完系统解压了dism++，桌面刷新几次就变白了。。。。而且整台电脑就这个软件会这样。其他绿化软件都没这样过。
