### ISSUE TITLE
当前账户打开文件资源管理器时打开此电脑&不显示最近打开文件

### ISSUE THREAD

**Issue by intionwun** [Chuyu-Team/Dism-Multi-language#462]
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer]
"ShowRecent"=dword:00000000
"ShowFrequent"=dword:00000000

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"LaunchTo"=dword:00000001

**Comment by MouriNaruto** [comment]
规则已存在

快速访问不显示最近使用的文件（by 溯汐潮）
快速访问不显示常用文件夹（by 溯汐潮）
打开资源管理器时显示此电脑

**Comment by fya16838** [comment]
关闭该功能后无法回复，是什么情况
