### ISSUE TITLE
当前账户任务栏不显示“人脉”

### ISSUE THREAD

**Issue by intionwun** [Chuyu-Team/Dism-Multi-language#465]
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\People]
"PeopleBand"=dword:00000000

**Comment by MouriNaruto** [comment]
规则已存在

隐藏任务栏上的人脉（by 、Cloud.）
