### ISSUE TITLE
当前账户桌面显示此电脑和控制面板图标

### ISSUE THREAD

**Issue by intionwun** [Chuyu-Team/Dism-Multi-language#467]
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\ClassicStartMenu]
"{20D04FE0-3AEA-1069-A2D8-08002B30309D}"=dword:00000000
"{5399E694-6CE5-4D6C-8FCE-1D8870FDCBA0}"=dword:00000000
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel]
"{20D04FE0-3AEA-1069-A2D8-08002B30309D}"=dword:00000000
"{5399E694-6CE5-4D6C-8FCE-1D8870FDCBA0}"=dword:00000000

**Comment by MouriNaruto** [comment]
此功能已存在

Dism++优化项 “桌面图标管理”
