### ISSUE TITLE
win10更新出现问题，请教如何解决。

### ISSUE THREAD

**Issue by rcyggdra** [Chuyu-Team/Dism-Multi-language#47]
![image](https://cloud.githubusercontent.com/assets/8652464/24081142/101bd7e2-0ce8-11e7-8495-63052a8f4e38.png)
修复受损也是同样的提示。

**Comment by mingkuang-Chuyu** [comment]
Hi，请先确保洗头是否被精简，如果你曾经精简过系统。那么报告此问题是非常正常的。解决办法就是修复到原版系统状态。谢谢

如果你未精简系统，那么请你等待一段时间。Dism++目前有个BUG，卸载更新后会出现你说的现象。请耐心等待新版本。暂时可以关闭差异传输（选项 - 详细设置 - 差异传输 = 关闭）来解决此问题。

**Comment by rcyggdra** [comment]
要说精简的话也是只用了Dism++。
这问题是最近这一次更新才有的，之前的补丁都可以顺利用Dism++更新，
截图的累积补丁也只是3月15日的，或许是你说的BUG吧，那我期待下一版本的更新不会出现这问题。
感谢回答。

**Comment by mingkuang-Chuyu** [comment]
Hi，Dism++并不是精简工具。这个问题 可以暂时关闭 差异传输 来解决。具体修复这个问题 需要下个版本

**Comment by NYM123** [comment]
如何修复到原版系统状态？？

**Comment by mingkuang-Chuyu** [comment]
Hi，此问题已经修复，能否帮忙试试测试版Dism++（QQ群 200783396）谢谢

**Comment by rcyggdra** [comment]
![image](https://cloud.githubusercontent.com/assets/8652464/24366940/6082b780-134d-11e7-944d-3156d010b01f.png)
按照默认的设置更新，结果失败了。

**Comment by mingkuang-Chuyu** [comment]
嗯 说明已经修复成功，不再是找不到指定源了。这个参数错误是微软BUG
我在知乎里写了修复办法，可以修复此问题。另外还建议你反馈给微软。
https://zhuanlan.zhihu.com/p/25994994

**Comment by mingkuang-Chuyu** [comment]
已经验证 测试版修复此问题，关闭
