### ISSUE TITLE
组策略-禁用“允许使用Cortana”

### ISSUE THREAD

**Issue by intionwun** [Chuyu-Team/Dism-Multi-language#474]
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Search]
"AllowCortana"=dword:00000000

**Comment by MouriNaruto** [comment]
该规则 Dism++ 已存在

> 关闭多嘴的小娜（by 朽木）
