### ISSUE TITLE
组策略-启用“Windows更新不包括驱动程序”

### ISSUE THREAD

**Issue by intionwun** [Chuyu-Team/Dism-Multi-language#475]
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate]
"ExcludeWUDriversInQualityUpdate"=dword:00000001

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy Objects\{582B387B-8F28-48F7-A74B-9A2056F9FA94}Machine\Software\Policies\Microsoft\Windows\WindowsUpdate]
"ExcludeWUDriversInQualityUpdate"=dword:00000001

**Comment by MouriNaruto** [comment]
需要扩充原有规则，做个标记
