### ISSUE TITLE
组策略-启用“用户帐户控制用于内置管理员帐户的管理员批准模式”

### ISSUE THREAD

**Issue by intionwun** [Chuyu-Team/Dism-Multi-language#478]
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
"EnableLUA"=dword:00000001

**Comment by MouriNaruto** [comment]
Dism++ 已有此项规则

“将用户账号控制程序（UAC）调整为”
