### ISSUE TITLE
禁用Win8、8.1、10第一次欢迎等待过久界面

### ISSUE THREAD

**Issue by intionwun** [Chuyu-Team/Dism-Multi-language#479]
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon]
"EnableFirstLogonAnimation"=dword:00000000

**Comment by MouriNaruto** [comment]
已添加
https://github.com/Chuyu-Team/Dism-Multi-language/commit/70dadd21bc4e0ca4b7ffac248ff78db475783185

顺便加上了组策略编辑器的对应键值
