### ISSUE TITLE
无法设置 多国语言选项

### ISSUE THREAD

**Issue by clfsoft** [Chuyu-Team/Dism-Multi-language#48]
比如在日文系统下面,要使用中文语言界面.

**Comment by mingkuang-Chuyu** [comment]
Hi,Dism++自动跟随系统语言设置，因此在控制面板 语言 格式 调整为中国即可。

如果你的格式是日文系统下面,而要使用中文语言界面。这样是不支持的。因为系统的相关设置都被配置成了日本区域本地化信息。Windows将无法正常显示中文字体。

建议你先反馈给微软，等Windows完整支持Unicode。Dism++才能完美支持你说的功能，那时而我才会开始做。

**Comment by mingkuang-Chuyu** [comment]
不过 需要注意的是，如果你把格式调整为中文，反之  日语相关字体显示就会异常，你自己好好把握吧。

**Comment by clfsoft** [comment]
我的意思是Dism的UI使用语言中文.不是内容.比如强行把ja.xml替换成中文的xml.

**Comment by mingkuang-Chuyu** [comment]
我知道你的意思，但是副作用我也跟你说了，中文无法完美显示。另外推荐的方法我也跟你说了，在系统控制面板 - 区域 - 格式 调整为 中国（中文）。
然后 重新登录账号即可。
