### ISSUE TITLE
Boot Camp使用DISM遇到问题

### ISSUE THREAD

**Issue by sclsj** [Chuyu-Team/Dism-Multi-language#480]
在研究Windows时，突然想到之前用过的DISM++，然后不小心点了选项中的“在WinRE里启动DISM”，结果重启之后，每次都进入WinRE，但没有启动DISM，而且选择除了“关机”和“使用命令行”选项选择其他选项都报错（我在关闭固件密码时也是如此），然后还不能使用内建触控版，键盘，和Touch Bar，只能用转换头外接键盘和鼠标。如何启动Win10而非WinRE?

**Comment by MouriNaruto** [comment]
你也许需要修改bcd文件

**Comment by mingkuang-Chuyu** [comment]
在WinRE里启动DISM 仅一次有效，这是微软自身机制，可能在Boot Camp下 这个机制有问题。

要解决此问题，你只能修改BCD文件，删除Dism++的启动项。
