### ISSUE TITLE
dism++备份win10显示句柄无效，OneDrive下的文件造成的

### ISSUE THREAD

**Issue by dahounet** [Chuyu-Team/Dism-Multi-language#486]
系统：Windows10 1803

检查日志发现这个错误
2018-05-12 04:58:16, Error	PID=20216 TID=2052, Wimgapi	\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy1\Users\xxxx\OneDrive\xxxx.rar 0x00000006

是OneDrive路径下的文件，然而我启用了OneDrive的“根据需要下载文件以节省空间”，里面的这个文件在此时只是占位符，并不是实际的文件，应该是这个原因造成备份失败。

**Comment by MouriNaruto** [comment]
got，这个问题我需要看看

**Comment by mingkuang-Chuyu** [comment]
此问题已经确认，暂时建议排除OneDrive相关文件

尚未有真正解决方案

**Comment by mingkuang-Chuyu** [comment]
#444 已经有其他 用户反馈，关闭此问题。重复反馈。
