### ISSUE TITLE
挂载Windows10（1803）时，版本识别错误

### ISSUE THREAD

**Issue by fanck0605** [Chuyu-Team/Dism-Multi-language#494]
从install.wim挂载Windows10 Pro到硬盘时，会被识别成企业版，导致无法正常集成专业版的补丁

**Comment by mingkuang-Chuyu** [comment]
系统本身就是企业版，只是启动过程中会改变为实际版本。另外无法扫描出专业版补丁的原因是微软的WSUS服务器中条件配置问题，吧17134写成了17133。

版本识别这个暂时先观望观望。

**Comment by mingkuang-Chuyu** [comment]
#456 重复，关闭此问题。
