### ISSUE TITLE
执行空间回收后，开始菜单空白、开始菜单按钮比原来少了两个、磁贴消失不见了

### ISSUE THREAD

**Issue by goeway** [Chuyu-Team/Dism-Multi-language#499]
只进行了执行空间回收操作，空间回收时，除了“windows更新安装纪录”、“windows预读取文件”和“package cache目录”没选外，其他的全选了，结果清理后开始菜单不仅变空白了，而且按钮也少了一两个，同时磁贴栏消失不见了，以前也曾试过这样子，不过仅仅是磁贴栏没了开始菜单是正常。现在看来，磁贴栏消失不见是Dism++"惹的祸"！系统为win10 1607 32位，使用的dism++版本是 10.1.1000.70

**Comment by mingkuang-Chuyu** [comment]
能提供截图吗？我猜测这是历史问题，explorer权限所致。

**Comment by subeth** [comment]
我最近使用Dism++进行空间回收操作，空间回收时，除了“windows更新安装纪录”、“windows预读取文件”和“package cache目录”没选外，其他的全选了，结果清理后出现以下问题：
1.	开始菜单点击无效，现在没法通过开始菜单使用程序，只能用第三方软件代替开始菜单；
2.	任务栏上的程序图标点击右键无效，现在无法通过该右键固定程序在任务栏；
3.	所有任务栏上的选项，包括操作中心、时间日历统统无法点击。
4.	我的系统为win10企业版2016长期服务版 1607 64位，OS版本 14393.2273。
5.	使用的Dism++版本是 10.1.1000.70 UEFI Firmware。

**Comment by goeway** [comment]
@mingkuang-Chuyu 在发表这个问题反馈时不知哪出问题了图传不上，于是多发了封邮件到你的mingkuang@live.com邮箱了，我再在这试一下看能不能成功发图。
![insertpic_ 05-27-11-46-31](https://user-images.githubusercontent.com/23276757/40582296-372bf3be-61a4-11e8-9846-c692e93e47ca.jpg)

**Comment by subeth** [comment]
![qq 20180527110510](https://user-images.githubusercontent.com/39661008/40582325-0450459a-6162-11e8-9ac8-4aa80d2d0393.jpg)
