### ISSUE TITLE
无法拖拉动作

### ISSUE THREAD

**Issue by AristotleYap** [Chuyu-Team/Dism-Multi-language#5]
只要勾选在系统优化-》资源管理器导航窗口图标管理-》隐藏资源管理器导航窗口中的快速访问（by starP），就会无法在导航栏里做复制和移动的拖拉

**Comment by AristotleYap** [comment]
更新了都还没解决问题啊

**Comment by mingkuang-Chuyu** [comment]
这个问题我问了 规则提供者，他并不清楚，追查还需要一段时间。另外这个问题也并不算严重，我先处理多国语言翻译

**Comment by AristotleYap** [comment]
好的，最近也是忙啊，加油

**Comment by mingkuang-Chuyu** [comment]
找了很久都没有解决办法，也不知道新的隐藏方式。只好给此项目添加一个警告：

启用此选项将导致导航窗口拖拽功能无法使用。

这个问题也算是解决了。以后如果有更好的解决方案。到时再说吧
