### ISSUE TITLE
"Internet Download Manager" line for their translation. All languages.

### ISSUE THREAD

**Issue by MS-PC2** [Chuyu-Team/Dism-Multi-language#504]
They could add the "IDM or Internet Download Manager" lines for their translation. All langueges.

**Comment by mingkuang-Chuyu** [comment]
OK

**Comment by MS-PC2** [comment]
@mingkuang-Chuyu 
And also if I could change all references my profile name from Jhovany200 to MS-PC2, in all languages.
Example: (by Jhovany200) to (by MS-PC2)

Please, thanks.

**Comment by MS-PC2** [comment]
@verdy-p thanks for adding the Internet Download Manager translations.
