### ISSUE TITLE
空间回收怎么没有老的驱动程序清理了？

### ISSUE THREAD

**Issue by i5151** [Chuyu-Team/Dism-Multi-language#507]
体积大，更新频繁的驱动占用空间挺大的，逐步积累起来更是客观，新版怎么没有老驱动清理了？

**Comment by MouriNaruto** [comment]
由于该功能可能会引起系统蓝屏，于是被放入了专家模式

如果想使用，请开启Dism++的专家模式
当然，不建议你在重要的机器上测试这个功能
