### ISSUE TITLE
WIM转ESD过程中CPU和内存占用率都飙升至90%以上

### ISSUE THREAD

**Issue by northsheep** [Chuyu-Team/Dism-Multi-language#509]
使用微软的MediaCreationTool下载了Win10 1803的iso，在参照帮助文档中的[给ISO离线集成补丁]( https://www.chuyu.me/zh-Hans/Document.html?file=Best/%E7%BB%99ISO%E7%A6%BB%E7%BA%BF%E9%9B%86%E6%88%90%E8%A1%A5%E4%B8%81.md)操作后，将打好补丁的install2.wim转成install2.esd时，出现如下图二情况，同时计算机开始卡顿。想知道这是因为本机配置过低，还是因为Dism++的WIM转ESD功能存在待改进的地方。

系统配置截图：
![system](https://user-images.githubusercontent.com/13964012/41223041-402bf718-6d9b-11e8-8dc9-1f6b0c7ee9e4.png)

任务管理器截图：
![dism cpu ram](https://user-images.githubusercontent.com/13964012/41223040-3fed099a-6d9b-11e8-8cfc-7f93647c8f56.png)

**Comment by MouriNaruto** [comment]
这不是Dism++的问题，也不是你配置的问题

这只能证明微软的映像API能充分利用系统资源
毕竟我笔记本的CPU是i7 8750H在这种情况下也能顺利地满载
