### ISSUE TITLE
Beta 10.1.26.7版本系统优化项目部分操作无作用

### ISSUE THREAD

**Issue by Kotori-0912** [Chuyu-Team/Dism-Multi-language#51]
Beta 10.1.26.7在Windows10里面Explorer选择里面”隐藏快捷方式小箭头“和“创建快捷方式时不添加”快捷方式”文字 这两个优化，在选择时提示用户取消操作

**Comment by mingkuang-Chuyu** [comment]
Hi,程序提示 是否需要重启Explorer时，选择确定即可。不要选择取消。如果选择取消，那么就会提示 用户取消操作。

**Comment by Kotori-0912** [comment]
@mingkuang-Chuyu 没有弹出窗口叫我是否重启Explorer，选之后直接提示用户取消操作

**Comment by mingkuang-Chuyu** [comment]
Windows 10上确实有这个问题…… 谢谢

**Comment by mingkuang-Chuyu** [comment]
已经修复，今晚会发布新的测试版。

**Comment by mingkuang-Chuyu** [comment]
新的测试版已经发布
