### ISSUE TITLE
想搭建一个补丁服务器

### ISSUE THREAD

**Issue by omaidb** [Chuyu-Team/Dism-Multi-language#510]
dism++ 集中安装补丁感觉用起来真是不错。
但如果内网环境有多台机器需要安装补丁，每一台都从外网下载补丁真的好慢。
所以在想，能不能搭建一个补丁服务器呢。让dism++可以自定义补丁源，该从内网下载补丁，这样就节省了带宽和时间。
不知道有没有大佬们想一起聊聊的

**Comment by MouriNaruto** [comment]
现阶段的话，也许你可以在局域网弄个共享目录
然后把Dism++的补丁缓存目录通过符号链接的方式链接到那个共享目录

也许能实现你的想法

**Comment by MouriNaruto** [comment]
@mingkuang-Chuyu

**Comment by omaidb** [comment]
脑洞好大啊
Naruto Mouri <notifications@github.com>于2018年6月12日 周二15:52写道：

**Comment by omaidb** [comment]
我可以在局域网搭建一个简易httpserver

Jon.Lee <omaidb@gmail.com>于2018年6月12日 周二17:21写道：

**Comment by mingkuang-Chuyu** [comment]
如果搭服务器，那么你需要在本地搭个反向代理服务器。你确定你会搭吗？
到时我功能增加了 你又不会用。

**Comment by omaidb** [comment]
再要么你做一个补丁服务端
mingkuang <notifications@github.com>于2018年6月14日 周四10:59写道：

**Comment by mingkuang-Chuyu** [comment]
服务器的事情你自己解决吧，到时我做了你还要求这个要求那个。比如能不能再加负载均衡，能不能加个ui，能不能控制缓存时间。你就回答你会不会搭反向代理服务器。

比如一个补丁下载地址是http://wsus.com/123.cab
我会向你的服务器请求这个url
http://mywsus.com/wsus.com/123.cab

另外服务器需要支持range，否则Dism++差异传输无法正常使用。

**Comment by omaidb** [comment]
😂，以前用过缓存方案。
不过还是 谢谢大佬

mingkuang <notifications@github.com>于2018年6月16日 周六09:21写道：
