### ISSUE TITLE
备份系统时 允许清空Computer\HKEY_LOCAL_MACHINE\SYSTEM\MountedDevices 下键值

### ISSUE THREAD

**Issue by 1and1get2** [Chuyu-Team/Dism-Multi-language#514]
我两个硬盘 第一个分区的系统的备份恢复到第二个会导致系统盘非 C 盘 （c盘为原本备份分区）

另，有没有文档说明是如何自定义规则？ 注册表操作或者cmd命令。 另外这些规则是在什么时候执行的

**Comment by 1and1get2** [comment]
另，如何修改Data.xml? 直接修改吗？如果是的话 这个文件是压缩到Data.zip中的  是否需要在打包进去？

**Comment by mingkuang-Chuyu** [comment]
Dism++新版本会自动修正盘符，你只需下载Dism++最新版即可（10.1.1000.70C）。

**Comment by 1and1get2** [comment]
还有自定义规则的格式怎么写？

**Comment by mingkuang-Chuyu** [comment]
https://www.chuyu.me/zh-Hans/Document.html?file=Dism++Library/%E8%A7%84%E5%88%99%E7%BB%93%E6%9E%84%E5%8F%82%E8%80%83.md

可以参考规则白皮书。
