### ISSUE TITLE
10.1.1000.70C 还原wim时提示数据无效

### ISSUE THREAD

**Issue by 1and1get2** [Chuyu-Team/Dism-Multi-language#515]
10.1.1000.70C 自带wimgapi.dll 版本 10.0.16299.15
备份系统版本 1803 （17692.1000）
应用镜像是提示数据无效

如何临时手动更新wimgapi.dll 版本？ 手动替换系统内的似乎无效，关于中的版本号依然是老版本（17692.1000）
可以直接删除使用，但是在老版本的pe环境中就无法使用最新的api

**Comment by mingkuang-Chuyu** [comment]
Hi，Dism++ Beta已经更新了wimgapi，如果一切顺利那么很快就会更新外网正式版。

最后话说我这边Dism++x64很正常啊，如果系统目录的wimgapi版本号高于Dism++自带的，则会优先使用系统目录的。

环境是 Dism++ 10.1.1000.70C，Windows 10 1803 x64 专业版
