### ISSUE TITLE
 ErrorThe parameter is incorrect. 

### ISSUE THREAD

**Issue by yuessir** [Chuyu-Team/Dism-Multi-language#517]
OS : Win10 v1709 x64 && v1803 x64
Dism++ :Dism++10.1.1000.70C

Action: Clicking the first one apps to remove, and threw the error following
Error
The parameter is incorrect.
![parmerrpr](https://user-images.githubusercontent.com/8326310/41709998-25a5c048-7577-11e8-8652-638cb1020877.png)

**Comment by mingkuang-Chuyu** [comment]
What's the Netflix ? I didn't find it in Windows 10 1803 x64. Is your oem customized version?

**Comment by yuessir** [comment]
@mingkuang-Chuyu It's my HP OEM laptop.
