### ISSUE TITLE
建议用wimlib压缩esd

### ISSUE THREAD

**Issue by daiaji** [Chuyu-Team/Dism-Multi-language#518]
cbs的实现太卡太慢了 wimlib貌似也能压lzx

**Comment by MouriNaruto** [comment]
由于Dism++的核心部分并不开源，而wimlib的许可是gpl，用了就要开源；所以并不能用
鸭子上次跟我说，他也许以后用自己写的wim库

**Comment by mingkuang-Chuyu** [comment]
这个跟CBS无关，Dism++用的是微软的wimgapi。另外就算wimlib许可没问题也不会用它，因为它不完全跟微软兼容。让了他生成的esd，微软那边的setup，Dism之类的程序都可能无法正常使用。

**Comment by daiaji** [comment]
开源就完事了 自写的压缩库没经过检验也不见得比ms实现的好

**Comment by MouriNaruto** [comment]
@daiaji 忘说了，纵使Dism++开源，也不会用带GPL的库。因为强迫开源还有传染性。还有鸭子的wim库必然会非GPL开源的（如果他做了的话）
但现在鸭子貌似不打算做，继续用微软的引擎保持与微软步调一致

**Comment by daiaji** [comment]
@MouriNaruto GPL没什么不好 就是因为有效力 linux才到今天还没死
国内许可证就是个弟弟 没人理的

**Comment by MouriNaruto** [comment]
@daiaji 

如果开源的话，我们不希望束缚其他开发者，但也不想被其他开发者所束缚。
锁只对君子有效，所以大概率会被别人恶意剽窃的部分是闭源的。

谁说用了GPL不能改协议的……我的个人项目先开始GPL v3 or later，但是其他人只是fork我的代码而不为我贡献。于是我后来用了MIT，反而偶尔有人pull request了。我依旧记得当时我从GPL转MIT的时候，我的个人项目的不少用户表示很高兴，那时才有人愿意对我的工具进行英化。

尤其是网络相关库，你现在如果弄个用GPL的新轮子，估计基本没人理你。因为这类库的许可都给开发者提供比较大的自由

毛利

**Comment by daiaji** [comment]
@MouriNaruto 你也知道是个人项目 稍微大一点的像是btrfs之类的 换协议不得是其他主要贡献者都同意才能换？所以正是强制性才能让linux系活下来 甚至说如果没有法律上的效力 GNU计划怕不是都死了几百年了 
你开源 我再闭源 有什么关系吗？
你不是允许的吗？
理所当然的事情
bsd之流只是对商业友好
至于项目死不死
会怎样？有人关心？
只是方便自己而已

**Comment by MouriNaruto** [comment]
@daiaji 我一般不用GPL的库，所以有底气吐槽。而且造新库一般都是不爽现有库。

**Comment by MouriNaruto** [comment]
@daiaji 独立作品用gpl库也需要开源，除非你用lgpl并使用动态编译才可以闭源。所以不少人即使喜欢开源也不喜欢gpl。

**Comment by daiaji** [comment]
@MouriNaruto 当然要开源 但是你可以选择不用

**Comment by mingkuang-Chuyu** [comment]
我不是已经解释了吗？  wimlib生成的 wim也有兼容性问题，会导致ms Dism无法正常使用。

另外 由于协议限制  Dism++也不能使用，一旦使用Dism++也需要开源，不然在国外容易被人喷。

最后一点，实现wimlib类似的库不算复杂，如果真的要用 也是我自己会写。我只是觉得暂时没有必要。

慢没关系，只要不出现什么兼容性问题 那么 都不是事情。

调用wimlib相关的工具 不少人已经跟我反馈 ms Dism无法识别，难道 用户辛辛苦苦保存了个wim最后发现 微软安装器 这样就对得起他们？

**Comment by mingkuang-Chuyu** [comment]
还有 你的理解有误，GPL他是传染性极强的癌症，一旦用了他的工程全部都要开。LGPL的话 到还有方式避免。

这是是为什么我们一般开源都是选择  MIT，因为这样使用者 只需要在readme里 写一行"Thunks"即可。
