### ISSUE TITLE
更新管理里手动增加补丁失败

### ISSUE THREAD

**Issue by wikilike7** [Chuyu-Team/Dism-Multi-language#52]
### 问题描述
1. win 7 sp1下加载win 7 sp1的镜像, 并使用更新管理中的添加补丁的功能增加一个win7的补丁
2. 增加的补丁是kb3125574, 是微软放出的集成补丁, 相当于是多个补丁打个包, 降低打补丁的次数
3. 错误截图如下:

![image](https://cloud.githubusercontent.com/assets/3377226/24533980/cd6c3cf6-15fd-11e7-8848-6616f75639f7.png)

**Comment by mingkuang-Chuyu** [comment]
这是你自己的问题，请严格按照微软官方的操作流程。

先集成 CBS堆栈更新，然后在集成此更新。
