### ISSUE TITLE
为什么winsxs临时文件每次扫描都有，而且删不掉？

### ISSUE THREAD

**Issue by wanrufang** [Chuyu-Team/Dism-Multi-language#521]
**Describe the bug（Bug信息）**
A clear and concise description of what the bug is. 用一句话概括这个Bug，哪里出现了异常。
**临时文件下的winsxs临时文件每次扫描都有，而且删不掉，这一项的大小就是204MB，删掉的总大小还不到100M，再扫描这一项还有204MB**

**To Reproduce（如何重现？）**
Steps to reproduce the behavior:（详细说明下Bug重新步骤，此过程非常重要，如果言语表达不了就用步骤记录器，在cmd里面输入psr即可。）

**Expected behavior（预期行为）**
A clear and concise description of what you expected to happen. 正常情况下应该是怎么样的？

**Screenshots（截图）**
If applicable, add screenshots to help explain your problem. 如果你能提供相关错误截图那么再好不过了。
**怎么发截图**

**please complete the following information:（环境信息）**
 - OS: [ **Windows 10 x64 1803**]
 - Dism++ Version [e.g. 10.0.1000.70]

**Additional context（其他）**
Add any other context about the problem here. 如果你有其他信息，可以在这里补充

**Comment by MouriNaruto** [comment]
应该是正常的，因为每次操作sxs的时候都会产生临时文件用于缓存以加快后续的操作

**Comment by wanrufang** [comment]
哦，那么产生的这些临时文件能不能删？ @MouriNaruto

**Comment by mingkuang-Chuyu** [comment]
不要点击扫描，直接点击删除就能删掉。一旦点击扫描就会初始化cbs，就会导致文件占用而删不掉。这个问题难以解决，因为Dism++各种接口都要用到cbs
