### ISSUE TITLE
[feature request] Dism++ 能否删除 Edge 之类的自带 App？

### ISSUE THREAD

**Issue by Trumeet** [Chuyu-Team/Dism-Multi-language#522]
**Is your feature request related to a problem? Please describe.（你提交这个反馈的目的是什么？是否遇到了Dism++现有的问题？）**
提一个功能建议，不知道 Dism++ 以后能否删除 Edge 等 Win10 自带删不掉的 Apps

**Describe the solution you'd like（描述你的解决方案）**
同上。
**Describe alternatives you've considered （是否有其他备选方案？）**
N/A
**Additional context（其他信息可以统一再此处填写）**
N/A

个人不懂 Win，望谅解，谢谢。

**Comment by mingkuang-Chuyu** [comment]
不于支持，Dism++不提供精简功能
