### ISSUE TITLE
两点建议

### ISSUE THREAD

**Issue by ghost** [Chuyu-Team/Dism-Multi-language#523]
1.编辑hosts的软件可以使用notepad++默认打开吗，每次打开都是系统自带笔记本。
2.希望可以增加程序列表导出功能，最好能导出为HTML格式，直观明了。

**Comment by AcmenFu** [comment]
1.编辑hosts的软件可以使用notepad++默认打开吗，每次打开都是系统自带笔记本。
2.希望可以增加程序列表导出功能，最好能导出为HTML格式，直观明了。

**Comment by mingkuang-Chuyu** [comment]
@青蛙，可以考虑使用open参数？

**Comment by MouriNaruto** [comment]
Partially archived, #707
