### ISSUE TITLE
能不能增加一个导出配置的功能？

### ISSUE THREAD

**Issue by mrliming** [Chuyu-Team/Dism-Multi-language#524]
每次安装系统，运行dism++，都要进行大量的设置，以符合自己的使用习惯。能不能在系统优化里增加一个导出按钮，将设置好的的配置，保存起来，下次再安装系统的时候，直接导入自己的配置，以免繁琐的设置。

**Comment by ciwangminghenyangqi** [comment]
我也在找这项功能，原来是没有啊   每次确实都比较麻烦

**Comment by MouriNaruto** [comment]
请转到 https://github.com/Chuyu-Team/Dism-Multi-language/issues/578 讨论

**Comment by MouriNaruto** [comment]
Archived, #707
