### ISSUE TITLE
勾选整合引导菜单时 出现函数不正确的错误

### ISSUE THREAD

**Issue by codemasterPro** [Chuyu-Team/Dism-Multi-language#526]
**Describe the bug（Bug信息）**
勾选整合引导菜单 出现函数不正确的错误

**To Reproduce（如何重现？）**
选项-详细设置-勾选整合引导菜单-确定

**Expected behavior（预期行为）**
不知道

**Screenshots（截图）**

![image](https://user-images.githubusercontent.com/25348944/42727294-8b742e98-87d6-11e8-9471-9c4f56d6604f.png)

**please complete the following information:（环境信息）**
 - OS:
![default](https://user-images.githubusercontent.com/25348944/42727339-5b8b942c-87d7-11e8-980a-e1a099db428b.PNG)
 - Dism++ Version ： 10.0.1000.70

**Additional context（其他）**
Add any other context about the problem here. 如果你有其他信息，可以在这里补充

**Comment by mingkuang-Chuyu** [comment]
需要更多信息

**Comment by mingkuang-Chuyu** [comment]
需要远程，可能Dism+

**Comment by mingkuang-Chuyu** [comment]
需要远程，可能系统盘被加密。

**Comment by mingkuang-Chuyu** [comment]
用户长时间 无应答……暂时先关闭此功能，如果后期有消息了，可以加QQ群，让我远程看看环境。
