### ISSUE TITLE
增加此电脑中七个文件夹的“单独”隐藏

### ISSUE THREAD

**Issue by atomsyoung** [Chuyu-Team/Dism-Multi-language#527]
**Is your feature request related to a problem? Please describe.（你提交这个反馈的目的是什么？是否遇到了Dism++现有的问题？）**
现有的“系统优化—Explorer”相关设置中，视频、图片、文档、音乐、下载、桌面、3D对象等七个文件夹要么全部隐藏，要么全部显示。

**Describe the solution you'd like（描述你的解决方案）**
为每个文件夹设置单独的开关

**Comment by DeltaJNG** [comment]
可以手动修改注册表隐藏 
1.  win+r : regedit

2. 定位到 ：
\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\

3. 搜索 3D Objects （注意：搜索时一定要看准：  名称是“Name ”，数据是“3d objects” ）
![01](https://user-images.githubusercontent.com/17097003/44561523-c9087b80-a787-11e8-8cc7-482398a33ab2.PNG)

  然后打开子文件夹PropertyBag 操作如图  把show 改成 hide
![02](https://user-images.githubusercontent.com/17097003/44561644-55b33980-a788-11e8-85d5-5084468058f2.PNG)

（如果没有 则新建“字符串值” 和上图一样就行了）

4. 其余的 根据需求依次搜索 My Video、my picture、my music、 local document、download、desktop
 每次搜索 都要重新用鼠标点回目文件夹 FolderDescriptions ，因为注册表内不能向上搜索

**Comment by xiaomacdut** [comment]
为什么设置为Hide，还是不能隐藏
![music](https://user-images.githubusercontent.com/13606700/48313963-faae1780-e5fd-11e8-9672-2bb8eea107d9.png)

**Comment by mingkuang-Chuyu** [comment]
抱歉，并不想增加。
