### ISSUE TITLE
已释放映像 系统版本识别错误

### ISSUE THREAD

**Issue by Yukinoshita** [Chuyu-Team/Dism-Multi-language#528]
**Describe the bug（Bug信息）**
已释放的Windows10 Pro被识别为Windows企业版

**To Reproduce（如何重现？）**
1. 选择文件-释放映像，将Win10 1803 x64中的专业版镜像释放至X:\
2. 释放完毕，DISM将释放后的系统识别为企业版

**Expected behavior（预期行为）**
应识别为专业版

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/22393782/42980615-bbd2535c-8c0a-11e8-9eff-42ce26c6c430.png)

**please complete the following information:（环境信息）**
 - OS: [Windows 10 x64 1803/10.0.17134.165]
 - Dism++ Version [10.1.1000.70]

**Additional context（其他）**
None

**Comment by mingkuang-Chuyu** [comment]
重复反馈，Dism++ Beta已经修复。
