### ISSUE TITLE
关于驱动清理的一个增项改进建议

### ISSUE THREAD

**Issue by Dytto** [Chuyu-Team/Dism-Multi-language#53]
参见https://github.com/lostindark/DriverStoreExplorer/releases

如果有可能的话，请DSIM++团队与其联络，是否可以实现整合，使之可以直接删除驱动。

**Comment by MouriNaruto** [comment]
Dism++只有在开启专家模式的情况下，才可以删除驱动

**Comment by mingkuang-Chuyu** [comment]
Dism++一直支持直接删除驱动，只是在新手模式不展示这些功能，如需删除驱动 请切换到专家模式
