### ISSUE TITLE
wim解出来的文件夹无法删除，“文件夹访问被拒绝”

### ISSUE THREAD

**Issue by hdjdm** [Chuyu-Team/Dism-Multi-language#531]
**Describe the bug（Bug信息）**
A clear and concise description of what the bug is. 用一句话概括这个Bug，哪里出现了异常。
wim解出来的文件夹无法删除，“文件夹访问被拒绝”
需要来自Administrator/Everyone/TrustedInstaller的权限才能对文件夹进行更改。

**To Reproduce（如何重现？）**
Steps to reproduce the behavior:（详细说明下Bug重新步骤，此过程非常重要，如果言语表达不了就用步骤记录器，在cmd里面输入psr即可。）
1. 挂载映像
2. 退出Dism++
3. win7下删除挂载映像解压出来的文件夹
“文件夹访问被拒绝”
需要来自Administrator/Everyone/TrustedInstaller的权限才能对文件夹进行更改。

**Expected behavior（预期行为）**
A clear and concise description of what you expected to happen. 正常情况下应该是怎么样的？
顺利删除。

**Screenshots（截图）**
If applicable, add screenshots to help explain your problem. 如果你能提供相关错误截图那么再好不过了。
![default](https://user-images.githubusercontent.com/38270404/43043166-7eadc5e0-8dbf-11e8-935a-c576a112c9ba.png)

**please complete the following information:（环境信息）**
 - OS: [Windows 7 x64 SP1, ]
 - Dism++ Version [10.0.1000.70]

**Additional context（其他）**
Add any other context about the problem here. 如果你有其他信息，可以在这里补充
卸载映像、取消任务，再关闭Dism++，也不能删除。

**Comment by mingkuang-Chuyu** [comment]
不是问题，释放的系统能这样删除才怪，，，如有更改映像需求请使用挂载功能？
