### ISSUE TITLE
离线安装office

### ISSUE THREAD

**Issue by omaidb** [Chuyu-Team/Dism-Multi-language#534]
**我发现ISO离线打补丁这个功能真的很好用,所以我想到是否可以离线安装office,可以在安装系统时节省很多时间

**既然离线打补丁都可以实现,那么离线安装office应该也可以实现的吧?
** 还想把万能驱动包集成到镜像里,想问问大家有方案吗

**Comment by mingkuang-Chuyu** [comment]
无法实现此功能。
