### ISSUE TITLE
wsusscn2.cab 还是老版本。

### ISSUE THREAD

**Issue by flynaj** [Chuyu-Team/Dism-Multi-language#535]
wsusscn2.cab 这个版本老了，上个月的补丁出不来
发现这个文件并非这个，http://download.windowsupdate.com/microsoftupdate/v6/wsusscan/wsusscn2.cab
那要怎么生成这个呢?

**Comment by mingkuang-Chuyu** [comment]
已经提供了7月更新，出不来你可能是Windiws 10 1803用户，Dism++的一个bug导致扫描不出补丁，Dism++ beta已经修复。
