### ISSUE TITLE
给ISO中WIM离线集成补丁后清理垃圾，安装系统后发现补丁集成失效

### ISSUE THREAD

**Issue by wangfs763** [Chuyu-Team/Dism-Multi-language#536]
**Describe the bug（Bug信息）**
给ISO中WIM离线集成补丁后清理垃圾，安装系统后发现补丁集成失效？

**To Reproduce（如何重现？）**
1. 从官方WIN7 64镜像释放旗舰版到虚拟磁盘
2. Dism++集成补丁
3. Dism++清理垃圾
4. 打包成WIM/ESD
5.释放到虚拟机磁盘安装系统
6.打开系统更新，检查更新，发现又很多安全补丁（Dism++查看已集成）待补

**Expected behavior（预期行为）**
正常情况当然是集成了的补丁不会提示咯

**Screenshots（截图）**

**Comment by mingkuang-Chuyu** [comment]
需要更多信息，可能是部分安装。

**Comment by mingkuang-Chuyu** [comment]
无法重现此问题，应该是某些更新部分安装所致，某些时候更新安装顺序不当容易出现此问题。
由于离线安装仅仅是一种补充，本身功能不全，因此  关闭 此问题。
