### ISSUE TITLE
能增加定时备份的功能吗？

### ISSUE THREAD

**Issue by zgyxclyty** [Chuyu-Team/Dism-Multi-language#539]
在下载分区助手的时候看见了他们还有个备份好像是基于ATI的，比Dism++的备份功能多了一个定时备份。之前一直是用Dism++备份的，因为增量备份和还原的速度非常快，所以才用Dism++备份的，但是看见了他们的定时备份功能好羡慕。本人喜爱折腾，电脑必须时常备份，但又时常忘记去备份，若是有定时备份的话会很方便的。目前C盘文件很多，若用他们的软件重新备份又要好久时间。所以希望Dism++能增加一个定时备份的功能。另问： Dism++备份出来的wim文件可以用Dism进行增量备份吗？

**Comment by MouriNaruto** [comment]
Archived, #707

**Comment by cyczq11** [comment]
现在有开发这个功能了吗？
