### ISSUE TITLE
关于更新管理

### ISSUE THREAD

**Issue by coldwave0525** [Chuyu-Team/Dism-Multi-language#54]
为什么只能搜索到有关系统的更新，但没有windows defender和office的更新

**Comment by mingkuang-Chuyu** [comment]
Dism++的数据库中 并未包含 windows defender，但是包含了 Office 2010~Office 2016（VL版）
此外离线模式仅支持CBS更新，由于你并没有提供详细信息。我并不能给你给出更多回复。

请问你有什么问题？能详细说明下吗？
