### ISSUE TITLE
是否可以给Windows加一个Mac的对其呢？

### ISSUE THREAD

**Issue by jc654123** [Chuyu-Team/Dism-Multi-language#540]
Windows的拖拽如果失手了，桌面就乱了。不网格对其，又没有苹果上的整理键。

虽说win已经放弃开发了，我想我可以补一补继续用

**Comment by mingkuang-Chuyu** [comment]
Hi，你好 Dism++定位是 系统部署工具，并非常规小功能集合。

谢谢你的支持
