### ISSUE TITLE
WIN10引导修复导,致RE被禁止

### ISSUE THREAD

**Issue by gdsteven** [Chuyu-Team/Dism-Multi-language#542]
引导修复导致RE被禁止。下面ReAgentc /info信息是已经enable完RE后的信息，修复引导后RE状态又变成disable了。

C:\Windows\system32>ReAgentc /info
Windows 恢复环境(Windows RE)和系统初始化配置
信息:

    Windows RE 状态:           Enabled
    Windows RE 位置:           \\?\GLOBALROOT\device\harddisk0\partition3\Recovery\WindowsRE
    引导配置数据(BCD)标识符:   47eabbdd-9fed-11e8-a7e5-de72ec3a542d
    恢复映像位置:
    恢复映像索引:              0
    自定义映像位置:
    自定义映像索引:            0

REAGENTC.EXE: 操作成功。

C:\Windows\system32>bcdedit

Windows 启动管理器
--------------------
标识符                  {bootmgr}
device                  partition=\Device\HarddiskVolume4
path                    \EFI\Microsoft\Boot\bootmgfw.efi
description          Windows Boot Manager
locale                   zh-CN
inherit                 {globalsettings}
default                {current}
resumeobject     {1de84915-a62c-11e8-b655-54ab3a02035c}
displayorder       {current}
toolsdisplayorder       {memdiag}
timeout                 30

Windows 启动加载器
-------------------
标识符                  {current}
device                  partition=C:
path                    \Windows\system32\winload.efi
description         Windows 10
locale                  zh-CN
inherit                 {bootloadersettings}
recoverysequence        {47eabbdd-9fed-11e8-a7e5-de72ec3a542d}
recoveryenabled          Yes
isolatedcontext            Yes
allowedinmemorysettings 0x15000075
osdevice                partition=C:
systemroot            \Windows
resumeobject        {1de84915-a62c-11e8-b655-54ab3a02035c}
nx                      OptIn
bootmenupolicy          Standard

DISKPART> list vol

  卷 ###      LTR  标签         FS     类型        大小     状态       信息
  ----------  ---  -----------  -----  ----------  -------  ---------  --------
  卷     0     C   SSD          NTFS   磁盘分区         231 GB  正常         启动
  卷     1         Recovery   NTFS   磁盘分区         815 MB  正常
  卷     2                          FAT32  磁盘分区         101 MB  正常         系统
  卷     3     D   Work       NTFS   磁盘分区         171 GB  正常
  卷     4     E   Soft          NTFS   磁盘分区         293 GB  正常
  卷     5     F   Data         NTFS   磁盘分区         466 GB  正常

DISKPART> sel disk 0

磁盘 0 现在是所选磁盘。

DISKPART> list partition

  分区 ###       类型              大小     偏移量
  -------------  ----------------  -------  -------
  分区      1    保留                 128 MB    17 KB
  分区      2    主要                 231 GB   129 MB
  分区      3    恢复                 815 MB   231 GB
  分区      4    系统                 101 MB   232 GB

**Comment by gdsteven** [comment]
修复引导后

Microsoft Windows [版本 10.0.17134.228]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\Windows\system32>reagentc /info
Windows 恢复环境(Windows RE)和系统初始化配置
信息:

    Windows RE 状态:           Disabled
    Windows RE 位置:
    引导配置数据(BCD)标识符:   47eabbdd-9fed-11e8-a7e5-de72ec3a542d
    恢复映像位置:
    恢复映像索引:              0
    自定义映像位置:
    自定义映像索引:            0

REAGENTC.EXE: 操作成功。


C:\Windows\system32>bcdedit -enum all

固件启动管理器
---------------------
标识符                  {fwbootmgr}
displayorder            {bootmgr}
                        {5721f256-9fa9-11e8-b63f-806e6f6e6963}
                        {5721f257-9fa9-11e8-b63f-806e6f6e6963}
                        {5721f258-9fa9-11e8-b63f-806e6f6e6963}
timeout                 0

Windows 启动管理器
--------------------
标识符                  {bootmgr}
device                  partition=\Device\HarddiskVolume4
path                    \EFI\Microsoft\Boot\bootmgfw.efi
description             Windows Boot Manager
locale                  zh-CN
inherit                 {globalsettings}
default                 {current}
resumeobject            {0b7049f9-a63c-11e8-b658-3252cb1a6623}
displayorder            {current}
toolsdisplayorder       {memdiag}
timeout                 30

固件应用程序(101fffff)
-------------------------------
标识符                  {5721f256-9fa9-11e8-b63f-806e6f6e6963}
description             EFI USB Device

固件应用程序(101fffff)
-------------------------------
标识符                  {5721f257-9fa9-11e8-b63f-806e6f6e6963}
description             EFI DVD/CDROM

固件应用程序(101fffff)
-------------------------------
标识符                  {5721f258-9fa9-11e8-b63f-806e6f6e6963}
description             EFI Network

Windows 启动加载器
-------------------
标识符                  {current}
device                  partition=C:
path                    \Windows\system32\winload.efi
description             Windows 10
locale                  zh-CN
inherit                 {bootloadersettings}
isolatedcontext         Yes
allowedinmemorysettings 0x15000075
osdevice                partition=C:
systemroot              \Windows
resumeobject            {0b7049f9-a63c-11e8-b658-3252cb1a6623}
nx                      OptIn
bootmenupolicy          Standard

Windows 启动加载器
-------------------
标识符                  {47eabbdd-9fed-11e8-a7e5-de72ec3a542d}
device                  ramdisk=[\Device\HarddiskVolume3]\Recovery\WindowsRE\Winre.wim,{47eabbde-9fed-11e8-a7e5-de72ec3a542d}
path                    \windows\system32\winload.efi
description             Windows Recovery Environment
locale                  zh-CN
inherit                 {bootloadersettings}
displaymessage          Recovery
osdevice                ramdisk=[\Device\HarddiskVolume3]\Recovery\WindowsRE\Winre.wim,{47eabbde-9fed-11e8-a7e5-de72ec3a542d}
systemroot              \windows
nx                      OptIn
bootmenupolicy          Standard
winpe                   Yes

从休眠状态恢复
---------------------
标识符                  {0b7049f9-a63c-11e8-b658-3252cb1a6623}
device                  partition=C:
path                    \Windows\system32\winresume.efi
description             Windows Resume Application
locale                  zh-CN
inherit                 {resumeloadersettings}
isolatedcontext         Yes
allowedinmemorysettings 0x15000075
filedevice              partition=C:
filepath                \hiberfil.sys
bootmenupolicy          Standard
debugoptionenabled      No

从休眠状态恢复
---------------------
标识符                  {14a9b5a4-a0d5-11e8-b647-54ab3a02035c}
device                  partition=C:
path                    \Windows\system32\winresume.efi
description             Windows Resume Application
locale                  zh-CN
inherit                 {resumeloadersettings}
recoverysequence        {47eabbdd-9fed-11e8-a7e5-de72ec3a542d}
recoveryenabled         Yes
isolatedcontext         Yes
allowedinmemorysettings 0x15000075
filedevice              partition=C:
filepath                \hiberfil.sys
bootmenupolicy          Standard
debugoptionenabled      No

从休眠状态恢复
---------------------
标识符                  {1de84915-a62c-11e8-b655-54ab3a02035c}
device                  partition=C:
path                    \Windows\system32\winresume.efi
description             Windows Resume Application
locale                  zh-CN
inherit                 {resumeloadersettings}
recoverysequence        {47eabbdd-9fed-11e8-a7e5-de72ec3a542d}
recoveryenabled         Yes
isolatedcontext         Yes
allowedinmemorysettings 0x15000075
filedevice              partition=C:
filepath                \hiberfil.sys
bootmenupolicy          Standard
debugoptionenabled      No

从休眠状态恢复
---------------------
标识符                  {ba71aed0-a0b3-11e8-b647-54ab3a02035c}
device                  partition=C:
path                    \Windows\system32\winresume.efi
description             Windows Resume Application
locale                  zh-CN
inherit                 {resumeloadersettings}
isolatedcontext         Yes
allowedinmemorysettings 0x15000075
filepath                \hiberfil.sys
bootmenupolicy          Standard
debugoptionenabled      No

从休眠状态恢复
---------------------
标识符                  {f2271fc3-9fa7-11e8-b63e-54ab3a02035c}
device                  partition=C:
path                    \WINDOWS\system32\winresume.efi
description             Windows Resume Application
locale                  zh-CN
inherit                 {resumeloadersettings}
recoverysequence        {47eabbdd-9fed-11e8-a7e5-de72ec3a542d}
recoveryenabled         Yes
isolatedcontext         Yes
allowedinmemorysettings 0x15000075
filedevice              partition=C:
filepath                \hiberfil.sys
bootmenupolicy          Standard
debugoptionenabled      No

Windows 内存测试程序
---------------------
标识符                  {memdiag}
device                  partition=\Device\HarddiskVolume4
path                    \EFI\Microsoft\Boot\memtest.efi
description             Windows 内存诊断
locale                  zh-CN
inherit                 {globalsettings}
badmemoryaccess         Yes

EMS 设置
------------
标识符                  {emssettings}
bootems                 No

调试器设置
-----------------
标识符                  {dbgsettings}
debugtype               Local

RAM 故障
-----------
标识符                  {badmemory}

全局设置
---------------
标识符                  {globalsettings}
inherit                 {dbgsettings}
                        {emssettings}
                        {badmemory}

启动加载器设置
--------------------
标识符                  {bootloadersettings}
inherit                 {globalsettings}
                        {hypervisorsettings}

虚拟机监控程序设置
-------------------
标识符                  {hypervisorsettings}
hypervisordebugtype     Serial
hypervisordebugport     1
hypervisorbaudrate      115200

恢复加载器设置
----------------------
标识符                  {resumeloadersettings}
inherit                 {globalsettings}

设备选项
--------------
标识符                  {47eabbde-9fed-11e8-a7e5-de72ec3a542d}
description             Windows Recovery
ramdisksdidevice        partition=\Device\HarddiskVolume3
ramdisksdipath          \Recovery\WindowsRE\boot.sdi

C:\Windows\system32>

**Comment by mingkuang-Chuyu** [comment]
这个问题一直存在，所以没事不要乱引导修复。暂时也不知道怎么解决，因为微软的bcdboot修复后本来就是如此。

**Comment by gdsteven** [comment]
修复完了调用下reagentc不能enable RE ??至少要给个说明,最不济也要告诉用户如何做，否则RE被禁止，一旦系统出现问题，大多数普通用户都直接傻眼了。上次换硬盘修复完了我都没注意到RE被禁了... ...
