### ISSUE TITLE
Cleanup Windows 7 WinSxS 出错

### ISSUE THREAD

**Issue by shawn8888** [Chuyu-Team/Dism-Multi-language#546]
用DISM++最新版清理空间时，WinSxS出错。尝试用PE启动，挂载到D盘再清理，一样出错。似乎不是文件被系统占用的问题。
查了一下log:
2018-08-23 21:45:16, Info	PID=6404 TID=6756, 空间回收	正在进行扫描或清理
2018-08-23 21:47:44, Debug	PID=3652 TID=4316, Dism++消息循环	消息循环已经退出！
2018-08-23 21:47:44, Debug	PID=3652 TID=4316, Dism++会话	会话全部退出！

Replaced WinSxS assemblies
Details:
Element not found

请问如果解决？谢谢！

**Comment by mingkuang-Chuyu** [comment]
这个错误代码是 一般是 系统精简导致，你先看看你的系统是否是精简系统。

**Comment by shawn8888** [comment]
这个是Win7的系统，当初安装的是ultimate 64bit 完全版。多年前装的系统，后来可能用工具“精简”过，包括现在用的DISM++。
那么，有办法解决吗？

**Comment by shawn8888** [comment]
无解？？？

**Comment by mingkuang-Chuyu** [comment]
无解，建议还是升级安装系统解决。 下个WIn7 SP1 的ISO 双击升级，不会丢失用户数据 以及应用程序。
