### ISSUE TITLE
强迫症的一些建议

### ISSUE THREAD

**Issue by DeltaJNG** [Chuyu-Team/Dism-Multi-language#547]
1. 完善 右键菜单管理 功能， 可以把 右键菜单管理 单独放到 工具箱 里。
   希望能对其它软件的右键菜单进行管理，比如百度云 腾讯 新建菜单

2.  能不能把 回收站 加进资源管理器导航栏

3. 可不可以把资源管理器导航栏中 本地磁盘c d 等，从我的电脑中剥离出来，像u盘一样显示 
![default](https://user-images.githubusercontent.com/17097003/44562399-0242ea80-a78c-11e8-8f54-4206138548ba.PNG)

![img1](https://user-images.githubusercontent.com/17097003/44562405-07a03500-a78c-11e8-926c-acb61f0e92ed.png)

![img2](https://user-images.githubusercontent.com/17097003/44562262-57cac780-a78b-11e8-8a87-57d2c93a2fca.png)
 要说这么做有啥用，就是方便，省着每次用的时候还要点此电脑 再点c盘，这样直接把本地磁盘移动到一级目录，看着舒服多了

**Comment by DeltaJNG** [comment]
i find way

**Comment by MouriNaruto** [comment]
Partially archived, #707
