### ISSUE TITLE
关于硬连接合并后的HardLinkBackup目录

### ISSUE THREAD

**Issue by shawn8888** [Chuyu-Team/Dism-Multi-language#549]
$HardLinkBackup文件夹是使用了Dism++的硬连接合并功能后留下的。
那么，到底能不能删除？有什么后果？
备份时要不要排除？排除规则怎么写？

谢谢！

**Comment by mingkuang-Chuyu** [comment]
Dism++自身不是提供了 $HardLinkBackup 的清理规则吗？

至于后果上面也写了 会导致无法回滚 HardLinkBackup 更改，一旦电脑出现问题 就会有麻烦。

**Comment by gynkms** [comment]
$ HardLinkBackup
怎么回滚,硬连接合并清理了,软件打不开,好几个软件闪退.

**Comment by mingkuang-Chuyu** [comment]
@gynkms  抱歉，HardLinkBackup只能手动回滚。你需要先准备一个PE，然后把 HardLinkBackup里面的文件全选剪切到外面即可。
