### ISSUE TITLE
清理垃圾后win10资源管理器无限闪退

### ISSUE THREAD

**Issue by FQFQzzy** [Chuyu-Team/Dism-Multi-language#55]
麻烦你们新版能够修复这个问题，并且顺便告诉我怎样修复资源管理器闪退的问题吧~ [（这个方法试过了没用）](http://www.xitongzhijia.net/xtjc/20150527/49383.html)

**Comment by mingkuang-Chuyu** [comment]
Hi，此类问题一般是Shell插件兼容性问题，建议你想想最近有没有安装什么包含Shell插件的软件，比如会添加右键菜单的，比如会添加图标预览的（解码器）之类的

**Comment by mingkuang-Chuyu** [comment]
关闭此问题，用户长时间没有回应，如果有什么新的进展可以再次打开此问题。
