### ISSUE TITLE
[建议]安装Windows时支持无人值守文件

### ISSUE THREAD

**Issue by shawn8888** [Chuyu-Team/Dism-Multi-language#550]
现在安装系统，基本上都是用WinNTSetup系统安装器，主要原因是它支持无人值守文件，因为实在是太太太太方便了！

很喜欢DISM++，也知道DISM支持从ISO安装系统，但是缺乏无人值守文件的支持实在没办法。

能不能考虑一下支持这个非常非常实用的功能呢？

谢谢！

**Comment by MouriNaruto** [comment]
重新开启，并请鸭子出山

**Comment by MouriNaruto** [comment]
Archived, #707
