### ISSUE TITLE
无法使用TAB键操作软件。

### ISSUE THREAD

**Issue by yularna** [Chuyu-Team/Dism-Multi-language#551]
**Is your feature request related to a problem? Please describe.（你提交这个反馈的目的是什么？是否遇到了Dism++现有的问题？）**
我的鼠标不能用了，希望通过TAB键对系统进行优化。

**Describe the solution you'd like（描述你的解决方案）**
A clear and concise description of what you want to happen. 你希望得到什么样子的结果？

**Describe alternatives you've considered （是否有其他备选方案？）**

**Additional context（其他信息可以统一再此处填写）**

**Comment by MouriNaruto** [comment]
https://github.com/Chuyu-Team/Dism-Multi-language/issues/422

可参考这个问题的答案，也不知道 @mingkuang-Chuyu  的UI库进展如何了……

**Comment by MouriNaruto** [comment]
Archived, #707
