### ISSUE TITLE
SutWizard卡在产生差异

### ISSUE THREAD

**Issue by kenhon93** [Chuyu-Team/Dism-Multi-language#552]
**Describe the bug（Bug信息）**
SutWizard一直卡在“”正在产生差异“”，程序占用CPU一直在十几%左右，但是硬盘没读取。试过等了一个小时也没法完成。

**please complete the following information:（环境信息）**
 - OS: Windows 10 x64 1803 （全新安装，英文版）
 - SutWizard Version 1.0.0.2

**Comment by wangbf19740612** [comment]
OS: Windows 10 ltsc2019 （全新安装，中文版）
SutWizard Version 1.0.0.2

话说我也碰上了这个问题，我是使用SutWizard制作StartIsBack++2.7.3，不知是不是安装过程中会重启explorer进程导致的

**Comment by asyowish** [comment]
我也是这样，和楼上同样的系统环境，
就安装了个7-zip，一直卡在这里不动。
![SutWizard_7-zip](https://user-images.githubusercontent.com/18084314/62341097-895c1f00-b514-11e9-9d6e-a769151e2200.PNG)
