### ISSUE TITLE
re

### ISSUE THREAD

**Issue by iduserid** [Chuyu-Team/Dism-Multi-language#553]
**Is your feature request related to a problem? Please describe.（你提交这个反馈的目的是什么？是否遇到了Dism++现有的问题？）**

**Describe the solution you'd like（描述你的解决方案）**
A clear and concise description of what you want to happen. 你希望得到什么样子的结果？

**Describe alternatives you've considered （是否有其他备选方案？）**

**Additional context（其他信息可以统一再此处填写）**

**Comment by mingkuang-Chuyu** [comment]
无效反馈
