### ISSUE TITLE
希望增加RE修复功能

### ISSUE THREAD

**Issue by iduserid** [Chuyu-Team/Dism-Multi-language#554]
恢复系统--“在RE中运行”--但我的电脑中RE功能已损坏，能否尝试修复RE---
（因系统很多类型，建议永远放在“测试功能”项中，那儿放一些未稳定的功能）
如果本机系统没有RE,能否另调用什么类似RE文件，谢谢
（本机：WIN7.32位专业版）
再次谢谢，让大家用了如此小巧实用的软件-

**Comment by mingkuang-Chuyu** [comment]
WinRE太大  有300MB+，再加上 中国精简系统多，想修复也有心无力。

这巨额流量……

如果你想恢复 RE可以可以，恢复 `C:\Windows\System32\Recovery` 目录的2个文件，然后重新使用此功能。你可以从 原版 ISO里的install.wim提取他们。


这时 Dism++会自动利用 这文件 修复 RE。

谢谢支持
