### ISSUE TITLE
使任务栏更透明在win10 2016LTSB 下无效

### ISSUE THREAD

**Issue by qiuranke5d42** [Chuyu-Team/Dism-Multi-language#555]
**Describe the bug（Bug信息）**
windows10 2016LTSB 下打开使任务栏更透明选项 无效，还是原来的透明成都。

**Screenshots（截图）**
If applicable, add screenshots to help explain your problem. 如果你能提供相关错误截图那么再好不过了。

**please complete the following information:（环境信息）**
 - OS: windows10 2016LTSB 1607 14393.2396
 - Dism++ Version [e.g. 10.0.1000.80]

**Comment by mingkuang-Chuyu** [comment]
这个就这样吧，不支持说明系统没有此功能。
