### ISSUE TITLE
ISO生成器遇到大文件显示未实现

### ISSUE THREAD

**Issue by Wickyan** [Chuyu-Team/Dism-Multi-language#556]
如题，工具箱中的ISO生成器无法生成较大的文件（10G？或是更小？）。
不知道有没有办法增大可生成文件的大小。
谢谢。

**Comment by mingkuang-Chuyu** [comment]
Hi，话说你要创建多大的？ ISO生成器 是用来制作 Windows ISO安装镜像用的，不推荐你用来做其他用途。
