### ISSUE TITLE
Server 2016 无法更新

### ISSUE THREAD

**Issue by ybbao** [Chuyu-Team/Dism-Multi-language#557]
每次扫描就说已是最新，但用官方的更新程序，就会下载和更新，请核查。

**Comment by mingkuang-Chuyu** [comment]
为了缩小数据库体积，Dism++没有添加小众系统的数据库。此外Dism++只允许个人用户使用，服务器版系统个人也不会去用。

Dism++数据库仅包含
Window 7/8.1/10(长期服务分支亦不受支持)
Office 2010/2013/2016
