### ISSUE TITLE
升级到1809后,有些以前清理的app又出现却清理不了

### ISSUE THREAD

**Issue by masktao** [Chuyu-Team/Dism-Multi-language#563]
以前已经清理掉的app
如今又在列表,却清理不了
比如weather

每次提示package was not found

**Comment by masktao** [comment]
我在市场里查看已安装的app没有bing weather
在dism里却看到weather ,删除不了

**Comment by mingkuang-Chuyu** [comment]
这个是正常的，微软自身的问题。系统升级后 会残留一些以前应用的信息。暂时没有办法解决，
