### ISSUE TITLE
LTSC 2019系统下，Appx管理不显示系统预装应用

### ISSUE THREAD

**Issue by Ariza25617** [Chuyu-Team/Dism-Multi-language#566]
**Describe the bug（Bug信息）**
Appx管理里没有显示WindowsInternal.ComposableShell.Experiences.TextInput.InputApp

**To Reproduce（如何重现？）**
////

**Expected behavior（预期行为）**
显示出WindowsInternal.ComposableShell.Experiences.TextInput.InputApp

**Screenshots（截图）**
![01](https://user-images.githubusercontent.com/6499068/46582827-adc7a600-ca7f-11e8-80e0-d5f3583a0fcb.png)
![02](https://user-images.githubusercontent.com/6499068/46582828-adc7a600-ca7f-11e8-8d9e-9e0417563082.png)
![03](https://user-images.githubusercontent.com/6499068/46582829-ae603c80-ca7f-11e8-9fae-f4204ad3f370.png)

**please complete the following information:（环境信息）**
 - OS: [Windows 10 LTSC 2019 x64 1809]
 - Dism++ Version [10.1.1000.80]

**Additional context（其他）**
////

**Comment by mingkuang-Chuyu** [comment]
不是问题，设计如此。
因为系统应用显示了 也删不掉。不如不显示。
