### ISSUE TITLE
Export WIM -> ESD (recovery) = Crash

### ISSUE THREAD

**Issue by ITKJK** [Chuyu-Team/Dism-Multi-language#569]
**Describe the bug（Bug信息）**
While exporting WIM>ESD of Windows 10 x86 image at Windows 8.1 x64 with 'Dism++x64.exe', Dism++ crashes.

**To Reproduce（如何重现？）**
1. File > Open Image File
2. Browse > install.wim (Located at USB hard drive) (Windows 10.0.10240.16384, Home x86)
3. Destination: C:\WIM\install.esd (Recovery ESD) --- '\WIM\'-folder has normal NTFS user rights.
4. Dism++x64.exe crashes

**Expected behavior（预期行为）**
Exporting and compressing WIM -> ESD with LZX

**Screenshots（截图）**
https://postimg.cc/4HGfr5h7
https://postimg.cc/Cn4hYqjv

**please complete the following information:（环境信息）**
 - OS: Windows 8.1 x64 (6.3.9600)
 - Dism++ 10.1.1000.80 x64

**Additional context（其他）**
- Might be memory issue as running with only 2GB of DDR3.
- Exporting WIM from WIM of same image works.

**Comment by ITKJK** [comment]
Sorry, my bug / crash report seems to be false as I just tested dism.exe (Version: 10.0.17763.1) and it seems it crashes as well at my computer. So, most be something at my machine or OS.

`.\amd64\dism.exe /Export-Image /SourceImageFile:I:\WIN10\NT100.WIM /SourceIndex:1 /DestinationImageFile:D:\WORK\NT100.ESD /Compress:recovery /CheckIntegrity

Deployment Image Servicing and Management tool
Version: 10.0.17763.1

Exporting image
[=                          3.0%                           ]
`

Crashes also after 3%.

**Comment by ITKJK** [comment]
Seems this works as a solution and was the issue as with dism.exe also:

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
DWORD: IRPStackSize
VALUE(decimal): 50

After adding that registry key between values 35-50 works.

**Comment by mingkuang-Chuyu** [comment]
It is recommended that you open the page file and you need at least 10GB of memory.

Best
