### ISSUE TITLE
普通模式全选 清理后dxdiag会崩溃

### ISSUE THREAD

**Issue by Gavin-wang0208** [Chuyu-Team/Dism-Multi-language#57]
Windows 10 15063 Pro 清理所有全选内容后dxdiag会崩溃
看门狗2 幽灵行动荒野也会有打不开的情况

**Comment by mingkuang-Chuyu** [comment]
Hi, 要不 撤销下 CompactOS试试……

在菜单 - 恢复功能 撤销CompactOS。

谢谢

**Comment by Gavin-wang0208** [comment]
不好意思   我找到bug的原因了  是因为duetdisplay  不是你们这个可爱的软件啦   特别谢谢你们的付出  谢谢

2017-04-15 15:02 GMT+08:00 mingkuang <notifications@github.com>:

**Comment by mingkuang-Chuyu** [comment]
谢谢你的支持，找到问题就好。那我关闭此问题了。
