### ISSUE TITLE
清理winsxs组件出错，详细信息拒绝访问

### ISSUE THREAD

**Issue by janekerry** [Chuyu-Team/Dism-Multi-language#574]
使用空间回收，清理winsxs组件出错，详细信息显示拒绝访问。
显示winsxs组件有7.53G，但是却清理不了。

![qq 20181015143440](https://user-images.githubusercontent.com/44154696/46933701-c0496d00-d087-11e8-93f7-86a65fb7b0f4.png)
![image](https://user-images.githubusercontent.com/44154696/46933716-cf301f80-d087-11e8-9989-a10b6489fd34.png)

 -  [ Windows 7 x64 SP1]
 - Dism++ Version [10.1.1000.80]

**Comment by mingkuang-Chuyu** [comment]
请加 QQ群，然后 联系小鸭子，谢谢。
