### ISSUE TITLE
系统优化能不能增加备份功能。。。

### ISSUE THREAD

**Issue by i5151** [Chuyu-Team/Dism-Multi-language#575]
优化里面设置了很多，新装系统的时候还得从头设置一遍，能不能把设置的优化项备份下来，新装系统的时候恢复一下，所有的设置就能恢复，这样的话，效率会提高很多。

**Comment by MouriNaruto** [comment]
请转到 https://github.com/Chuyu-Team/Dism-Multi-language/issues/578 讨论

**Comment by MouriNaruto** [comment]
Archived, #707
