### ISSUE TITLE
个人配置备份

### ISSUE THREAD

**Issue by ArisHub** [Chuyu-Team/Dism-Multi-language#577]
** 新规则的名称 **
在此处大概的说明下这个规则能做什么。

** 这个么做有什么合理性？ **
在此处描述下这样做的合理性，为什么可以删它或者可以设置这个注册表。最好能解释下它的原理，以及枚举下所有可能出现的情况。如果参考了什么网站资料建议一并提供。

** 有什么潜在风险？ **
执行新规则后是否会存在一些已知的副作用？

** 如何回滚操作？ **
假如用户应用了这个操作，请问有什么措施可以回滚，或者说怎么恢复到系统初始状态？（温馨提示：系统优化项目必须支持回滚！！！否则不受理。）

** 系统适应性 **
大概说明下规则的适应性，什么时候显示这条规则？减少用户无用信息。
比如Windows 10 1803（或更高） x64 专业版才显示这个规则。
比如开启了OneDrive的用户不显示这个规则。

** 其他信息 **
比如规则出处，如果不提供则直接使用当前GitHub账号名称（为了尊重他人劳动成果，请勿冒名顶替）。
有什么特别需要注意的地方？等等……

**Comment by MouriNaruto** [comment]
请转到 https://github.com/Chuyu-Team/Dism-Multi-language/issues/578 讨论

**Comment by MouriNaruto** [comment]
Archived, #707
