### ISSUE TITLE
系统优化增加导出（备份）功能反馈

### ISSUE THREAD

**Issue by MouriNaruto** [Chuyu-Team/Dism-Multi-language#578]
PS：这是一个总结性issue，单独开一个issue方便大家了解我们已经收到了这个建议

**Comment by i5151** [comment]
这个功能真的非常必要，也是一个工具软件应该具备的基本功能。

**Comment by i5151** [comment]
不用问了，好多人发完都不来了，直接加上备份功能吧。

**Comment by MouriNaruto** [comment]
@i5151 我知道，这个建议已经转告给了开发者，只是需要一些时间

**Comment by Aaloone** [comment]
最起码让我还原默认的配置吧。。。。。。。

**Comment by mrliming** [comment]
等待这个功能很久了。这个导出功能，从实现上来说，应该不是太难，这么长时间都没有提供，是不是考虑了竞争的问题？如果担心这个，导出时对数据加个密吧，导入时把用户的设置数据提供给服务器在线解密，dism++直接从服务器取得解密后的数据进行设置，用户就不需要看到具体的数据了

**Comment by 424778940z** [comment]
关注很久了也依然没消息
之前去过qq群问, 结果有种爱用用不用滚的感觉
可能开发者从一开始根本就没想加上这个功能吧

**Comment by MouriNaruto** [comment]
@mrliming @424778940z 主要是时间问题，这个功能讨论过

只是现在，开发者们的重心不在 Dism++ 上面，都有各自的项目要忙

鸭子的话，主要是 VC-LTL 和 YY-Thunks（鸭子在大型互联网公司工作，也是很忙的）
青蛙的话，貌似退隐好久了
我的话，主要是 NSudo 和 Nagisa （虽然现实中的事情导致我自己的项目都忙不过来）

毛利

**Comment by MouriNaruto** [comment]
@424778940z 还有就是
让开发者高兴和提供各自项目的测试场地是 Dism++ 的主要目的之一
实际上，这的确做到了
鸭子、青蛙和我的项目都有与 Dism++ 共用的部分

**Comment by Tody-Guo** [comment]
要能open source估计好多的功能就上去了。哈哈哈

**Comment by MouriNaruto** [comment]
@Tody-Guo 完全 Open Source 啊，虽然感觉可以解决很多问题。但是开源后社区带来的贡献数量能否打消掉开发团队对代码只是被其他项目改名借鉴的担忧。

对于一些人来说，也许包括鸭子，我是个傻瓜。自己的个人项目基本都是开源的，自己也是为了默默积攒 star 数和 follower 数来实现自我满足。
只是自己的一个项目也步入了 400+ star 时代，通过五年的积攒。但是，能主动 Pull Request 的人还是太少，其实这还是往好了说，实际上是基本没人……很多时候不是发一个 Issue 就能让开发者顺利的添加功能的。
该项目的发起者曾经也向往完全开源，但是被某些人未经授权改名直接商业化……算了不说了。
我在凭借自己的努力，让其重新拾起信任。
但是……怎么说呢，完全开源了，如果发起者再经历类似的打击……该怎么说呢……

我的话，最近打算抽出时间做 NCleaner2 也就是 Dism++ 的 NCleaner 组件（增强系统清理组件）的重构版。倒是 NCleaner2 是 MIT 开源的。
我倒是要看看，这次试水的结果，是否能打消疑虑……

毛利

**Comment by MouriNaruto** [comment]
Archived, #707

**Comment by mrliming** [comment]
> @mrliming @424778940z 主要是时间问题，这个功能讨论过，没有大问题
> 
> 只是现在，开发者们的重心不在 Dism++ 上面，都有各自的项目要忙
> 
> 鸭子的话，主要是 VC-LTL 和 YY-Thunks（鸭子在大型互联网公司工作，也是很忙的）
> 青蛙的话，貌似退隐好久了
> 我的话，主要是 NSudo 和 Nagisa （虽然现实中的事情导致我自己的项目都忙不过来，换句说法就是我连自己的项目都在跳票……）
> 
> 毛利

谢谢！理解。还是期待着这个重要的功能。
