### ISSUE TITLE
注册表清理功能反馈

### ISSUE THREAD

**Issue by MouriNaruto** [Chuyu-Team/Dism-Multi-language#579]
PS：这是一个科普性issue，单独开一个issue方便大家了解。

DISM++ 是存在注册表清理功能的，由于至今还不敢保证没有严重的副作用，于是需要大家去官方群下载DISM++的测试版本且开启专家模式才能用上。（不建议在生产环境使用该功能）（出现坑后希望立马反馈于此issue）

**Comment by MouriNaruto** [comment]
Archived, #707

**Comment by Derek5-SeaFever** [comment]
特别需求注册表清理功能，同时希望能简单标注出系统重要的注册表项，提醒用户，防止误删导致系统损坏。同时还希望能不能略微在清理垃圾时标注一下哪些重要，就是划分一下等级之类的，方便小白的使用。
