### ISSUE TITLE
Windows主题相关设置

### ISSUE THREAD

**Issue by q1953555067** [Chuyu-Team/Dism-Multi-language#58]
显示颜色（By Rambin）开启后，颜色变成了黑色，（即使我自己调了其他的颜色）
我的系统版本是Win10 1703

**Comment by mingkuang-Chuyu** [comment]
谢谢，应该是此功能已经被微软删除。下个版本库中我会隐藏此功能

**Comment by mingkuang-Chuyu** [comment]
库中已经正对1703屏蔽此功能，请耐心等待新版本推送
