### ISSUE TITLE
升级后挂载和卸载变得好慢~

### ISSUE THREAD

**Issue by draker520** [Chuyu-Team/Dism-Multi-language#580]
**Describe the bug（Bug信息）**
A clear and concise description of what the bug is. 用一句话概括这个Bug，哪里出现了异常。

**To Reproduce（如何重现？）**
Steps to reproduce the behavior:（详细说明下Bug重新步骤，此过程非常重要，如果言语表达不了就用步骤记录器，在cmd里面输入psr即可。）

**Expected behavior（预期行为）**
A clear and concise description of what you expected to happen. 正常情况下应该是怎么样的？

**Screenshots（截图）**
If applicable, add screenshots to help explain your problem. 如果你能提供相关错误截图那么再好不过了。

**please complete the following information:（环境信息）**
 - OS: [e.g. Windows 7 x64 SP1, Windows 10 x86 1803]
 - Dism++ Version [e.g. 10.0.1000.70]

**Additional context（其他）**
Add any other context about the problem here. 如果你有其他信息，可以在这里补充

**Comment by mingkuang-Chuyu** [comment]
应该是杀毒软件所致，建议看看 是否启用了WD或者QQ管家。

目前有用户反馈 安装QQ管家后 Dism++性能暴降。如果你也安装了 建议卸载QQ管家后 然后在继续看看。
