### ISSUE TITLE
挂载映像时"只读模式"复选框默认勾选并且无法取消选择

### ISSUE THREAD

**Issue by CirnoSalt** [Chuyu-Team/Dism-Multi-language#581]
**Describe the bug（Bug信息）**
挂载Windows7x64 wim映像，只读模式为灰色无法取消勾选

**To Reproduce（如何重现？）**
挂载映像，选择本地分区上的Windows7 install.wim文件(从iso中解出)，
“只读模式”默认打勾并且无法取消勾选，导致之后的操作无法保存。

**Expected behavior（预期行为）**
按照网络上的教程截图，挂载时只读模式复选框可以自由选择勾选，
经过搜索，未发现有此情况出现的先例。

**Screenshots（截图）**
![tim 20181020000813](https://user-images.githubusercontent.com/23478997/47230268-5a991000-d3fc-11e8-9144-c9c93890da3d.png)

**please complete the following information:（环境信息）**
 - OS: [e.g. Windows 10 x64 1809]
 - Dism++ Version [e.g. 10.0.1000.80]

**Additional context（其他）**
镜像来源为itellyou.cn，未进行过其他修改

**Comment by mingkuang-Chuyu** [comment]
这应该不是问题，请手动取消 install.wim 的只读文件属性……
如有疑问可以继续回复。
