### ISSUE TITLE
+“丢失*.dll文件”的修复

### ISSUE THREAD

**Issue by mailoksoft** [Chuyu-Team/Dism-Multi-language#584]
** 新规则的名称 **
丢失*.dll文件时修复。

** 这个么做有什么合理性？ **
-_-

** 有什么潜在风险？ **
.dll不是官方的，传播病毒。

** 如何回滚操作？ **
不懂

** 系统适应性 **
98～10

** 其他信息 **
你这个反馈就是给专业人士的，一般人根本没法这么反馈问题。

**Comment by mingkuang-Chuyu** [comment]
感谢你的支持，但是Dism++暂时并不考虑增加此类功能。谢谢
