### ISSUE TITLE
PE系统下无法完整还原镜像

### ISSUE THREAD

**Issue by Doeams** [Chuyu-Team/Dism-Multi-language#585]
在PE系统下还原镜像时，还原到一半弹出提示框，点击确定后会重新打开软件（只有前2次会发生，第三次正常使用）

![1](https://user-images.githubusercontent.com/44563816/47633069-92841e00-db87-11e8-9262-1dab70843cb1.png)
![2](https://user-images.githubusercontent.com/44563816/47633076-9617a500-db87-11e8-9469-8e5ee8d788a2.png)

请确认是软件问题还是系统问题

**Comment by suwakowww** [comment]
pe的ramdisk看内存有多少的，要是内存太小就会这样
换一个位置放dism++本体试下

**Comment by Doeams** [comment]
> PE的虚拟盘看内存有多少的，内存要是太小就会这样
> 换速一个位置放DISM ++本体试下

我使用的是硬盘内的DISM++，一样这样，可能是PE有问题，换了一个就没问题了

**Comment by mingkuang-Chuyu** [comment]
这个是Dism++崩溃了，建议用原版PE试试。另外 Dism++临时目录空间不足也会发生稀奇古怪的事情，建议复制DIsm++到其他空闲的分区中 在执行。

你的会这样弹窗，Dism++肯定是没有在空闲的分区里。另外不要用PE里面的单文件版，单文件版 你就算复制到了其他分区。他还是会在X盘解压，导致Dism++还是在X盘里。
