### ISSUE TITLE
最新的Dism++已经更新但是每次打开时总是要求更新最新的Dism++

### ISSUE THREAD

**Issue by Enderwaiter** [Chuyu-Team/Dism-Multi-language#586]
最新的Dism++版本是10.1.1000.80，我现在已经位于这个版本，但是每次打开还是会提醒更新。非常麻烦而且点击更新之后重新启动应用程序还是会弹。希望可以修复下！

**Comment by mingkuang-Chuyu** [comment]
并没有发现这个问题，建议你加我QQ 343183163.

**Comment by Enderwaiter** [comment]
> 并没有发现这个问题，建议你加我QQ 343183163.

今天周日的话说我没办法回家呢，现在在学校。我想通过邮箱和您联系呢，请问您的邮箱是mingk****@****.com吗（部分已隐藏）

**Comment by mingkuang-Chuyu** [comment]
@Enderwaiter  没错，要不你先吧你本地的Dism++ 打个 zip 包，邮件附件的形式发送给我？

**Comment by Enderwaiter** [comment]
> @Enderwaiter 没错，要不你先吧你本地的Dism ++打个拉包，邮件附件的形式发送给我？

已经发送了请查看一下呢

**Comment by mingkuang-Chuyu** [comment]
没有收到，你还是直接上传到这里吧。反正 Github也能上传。

**Comment by asmosn** [comment]
请问下～Windows Update扫描列表中橙色补丁是什么意思？容易出BUG吗？
