### ISSUE TITLE
【功能建议】希望增加处理【Linux发行版的安装镜像、macOS安装镜像】的功能。

### ISSUE THREAD

**Issue by qwas982** [Chuyu-Team/Dism-Multi-language#587]
**Is your feature request related to a problem? Please describe.（你提交这个反馈的目的是什么？是否遇到了Dism++现有的问题？）**
经过使用目标程序（在pe下安装win系列），我萌生一个想法，能否在当前基础上对更多的系统镜像的设置操作增删改查？

**Describe the solution you'd like（描述你的解决方案）**
A clear and concise description of what you want to happen. 你希望得到什么样子的结果？
我是用举一反三的使用逻辑来思考的，我设想的是，目标程序（dism++）可以处理磁盘以及文件中的镜像（或镜像中的文件），特别是在PE预安装环境下，在完全运行在内存中的系统，可以对磁盘有全权限的操控能力的时候，通过加载某个系统的镜像，然后设置操作增删改查，最后将其恢复到某个分区中，来完成系统的安装，用此法对Linux发行版的安装镜像、macOS安装镜像、（甚至Android的安装镜像）也进行一样的处理，岂不美哉？试想下，那会多么的方便。不过我想到了分区格式、磁盘文件系统、操作系统引导方式的迥异，可能会为此带来阻力，后面一想，现在有gpt+uefi，并且，不但三大系统都支持，各种硬件的支持也已普及如常，如果将整个磁盘的引导和分区都统一到gpt+uefi的方式下，那么，三大系统类型将和谐并存（已经有很多人实现，不过方法太庸冗繁复，主要就是处理系统镜像的手段和方法没有一个优秀的解决方案），更不用说只处理某种单一的系统镜像，何况现在很多人都用上了多磁盘电脑，那么，现时代一种处理磁盘和系统镜像的神器工具也就成了众望所归了。

**Describe alternatives you've considered （是否有其他备选方案？）**
没找到过其他能统一集中处理各种系统镜像的工具。

**Additional context（其他信息可以统一再此处填写）**
希望增加处理【Linux发行版的安装镜像、macOS安装镜像、（甚至Android的安装镜像）】的功能。

**Comment by suwakowww** [comment]
* Dism++ 的定位是**处理 Windows 相关系统**的软件。
* 到目前为止，别说这些系统了，连 **Windows XP 都不支持**。
* Linux，macOS 这些如果要加入支持估计很困难，**前者有 GPL 许可证（），后者是苹果的专有软件**。
* 三者所使用的**文件系统都有所区别**，Windows 目前以 NTFS、REFS、FAT 系为主，Linux 则以 EXT2/3/4、F2FS 等等为主，macOS 则以 HFS+、APFS 为主。
* macOS 的镜像是 `*.dmg` 格式的，你试下找一个**免费、非类 GPL 许可证、可以修改数据**的相关工具（不含破解版）
* 即使你说的有 UEFI 环境以及 GPT 分区表，但是早期 UEFI 正常情况下**只能识别 FAT12/FAT16/FAT32 的文件系统**（没错，exFAT 都不行），除了苹果自成体系（不考虑黑苹果）之外，其它的基本以 FAT 系文件系统作为“引导区”，而系统则在另外的分区，而加载这些分区，则需要这些“引导区”进行各自的加载。
* 综上所述，估计你也有答案了吧。

**Comment by qwas982** [comment]
@suwakowww 谢谢回复,看了你的观点后,真是让人感到没有希望啊,哈哈哈
你对内存操作系统RAMos怎么看? 有开源的实现吗?

**Comment by suwakowww** [comment]
印象中Linux系列有些有LiveCD的，至于Windows...预安装环境（PE）算不算？
如果是自制的，没怎么了解过，好像无忧有人做的

**Comment by qwas982** [comment]
找到教程了,[http://bbs.wuyou.net/forum.php?mod=viewthread&tid=410474](url)
看来不管是理论还是实践,还是开源实现都有长足的进步了,希望dism++也能跟进内存磁盘相关的系统镜像操作

**Comment by mingkuang-Chuyu** [comment]
另外 Dism++本身定位就是 Windows，Linux发行版的安装镜像、macOS安装镜像 暂不考虑。

就算考虑了 有什么用，几个人会去安装 Linux？另外macOS支持它做什么？自己去买个苹果本不就好了？Windows电脑为什么要安装这个系统？去装逼吗？
