### ISSUE TITLE
建议增加批量优化导入导出的功能

### ISSUE THREAD

**Issue by fire9ipc** [Chuyu-Team/Dism-Multi-language#589]
建议增加批量优化导入导出的功能
一次性如果要对多台相同的电脑做优化配置就不需要重复的用鼠标点。能做导入导出。

**Comment by MouriNaruto** [comment]
建议已收到，请到 https://github.com/Chuyu-Team/Dism-Multi-language/issues/578 讨论

**Comment by MouriNaruto** [comment]
Archived, #707
