### ISSUE TITLE
功能请求:希望增加增量备份和差异备份功能,dism /Append image无法热备份

### ISSUE THREAD

**Issue by ShayCormac1963** [Chuyu-Team/Dism-Multi-language#590]
**Is your feature request related to a problem? Please describe.（你提交这个反馈的目的是什么？是否遇到了Dism++现有的问题？）**

**Describe the solution you'd like（描述你的解决方案）**
A clear and concise description of what you want to happen. 你希望得到什么样子的结果？

**Describe alternatives you've considered （是否有其他备选方案？）**

**Additional context（其他信息可以统一再此处填写）**

**Comment by mingkuang-Chuyu** [comment]
听不懂你再说什么，Dism++目前本身就会自动增量，如果你保存到一个现有的wim文件里。
