### ISSUE TITLE
win10 1607 14393.2580接收不到11月补丁的问题

### ISSUE THREAD

**Issue by hdcscy** [Chuyu-Team/Dism-Multi-language#591]
**Describe the bug（Bug信息）**
win10 ltsb 2016 1607版本更新的问题。
官方推送了KB4467691升级至14393.2608，而dism++补丁数据库未更新。

**To Reproduce（如何重现？）**
在上一个版本win10 1607 14393.2580进行更新扫描即可。

**Expected behavior（预期行为）**
正常情况：dism++补丁数据库会更新。

**Screenshots（截图）**
If applicable, add screenshots to help explain your problem. 如果你能提供相关错误截图那么再好不过了。

**please complete the following information:（环境信息）**
 - OS: [Windows 10 x64 1607 14393.2580]
 - Dism++ Version [e.g. 10.0.1000.80]

**Additional context（其他）**
Add any other context about the problem here. 如果你有其他信息，可以在这里补充

**Comment by mingkuang-Chuyu** [comment]
元数据已经更新，预计明天你才会收到。
