### ISSUE TITLE
[Question] How are System Optimizer values EXPORTED?

### ISSUE THREAD

**Issue by TmvJosue** [Chuyu-Team/Dism-Multi-language#595]
In Control Panel > System Optimizer, I see an "Import Registry" button but I want to **EXPORT** the values there.

Is this possible?

![export registry values](https://user-images.githubusercontent.com/36319294/49404642-0cc33780-f71e-11e8-850e-965cf58d1c7e.png)

**Comment by TecnoPCEc** [comment]
hi, the new edition don´t has that option.....

**Comment by MouriNaruto** [comment]
Closed because it is a duplicated issue.
You can feedback under https://github.com/Chuyu-Team/Dism-Multi-language/issues/578
Thank you.

Mouri

**Comment by MouriNaruto** [comment]
Archived, #707
