### ISSUE TITLE
通过Windows10内置Edge浏览器无法下载该程序

### ISSUE THREAD

**Issue by kavdx** [Chuyu-Team/Dism-Multi-language#598]
**Describe the bug（Bug信息）**
通过Windows10内置的Edge浏览器无法下载Dism++，显示“下载不安全，已被Windows Defender SmartScreen阻止”。

**To Reproduce（如何重现？）**
1. 打开Edge浏览器
2. 下载链接为http://cdn.chuyu.me/Dism++10.1.1000.80_a17953e8473f7f23592c97f64b25091d.zip的文件
3. 在“你想怎么处理？”对话框中选择“保存”
4. 错误出现

**Expected behavior（预期行为）**
正常下载文件。

**Screenshots（截图）**

**please complete the following information:（环境信息）**
 - OS: Windows10 version：1803
 - Browser：Edge version: 42.17134.1.0

**Additional context（其他）**
Add any other context about the problem here. 如果你有其他信息，可以在这里补充

**Comment by zhujinle** [comment]
建议关闭Smartscreen应用筛选器
好像可以在Edge的高级设置最下面或者Windows Defender里面找到开关
可参考https://jingyan.baidu.com/article/fdffd1f877d377f3e88ca155.html

**Comment by MouriNaruto** [comment]
在我的Edge浏览器里正常下载
而且由于Dism++新版本已发布，你所提供的下载链接已经失效，你可以试试新版本下载是否正常
所以我会关闭这个问题，如果你还有疑惑可以继续在这个问题回复，谢谢

毛利
