### ISSUE TITLE
无法更新dism++

### ISSUE THREAD

**Issue by haitaoh** [Chuyu-Team/Dism-Multi-language#6]
chuyu.me官网无法访问，直接跳转到403页面，同时ip地址：111.206.38.21也会指向403，dism++更新程序一直卡在更新重试这个界面。
不知道这个问题什么时候能够解决，造成这些问题的原因是什么。

**Comment by mingkuang-Chuyu** [comment]
网站目前正在备案中，所以无法访问，另外自动更新显示重试，请问程序显示的是那个文件？

**Comment by haitaoh** [comment]
Dism++主程序，更新有问题。
网站备份只是域名无法访问，我用ip还出现就不正常了吧，当然我用的是阿里云。

**Comment by mingkuang-Chuyu** [comment]
IP也是不行的，百度云 没有备案是禁止接入的
你还是提供详细截图吧，因为我需要知道你当前是什么版本

**Comment by haitaoh** [comment]
![2017-01-06_215945](https://cloud.githubusercontent.com/assets/11689240/21737934/3170f5ec-d4b9-11e6-8f57-0ce2ab252537.jpg)
（上图所示）
更新主程序出错

**Comment by haitaoh** [comment]
我刚才使用的时候突然好了。。更新完成

**Comment by mingkuang-Chuyu** [comment]
嗯 以后在提供Dism++版本号，另外提供详细截图……

这个问题应该是服务器没有CDN所致，等备案成功后，搞了CDN应该就好了
