### ISSUE TITLE
10.1.25.3版本集成 win 7 64bit 下IE11出错

### ISSUE THREAD

**Issue by taochuwang** [Chuyu-Team/Dism-Multi-language#60]
系统是从itellyou下载的cn_windows_7_ultimate_with_sp1_x64

首先用微软的dism把install.win里面的ultimate版本单独分离出来，然后用dism++来集成系统补丁。

首先安装微软的kb2670388没问题，然后安装IE11的时候就报错了，提示 "操作系统被严重精简,请放弃此系统,然后重新开始"

同样的install.win文件，同样的操作步骤，使用上一个版本(v10.1.25.2) 没有此情况

**Comment by mingkuang-Chuyu** [comment]
已经收到，建议先看看直接用Dism是否有此问题，这个问题应该是更新本身的限制。

另外 推荐先集成IE11，然后在集成kb2670388。

**Comment by mingkuang-Chuyu** [comment]
关闭此问题，必要时可以重新打开此问题
