### ISSUE TITLE
这个是魔兽玩家清理规则

### ISSUE THREAD

**Issue by bAdOoWindy** [Chuyu-Team/Dism-Multi-language#600]
** 新规则的名称 **
暴雪战网更新时不会清理旧客户端.

** 这个么做有什么合理性？ **
删除时候为保证兼容,保留2个客户端,大概能

** 有什么潜在风险？ **
0风险

** 如何回滚操作？ **
对系统0修改,属于TEMP类的垃圾文件

** 系统适应性 **
任何具有ProgramData结构的系统都支持,目前百度得知XP用的不是,不过战网好像放弃XP了?

** 其他信息 **
by 尺子上的彩虹

不会写规则只好把大概流程放出来
1.判断 系统盘下的"ProgramData"是否存在?不存在:跳过 结束或隐藏"规则";存在:进行下一个判断--系统兼容判断
2.判断 "ProgramData"内是否有"Battle.net"文件夹?不存在:跳过 结束或隐藏"规则";存在:进行下一个判断--战网客户端搜索
3.通过正则 获取 "Battle.net"内的"Agent"内的 "Agent."开头的所有文件夹名字 组成数组,排序--获取所有版本的客户端的文件夹名字
4.数组长度-2--保留2个版本的客户端
5.根据数组内容删除旧客户端

**Comment by bAdOoWindy** [comment]
在判断战网存在之后,联动删除战网的LOG文件
AppData\Local\Battle.net\Logs

**Comment by bAdOoWindy** [comment]
最近战网没更新( ╯□╰ )
等下次更新我截个图吧
没清理过的话大概几十M吧
github似乎不支持传图/(ㄒoㄒ)/~~

**Comment by InoryLwc** [comment]
> 最近战网没更新( ╯□╰ )
> 等下次更新我截个图吧
> 没清理过的话大概几十M吧
> github似乎不支持传图/(ㄒoㄒ)/~~

可以传图啊，加个图片连接也可以

**Comment by bAdOoWindy** [comment]
啊  大概不必了  最新的战网客户端 终于把"移除旧客户端文件"加进去了 虽然还有缺陷 还没有移除战网客户端 的 直接安装目录的 旧客户端,但是 后面向暴雪反馈就好

**Comment by seven-mile** [comment]
事实上大量基于 CEF（尤其是 electron） 的软件都会保存多个版本的 app，比如 chrome, discord, battle.net 等等
![OP2$ASQ)J U2JPB3H47(`ZP](https://user-images.githubusercontent.com/56445491/108469353-0ac7fd80-72c3-11eb-842b-d67233cebd4b.png)
如图，匹配 `app-num.num...` 一类的就能找到一些。写个通用的清理也未尝不可，只是，有一定误删风险，需要较高的鲁棒性，或者找到后交由人工识别清理。

**Comment by bAdOoWindy** [comment]
> 事实上大量基于 CEF（尤其是 electron） 的软件都会保存多个版本的 app，比如 chrome, discord, battle.net 等等
> ![Sample Image](https://user-images.githubusercontent.com/56445491/108469353-0ac7fd80-72c3-11eb-842b-d67233cebd4b.png)
> 如图，匹配 `app-num.num...` 一类的就能找到一些。这些软件本就体量大，还喜欢保存旧版本，写个通用的清理也未尝不可，只是，有一定误删风险，需要较高的鲁棒性，或者找到后交由人工识别清理。
> 我猜已经有人注意到了这个问题，写了其它小工具，如果要实现的话务必看下有没有轮子可以抄过来。

所以最后删除操作是保留2个

**Comment by bAdOoWindy** [comment]
Data.xml 我看过了 如果只能写在Data.xml 不可能实现的

**Comment by seven-mile** [comment]
> Data.xml 我看过了 如果只能写在Data.xml 不可能实现的

那没关系啊，内嵌 CDATA 和写个 Native C/C++ Dll 都行啊，本来搜索就是个复杂逻辑

你可以找 NCleaner 直接加
