### ISSUE TITLE
【问题求助】更新管理uprades安装新系统失败，如何删除安装包？

### ISSUE THREAD

**Issue by yudiya** [Chuyu-Team/Dism-Multi-language#601]
尝试多次都安装失败，弹窗显示一个错误代码。。。
这个下载好的安装包如何删除呢？

**Comment by mingkuang-Chuyu** [comment]
Dism++的安装包过期会自动删除，如果你希望手动删除可以直接删掉Dism++/Config/UpdateCache


最后一下次反馈问题最好带个截图啥的
