### ISSUE TITLE
Turkish translation

### ISSUE THREAD

**Issue by kayazeren** [Chuyu-Team/Dism-Multi-language#604]
Please find Turkish translation file for Dism ++ 10.1.1000.80
[tr.zip](https://github.com/Chuyu-Team/Dism-Multi-language/files/2704480/tr.zip)

**Comment by mingkuang-Chuyu** [comment]
thanks for your support, I'll ma

**Comment by MouriNaruto** [comment]
I will close this issue because your contribution is commited in this repository.

Mouri.
