### ISSUE TITLE
我用命令关闭了compactOS功能，结果启动Dism+就又自动开启了

### ISSUE THREAD

**Issue by masktao** [Chuyu-Team/Dism-Multi-language#607]
compactOS这个功能貌似绑架启动的，为了节约空间，问题我不需要压缩，也不需要节约点空间。能不能取消compactOS捆绑启动激活？

**Comment by MouriNaruto** [comment]
你在清理空间的时候是否勾选了compactOS

**Comment by masktao** [comment]
@MouriNaruto 这个是专家模式才可以清理的选项。 而dism+ 默认就开启压缩。 每次又是清理压缩空间，又自动压缩，累？不要这个压缩功能，不缺这点空间，可以吗？

**Comment by mingkuang-Chuyu** [comment]
没有此功能，Dism++不会自动开启CompactOS。
