### ISSUE TITLE
简体中文一处错别字

### ISSUE THREAD

**Issue by R-Kit** [Chuyu-Team/Dism-Multi-language#608]
控制面板-系统优化-开始菜单以及Windows体验处
“登陆界面默认打开小键盘（by IT之家）”中，“登陆”是指登上陆地，即landing，在计算机领域方面的login应为“登录”。

**Comment by MouriNaruto** [comment]
https://github.com/Chuyu-Team/Dism-Multi-language/commit/5555b001abcc1e9f597758860e15674dbea611c5

感谢，问题已修复。

毛利
