### ISSUE TITLE
部分右键菜单禁用后自动恢复

### ISSUE THREAD

**Issue by xcwang2018** [Chuyu-Team/Dism-Multi-language#609]
![2018-12-25 081719](https://user-images.githubusercontent.com/46279336/50559190-45f7c300-0d2f-11e9-8510-5ca47a235f59.jpg)
![2018-12-25 081620](https://user-images.githubusercontent.com/46279336/50559168-2365aa00-0d2f-11e9-894a-1361321b91a9.jpg)

原因是与eset杀毒软件冲突，御载ESET后，再重新设置，就不会自动恢复了。

**Comment by Yafeiml** [comment]
同样有这个问题，但是发现eset并没有拦截，注册表好像自动还原了

**Comment by hitman888** [comment]
同样有这个问题，但是eset没有拦截，可有方法能解决?
