### ISSUE TITLE
请问1703版本如何删掉开始菜单的windows defender安全中心呢

### ISSUE THREAD

**Issue by dreamkaylee** [Chuyu-Team/Dism-Multi-language#61]
如题，开始菜单有个windows defender安全中心快捷方式，研究了好久不知道怎么删除，windows defender都卸载掉了，这个快捷方式还是存在

**Comment by mingkuang-Chuyu** [comment]
Hi，这里只接受Dism++的建议与BUG反馈。至于你怎么删除windows defender安全中心快捷方式，这种提问，不应该出现在这里。另外我也不知道怎么做。建议你在研究研究。
