### ISSUE TITLE
使用回收清理之后CSGO出现VAC提示

### ISSUE THREAD

**Issue by yaoshuige** [Chuyu-Team/Dism-Multi-language#614]
csgo为vavle旗下steam平台的游戏，也就是说，空间回收清理可能会清理某些文件导致无法正常通过VAC反作弊系统检测而被游戏踢出，请务必修复谢谢

**Comment by mingkuang-Chuyu** [comment]
可是程序一般就删除一些系统垃圾文件还有日志啊啊。能否帮忙测试下具体是那个条目引起的？
