### ISSUE TITLE
Backup the OS.

### ISSUE THREAD

**Issue by PiliJ** [Chuyu-Team/Dism-Multi-language#615]
Hello,
Backing up the OS in the tools does not work on my system (?) 8.1 64x !
Nothing is happening at the level of the progress bar of Dism++ (10.1.1000.80).
If I want to close the program, I get the message "Dism tis working. Forcing the stop now?".
The process does not show any activity, however.
If I force the shutdown, the program freezes.
Thank you.
![image 001](https://user-images.githubusercontent.com/33757855/51440229-3e3f9480-1cc5-11e9-8421-1a3302d0fa73.png)
![image 002](https://user-images.githubusercontent.com/33757855/51440230-3e3f9480-1cc5-11e9-8096-edbe51e25517.png)

**Comment by mingkuang-Chuyu** [comment]
Hi, Have you saved to esd file?

**Comment by PiliJ** [comment]
Hi,

No, wim-file.
 
 
 
-----Original Message-----
