### ISSUE TITLE
windows功能 显示不支持该请求

### ISSUE THREAD

**Issue by cocoeoli** [Chuyu-Team/Dism-Multi-language#616]
在程序与功能选项里点击windows功能应用后弹出”不支持该请求“对话框。

**Expected behavior（预期行为）**
正常应该显示应用成功

**Screenshots（截图）**

**please complete the following information:（环境信息）**
 - OS: win10企业版 64位(10.0 ,版本 14393)
 - Dism++ Version: Dism++x64 10.1.1000.80

**Comment by mingkuang-Chuyu** [comment]
建议你说的再详细点，启用了啥功能。
