### ISSUE TITLE
win10 1809 更新禁止不彻底

### ISSUE THREAD

**Issue by tiangarin** [Chuyu-Team/Dism-Multi-language#617]
系统win10 1809，使用dism ++ 将update 设为只检查更新，但系统依旧重启并自动更新。我希望能够像之前一样，完全由自己选择什么时候更新，而不是微软不通知或者延迟更新。

**Comment by mingkuang-Chuyu** [comment]
需要设置为禁止，这个是微软的逻辑。

**Comment by mingkuang-Chuyu** [comment]
因为  你设置只检查更新，微软的一旦检查就会自动安装。
