### ISSUE TITLE
最新版本10.1.1000.90的系统备份出现严重bug

### ISSUE THREAD

**Issue by FMIB-DSG** [Chuyu-Team/Dism-Multi-language#618]
**Describe the bug（Bug信息）**
使用最新版本**10.1.1000.90**在PE环境下备份系统时，出现错误提示：“制定的路径无效”

**To Reproduce（如何重现？）**
Steps to reproduce the behavior:（详细说明下Bug重新步骤，此过程非常重要，如果言语表达不了就用步骤记录器，在cmd里面输入psr即可。）
1. 打开需要备份的系统
2. 单击恢复功能，系统备份。
3. 选择好非系统盘路径，确定磁盘有剩余空间
4. 选择可启动，然后点击确定
5. 5秒内必定出现错误提示“**指定的路径无效**”

**Expected behavior（预期行为）**
前不久使用过系统备份功能，备份是正常的。那是因为前不久使用的是旧版本**10.1.1000.80**。所以我怀疑是我把Dism++更新到了最新版本后才出现的问题，是新版本的Bug。为了验证我的思路，我重新使用了保留在U盘里的旧版本**10.1.1000.80**的Dism++，进行了完全一样的操作，发现一切正常，备份顺利。因此，已经可以确定是新版本出现的bug，应该算是比较严重的bug了。

**Screenshots（截图）**
PE里面没法截图，手机拍照也不清晰，所以就不截图了，不过问题一定是存在的，测试一下就可以了。

**please complete the following information:（环境信息）**
 - OS: Windows 10 x64 1809（操作系统版本：17763.292，最新版）
 - Dism++ Version: 10.1.1000.90

**Additional context（其他）**
希望能够改进吧，这个功能还是比较常用的

**Comment by MouriNaruto** [comment]
请问你使用的PE的版本是多少？

**Comment by FMIB-DSG** [comment]
你好，是U盘启动系统，U启动的，系统是Windows 8专业版64位的PE。官方网站：[U启动PE](http://www.uqidong.com/)，里面我用的是增强版。
> **ps**：快过年了，开发人员也别太辛苦了，过完年再修复吧！预祝楼主猪年猪事顺利。
