### ISSUE TITLE
建议WIN7模式下系统更新增加只显示IE11和最近期积累更新

### ISSUE THREAD

**Issue by Windypao** [Chuyu-Team/Dism-Multi-language#62]
如题，因为我测试过，只要安装过IE11和.NET 4.6.2和最近月度安全质量汇总和季度.NET后
安装之前的很多 补丁都会报错，查阅错误说明就是被告知已经被取代
事实上只要是WIN7-SP1 安装过IE11 和.NET 4.6.2后直接月度安全质量汇总和季度.NET就已经好了
他们已经包含了其它全部补丁（或者包含可替代其它补丁的补丁）并不需要额外再补丁
你要硬打 打上去不仅没用而且可能还会报错或者出问题
月度安全质量汇总就是微软专门做给装好IE11和.NET4.6.2的人的
如果不装好IE11 和,NET 4.6.2的确会少一些补丁

所以 建议WIN7模式下系统更新增加只显示IE11和最近期积累更新 的选项

**Comment by mingkuang-Chuyu** [comment]
Hi， Dism++已经更新库，剔除了过期的月度累计更新。另外这个也是好不受影响的，Dism++会自动屏蔽过期更新。重新扫描即可。
