### ISSUE TITLE
建议增加系统常用运行库（RunTimes）安装选项

### ISSUE THREAD

**Issue by Windypao** [Chuyu-Team/Dism-Multi-language#63]
如.net462 以及vc05 08（11年5月14日最终版）
10 sp1
12 13 15 update x
directx_Jun2010_redist

因为无论是win10还是win7这些扩展运行库都是默认没有安装的，不安装的话很多程序都会报错
普通小白根本不知道怎么装 装那个版本 才是最新的（比如vc05就有6个版本，只有11年5月alt安全修复 才是最新的）
属于必备品

**Comment by mingkuang-Chuyu** [comment]
Sorry  Dism++暂时并不打算添加这些功能……
