### ISSUE TITLE
French language support

### ISSUE THREAD

**Issue by GrosBourrin** [Chuyu-Team/Dism-Multi-language#634]
![2019-03-11_19h46_34](https://user-images.githubusercontent.com/40931468/54172787-9736d800-447f-11e9-9a0c-074b15396ba8.png)

French language not complete at this point ! can't see what's new on this dialog box !

**Comment by verdy-p** [comment]
Unfortunately, this just displays a log from developers only in Chinese that most users can't decipher.
There's not even a summary in English.
What is displayed is just the same as the log file in Github, but there's still no support for translating it. 

I also really suggest they translate these release notes at least in English. But the Chinese developers also have very limited knowledge of English and apparently can just use automatic translators. 
They should hire a good English/Chinese bilingual speaker in their support team and to make these announcements, e.g. someone from Hong Kong / Shenzhen. But I don't know where the Chuyu Team is actually located. There's probably only one or two persons.

**Comment by GrosBourrin** [comment]
that's ok, i understand the problem :) i have found the log in github, i can speak english too so don't worry about that and thanks for your reply !

**Comment by MouriNaruto** [comment]
@verdy-p 

You are right. There are only three part-time Chinese developers in Chuyu Team. I'm proud because I'm also one of them. (Two developers are programmers in a Chinese company and I'm a junior. )
All language translations are translated by the community. I am very grateful to them.
I might be the best at English among them. But you will find a lot of grammar bugs in my sentences and I am trying my best to improve my English.
We don't have more money to hire some full-time developers at the present because Dism++ is a software without fees. Someone donate some money to Dism++,  but it's just a drop in the bucket especially the server cost.

@GrosBourrin 

I have read your issues several hours ago. But I can't say anything to you because I have no words. I feel so sorry.

Mouri

**Comment by MouriNaruto** [comment]
P.S. You may ask why don't I translate for the "What's new?". Because the main developer will release small updates in any time. I am busy. Because not only I want to be a postgraduate student and prepare for exams, but also I have a lot of works to do in an autonomous driving lab.

Mouri.

**Comment by GrosBourrin** [comment]
i close the issue

**Comment by verdy-p** [comment]
Note: by "hiring" it does not neacessarily means offering a paid work contract. But you should seek some good Chinese friends that can help you at least in English (just review your existing licencing terms in English, they are full of grammatical errors and make little sense or are very hard to retranslate as is; and most probably even the "official" terms in Chinese have various spread errors, that would not resist an action in a Chinese court).

Three part-time volunteers is certainly not enough for this project. You should seek more local contacts to help you and you should discuss more (for licencing terms in Chinese and English you should consider help from other Chinese open-sourcers to secure them as you intend and get an advice from some lawyer for the Chinese version, for now this lience does not properly protect your work as you may think). 

But for the "update news log", you should have no problem to make some efforts creating at least an English summary, put it in some files that opensourcers will help you fix in correct English and then other languages. You don't need to be completely correct: minor lingusitic errors in English in these news is not a real problem.

So I suggest you include these news also as part of the opensourced "Languages" part of your project (you may continue using Chinese for the various commits in the public GitHub or your private source of the main program, which remains covered by your licence that you'll have fixed and secured first in Chinese, then in English)
