### ISSUE TITLE
清理过期驱动总显示出错

### ISSUE THREAD

**Issue by i5151** [Chuyu-Team/Dism-Multi-language#635]
清理过期驱动总显示出错，但是也清理了不少空间，不知道是不是过期的驱动。

**Comment by mingkuang-Chuyu** [comment]
点击下出错的项目显示是啥问题？

**Comment by i5151** [comment]
> 点击下出错的项目显示是啥问题？

没有其他的显示了，就是显示清理出错，之前都是好好的。
现在也不敢用这个功能了，好多过期的驱动都放在C盘里。

**Comment by calonye** [comment]
报0xE000023D错误
