### ISSUE TITLE
建议增加功能：开机自动启动win10自带移动热点

### ISSUE THREAD

**Issue by Sring65** [Chuyu-Team/Dism-Multi-language#636]
win10自动热点功能，但每次开机要手动开启，希望能提供开机自动启动win10自带的热点功能

**Comment by zhengpf823** [comment]
这个你可以自己写一个程序啊，记得linux里面很多类似的功能，比如写一个脚本实现，每次开机添加入启动。这个功能和本软件相关性不强

**Comment by MouriNaruto** [comment]
新规则建议请直接创建 Pull Request，Issue 只受理疑难解答和问题反馈，谢谢

**Comment by mingkuang-Chuyu** [comment]
Dism++不关心这些，另外市面上这样的软件一大把。
