### ISSUE TITLE
建议增加清理C:\Windows\Installer文件夹的功能

### ISSUE THREAD

**Issue by PatrickTscheng** [Chuyu-Team/Dism-Multi-language#639]
首先非常感谢开发的诸位，空间回收和备份系统的功能非常好用。
提一点建议希望参考
使用过程中，发现c:\windows\installer总会增加许多无用的驱动备份程序，让c盘非常臃肿，在网上搜索问题看到了这个网页也有讨论这个问题
https://superuser.com/questions/707767/how-can-i-free-up-drive-space-from-the-windows-installer-folder-without-killing
请问是否可以将这个文件夹的清理功能也加入空间回收部分？
非常感谢各位大神的工作

**Comment by gdsteven** [comment]
这个功能确实应该增加，现在用 PatchCleaner，但好久没更新了，win10更新很频繁，担心旧版本的会不会出问题。installer目录也是垃圾文件大户，补丁更新后，旧的安装文件依然留在installer里面，这个目录的垃圾文件体积很惊人。另外就是UWP应用的日志文件，最近无意中发现了微软纸牌、扫雷、麻将等几个目录里面的日志文件竟然快1G了，都好几年没删过，希望能增加清理UWP应用的日志和onedrive日志功能。

**Comment by MouriNaruto** [comment]
Windows Installer 清理功能是有的，只是效果不大好，你需要进入专家模式开启，这个功能我会继续改进
UWP 的常见垃圾清理我记得 Dism++ 应该也有（集成到其他项目里面了）
