### ISSUE TITLE
win10 rs1家庭版，系统优化中windows update从不检查实际无效

### ISSUE THREAD

**Issue by Windypao** [Chuyu-Team/Dism-Multi-language#64]
因为rs1开始，微软调整了更新强推策略
专业版可以选择推迟更新和从不检查 ，在钩选推迟更新后 从不检查生效
家庭版无法选择推迟更新，就算注册表改从不检查，其实也还是会每35天检查一次
而且还是会自动下载安装

目前家庭版可以通过下面方法彻底禁止windows update 该方法专业版也有效
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate]
"DisableWindowsUpdateAccess"=dword:00000001

注册表导入后需要重启生效

**Comment by mingkuang-Chuyu** [comment]
这个键值副作用太大……变成了完全禁用……而我们最初是想把它单纯别自动扫描。

此外家庭版由于不支持策略所以相关设置无效……这个问题暂时无解……是属于系统问题。暂时关闭……

如有需要可以暂时使用Dism++自定义规则实现。
