### ISSUE TITLE
企业常用的功能，如开启远程桌面、开启共享

### ISSUE THREAD

**Issue by panzhiyao** [Chuyu-Team/Dism-Multi-language#640]
某些企业需要的功能通常要在多个地方做设置，比如远程桌面和共享的开启，希望能做到一步开启这些功能，这样dism++在企业环境下的可用性就很高了。

**Comment by MouriNaruto** [comment]
新功能建议请直接创建 Pull Request，Issue 只受理疑难解答和问题反馈，谢谢

**Comment by mingkuang-Chuyu** [comment]
自己写个注册表 批量导入吧……
