### ISSUE TITLE
能否增加   真·离线    安装补丁的操作？？~~

### ISSUE THREAD

**Issue by AlbertETA** [Chuyu-Team/Dism-Multi-language#643]
**Is your feature request related to a problem? Please describe.（你提交这个反馈的目的是什么？是否遇到了Dism++现有的问题？）**
希望Dism++增加一个实用功能。有的内网电脑无法连接外网，但外网机可以啊，将补丁集下载到U盘后在内网电脑安装补丁。在现有的Dism++理论上有方法能够实现，但成果有可能会被清理。

**Describe the solution you'd like（描述你的解决方案）**
A clear and concise description of what you want to happen. 你希望得到什么样子的结果？
增加针对不同原盘（msdn）系统，一次性下载至今的全部更新补丁的功能，然后直接将这些补丁（文件，非下载链接）一起保存下来，最后用户通过U盘等存储介质将Dism++及其目录下的补丁大全集复制到不同电脑中，Dism++针对不同系统的状况打上相应（用户可选）补丁
（类似照相中  先拍照，后对焦那种）

**Describe alternatives you've considered （是否有其他备选方案？）**
有哇，就是把各种系统原盘挂载一遍，然后依次更新以获取到缓存的补丁，然后在其他电脑上用缓存补丁更新。不过Dism++有清理过期补丁的功能，会把缓存的补丁清理掉o(╥﹏╥)o

**Additional context（其他信息可以统一再此处填写）**

**Comment by mingkuang-Chuyu** [comment]
HI.你需要关闭差异传输引擎即可，在选项，详细设置，Windows Update 差异传输引擎，选择关闭。

这样下载下来的文件与环境无关
