### ISSUE TITLE
能不能添加个恢复默认的ClearType设置。。。

### ISSUE THREAD

**Issue by CrazyDoge666** [Chuyu-Team/Dism-Multi-language#646]
**Is your feature request related to a problem? Please describe.（你提交这个反馈的目的是什么？是否遇到了Dism++现有的问题？）**提交新功能

**Describe the solution you'd like（描述你的解决方案）**http://www.shenduwin8.com/jiaocheng/win8/8846.html
A clear and concise description of what you want to happen. 你希望得到什么样子的结果？
一键恢复默认

**Describe alternatives you've considered （是否有其他备选方案？）**

**Additional context（其他信息可以统一再此处填写）**

**Comment by MouriNaruto** [comment]
建议依葫芦画瓢修改 data.xml 然后进行测试后后直接 pull request，在 issue 里提新功能实现细节不是一个好的主意
