### ISSUE TITLE
WinSXS 無法清除

### ISSUE THREAD

**Issue by bwisely** [Chuyu-Team/Dism-Multi-language#648]
掃描WinSXS 後，確認有3.45GB 的檔案可以清除，但是按了清除時，卻出現無法清除

DISM, x64, 10.1.1000.90
OS: Win7 Sp1 enterprise x64

**Comment by mingkuang-Chuyu** [comment]
建议提供详细的错误信息……点击下 出错的项目，程序会在右侧提示错误错误代码。谢谢
