### ISSUE TITLE
扫描垃圾闪退

### ISSUE THREAD

**Issue by toorich** [Chuyu-Team/Dism-Multi-language#649]
**Describe the bug（Bug信息）**
在Windows 10 Insider Preview Build 18875.1000上，用“空间回收”扫描“传递优化缓存”直接闪退

**To Reproduce（如何重现？）**
Steps to reproduce the behavior:（详细说明下Bug重新步骤，此过程非常重要，如果言语表达不了就用步骤记录器，在cmd里面输入psr即可。）
1. 打开DISM++（废话）
2. 选择“空间回收”
3. 勾选“传递优化缓存”
4. 点击“扫描”
5. 直接闪退

**Expected behavior（预期行为）**
能够正常扫描出垃圾，而不闪退

**Screenshots（截图）**
暂无

**please complete the following information:（环境信息）**
 - OS: Windows 10 Insider Preview 10.0.18875.1000 x86
 - Dism++ Version 10.1.1000.90

**Additional context（其他）**
Add any other context about the problem here. 如果你有其他信息，可以在这里补充

**Comment by mingkuang-Chuyu** [comment]
NCleaner插件不适用于新系统，等待毛利更新。谢谢反馈

**Comment by MouriNaruto** [comment]
@mingkuang-Chuyu 问题已找到，正在修复

**Comment by mingkuang-Chuyu** [comment]
Dism++10.1.1000.100已经发布，带上了最新NCleaner。感谢反馈。
