### ISSUE TITLE
关于文字的小问题

### ISSUE THREAD

**Issue by imba-tjd** [Chuyu-Team/Dism-Multi-language#65]
dism++版本和系统版本见图，dpi缩放级别为150%，文字少了一个“6”。未测试其他系统。
<img width="209" alt="344" src="https://cloud.githubusercontent.com/assets/24759802/25108287/67cfbe96-2407-11e7-97dd-adb058c6b006.png">

**Comment by mingkuang-Chuyu** [comment]
Hi，请无视此问题，因为这个系统名称太长了，显示不下是正常的，此外Dism++有悬浮提示，鼠标放在 Tab上，等500ms，程序会显示 当前系统的完整信息，那里不会被遮挡，谢谢。
