### ISSUE TITLE
添加部分可由注册表打开的选项

### ISSUE THREAD

**Issue by 1582130940** [Chuyu-Team/Dism-Multi-language#651]
#打开桌面水印（普通版本，预览版不需要）
[HKEY_CURRENT_USER\Control Panel\Desktop]
"PaintDesktopVersion"=dword:1

#软件层关闭Meltdown
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management]
"FeatureSettingsOverride"=dword:3
"FeatureSettingsOverrideMask"=dword:3

#在电源管理中添加AHCI Link（阻止机器自动睡眠）
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\0012ee47-9041-4b5d-9b77-535fba8b1442\0b2d69d7-a2a1-449c-9680-f91c70521c60]
"Attributes"=dword:2

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\0012ee47-9041-4b5d-9b77-535fba8b1442\dab60367-53fe-4fbc-825e-521d069d2456]
"Attributes"=dword:2

#让鼠标自动移动到默认对话框
[HKEY_CURRENT_USER\Control Panel\Mouse]
"SnapToDefaultButton"="1"

#关闭默认游戏模式
[HKEY_CURRENT_USER\Software\Microsoft\GameBar]
"AutoGameModeEnabled"=dword:00000000

#关闭IE默认浏览器检查
[HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main]
"Check_Associations"="no"

#关闭允许应用使用AD ID
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo]
"Enabled"=dword:00000000

#将诊断数据设置为基础
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection]
"AllowTelemetry"=dword:00000001

#关闭反馈频率
[HKEY_CURRENT_USER\Software\Microsoft\Siuf\Rules]
"NumberOfSIUFInPeriod"=dword:00000000

#可选添加OEM信息
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation]
"Manufacturer"="（添加厂商信息）"
"Model"="（添加设备信息）"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion]
"RegisteredOwner"="（修改默认用户，winver可见）"
"RegisteredOrganization"="（修改默认公司，winver可见）"

**Comment by MouriNaruto** [comment]
建议依葫芦画瓢修改 data.xml 然后进行测试后后直接 pull request，在 issue 里提新功能实现细节不是一个好的主意
