### ISSUE TITLE
DISM++全部清理之后无法打开1903的sandbox

### ISSUE THREAD

**Issue by inkusa** [Chuyu-Team/Dism-Multi-language#654]
![图片](https://user-images.githubusercontent.com/37321948/56572978-ad919100-65f2-11e9-998d-08979b5d122f.png)
一直卡在这里，没有做过别的清理

**Comment by wzj1695224** [comment]
同样碰到此问题，做了一些优化后无法打开sandbox，把优化开关全部调回后还是无法打开

**Comment by mingkuang-Chuyu** [comment]
感谢支持，我尝试重新下次问题。

**Comment by wzj1695224** [comment]
系统更新至 18362.239 (Update July?) 后问题解决，怀疑是系统bug

**Comment by wzj1695224** [comment]
@mingkuang-Chuyu @inkusa 系统更新至 18362.239 (Update July?) 后问题解决，怀疑是系统bug
