### ISSUE TITLE
清理后，win10 1903更新(KB4495666) - 错误 0x800f0988

### ISSUE THREAD

**Issue by lingyongji** [Chuyu-Team/Dism-Multi-language#655]
**Describe the bug（Bug信息）**
A clear and concise description of what the bug is. 用一句话概括这个Bug，哪里出现了异常。

**To Reproduce（如何重现？）**
Steps to reproduce the behavior:（详细说明下Bug重新步骤，此过程非常重要，如果言语表达不了就用步骤记录器，在cmd里面输入psr即可。）

**Expected behavior（预期行为）**
A clear and concise description of what you expected to happen. 正常情况下应该是怎么样的？

**Screenshots（截图）**
If applicable, add screenshots to help explain your problem. 如果你能提供相关错误截图那么再好不过了。

**please complete the following information:（环境信息）**
 - OS: [e.g. Windows 7 x64 SP1, Windows 10 x86 1803]
 - Dism++ Version [e.g. 10.0.1000.70]

**Additional context（其他）**
Add any other context about the problem here. 如果你有其他信息，可以在这里补充

**Comment by jviinf** [comment]
同样遇到了无法更新 错误2019-适用于 Windows 10 Version 1903 的 04 累积更新，适合基于 x64 的系统 (KB4495666) - 错误 0x800f0988

**Comment by itheabyss** [comment]
今天微软推送了04更新，我也碰到这个问题了。远景上一堆人都出现这个错误。都没有精简过系统，但所有人都用DISM清理过系统！我也清理过 :(

估计是现在不能动winsxs文件夹。

**Comment by qinluezhew3** [comment]
同样遇到了无法更新 错误2019-适用于 Windows 10 Version 1903 的 04 累积更新，适合基于 x64 的系统 (KB4495666) - 错误 0x800f0988

**Comment by redblue9771** [comment]
包括KB4497093累积更新错误 0x800f0988，我也清理过

**Comment by mili-tan** [comment]
同样也遇到了 
Cumulative Update for Windows 10 Version Next (10.0.18356.21) (KB4496796) - 错误 0x800f0988 
应该也清理过winsxs

**Comment by reov** [comment]
同样如此更新失败
