### ISSUE TITLE
如何移除系统的Flash包？

### ISSUE THREAD

**Issue by ashuai** [Chuyu-Team/Dism-Multi-language#656]
**Is your feature request related to a problem? Please describe.（你提交这个反馈的目的是什么？是否遇到了Dism++现有的问题？）**
系统天天更新flash让我重启，垃圾flash一堆漏洞天天需要更新，而我根本不用flash

**Describe the solution you'd like（描述你的解决方案）**
能否增加一个flash包的清理功能

**Describe alternatives you've considered （是否有其他备选方案？）**
kill adobe flash

**Comment by mingkuang-Chuyu** [comment]
抱歉Dism++不提供精简功能，你可以使用一些精简工具删除此功能。
