### ISSUE TITLE
appx 卸载不了

### ISSUE THREAD

**Issue by spitWind** [Chuyu-Team/Dism-Multi-language#657]
**Describe the bug（Bug信息）**
应用卸载一场

**To Reproduce（如何重现？）**
Steps to reproduce the behavior:（详细说明下Bug重新步骤，此过程非常重要，如果言语表达不了就用步骤记录器，在cmd里面输入psr即可。）
1. 应用疑似损坏
2.  应用卸载不支持
3. 电脑有问题才用这软件的。。可以做些兼容吗。。

**Expected behavior（预期行为）**
A clear and concise description of what you expected to happen. 正常情况下应该是怎么样的？

**Screenshots（截图）**
If applicable, add screenshots to help explain your problem. 如果你能提供相关错误截图那么再好不过了。
![image](https://user-images.githubusercontent.com/18753430/57004305-82193280-6c00-11e9-864d-7abac3b3b5f7.png)

**please complete the following information:（环境信息）**
 - OS: [e.g. Windows 7 x64 SP1, Windows 10 x86 1803]
 - Dism++ Version [e.g. 10.0.1000.70]

**Additional context（其他）**
Add any other context about the problem here. 如果你有其他信息，可以在这里补充

**Comment by mingkuang-Chuyu** [comment]
你应该在删除 第一个  `疑似损坏`的项目吧，这个微软API删不了。不是我不想做兼容，而是我真的不知道该怎么残留的需要怎么删啊……

**Comment by mingkuang-Chuyu** [comment]
你要是你知道怎么删 你可以告诉我，帮我们改进DIsm++。谢谢
