### ISSUE TITLE
Windows Server 2012 R2 备份后还原部分功能异常

### ISSUE THREAD

**Issue by wojiushixiaobai** [Chuyu-Team/Dism-Multi-language#659]
IIS服务 无法正常运行

提示：指定的登陆会话不存在
日志里面提示：iis admin service 无效签名

**Comment by mingkuang-Chuyu** [comment]
这可能 是Dism++的默认排除列表导致的问题，能否帮忙看看跟哪个规则冲突？

Dism++排除列表 可以通过 选项 - 详细设置 - 文件过滤列表 查看

感谢支持。
