### ISSUE TITLE
建议在左边的功能列表上添加与Windows功能匹配的图标

### ISSUE THREAD

**Issue by staryy** [Chuyu-Team/Dism-Multi-language#66]
建议在左边的功能列表上添加与Windows功能匹配的图标,方便使用,推荐给新用户时对方表现非常迷茫,不容易上手

**Comment by mingkuang-Chuyu** [comment]
Hi，微软自带的Windows 功能也没有图标…… 所以Dism++也无法 拿到你所谓 Windows功能匹配的图标。除非Dism++自己制作一套图标，但是也不见得就能跟Windows 功能匹配啊。

**Comment by mingkuang-Chuyu** [comment]
关闭此问题，必要时可以重新打开此问题
