### ISSUE TITLE
ESD 转 ISO 错误对话框显示不完整

### ISSUE THREAD

**Issue by pzhlkj6612** [Chuyu-Team/Dism-Multi-language#660]
**Bug信息**
ESD 转 ISO 错误对话框显示不完整。

**如何重现？**
1. 打开“文件”菜单
2. 打开“ESD -->ISO 向导”
3. 选择源 esd 和目的 iso ，点完成
4. 弹出错误对话框

**截图**
![20190502_Dism++-UI-BUG](https://user-images.githubusercontent.com/29089388/57065263-778f9380-6cfb-11e9-93ff-b0d0660ac726.png)

**环境信息**
 - OS: Windows 10 x64 1607 14939.rs1_release_inmarket.190401-1809
 - Dism++ 10.1.1000.90B

**其他**
最小化再最大化错误对话框可以使其布局正常（即能显示完整）。

**Comment by mingkuang-Chuyu** [comment]
感谢支持。
