### ISSUE TITLE
語言繁中時，無微軟注音選項

### ISSUE THREAD

**Issue by rayhsu0303** [Chuyu-Team/Dism-Multi-language#661]
語言為中文-繁體中文(台灣)，
系統最佳化無顯示注音繁中選項。

**Comment by suwakowww** [comment]
Hi,
因为这个是以前有人提交调整规则的，如果你知道如何进行调整的话（比如修改注册表），可以写出调整方案或者提交pull request。
至于如何写调整规则，可以参考下`data.xml`。

**Comment by mingkuang-Chuyu** [comment]
确实 主要我们也不懂什么  微軟注音選項 是啥……
