### ISSUE TITLE
[Bug] 意外的网络错误

### ISSUE THREAD

**Issue by dingyifei** [Chuyu-Team/Dism-Multi-language#665]
**Describe the bug（Bug信息）**
进行系统备份到一个SMB的网络文件夹时遇到”意外的网络错误“

**To Reproduce（如何重现？）**
1. 点击恢复功能-》系统备份
2. 点击 “浏览” 并选择 一个网络位置（\\192.168.2.254\backup ），选择wim无压缩
3. 点击确定
4. 备份在大约20分钟后提示“意外的网络错误”并终止

**Expected behavior（预期行为）**
正常备份

**Screenshots（截图）**
If applicable, add screenshots to help explain your problem. 如果你能提供相关错误截图那么再好不过了。

**please complete the following information:（环境信息）**
 - dism++ x64 10.1.1000.90
 - Melannox Connect-X2 10Gbps 网卡
[MelannoxConnectX-2.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/3189241/MelannoxConnectX-2.log)

 - Windows 10 Professional Insider Preview Build 18898.rs_prerelease.190510-1634
 - SMB服务器版本：samba/stable,now 2:4.5.16+dfsg-1+deb9u2 amd64 
 ```
[homes]
	directory mode = 0777
	user = root
	write list = root
	valid users = root
	writeable = yes
	create mode = 0777
	path = /backup
	force user = root

[global]
    auto services = homes
    max log size = 50
    socket options = TCP_NODELAY 
    preferred master = No
    local master = No
    dns proxy = No
    security = User
```

**Additional context（其他）**
Add any other context about the problem here. 如果你有其他信息，可以在这里补充

**Comment by mingkuang-Chuyu** [comment]
我尝试重现下此问题。
