### ISSUE TITLE
提供Dism日志分析

### ISSUE THREAD

**Issue by wildoxlee** [Chuyu-Team/Dism-Multi-language#67]
dism日志太复杂了，尝试用了网上的PS脚本来分析DISM.Log，但是仍然看的不清不粗。能不能提供一个简单的dism日志分析功能，其实我就是想指导，验证受损或修复受损失败后能告诉我到底是哪个文件除了问题。

**Comment by mingkuang-Chuyu** [comment]
此功能跟Dism++无关，另外 日志也很通俗易懂，只是用英语写了而已，准备个翻译工具，对照着看吧。
