### ISSUE TITLE
清理时确认窗口优化

### ISSUE THREAD

**Issue by wqw6** [Chuyu-Team/Dism-Multi-language#670]
我一般都是在在做电脑空闲的时候清理垃圾，但是每次回来，都是有一个窗口，比如像是“将要重启资源管理器”，需要我确认才能继续清理，所以，想要有一个“离开模式”，就是无人值守的时候自动清理自动选择合适的选项不弹出确认的窗口，我回来的时候希望能够看到的最后一个“已释放了多少多少的空间”这个窗口。

**Comment by Threonine-Animist** [comment]
同，建议最先进行要重启Explorer的项

**Comment by mingkuang-Chuyu** [comment]
感谢支持与建议……以后做个倒计时吧……

**Comment by MouriNaruto** [comment]
Archived, #707
