### ISSUE TITLE
找不到Vmware 映射的磁盘

### ISSUE THREAD

**Issue by ted423** [Chuyu-Team/Dism-Multi-language#671]
**Describe the bug（Bug信息）**
A clear and concise description of what the bug is. 用一句话概括这个Bug，哪里出现了异常。
由于VMware有快照功能，所以想用VMware来进行封装，但随后发现映射为本地盘后，DISM++里无论如何都无法显示该盘符并且进不去。

**please complete the following information:（环境信息）**
 OS: Windows 10 x64 1903
 Dism++ Version  10.1.1000.90
VMware 15.1.0 build-13591040

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/59245013-79793a80-8c49-11e9-8544-38796a6ec137.png)

补充一个截图，可以看到DISM++里没显示VMware映射的F盘

**Comment by MouriNaruto** [comment]
请使用管理员权限或者 SYSTEM 权限映射

**Comment by ted423** [comment]
> 请使用管理员权限或者 SYSTEM 权限映射

这回确实能看到了.......不过资源管理器又看不到了，总之感谢
