### ISSUE TITLE
Win10 1803更新後Windows 系統 裡面沒有控制台了，必須要用搜尋的才找的到!

### ISSUE THREAD

**Issue by sex78** [Chuyu-Team/Dism-Multi-language#672]
**Is your feature request related to a problem? Please describe.（你提交这个反馈的目的是什么？是否遇到了Dism++现有的问题？）**

**Describe the solution you'd like（描述你的解决方案）**
A clear and concise description of what you want to happen. 你希望得到什么样子的结果？

**Describe alternatives you've considered （是否有其他备选方案？）**

**Additional context（其他信息可以统一再此处填写）**

**Comment by mingkuang-Chuyu** [comment]
啥意思？你升级到1803没有控制台 然后提交 Bug做什么？

**Comment by MouriNaruto** [comment]
问题含糊其词，关闭
