### ISSUE TITLE
希望增加一个可以锁定输入法的功能

### ISSUE THREAD

**Issue by KieruZero** [Chuyu-Team/Dism-Multi-language#673]
**Is your feature request related to a problem? Please describe.（你提交这个反馈的目的是什么？是否遇到了Dism++现有的问题？）**
平时打游戏时候会误触发CTRL+SPACE的快捷键导致切出窗口,并非现在DISM++的问题。

**Describe the solution you'd like（描述你的解决方案）**
说实话还是个小白 还烦请各位大佬开始表演
A clear and concise description of what you want to happen. 你希望得到什么样子的结果？
锁定美国键盘 不会触发任何输入法快捷键

**Describe alternatives you've considered （是否有其他备选方案？）**
微软中文输入法的中/英切换ctrl+space快捷键取消掉（但是这个不能取消好像是BUG?

**Additional context（其他信息可以统一再此处填写）**

**Comment by MouriNaruto** [comment]
信息不足，如果是规则建议请发 PR

**Comment by liuxilu** [comment]
@KieruZero 这个功能和DISM有什么关系啊？DISM++又不是万能的……
 - 快捷键删不掉改成别的不容易按到的不就行了。
 - 切换到英语玩游戏啊。输入法为“英语美国”时，Ctrl+空格就不会有反应了。

@MouriNaruto 关了吧

**Comment by KieruZero** [comment]
> @KieruZero 这个功能和DISM有什么关系啊？DISM++又不是万能的……
> 
> * 快捷键删不掉改成别的不容易按到的不就行了。
> * 切换到英语玩游戏啊。输入法为“英语美国”时，Ctrl+空格就不会有反应了。
> 
> @MouriNaruto 关了吧

什么叫功能和dism没关系，那这么说dism系统优化里的项目都是没关系的吗？

**Comment by liuxilu** [comment]
自然是和DISM没关系，不过可能和DISM++有关系吧😀我倒是支持UNIX哲学的。

**Comment by mingkuang-Chuyu** [comment]
我不知道该如何做，我会关闭此问题，谁可以提供方案时  可以重新打开此问题。
