### ISSUE TITLE
DISM++在intall.wim中集成WIN10补丁问题

### ISSUE THREAD

**Issue by boviapei** [Chuyu-Team/Dism-Multi-language#674]
**Describe the bug（Bug信息）**
WIN10 1903，提取install.wim后，手工下载WIN10补丁，.MSU文件，然后，使用DISM++添加补丁方式安装。
封装后，安装1903，在系统中看到文件小版本号，是成功的，但windows update依然会扫描出DISM++集成的补丁。困扰我很久。

**To Reproduce（如何重现？）**
Steps to reproduce the behavior:（详细说明下Bug重新步骤，此过程非常重要，如果言语表达不了就用步骤记录器，在cmd里面输入psr即可。）

**Expected behavior（预期行为）**
A clear and concise description of what you expected to happen. 正常情况下应该是怎么样的？

**Screenshots（截图）**
If applicable, add screenshots to help explain your problem. 如果你能提供相关错误截图那么再好不过了。

**please complete the following information:（环境信息）**
 - OS: [e.g. Windows 7 x64 SP1, Windows 10 x86 1803]
 - Dism++ Version [e.g. 10.0.1000.70]

**Additional context（其他）**
Add any other context about the problem here. 如果你有其他信息，可以在这里补充

**Comment by mingkuang-Chuyu** [comment]
这个是部分安装导致的，简单说就是   在集成补丁后  你又安装了其他功能。这导致补丁需要重新安装。

比如说，你先安装补丁，然后安装 .NET 3.5。然后就这样了。
