### ISSUE TITLE
空间回收（chrome历史可删）

### ISSUE THREAD

**Issue by zpengcom** [Chuyu-Team/Dism-Multi-language#677]
C:\Users\用户名\AppData\Local\Google\Chrome\User Data\Profile 1

History文件如果久了会有几个G的大小

**Comment by MouriNaruto** [comment]
新功能建议请直接创建 Pull Request，Issue 只受理疑难解答和问题反馈，谢谢

**Comment by liuxilu** [comment]
不如在chrome里“清除浏览数据”……

**Comment by mingkuang-Chuyu** [comment]
请版本Chrome没这个文件……
