### ISSUE TITLE
“登录界面默认打开小键盘” Win10系统下失效

### ISSUE THREAD

**Issue by h6fYe34KFSiH** [Chuyu-Team/Dism-Multi-language#679]
**Describe the bug（Bug信息）**
“登录界面默认打开小键盘” Win10系统下失效

**Expected behavior（预期行为）**
注册表位置：计算机\HKEY_USERS\.DEFAULT\Control Panel\Keyboard
InitialKeyboardIndicators 的值应该是 80000002

**please complete the following information:（环境信息）**
 - OS: Windows 10 x64 1903]
 - Dism++ Version [e.g. 10.0.1000.100]

参考https://jingyan.baidu.com/article/d3b74d64ccdc0c1f77e609a8.html

**Comment by mingkuang-Chuyu** [comment]
感谢~~~~

**Comment by MouriNaruto** [comment]
新规则建议，请发 PR

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/Dism-Multi-language/issues/828

重复问题
