### ISSUE TITLE
清理后Net4.6.2卸载失效

### ISSUE THREAD

**Issue by LC-BX** [Chuyu-Team/Dism-Multi-language#68]
已解决 软件没问题

**Comment by mingkuang-Chuyu** [comment]
Hi， Dism++ 并不删除这个文件……目前来说还没有正对.NET的清理项目。不过这个问题我会去验证下，谢谢

**Comment by LC-BX** [comment]
Hi，我在清理前看了DISM右侧的清理列表，里面确实有我提及的Setupcache文件夹。还请验证下。如需其他信息，请联系我，谢谢

**Comment by mingkuang-Chuyu** [comment]
Dism++规则中会删除 
%ProgramFiles%\Microsoft.NET\Multi-Targeting Pack\*\Setupcache
但是 并不会 删除你提到的 C:\Windows\Microsoft.NET\Framework64\v4.0.30319\SetupCache

最后这个规则 等级也是 风险……程序默认并不现实他们……

**Comment by LC-BX** [comment]
....So sorry 是我的问题，搞错了软件。有另一清理软件界面和DISM差不多，所以记错了 抱歉抱歉

**Comment by mingkuang-Chuyu** [comment]
这都行…… 我惊呆了
谢谢支持
