### ISSUE TITLE
Win7下清理Windows事件时出错

### ISSUE THREAD

**Issue by Threonine-Animist** [Chuyu-Team/Dism-Multi-language#680]
在WIN7下，扫描 空间回收\Windows事件 时会提示函数错误
环境是Win 7 x64 SP1与最新版DISM++（.100）

**Comment by adamp4** [comment]
遇到相同情况
![2019-06-24_172914](https://user-images.githubusercontent.com/44283910/60007855-a7c53400-96a5-11e9-81d0-a53ce624c2a2.jpg)

![2019-06-24_172802](https://user-images.githubusercontent.com/44283910/60007782-85cbb180-96a5-11e9-9b93-f82708017f75.jpg)

**Comment by MouriNaruto** [comment]
@adamp4 如果可以的话，希望再次清理该项目出错的时候提供 Dism++ 的日志

**Comment by Threonine-Animist** [comment]
> @adamp4 如果可以的话，希望再次清理该项目出错的时候提供 Dism++ 的日志

我这边如果只选择该项进行清理的话，.\Config\Dism++.log并未提供有价值的错误信息

**Comment by MouriNaruto** [comment]
@Threonine-Animist 好的

**Comment by adamp4** [comment]
> @adamp4 如果可以的话，希望再次清理该项目出错的时候提供 Dism++ 的日志

你好,日志见附件.
[Dism++.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/3321670/Dism%2B%2B.log)

**Comment by MouriNaruto** [comment]
@adamp4 谢谢

**Comment by adamp4** [comment]
> @adamp4 谢谢

客气了,很喜欢你们的作品,希望初心不改,越来越好^_^

**Comment by MouriNaruto** [comment]
@adamp4 突然忘记了，我希望看看你安装的补丁列表

管理员身份运行命令提示符，输入
> dism /online /Get-Packages /format:table > C:\1.txt

把 C 盘的 1.txt 发给我

我感觉可能猜到了原因，但是不确定，于是需要看看

**Comment by MouriNaruto** [comment]
@adamp4 不用了，我找到了原因……

**Comment by MouriNaruto** [comment]
[NCleaner.zip](https://github.com/Chuyu-Team/Dism-Multi-language/files/3321795/NCleaner.zip)

@adamp4 你试试看吧，这是 x64 的 NCleaner.dll
应该替换掉 [Dism++目录]\Config\AMD64 目录里的同名文件

希望你的 Bug 被修复了

**Comment by adamp4** [comment]
> [NCleaner.zip](https://github.com/Chuyu-Team/Dism-Multi-language/files/3321795/NCleaner.zip)
> 
> @adamp4 你试试看吧，这是新鲜出炉的 x64 的 NCleaner.dll
> 应该替换掉 [Dism++目录]\Config\AMD64 目录里的同名文件
> 
> 希望你的 Bug 被修复了

试过了,还是不行
[Dism++.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/3323117/Dism%2B%2B.log)

**Comment by MouriNaruto** [comment]
@adamp4 好的看来我需要深入测试

**Comment by MouriNaruto** [comment]
该问题已经被鸭子修复

**Comment by adamp4** [comment]
> 该问题已经被鸭子修复

打开提示更新的还是6月7号的更新,而且官网也打不开(提示电脑日期时间不对,但并无此问题,其他网站均正常)
![11111111111111111](https://user-images.githubusercontent.com/44283910/63478056-a30cd880-c4ba-11e9-831e-565e6d0344ed.jpg)
![2](https://user-images.githubusercontent.com/44283910/63478067-b6b83f00-c4ba-11e9-8a95-cd6ab14f7483.jpg)
