### ISSUE TITLE
APPX管理功能友好性改进

### ISSUE THREAD

**Issue by Threonine-Animist** [Chuyu-Team/Dism-Multi-language#683]
目前Dism++的appx管理功能较为不友好
能否通过读取AppxManifest.xml获得每个应用的友好名称与图标，并支持通过包名/应用名查找

**Comment by MouriNaruto** [comment]
AppxManifest.xml 里面不一定有你想要的应用名，尤其是不同语言有不同名字的应用（例如 照片 App），你还需要单独读取 pri 资源文件，暂时没有找到好的办法，而且巨硬的 DISM 实现也没有显示友好名称。
图标的话倒是可以试试。

**Comment by MouriNaruto** [comment]
暂时关闭问题，如果能搞出解决方案再重新开启
