### ISSUE TITLE
添加代理服务器设置

### ISSUE THREAD

**Issue by stlfatboy** [Chuyu-Team/Dism-Multi-language#684]
**Is your feature request related to a problem? Please describe.（你提交这个反馈的目的是什么？是否遇到了Dism++现有的问题？）**
更新管理，扫描，提示无法连接服务器。由于需要网络代理，系统代理已设置，仍提示无法连接。

**Describe the solution you'd like（描述你的解决方案）**
A clear and concise description of what you want to happen. 你希望得到什么样子的结果？

**Describe alternatives you've considered （是否有其他备选方案？）**

**Additional context（其他信息可以统一再此处填写）**

**Comment by mingkuang-Chuyu** [comment]
更新管理，扫描， 提示无法连接服务器。由于需要网络代理。这个问题不会在有了。

因为DIsm++不在分发此数据库文件，另外我看你的描述 跟标题好像也没有啥关系……。
