### ISSUE TITLE
用dism++备份 win10显示the specified path is invalid错误

### ISSUE THREAD

**Issue by jmonk2018** [Chuyu-Team/Dism-Multi-language#686]
**Describe the bug（Bug信息）**
用dism++备份 win10显示the specified path is invalid错误

无法备份

 - OS: Windows 10 x64 Education]
 - Dism++ Version [e.g. 10.0.1000.70]

**Additional context（其他）**
Add any other context about the problem here. 如果你有其他信息，可以在这里补充

**Comment by MouriNaruto** [comment]
信息不充足，关闭问题
