### ISSUE TITLE
希望增加资源管理器导航窗口的【Dropbox】选项

### ISSUE THREAD

**Issue by YIZHEV** [Chuyu-Team/Dism-Multi-language#687]
使用起来没有任何问题，只是觉得可以隐藏OneDrive的话应该也可以隐藏Dropbox选项。
因为我平时使用起来OneDrive只是用来同步1Password的密码库，所以不需要打开看。隐藏后台工作就完美了。

**Comment by MouriNaruto** [comment]
如果是规则建议，请发 PR

**Comment by mingkuang-Chuyu** [comment]
我不需要用Dropbox，所以不会去研究。如果有人知道，那么可以提供 PR，谢谢。
