### ISSUE TITLE
Import/Export PowerShell Scripts or registry settings...

### ISSUE THREAD

**Issue by mcc85s** [Chuyu-Team/Dism-Multi-language#688]
I'm not sure if this is a feature in this program, but suppose that this tool could configure a template that I can apply to all loaded images or anything in a programatic loop, for instance everything in this picture

![image](https://user-images.githubusercontent.com/44849131/60870448-e2c77b80-a1fe-11e9-9ef7-87f7eb3c9147.png)

Occasionally I'll have to dump my WIM files and start from scratch. it would be incredibly useful to be able to feed this program a previous template and/or export a configuration to a registry or powershell script file... and If this program already does that, then perhaps someone could tell me how it works, because I don't see a way to import a script, or to export a script without concerting it back from registry.

Also, Windws Updates, not always able to pull from the MUC properly. I often do a clean installation and then wait to see what updates weren't installed and stream them in again...

Also... 

Can DISM++ do a WinPE build? For instance, this is from the PSD-MDT modification I've been working on... I am aware that I'm doubling the work I do by using both of these tools... but I've experimented with MDT. DISM++ I know my way around, but I can't read a lot of the documentation.

[winpe.txt](https://github.com/Chuyu-Team/Dism-Multi-language/files/3371885/winpe.txt)

-MC

**Comment by MouriNaruto** [comment]
You can learn Chinese first.

I don't know how to tell you something you want in English.
