### ISSUE TITLE
win10升级到1703后验证映像受损但无法修复。

### ISSUE THREAD

**Issue by pliskinfree** [Chuyu-Team/Dism-Multi-language#69]
刚刚用win10系统升级到1703，使用DISM++的验证受损功能显示映像受损可以修复，使用修复功能到最后总是修复失败，说是找不到安装源，升级之前是没这个问题的，另外使用命令行，DISM /online /cheanup-image /restorehealth也是无法修复。不知道其他人有没有这个问题

**Comment by mingkuang-Chuyu** [comment]
Hi 这个是微软的问题，微软系统 自生 就存在此问题。

建议你反馈给微软。谢谢
