### ISSUE TITLE
Bug detected when using Disk Cleanup - Windows Events

### ISSUE THREAD

**Issue by PST502** [Chuyu-Team/Dism-Multi-language#692]
**Describe the bug（Bug信息）**
I have used Disk Cleanup in Dism++ 10.0.1000.100 to clean up my hard drive. However, I have detected that the English language file (en.zip) has been removed after that and it has been detected as a file in "Windows Events" (Disk Cleanup > System > Windows Events). Therefore, I need to install an update when Dism++ prompts to make English language come back.

**To Reproduce（如何重现？）**
...

**Expected behavior（预期行为）**
Exclude "en.zip" (maybe other languages also) from Windows Events to avoid accidentally removing.

**Screenshots（截图）**
If applicable, add screenshots to help explain your problem. 如果你能提供相关错误截图那么再好不过了。

**please complete the following information:（环境信息）**
 - OS: [e.g. Windows 8.1 Pro build 9600 x64, Windows 10, maybe Windows 7]
 - Dism++ Version [e.g. 10.0.1000.100]

**Additional context（其他）**
Add any other context about the problem here. 如果你有其他信息，可以在这里补充

**Comment by MouriNaruto** [comment]
It's not related to Windows Events Cleanup. But I think you have chosen something like "Leftover Files of the Previous Version(s) of Dism++".

So case closed.
