### ISSUE TITLE
Windows 10 ISO 不支援離線更新

### ISSUE THREAD

**Issue by ellery79** [Chuyu-Team/Dism-Multi-language#693]
**Describe the bug（Bug信息）**
A clear and concise description of what the bug is. 用一句话概括这个Bug，哪里出现了异常。
我下載了最新的Windows 10 ISO 1903 繁體版。解壓，將install.esd 轉換成 install.wim，掛載，到更新管理掃瞄，會提示我已有最新更新。
但新安裝Windows後，其實有其他Windows  update.

**To Reproduce（如何重现？）**
Steps to reproduce the behavior:（详细说明下Bug重新步骤，此过程非常重要，如果言语表达不了就用步骤记录器，在cmd里面输入psr即可。）

**Expected behavior（预期行为）**
A clear and concise description of what you expected to happen. 正常情况下应该是怎么样的？
正常情況下應有Security Update安裝

**Screenshots（截图）**
If applicable, add screenshots to help explain your problem. 如果你能提供相关错误截图那么再好不过了。

**please complete the following information:（环境信息）**
 - OS: [e.g. Windows 7 x64 SP1, Windows 10 x86 1803]
 - Dism++ Version [e.g. 10.0.1000.70]

**Additional context（其他）**
Add any other context about the problem here. 如果你有其他信息，可以在这里补充

**Comment by MouriNaruto** [comment]
这个和 Dism++ 更新数据库更新不及时有关
