### ISSUE TITLE
Windows 8.1 Defender Problem

### ISSUE THREAD

**Issue by Tiara-11** [Chuyu-Team/Dism-Multi-language#698]
Hi...^^
I'm using Windows 8.1 Pro x64.
Turning on Defender when using Dism ++ makes installation or mounting of images very slow.

Turning off the defender is very fast.

Thank you for making a good program.

I wish you good luck.

**Comment by MouriNaruto** [comment]
It's known issue.

Windows Defender will scan per file when opening files, and image operation will create or open lots of files, so it's slow.

So case closed.
