### ISSUE TITLE
界面语言

### ISSUE THREAD

**Issue by tkfjj1994** [Chuyu-Team/Dism-Multi-language#7]
时间格式修改为英语后，程序的界面语言也随着英文。PS.区域以及显示语言都是中国/中文

**Comment by mingkuang-Chuyu** [comment]
这是正常的，Dism++默认跟随系统默认的线程语言环境。也就是你说的 时间格式

其实微软的说法并不准确，一旦修改时间格式，那么所有程序的默认线程LCID就会变成你修改后的，此外所有的字体设置都会切换为对应的语言。这些设置都不跟随 区域以及显示语言，另外你这种系统显示语言跟系统格式不一致的设置会导致字体发虚，原因之前我也解释了一旦修改系统格式，系统的字体设置也跟着变……

最后   程序逻辑没有错，你把格式改回中文就好了。Dism++这样跟随系统默认语言环境可以避免字体发虚问题。
