### ISSUE TITLE
壓縮包存在亂碼問題

### ISSUE THREAD

**Issue by kulaLin** [Chuyu-Team/Dism-Multi-language#70]
下載目前最新的Dism++ zip壓縮包後，該項會顯示亂碼，在非簡體中文情況下
zip壓縮包尚未支持Unicode，建請使用英文命名。

顯示為以下
「32弇炵苀邧僻Dism++x86.txt」

**Comment by mingkuang-Chuyu** [comment]
Hi，这个文件本来就是给简中用户看的…… 
如果搞成英语，中文用户又看不懂了……
而zip标准不支持Unicode然后就只能这样了，这个问题，无解

你懂的……
