### ISSUE TITLE
[Question] What is "Windows Update Differ Engine" ?

### ISSUE THREAD

**Issue by DooML** [Chuyu-Team/Dism-Multi-language#700]
![image](https://user-images.githubusercontent.com/26717942/63195418-6aa86d00-c06a-11e9-8208-fc67c02d22d1.png)

**Comment by MouriNaruto** [comment]
Same as Windows Updates's implementation.

"express" edition packages

**Comment by DooML** [comment]
And how does it relate to this program? Is it about the offline _wsusscn2.cab_ update package?

**Comment by MouriNaruto** [comment]
All information about update packages are in wsusscn2.cab.
