### ISSUE TITLE
DCOM issues

### ISSUE THREAD

**Issue by mcc85s** [Chuyu-Team/Dism-Multi-language#701]
Running DISM /Online /Cleanup-Image /RestoreHealth

Fails. Writes errors to "C:\Windows\Logs\DISM\dism.log"

Filtered out the GUID's, and none of these show up in CLSID or in DCOM.

{53BFAE52-B167-4E2F-A258-0A37B57FF845}
{85381772-2F23-4807-86AF-8D83A172371C}
{30BC39EF-FA14-42C3-BE77-22C7F1DF4E63}
{E9AC7116-8B6F-4A1A-BC43-94CB7CB944E1}
{5336F940-4DF3-4DE6-BE5A-8F581CC18094}
{648A4F44-3730-4184-90FD-07E283163B0E}
{19EA5405-2914-4836-81BD-ACF2D8EC3588}
{125AFB23-8432-46DF-8071-1F921C7462A9}
{FF324B85-BE21-4749-B2FD-B97B12EC2D74}
{4D36E96C-E325-11CE-BFC1-08002BE10318}
{4D36E968-E325-11CE-BFC1-08002BE10318}
{E0CBF06C-CD8B-4647-BB8A-263B43F0F974}
{4D36E972-E325-11CE-BFC1-08002BE10318}
{92616AE4-2D9D-4660-B5A0-7ED4C56E3D76}
{0D608600-D202-403D-A610-DFAAED0466B5}
{BA930F49-E9F0-4FD2-9A24-34C9351BF7DA}
{6939B893-E7E8-477D-896C-B219834A0E85}
{9F63D0B1-9EF8-4AAF-9F31-24CE8538429D}
{AFA9B532-2BA6-481F-A899-08BA56B6BE35}
{EB5853DF-21BD-4CD2-9B59-59B117BA3937}

Here's the tool where I started to conceptualize that perhaps the product you've been working on is 'allowing remote entry into those systems'

Might not be you, could be Microsoft, or whoever... All I know is, when the SID's or GUID's don't show up, I start to get very concerned as to the reason why.

https://youtu.be/rKKmLwxeXbM

At this time, I'm waiting for ASUS to report back over some driver installation issues I've had. Has nothing to do with DISM++ but I figured I would report my findings with you and hope that there's a good explanation for this GUID's not being able to be 'found' anywhere, and why basic DISM won't work.

**Comment by MouriNaruto** [comment]
This problem is not related to Dism++.

I never find these GUIDs in Dism++'s source code.

Closed.
