### ISSUE TITLE
Will updates be available?

### ISSUE THREAD

**Issue by caspertone2003** [Chuyu-Team/Dism-Multi-language#703]
a) Would you publish in github or wherever future updates?
b) is current version working ok with 1903?

(as website is down...)

**Comment by MouriNaruto** [comment]
a) I think you should ask @mingkuang-Chuyu
b) Yes

**Comment by MouriNaruto** [comment]
Closed temporarily, we will reopen again if have response.

**Comment by MouriNaruto** [comment]
Please goto #717
