### ISSUE TITLE
[Feature Request] 永久开启Mobile Hotspot

### ISSUE THREAD

**Issue by Ehekatl** [Chuyu-Team/Dism-Multi-language#705]
** 新规则的名称 **
永久开启Mobile Hotspot

** 这个么做有什么合理性？ **
Windows 10默认会在无设备连接的情况下，一段时间后自动关闭Hotspot。
对于长久开启做热点的机器这很不方便。
去年以前还可以通过注册表修改过期时间，而新版本注册表已去掉该条目。

参考：https://superuser.com/questions/1144664/windows-10-mobile-hotspot-turning-off-on-its-own

** 有什么潜在风险？ **
对于移动设备来说增加耗电，固定设备则无此问题

** 如何回滚操作？ **
关闭优化或关闭Hotspot即可

** 系统适应性 **
适合所有Windows 10用户

** 其他信息 **
暂无

**Comment by MouriNaruto** [comment]
新功能添加请直接创建 Pull Request

**Comment by mingkuang-Chuyu** [comment]
听起来没有太大意思……而且也无法实现 不是吗？
