### ISSUE TITLE
空间回收功能 UI改进建议

### ISSUE THREAD

**Issue by Threonine-Animist** [Chuyu-Team/Dism-Multi-language#708]
1.在每一项上添加一个右键菜单“仅清理该项”
2.允许“全选/全不选”
3.在选择一个组时，将所有警告移至同一个对话框而不是弹出一堆对话框
4.在有风险的清理项被选中时，将清理按钮变为红色
5.同#670

**Comment by MouriNaruto** [comment]
嗯……让我回复下

1. 仅清理该项可以做到，你可以全不选，然后勾选你要清理的即可，调试程序的时候是这样做的
2. 全不选复选框在空间回收已经存在，全选虽然没有，但点击类型（例如 过期文件）旁边的复选框也是可以多选的，就是多点几次鼠标（按现在 Dism++ 所有的规则数量来看，点击次数在 10 以内）
![image](https://user-images.githubusercontent.com/10867563/63648349-2ea79300-c761-11e9-88cd-d09c6b84772b.png)
3. 这个建议记下
4. 这个建议记下
5. 建议已经收到（因为问题已存档）

**Comment by MouriNaruto** [comment]
已存档 #707
