### ISSUE TITLE
win7-X64添加驱动时出现“拒绝访问”错误

### ISSUE THREAD

**Issue by babyface2018** [Chuyu-Team/Dism-Multi-language#71]
win7-X64添加驱动时出现“拒绝访问”错误
![cj1b3kx0wxlgb93z3oy8265](https://cloud.githubusercontent.com/assets/28137142/25520142/62fadc6a-2c2d-11e7-8b13-e11f1db4c694.png)

**Comment by babyface2018** [comment]
使用老版本Dism++10.1.7.1时无此问题，能够顺利添加驱动。

**Comment by mingkuang-Chuyu** [comment]
收到…… 5-7 节后回来我来看看，谢谢。

**Comment by mingkuang-Chuyu** [comment]
Hi，没发现此问题啊……

**Comment by mingkuang-Chuyu** [comment]
暂时关闭此问题，如果能复现次问题可以重新打开此问题
