### ISSUE TITLE
能不能加上APPX 重装?

### ISSUE THREAD

**Issue by imapx2** [Chuyu-Team/Dism-Multi-language#712]
Diss++的 Appx 管理 ...删除预装应用后...能否加入重装功能..???

**Comment by MouriNaruto** [comment]
建议收到，虽然暂时还不知道该怎么实现
因为微软并没有提供从商店下载特定应用的公开接口

**Comment by 200514xwl** [comment]
Get-AppxPackage -AllUsers| Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}

**Comment by MouriNaruto** [comment]
@200514xwl 这个只是重新注册 AppX 而已（可以解决一些问题，但是感觉和题主说的不符，谁知道删除预装应用是开始菜单里面的删除还是用 Dism 命令行做的删除），如果你要真重装的话，还是需要去商店下载的……

**Comment by imapx2** [comment]
是用用Dism完全删除的.....分别在三台不同的PC试了用PowerShell 方法似乎重装不了..

**Comment by sanguog** [comment]
我也需要，拜托啦

**Comment by mingkuang-Chuyu** [comment]
自己升级系统解决吧。既然你要删除 为什么你要删除的那么彻底？

如果你保留应用商店，那么他么都可以重新安装。
