### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by yaoqs** [Chuyu-Team/Dism-Multi-language#713]
网站无法打开https://www.chuyu.me/
>
                                            403 Forbidden
-----------------------------------------
                                                 nginx

**Comment by MouriNaruto** [comment]
因四部委检查，为了减少不必要的麻烦，鸭子在九月之前选择暂时把网站下线

**Comment by yaoqs** [comment]
收到，明白

**Comment by MouriNaruto** [comment]
请转到 #717
