### ISSUE TITLE
希望优化的地方

### ISSUE THREAD

**Issue by 1820xwl** [Chuyu-Team/Dism-Multi-language#714]
1.清理的时候界面无法操作

2.官网进去报错，QQ群也满人，不知道在哪下载最新版本

3.预览版安装后桌面右下角有水印，希望在系统优化中添加删除桌面水印功能

4.系统更新后，部分设置被重置

5.添加登录界面壁纸切换

....

**Comment by 1820xwl** [comment]
6.在可选功能里，建议添加关键词搜索

**Comment by 1820xwl** [comment]
7.强制使Defender与第三方杀毒软件共存...

**Comment by MouriNaruto** [comment]
1. 设计原因，为了不让用户在清理时在当前映像乱点
2. QQ 群，有多个，当群满的时候，可以换另一个群
3. 如果能通过简单的修改注册表做到，不需要第三方工具，则请直接发 PR 贡献规则
4. 请说的详细一些
5. 请提供 PR
6. 这个建议收下了
7. 这个是微软的策略，除非你的安全软件没有注册入 Windows 安全中心，否则做不到

**Comment by bill2431971** [comment]
因不是什麼大問題所以借用1820xwl大大的地方反應一下，
報錯的郵箱似乎有問題能給個可用的嗎?
另外想回報一下說明文件部分能補充一下部署功能方面的說明嗎?
謝謝。

**Comment by mingkuang-Chuyu** [comment]
@bill2431971 可以在这里说明。
