### ISSUE TITLE
Dism++ 官网镜像 (Dism++ official website mirror)

### ISSUE THREAD

**Issue by MouriNaruto** [Chuyu-Team/Dism-Multi-language#717]
## 最新稳定版 (Latest stable version) 
- [Dism++ 10.1.1000.100 (2019-6-7)](http://cdn.chuyu.me/Dism++10.1.1000.100_2d2bf466baca088c4b35248f5a7316f4e00cac0b.zip)

## 文档 (Documents)
- [更新日志 (Update history)](https://github.com/Chuyu-Team/Dism-Multi-language/blob/master/UpdateHistory.md)
- [其他文档 (Other documents)](https://github.com/Chuyu-Team/Dism-Multi-language/tree/master/www.chuyu.me/zh-Hans/library)
- [已经收到的建议 (Feature wishlist)](https://github.com/Chuyu-Team/Dism-Multi-language/issues/707)
- [可以由社区进行贡献的内容 (Contributor needed)](https://github.com/Chuyu-Team/Dism-Multi-language/issues?q=is:open%20is:issue%20label:%22Contributor%20Needed%20(PR%20%E5%8B%87%E8%80%85%E6%8B%9B%E5%8B%9F)%22)

## 联系方式 (Contact us)
- QQ 群 (QQ Group)
  - [200783396](http://shang.qq.com/wpa/qunwpa?idkey=07a04c095aee1e31f54b82ba98499a5b49aa10185f975946243ba68e0134a34e)
  - [282276394](http://shang.qq.com/wpa/qunwpa?idkey=7ca055997a5e30da11c5ad500bbb31cc66aa4f01bd27404d58568d1dbd32e48e)
- 电子邮件 (E-mail)
  - [mingkuang@live.com](mailto:mingkuang@live.com)

初雨团队 (Chuyu Team)

**Comment by woytu** [comment]
咋不使用GitHub pages

**Comment by MouriNaruto** [comment]
GitHub Pages 放的应该是正式官网，既然是临时的，那么 Issue 比较方便，而且也不用做复杂的布局什么的 @woytu

**Comment by caspertone2003** [comment]
chuyu.com is working now
Thanks

**Comment by Trumeet** [comment]
服务器放国内么... 凄凄惨惨（

**Comment by MouriNaruto** [comment]
@Trumeet 毕竟……用了国内的 CDN 就得备案……然后花大力气备了案后……麻烦的事情还在后头……

**Comment by mingkuang-Chuyu** [comment]
现在已经恢复，关闭了。
