### ISSUE TITLE
清理过期驱动一直失败

### ISSUE THREAD

**Issue by wanrufang** [Chuyu-Team/Dism-Multi-language#718]
系统是 最新的win10专业版64位，dism++用的也是64位
高级模式里清理过期驱动一直显示出错

**Comment by mingkuang-Chuyu** [comment]
应该是intel驱动的问题，出现了误杀。这个问题需要详细的远程……要不然无法解决。

**Comment by mzthn** [comment]
C:\Windows\System32\DriverStore\FileRepository\hdbusext.inf_amd64_aff21bee976fe510\
一样的问题，这个清不掉

**Comment by TurnOffNOD** [comment]
一样的问题，不过应该是只有1个或者几个文件的问题：原来“过期驱动”有650+MB，清理了之后尽管过期驱动清理显示“出错”，但是再次扫描只剩下488KB了。

**Comment by DustinWin** [comment]
Win10 19042.662，一样的问题。Dism++版本：10.1.1001.10

**Comment by mingkuang-Chuyu** [comment]
重复问题

https://github.com/Chuyu-Team/Dism-Multi-language/issues/848

其实这个问题不严重，因为出错并不会阻断清理，能清理的已经清理了。
