### ISSUE TITLE
updates are missing

### ISSUE THREAD

**Issue by YamazakiRobert** [Chuyu-Team/Dism-Multi-language#72]
on the previous version i can find the updates for windows 10 rs2, but on the latest version i cant

**Comment by MouriNaruto** [comment]
I suggest you to provide the [Dism++ Folder]\Config\Dism++.log

**Comment by mingkuang-Chuyu** [comment]
The "Config\wsusscn2.cab" need update。
http://cdn.chuyu.me/files/wsusscn2_2017-04-28.cab
