### ISSUE TITLE
win10 系统更新

### ISSUE THREAD

**Issue by liao6964799** [Chuyu-Team/Dism-Multi-language#720]
win10 家庭中文版  系统更新选择哪项可以禁止更新？ 从不检查或者仅检查都可以？更新服务需要同时关闭吗

**Comment by pongfcnkl** [comment]
用hosts屏蔽*.windowsupdate.com试试

**Comment by mingkuang-Chuyu** [comment]
家庭版目前没有太好的办法，微软可能随时封杀。建议升级到专业版然后禁用。
