### ISSUE TITLE
使用Dism++对win7进行补丁集成

### ISSUE THREAD

**Issue by jackkke** [Chuyu-Team/Dism-Multi-language#722]
首先特别感谢作者！！！
我在使用过程当中，按照官方文档指示使用工具对win7iso文件进行补丁集成，当我把所有补丁都打好之后，一步步制作出“win7-new.iso”，满心欢喜装到虚拟机，在虚拟机里面我继续使用dism++工具检测更新，但是仍然出来了一些要更新的补丁，可是我在制作iso的时候，工具提示我的是所有补丁都已经打好，没有要打的补丁，然后我发现我之前打的补丁后面都写着**“安装挂起”**，是不是这个原因啊？那么我该怎么办呢？希望开发者能给提供一些解决思路。谢谢！
另外sut也非常好用，感谢诸位！！！

**Comment by mingkuang-Chuyu** [comment]
离线补丁本来就是不全的，另外Win7的新的堆栈更新安装后就会直接就会扫描不出补丁。

要解决此问题 你只能在线扫描安装补丁。

离线仅仅是一种补充，请不要认为能全……

**Comment by mingkuang-Chuyu** [comment]
至于安装挂起 无视即可，跟你的问题没有影响。
