### ISSUE TITLE
提示栏建议

### ISSUE THREAD

**Issue by worrywast** [Chuyu-Team/Dism-Multi-language#723]
建议提示栏增大，这样更加直观，避免看不到进度
特别是初次使用人员
如下图，空白位置是否可以直接拉满
![WechatIMG961](https://user-images.githubusercontent.com/53715791/65399954-13788380-ddf2-11e9-9ffd-079fe7f15801.jpeg)

**Comment by MouriNaruto** [comment]
这部分和浏览器的标签栏差不多，Dism++ 支持多映像同时处理

**Comment by mingkuang-Chuyu** [comment]
故意这样设计的……支持多镜像处理
