### ISSUE TITLE
建议增加功能：禁用开始菜单的Bing web搜索结果

### ISSUE THREAD

**Issue by hhelibeb** [Chuyu-Team/Dism-Multi-language#726]
对应的配置项，
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Search]
--将以下两个DWORD键的值更改为0
BingSearchEnabled
CortanaConsent

这个应该没人提过吧，先占个坑

**Comment by liuxilu** [comment]
提醒：这样会把小娜关掉

**Comment by whitepoplars** [comment]
现在按照这个做法已经关不了亲测

**Comment by mingkuang-Chuyu** [comment]
先关了吧……有什么好的方法再说……
