### ISSUE TITLE
Registry Transaction Logs

### ISSUE THREAD

**Issue by kvnsmmm** [Chuyu-Team/Dism-Multi-language#727]
Please add cleans Registry Transaction Log.

-**Registry Transaction Logs (.LOG)**
*.LOG
*.LOG1
*.LOG2

-**Transactional Registry Transaction Logs (.TxR)**
Transactional registry logs use the Common Log File Sytstem (CLFS) format. The logs are stored to files of the form **<hive><GUID>.TxR.<number>.regtrans-ms**. For user hives these files are stored in the same directory as the hive and are cleared on user logout. However, for system hives logs are stored in %SystemRoot%\System32\config\TxR, and the logs are not automatically cleared.

-**Registry Backups**
Windows includes a simple mechanism to backup system registry hives periodically. The hives are backed up with a scheduled task called RegIdleBackup, which is scheduled to run every 10 days by default. Backed up hives are stored to **%SystemRoot%\System32\config\RegBack**. Only the most recent backup is stored in this location. This can be useful for investigating recent activity on a system.

MORE INFO
https://www.fireeye.com/blog/threat-research/2019/01/digging-up-the-past-windows-registry-forensics-revisited.html

**Comment by mingkuang-Chuyu** [comment]
Deleting these files will damage machine registry files in certain special states.
