### ISSUE TITLE
Tracing Keys cleans

### ISSUE THREAD

**Issue by kvnsmmm** [Chuyu-Team/Dism-Multi-language#728]
All tracing keys are located in HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Tracing

These keys are deleted by Malwarebytes' AdwCleaner. They claim that malware sometimes target these keys and they can safely be removed.

**Comment by mingkuang-Chuyu** [comment]
Sorry, Dism++ has no registry cleanup.
