### ISSUE TITLE
*.ETL files

### ISSUE THREAD

**Issue by kvnsmmm** [Chuyu-Team/Dism-Multi-language#729]
Please add cleans *.ETL files. 

An ETL file is a log file created by Microsoft Tracelog, a program that creates logs using the events from the kernel in Microsoft operating systems. It contains trace messages that have been generated during trace sessions, such as disk accesses or page faults. ETL files are used to log high-frequency events while tracking the performance of an operating system.

**Comment by mingkuang-Chuyu** [comment]
由于没有人提供实现，因此关闭。
