### ISSUE TITLE
修复镜像时提示找不到源，请到“详细设置中添加本地源”，然而详细设置中没有这个选项。

### ISSUE THREAD

**Issue by AndyX-Net** [Chuyu-Team/Dism-Multi-language#73]
修复镜像时提示找不到源，请到“详细设置中添加本地源”，然而详细设置中没有这个选项。

程序版本：10.1.27.1 UEFI 专家模式
系统： Windows 10 Rs2 15063.138

如图：http://chuantu.biz/t5/75/1493469032x2728287112.jpg

**Comment by mingkuang-Chuyu** [comment]
这个是描述问题，暂时无视吧，选项曾经有过，后来删除了。

另外 没事不用想着修复，这个功能就是这样的……鸡肋，几乎修复不了问题

最后Windows 10本身就是扫描不通过的，所以你有什么问题反馈给微软吧，为什么不通过。

**Comment by AndyX-Net** [comment]
感谢回复。
