### ISSUE TITLE
More Cleanup Items

### ISSUE THREAD

**Issue by kvnsmmm** [Chuyu-Team/Dism-Multi-language#730]
DirectInput LOGS: DirectInput has an annoying habit of creating a key for every unique app run.
**HKEY_CURRENT_USER\Software\Microsoft\DirectInput**

WinSxS Folder Backup:
**C:\Windows\winsxs\Backup**

SoftwareDistribution LOGS:
**C:\Windows\SoftwareDistribution**
**C:\Windows\SoftwareDistribution\DataStore\DataStore.edb**
**C:\Windows\SoftwareDistribution\DataStore\Logs**

ElevatedDiagnostics LOGS:
**C:\Users\YOUR USERNAME\AppData\Local\ElevatedDiagnostics**

AppCompatCache:
**HKEY_LOCAL_MACHINE\SYSTEM\ControlSet002\Control\Session Manager\AppCompatCache" /v AppCompatCache**

AUDIO PROPERTIES LOGS:
**HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\LowRegistry\Audio\PolicyConfig\PropertyStore**

APP FLAGS LOGS:
**HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers**

Reliability Monitor LOGS:
**C:\ProgramData\Microsoft\RAC**

Windows Diagnostics Infrastructure LOGS:
**C:\Windows\System32\wdi**
**C:\Windows\SysWOW64\wdi**

Power Efficiency Diagnostics LOGS:
**C:\ProgramData\Microsoft\Windows\Power Efficiency Diagnostics**

**C:\Windows\AppCompat\Programs**

**C:\ProgramData\Microsoft\Network\Downloader\qmgr0.dat**

**C:\ProgramData\Microsoft\Network\Downloader\qmgr1.dat**

Removes from the device tree non present
- USB hubs
- USB mass storage devices
- USB Disk devices
- USB CDROM devices
- USB Floppy devices
- USB Storage Volumes
- USB WPD devices (Vista, Win7, Win8, Win10)

and their registry items under

**HKEY_LOCAL_MACHINE\SYSTEM\MountedDevices
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\UsbFlags
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceClasses
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\EMDMgmt
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\MountPoints2
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\MountPoints2\CPC\Volume
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\BitBucket\Volume**

**Comment by mingkuang-Chuyu** [comment]
主要是项目是存在的，另外一些我的电脑上是一个空文件。

最后那些注册表删除的太狠了，我觉得没有必要。
