### ISSUE TITLE
[不算bug的bug]DISM++无法修复vista引导

### ISSUE THREAD

**Issue by Threonine-Animist** [Chuyu-Team/Dism-Multi-language#732]
虽然9102年真的没人用vista了
但是DISM++在修复vista引导时会提示错误
或许可以禁用vista的引导修复

**Comment by mingkuang-Chuyu** [comment]
支持此功能，但是你必须在Windows 7 PE中修复，因为Dism++并不带Win7的 bcdboot。
我也不可能为了支持Vista而给所有人带一个没用的Win7 bcdboot 对吧？
