### ISSUE TITLE
备份系统  句柄无效

### ISSUE THREAD

**Issue by libisheng** [Chuyu-Team/Dism-Multi-language#733]
Dism++，程序版本: 10.1.1000.100，CBS抽象层: 10.1.1000.100，Host版本：10.0.18362.418
Microsoft Windows [版本 10.0.18363.418] 企业版  AMD64 

**备份系统总是句柄无效**

**Comment by libisheng** [comment]
[CBS.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/3760208/CBS.log)

[dism.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/3760213/dism.log)

**Comment by MouriNaruto** [comment]
这个需要 Dism++ 的日志文件，而不是 DISM 和 CBS 的

况且 Dism++ 完全不依赖 DISM 于是拿出 DISM 的日志也没用
CBS 的话，备份系统和 CBS 无关，CBS 主要是组件管理

你可以在备份系统的时候去掉卷影复制的勾也许能帮到你

**Comment by mingkuang-Chuyu** [comment]
这一般都是 onedrive导致的，需要Condig/Dism++.log

**Comment by million7355608** [comment]
> 这个需要Dism ++的日志文件，而不是DISM和CBS的
> 
> 况且Dism ++完全不依赖DISM于是拿出DISM的日志也没用
> CBS的话，备份系统和CBS无关，CBS主要是组件管理
> 
> 你可以在备份系统的时候去掉卷影复制的勾也许能帮到你

你好，我也遇到了一样的问题，而且备份时无法去掉卷影复制的勾，这是我的日志文件
[Dism++.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/4514958/Dism%2B%2B.log)

**Comment by mingkuang-Chuyu** [comment]
@million7355608  C:\Users\Administrator\AppData\Local\Google\Chrome\User Data\Default\Code Cache\js\0f1c2bdc4fc5a259_0

此文件损坏了，无法访问……

**Comment by mingkuang-Chuyu** [comment]
这种问题一般都是硬盘文件损坏导致的。先关闭吧。
