### ISSUE TITLE
10.1.1不识别VMware15.5映射虚拟磁盘的分区。（win10-64 1903 18362.418）（2019-11-8已解决）

### ISSUE THREAD

**Issue by cfansjh** [Chuyu-Team/Dism-Multi-language#734]
感谢提供如此精良实用的软件。

最近折腾虚拟机，希望dism++能够读写vmdk文件。使用VM自带的映射磁盘功能，映射出来的磁盘，不能被dism++识别。
DAEMON Tools和OSFMount等虚拟光驱软件虚拟的vmdk磁盘文件，dism++可以识别。但是这些虚拟光驱软件虚拟的vmdk文件经常出莫名其妙的问题，不稳定。dism++在释放系统镜像的过程中，容易出问题。

所以希望，dism++能够支持VM原生映射的虚拟磁盘分区，或者帮忙给出其他兼容性强的vmdk挂载软件（当然我们也可以在VM的虚拟机中操作磁盘，安装系统。更希望dism++具备此功能）。

系统挂载VM的虚拟磁盘后显示的盘符：
![dism2](https://user-images.githubusercontent.com/53043448/67380844-84f84d00-f5bd-11e9-9805-ced241c37dde.PNG)

dism++中显示的盘符：
![dism1](https://user-images.githubusercontent.com/53043448/67380868-8c1f5b00-f5bd-11e9-9b73-303851e7593e.PNG)

**Comment by MouriNaruto** [comment]
你需要在管理员权限的文件管理器上下文去挂载 vmdk
默认情况下是以标准用户的身份挂载的，管理员是看不到的，这是 Windows 的设计原因

**Comment by cfansjh** [comment]
问题解决，感谢您。
运行gpedit.msc，打开本地组策略编辑器：计算机配置->Windows设置->安全设置->本地策略->安全选项。将“用户帐户控制：以管理员批准模式运行所有管理员”改为禁用。重启即可。

**Comment by cfansjh** [comment]
> 你需要在管理员权限的文件管理器上下文去挂载 vmdk
> 默认情况下是以标准用户的身份挂载的，管理员是看不到的，这是 Windows 的设计原因

问题解决，感谢您。
运行gpedit.msc，打开本地组策略编辑器：计算机配置->Windows设置->安全设置->本地策略->安全选项。将“用户帐户控制：以管理员批准模式运行所有管理员”改为禁用。重启即可。
