### ISSUE TITLE
安装可选功能

### ISSUE THREAD

**Issue by vipmumu** [Chuyu-Team/Dism-Multi-language#735]
安装**可选功能**（不是程序和功能）时，跳出对话框：DISM++找不到安装源，如果需要开启.Net 3.5请挂载ISO然后继续。系统为联网状态。
DISM++版本：10.1.1000.100
系统版本：10.0.17763.805

**Comment by lychichem** [comment]
@vipmumu @MouriNaruto 我用dism命令行试过，这个问题的原因是下载的可选功能cab包名字不对…那些cab包必须叫微软设定的名字，只要改了名就不认的…
另外还有一点麻烦的是有的可选功能要安装依赖包，这时除了命名问题，安装顺序也很重要。此外，安装可选功能必须在安装更新之前否则可能会造成冲突，这点怎么提醒用户也是个问题

**Comment by lychichem** [comment]
所以问题就变成了怎么获取这些cab包的名称列表的问题。按目前已知的方法，要么去下微软的FoD包iso镜像去拿cab名，要么就只能从一个安装好的windows，把可选功能全部添加一遍，然后从softwaredistribution目录找cab包名了

**Comment by mingkuang-Chuyu** [comment]
这是微软固有现在，离线情况下无法通过网络自动搜寻。

在线处理时不受影响。如果有需要请自行寻找安装源，目前已知的，UUP ISO包中提供了这些文件。

**Comment by lychichem** [comment]
> 这是微软固有逻辑，离线情况下无法通过网络自动搜寻。
> 
> 在线处理时不受影响。如果有需要请自行寻找安装源，目前已知的，UUP ISO包中提供了这些文件。

提供了文件是不假，只是我当年测试的时候发现还必须文件名叫对了才行否则无法安装。具体每个可选功能本身的名称以及对应的包名可以在https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/features-on-demand-non-language-fod 和 https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/features-on-demand-language-fod 查看

**Comment by wzqvip** [comment]
恢复功能-修复受损的时候也是这样提示了，不清楚如何处理。
修复完系统引导后仍然无法启动，蓝屏提示0xc00000000000001
安装可选功能（不是程序和功能）时，跳出对话框：DISM++找不到安装源，如果需要开启.Net 3.5请挂载ISO然后继续。

**Comment by wzqvip** [comment]
复制多了，第三行是 跳出对话框：DISM++找不到安装源，如果需要开启.Net 3.5请挂载ISO然后继续。

**Comment by n-WN** [comment]
> 恢复功能-修复受损的时候也是这样提示了，不清楚如何处理。
> 修复完系统引导后仍然无法启动，蓝屏提示0xc00000000000001
> 安装可选功能（不是程序和功能）时，跳出对话框：DISM++找不到安装源，如果需要开启.Net 3.5请挂载ISO然后继续。

+1
