### ISSUE TITLE
小白请教一个关于防火墙与Windows Defender的问题

### ISSUE THREAD

**Issue by 672110619** [Chuyu-Team/Dism-Multi-language#736]
早前用用dism++优化系统的时候禁用了防火墙与Windows Defender，但是后来因为处理一个问题需要开启这两个东西。但是发现用软件关闭禁止后却还是没有办法开启。
在服务中找到“Windows Firewall”这个选项的时候它是灰色的（具体可以看后面上传的图片1），在控制面板中想要恢复也会提示“0x80070422”这个错误代码（具体可以看后面上传的图片2），找了很多办法都没办法修复这个问题，所以不知道这个问题应该如何进行解决~
希望大佬不要嫌弃小弟技术菜就嫌弃我5555

dism++版本：x64 10.1.1000.100
系统版本：因为中途升级了很多次，也不知道当时具体是哪个版本了…只能给出当前的信息，如下：
部署映像服务和管理工具
版本: 10.0.17763.771

映像版本: 10.0.17763.805

当前版本为:

当前版本 : Education

**Comment by Vulcankta** [comment]
我也同样遇到了类似问题，不过我的问题是无法用此软件禁用Windows Defender。

**Comment by Vulcankta** [comment]
我也同样遇到了类似问题，不过我的问题是无法用此软件禁用Windows Defender。

**Comment by mingkuang-Chuyu** [comment]
![image](https://user-images.githubusercontent.com/19919717/107342663-65d64500-6ab8-11eb-9f01-de29b44e4723.png)

重新改成 2 应该就好了。

但是我不记得Dism++有规则会修改这个……

**Comment by mingkuang-Chuyu** [comment]
@Vulcankta  你的问题是WD的自保导致的……
