### ISSUE TITLE
C:\Program Files\WindowsApps里的垃圾何时进行开发清理

### ISSUE THREAD

**Issue by isjame** [Chuyu-Team/Dism-Multi-language#738]
0.0
我用360粉碎机也碎不了

**Comment by MouriNaruto** [comment]
Windows 10 开始，WindowsApps 并不需要特意清理旧版本包，因为 AppX 的旧版本会在 Microsoft Store App 升级的时候自动删除。（Windows 8/8.1 需要，但只需要用第三方工具清理一次之后系统就能自动清理）

当然这个目录是不应该动的，尤其是近几年的 Windows 10 更新把越来越多的需要滚动更新的系统组件放在了这个目录里以让 Microsoft Store App 自动升级。

举个例子，现在的 Windows 10 的系统语言包就安装在这个目录里面。

Dism++ 其实是有这个目录的清理功能的，只是不够稳定。而且策略激进，如果你操作离线映像的话，那个功能相当于移除全部非系统级 AppX。

毛利

**Comment by mingkuang-Chuyu** [comment]
一直支持此功能，只是这个功能功能可能导致appx损坏（出错i  概率虽然不高，但是这事情怕说不清楚）。如果想使用此功能，自行去专家模式使用，另外如果不幸遇到了问题，我们基本也不能解决。
