### ISSUE TITLE
DISM++X64 10.1.27.1  状态栏右侧图标丢失

### ISSUE THREAD

**Issue by qwetrouble** [Chuyu-Team/Dism-Multi-language#74]
空间回收，缓存文件，缩略图缓存，重启explore后，状态栏右侧部分图标丢失，无法通过系统自带的打开关闭图标功能恢复，也不能重启恢复，需要在任务管理器里面，多次强制关闭应用后，重新打开应用图标才能出现

系统win10专业版，1703，15063.250，uefi+gpt

**Comment by mingkuang-Chuyu** [comment]
谢谢，这个问题确实存在。暂时可以手动在任务管理器里重启Explorer解决

**Comment by mingkuang-Chuyu** [comment]
已经解决，Dism++测试版 10.1.2000.90 已经修复此问题，麻烦你抽空帮忙验证此问题，谢谢。
