### ISSUE TITLE
删除疑似损坏的appx时提示找不到包

### ISSUE THREAD

**Issue by wangruoyao** [Chuyu-Team/Dism-Multi-language#741]
开始菜单里多出了一项ms-resource：appname/text，拖到桌面看到其目标是windows.holographicfirstrun，在appx管理中看到该项目疑似损坏，选择删除时提示找不到包。

**Comment by mingkuang-Chuyu** [comment]
正常的，这个是因为微软接口不支持删除，所以无法删除。
