### ISSUE TITLE
Dism++增加TEMP路径的设置选项。

### ISSUE THREAD

**Issue by free68** [Chuyu-Team/Dism-Multi-language#743]
请﻿Dism++增加TEMP路径的设置选项。因为将Dism++放置在移动设备/硬盘中使用，TEMP中的临时文件会很大，特别是添加更新补丁时，不仅占用空间而且还因USB等接口的数据速度降低了作业速度，望增加设置能够将其设置到其他较快且空间较大的位置的选项。谢谢！！！

**Comment by mingkuang-Chuyu** [comment]
http://www.chuyu.me/zh-Hans/Document.html?file=Dism++Library/%E9%9A%90%E8%97%8F%E5%8A%9F%E8%83%BD.md

一直支持此功能
