### ISSUE TITLE
Windows 10 1909 更新重复安装问题

### ISSUE THREAD

**Issue by SakuraNeko** [Chuyu-Team/Dism-Multi-language#747]
现在有一个问题，“通过支持包实现基于X64的系统的Windows 10版本1909功能更新2019-11-2019/11/03”在本软件中会**重复**安装，其表现为：完成安装后 再次进行更新扫描 其补丁内容会在列表中重新出现，并可以进行安装。
目标系统已为升级后的1909版本。

**其他信息**

- OS：Windows 10 Pro 1909 x64  10.0.18363.476
- CPU：Intel Core 6th
- RAM：8GB

**Comment by tigeruncle111** [comment]
这个，会不会跟微软重复同送补丁的BUG有一定关系呢？

**Comment by mingkuang-Chuyu** [comment]
那就再安装一遍，看看是否真的重复安装。

**Comment by mingkuang-Chuyu** [comment]
已经确认，Bug。

**Comment by mingkuang-Chuyu** [comment]
[Dism++Beta 10.1.2002.110.zip](https://github.com/Chuyu-Team/Dism-Multi-language/files/4085010/Dism%2B%2BBeta.10.1.2002.110.zip)

感谢  Dism++Beta 10.1.2002.110 已经解决此问题。

**Comment by SakuraNeko** [comment]
已经确认问题是因为这两个版本均未搭载 wsusscn3.cab ，现在已经解决。

**Comment by SakuraNeko** [comment]
已经验证确认#747所述问题在version Beta 10.1.2002.110（2020-01-20）被解决。

**Comment by mingkuang-Chuyu** [comment]
感谢
