### ISSUE TITLE
清理winsxs出错，详细信息显示错误码 0x800F0817

### ISSUE THREAD

**Issue by c00134744** [Chuyu-Team/Dism-Multi-language#748]
﻿If you are not a Chinese, please use translator.

如果是清理规则、优化规则、多语言改善的提议，建议直接发布 Pull Request 直接为 
Dism++ 添加，不明白的可以直接通过邮箱或者 QQ 群直接联系鸭子；当然你发 Issue 也
没问题，只是开发者们没法处理，需要等待有志者帮你发 Pull Request 了。

如果是除此之外的问题，发 Issues 即可。

发 Issue 需要注意你当前使用的环境信息描述清楚，譬如 Dism++ 的版本、放置路径和截
图，Windows 的版本（完整版本，例如 10.0.18362.10014）、SKU（例如 专业版）、架构
（例如 AMD64），当然如果能提供 Dism++ 目录下 Config 内的日志文件和 Windows\Logs
目录内有关 CBS 和 DISM 的相关日志我们会更加高兴。

发布问题的时候请删掉以上内容，我们也不通过格式来限制你们。

**Comment by mingkuang-Chuyu** [comment]
请重启系统后在来一次，如果是挂载的系统，那么可以先安装到虚拟机，应用补丁后继续。。

**Comment by mingkuang-Chuyu** [comment]
固有逻辑
