### ISSUE TITLE
禁用NET4.7安装3.5后 无法再次启用！for win10 server2019

### ISSUE THREAD

**Issue by lirener** [Chuyu-Team/Dism-Multi-language#749]
禁用NET4.7安装3.5后 无法再次启用！for win10 server2019

系统版本：windows server 2019
禁用时软件版本：Dism++10.1.7.1x64
更新版本：Dism10.1.1000.100
仍然不行
![QQ截图20191211010919](https://user-images.githubusercontent.com/19354130/70551939-725cc600-1bb3-11ea-8480-e12b9b135401.jpg)

**Comment by lirener** [comment]
禁用NET4.7后导致server自带window功能打不开
![禁用NET4 7后导致server自带window功能打不开](https://user-images.githubusercontent.com/19354130/70552321-147cae00-1bb4-11ea-8b57-775d284c694e.jpg)

根据提示安装4.0版本有文字 但是仍然无法打开
原版本已经不小心用DISM++的查查功能删除 无法通过启用恢复
试图通过 本地ISO解压安装 但是无法找到netfx4 源
使用netfx3源文件夹导入 本地源 仍然报错

**Comment by lirener** [comment]
通过命令【dism /online  /Get-Features >C:\Users\Administrator\Desktop\1.txt】
查看 结果如下

功能名称 : NetFx4ServerFeatures
状态 : 已启用

功能名称 : NetFx4
状态 : 禁用已删除的负载

功能名称 : NetFx4Extended-ASPNET45
状态 : 禁用已删除的负载

**Comment by mingkuang-Chuyu** [comment]
其实……你本地源的地址错了……不用 “” 包裹……

不过你说的问题我大概明白了，因为你删除了NetFx4，所以就导致启用Windows功能废掉了。

另外从你的信息来看你并非禁用 NetFx4，而是直接删除了……

**Comment by mingkuang-Chuyu** [comment]
请认真添加 源地址，需要添加 “”  包裹。
