### ISSUE TITLE
管理员误解了我的意思……我之前说

### ISSUE THREAD

**Issue by Windypao** [Chuyu-Team/Dism-Multi-language#75]
建议WIN7模式下系统更新增加只显示IE11、.NET 4.6.2和最近期积累更新

我意思是增加一个仅仅显示IE11 和 最近积累更新的功能，过滤掉其他所有过期积累和零散小补丁

因为这些零散小补丁，在打完IE11 .NET4.6.2和最近积累更新后都已经不起作用了（硬打要么打不上，要么打上去也无效），没有必要再打零散补丁了

您误解成，只是过滤掉过期的积累更新

我意思是增加一个功能
举例：可以叫“仅显示积累更新”，选中后自动过滤掉其他所有零散补丁和过期积累更新，除IE11

**Comment by mingkuang-Chuyu** [comment]
不会增加此选择，另外累计更新也不是全部。并不是说累计更新装了就能不安装其他所有更新了……

建议你手动操作吧……谢谢支持

**Comment by Roger-WIN** [comment]
其实我想说，为什么列表里没有“Convenience rollup update”呢？比如 Win7 的 KB3125574，这样不就可以少打很多零散的小补丁了吗？日后要是这个补丁更新了，直接取代旧版本就好了嘛。

**Comment by mingkuang-Chuyu** [comment]
以前Dism++添加过这个更新，但是发现这个补丁问题太多 才撤回的。具体也可以参考下Dism++更新日志，某次升级提到了这个。

**Comment by Windypao** [comment]
其实这种类型补丁出问题都是由于用户使用了修改系统文件的激活方式导致的

像WindowsLoader 改的是bootmgr引导文件，打了这类补丁都会引起无限重启，要F8关闭签名检查
Clew WGA改的是系统里面的文件，打了后会蓝屏，F8也没用

只有kms类（有180天期限）、MAK KEY的激活才能打这类补丁

很多用户，他用的都是第三方GHO系统，可能这些系统默认情况下就被激活，他也不知道用的啥激活

目前所有 积累安全更新 都是这样的，所以我才说 应该分类出来，零散区显示零散。积累区就显示最新几个

然后检测下他系统是否已经激活，是否是kms、mak激活，如果不是就不让他打这类补丁

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: mingkuang<mailto:notifications@github.com>
发送时间: 2017年7月12日 PM 12:54
收件人: Chuyu-Team/Dism-Multi-language<mailto:Dism-Multi-language@noreply.github.com>
抄送: Windypao<mailto:windypao@live.cn>; Author<mailto:author@noreply.github.com>
主题: Re: [Chuyu-Team/Dism-Multi-language] 管理员误解了我的意思……我之前说 (#75)


以前Dism++添加过这个更新，但是发现这个补丁问题太多 才撤回的。具体也可以参考下Dism++更新日志，某次升级提到了这个。

―

**Comment by mingkuang-Chuyu** [comment]
建议你先看看Dism++的更新日志，你说的完全就对不上号。

我发现的是这个补丁组件应用不全，安装后 不少漏洞根本没有堵上，这个补丁奇大，但是实际应用到系统却是极少一部分。所以Dism++砍掉了这补丁。还是直接安装补丁来的愉快。
