### ISSUE TITLE
扫描更新不能用问题

### ISSUE THREAD

**Issue by saber-kings** [Chuyu-Team/Dism-Multi-language#750]
win10 1909版本使用Dism++扫描更新，不能用了：
![image](https://user-images.githubusercontent.com/50172554/71414820-b6f85f00-2693-11ea-8a5a-3eacf8daca66.png)
。

**Comment by xmmo** [comment]
同样问题，chuyu大神有什么解决方法么？

**Comment by 2267184123** [comment]
+1 我用的是Win8.1

**Comment by Matthew-Wai** [comment]
I have the same problem. I use Windows 10 Version 1903. The "wsusscn2.cab" file is missing from the zipped files downloaded from the following:
https://www.majorgeeks.com/mg/get/dism,1.html
https://www.majorgeeks.com/mg/getmirror/dism,1.html
https://www.majorgeeks.com/mg/getmirror/dism,2.html

**Comment by Matthew-Wai** [comment]
> 同样问题，chuyu大神有什么解决方法么？

Download the following "wsusscn2.cab" file and put it into the "Config" folder.
https://1drv.ms/u/s!Au7hVmQX8-gVgRx549b7S-GNalT6?e=gJK8kz

**Comment by mingkuang-Chuyu** [comment]
您好，由于数据库不在分发，因此会存在此问题。
我把数据放在这里，大家可以自行下载。
https://github.com/Chuyu-Team/Dism-Multi-language/releases/latest

**Comment by gyakkun** [comment]
> 您好，由于数据库不在分发，因此会存在此问题。
> 我把数据放在这里，大家可以自行下载。
> https://github.com/Chuyu-Team/Dism-Multi-language/releases/latest

请问是否方便透露是出于何种原因不再分发数据库? 是否能考虑兼容微软官方公开提供的完整wsusscn2.cab? (https://docs.microsoft.com/zh-cn/archive/blogs/mempson/wsusscn2-cab-manual-download-location)

**Comment by mingkuang-Chuyu** [comment]
不考虑，另外微软的 wsusscn2.cab 何来完整一说，明明只有安全更新……

不在分发主要原因是 很多人 总是不停的重复下载库，因为2%的人消耗的80%的流量，所以就砍了。
其实我也郁闷，为啥总是不停的通过Dism++自动更新下载，难道他每次都重新解压 从一个全新的开始……

**Comment by 475310942** [comment]
https://github.com/Chuyu-Team/Dism-Multi-language/releases/latest下载速度只有十多k而且每次下到19M就下载失败了。

**Comment by mingkuang-Chuyu** [comment]
> [https://github.com/Chuyu-Team/Dism-Multi-language/releases/latest下载速度只有十多k而且每次下到19M就下载失败了。](https://github.com/Chuyu-Team/Dism-Multi-language/releases/latest%E4%B8%8B%E8%BD%BD%E9%80%9F%E5%BA%A6%E5%8F%AA%E6%9C%89%E5%8D%81%E5%A4%9Ak%E8%80%8C%E4%B8%94%E6%AF%8F%E6%AC%A1%E4%B8%8B%E5%88%B019M%E5%B0%B1%E4%B8%8B%E8%BD%BD%E5%A4%B1%E8%B4%A5%E4%BA%86%E3%80%82)

建议你灵魂出境试试……
