### ISSUE TITLE
Windows 10 20H1 boot issue

### ISSUE THREAD

**Issue by EcoVolt3306** [Chuyu-Team/Dism-Multi-language#755]
﻿If you are not a Chinese, please use translator.

如果是清理规则、优化规则、多语言改善的提议，建议直接发布 Pull Request 直接为 
Dism++ 添加，不明白的可以直接通过邮箱或者 QQ 群直接联系鸭子；当然你发 Issue 也
没问题，只是开发者们没法处理，需要等待有志者帮你发 Pull Request 了。

如果是除此之外的问题，发 Issues 即可。

发 Issue 需要注意你当前使用的环境信息描述清楚，譬如 Dism++ 的版本、放置路径和截
图，Windows 的版本（完整版本，例如 10.0.18362.10014）、SKU（例如 专业版）、架构
（例如 AMD64），当然如果能提供 Dism++ 目录下 Config 内的日志文件和 Windows\Logs
目录内有关 CBS 和 DISM 的相关日志我们会更加高兴。

发布问题的时候请删掉以上内容，我们也不通过格式来限制你们。
---------------------------------------------------------------

您好，我是韩国人，所以我用了翻译。
我最近安装并使用了Windows 10 20H1。
使用Dism ++程序进行清洁时，
替换的WinSxS程序集（非常慢）
当您选择此项目并进行处理时
它只是保持加载而无需引导。
在其他主题中未发现任何问题。
希望您能复习此部分。
Dism版本是10.1.1000.100 / Windows 10内部版本是19041.21
如果您需要与我联系，请联系seung9721@naver.com。
谢谢你

Hello, I'm Korean so I used a translator.
I've recently installed and used Windows 10 20H1.
When cleaning with the Dism ++ program,
Replaced WinSxS assemblies (very slow)
When I select this item and work on it
It just keeps loading without booting.
No issues were found in other topics.
I hope you will review this section.
Dism version is 10.1.1000.100 / Windows 10 build version is 19041.21
If you need to contact me, please contact seung9721@naver.com.
Thank you.

**Comment by mingkuang-Chuyu** [comment]
Sorry, I didn't understand your intention.

**Comment by lychichem** [comment]
@EcoVolt3306 Microsoft has confirmed a bug in build 19041.21, which happens after users used `dism /cleanup-image /startcomponentcleanup`. When this bug happens, users fails to boot their device. Microsoft has published build 19041.84 and build 19041.113 to fix this problem. Please update to latest insider build.

**Comment by mingkuang-Chuyu** [comment]
@lychichem Thanks.
