### ISSUE TITLE
处理另存过win10_1909_18363.535映象后应用市场和自带邮件是EN版了

### ISSUE THREAD

**Issue by qingfengxieying** [Chuyu-Team/Dism-Multi-language#756]
最新DISM++处理优化另存过win10_1909_18363.535的简体中文企业版映象后，装在另外电脑上后应用市场和自带邮件是EN版了。不知道是不是只有我一个人出现这个问题？
谢谢。

**Comment by mingkuang-Chuyu** [comment]
请把问题描述清楚。。处理了什么优化了什么。
