### ISSUE TITLE
Win7 不能做更新扫描，是否和微软停止维护有关，但是官方windows update可用

### ISSUE THREAD

**Issue by zjqzero** [Chuyu-Team/Dism-Multi-language#757]
![image](https://user-images.githubusercontent.com/12052416/72676956-eacb7680-3ad1-11ea-93d7-a97bbdefb0fc.png)

**Comment by mingkuang-Chuyu** [comment]
无效反馈，参考 https://github.com/Chuyu-Team/Dism-Multi-language/releases/latest
