### ISSUE TITLE
重启explorer会导致资源管理器错位

### ISSUE THREAD

**Issue by 2370177068** [Chuyu-Team/Dism-Multi-language#758]
DISM++x64 10.1.1001.10 UEFI FIRMWARE
空间回收：清理缩略图缓存时需要重启explorer，会导致资源管理器错位，同时错位的资源管理器不能用tab+alt切换窗口
放置路径：C:\Program Files (x86)\1MYAPP\Dism++

![0KP 5B90D 2Q}1)K`PHV V6](https://user-images.githubusercontent.com/51988982/73268836-a13c0380-4216-11ea-8757-40bfc166f430.png)

![`~ID B0`ZQSRFWHHK9~2GK1](https://user-images.githubusercontent.com/51988982/73268838-a1d49a00-4216-11ea-8c33-ddafee58f1a0.png)

![9SK4MTCO_75Q6@KE28ZV)@P](https://user-images.githubusercontent.com/51988982/73268839-a26d3080-4216-11ea-90a9-b23e607e229a.png)

![0V)B3NNK`H5WWHA4E7Y@P5V](https://user-images.githubusercontent.com/51988982/73268840-a26d3080-4216-11ea-80c9-23a0cdd7e79e.png)

[Config.zip](https://github.com/Chuyu-Team/Dism-Multi-language/files/4122630/Config.zip)

[Logs.zip](https://github.com/Chuyu-Team/Dism-Multi-language/files/4122631/Logs.zip)

附件也上传至蓝奏云https://www.lanzous.com/i8wepmb

**Comment by mingkuang-Chuyu** [comment]
一定概率会这样，这时再次使用explorer缓存清理功能即可。
