### ISSUE TITLE
dism++程序与功能中的 Windows功能 无法列出功能，显示为空白

### ISSUE THREAD

**Issue by sch-lda** [Chuyu-Team/Dism-Multi-language#759]
dism++程序与功能中的 Windows功能 无法列出功能，显示为空白
dism++其他功能未见异常
dism++ x64 10.1.1001.10 UEFI
windows 1909 内部版本18363.592 专业版 AMD64
系统盘盘符为C
Dism++ 放在D:\Dism++  目录中没有其他软件的文件
控制面板中添加功能显示正常
此问题出现于Windows10从1903版本升级至1909版本之后
dism++的上一个版本也存在此问题，确定不是由dism++更新 后导致的

截图（dism++问题）：
![1](https://user-images.githubusercontent.com/54973190/73335268-cf1e5800-42a9-11ea-81d8-d2cf1cf740e1.PNG)
![2](https://user-images.githubusercontent.com/54973190/73335275-d3e30c00-42a9-11ea-9674-dd34261bac69.PNG)

截图（Windows版本）：
![3](https://user-images.githubusercontent.com/54973190/73335711-15c08200-42ab-11ea-8f8e-bac2f1844ff3.PNG)
![4](https://user-images.githubusercontent.com/54973190/73335801-4f918880-42ab-11ea-92b5-ec379d2dc07f.PNG)

日志文件：
[CBS.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/4126655/CBS.log)
[dism.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/4126660/dism.log)
[Dism++.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/4126662/Dism%2B%2B.log)

**Comment by Auce** [comment]
我也碰到这个问题，看这里。
https://github.com/Chuyu-Team/Dism-Multi-language/releases

**Comment by mingkuang-Chuyu** [comment]
微软自己的Windows功能能正常显示吗？

**Comment by sch-lda** [comment]
微软自己的Windows功能能正常显示
谢谢，今日打开dism++，提示更新，更新后功能就能正常显示了
