### ISSUE TITLE
关于Windows更新管理问题

### ISSUE THREAD

**Issue by 13567919504** [Chuyu-Team/Dism-Multi-language#766]
这个我下了两三遍了，结果还是在，求解决
![image](https://user-images.githubusercontent.com/59106659/74597823-8683de80-50a0-11ea-983e-88391617c877.png)

**Comment by mingkuang-Chuyu** [comment]
重复反馈

https://github.com/Chuyu-Team/Dism-Multi-language/issues/747

解决方案在内部
