### ISSUE TITLE
系统优化后右键菜单响应慢

### ISSUE THREAD

**Issue by zslll** [Chuyu-Team/Dism-Multi-language#768]
win10.1909(18363.657)      dism++x64 10.1.1001.10 bios Firmware
系统优化后（忘了优化的项），桌面鼠标右键，需要10s才能显示右键菜单，请问是哪一项优化的后果？可以怎么调整？
![2020-02-28_131424](https://user-images.githubusercontent.com/33146677/75513333-89cb8280-5a2f-11ea-8d8c-788d67d2ab5a.jpg)
建议增加恢复初始功能

**Comment by mingkuang-Chuyu** [comment]
Intel显卡菜单的Bug，你把Intel显卡菜单 禁用就可以了。
