### ISSUE TITLE
开始备份后，无法取消任务

### ISSUE THREAD

**Issue by ghmole** [Chuyu-Team/Dism-Multi-language#769]
win10
dism++64  10.1.1001.10
开始系统备份后，想停止，无法取消任务，一直等待，资源管理器显示一直读硬盘

**Comment by mingkuang-Chuyu** [comment]
此功能取决与系统，Dism++只向系统发出取消请求。

某些极端情况，取消将非常迟钝，但是程序需要等待系统返回，如果你等不下去，可以考虑强行杀死Dism++。

但是数据安全将无法保证。
