### ISSUE TITLE
建议添加多语言选项

### ISSUE THREAD

**Issue by lixuy** [Chuyu-Team/Dism-Multi-language#77]
目前更新会自动把其他语言删掉 也不能指定使用语言
另外在一些OEM定制的re环境里会适配为英文界面，如果有了多语言选项就应该能解决这个尴尬

**Comment by lixuy** [comment]
其实我是代日本的小姐姐反馈的

**Comment by EMLVIRUS** [comment]
这需要在本地保留所有locale的XML，我不确定鸭神是否愿意这样做

**Comment by mingkuang-Chuyu** [comment]
无法做到，首先显示一门语言需要有对应的字体以及相应区域的环境。如果RE本身没有日语字体以及相应的区域环境，程序是不能正常显示的。

**Comment by mingkuang-Chuyu** [comment]
无法做到，首先显示一门语言需要有对应的字体以及相应区域的环境。如果RE本身没有日语字体以及相应的区域环境，程序是不能正常显示的。
