### ISSUE TITLE
Random config\languages\* files deletion (10.1.1001.10x64)

### ISSUE THREAD

**Issue by necros2k7** [Chuyu-Team/Dism-Multi-language#770]
win10x64 pro 1909
anyone experienced it ?

**Comment by mingkuang-Chuyu** [comment]
Please see
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c?redirectedfrom=MSDN

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/Dism-Multi-language/issues/772

重复问题。
