### ISSUE TITLE
bug反馈，Dism++x64 10.1.1001.10版本重复更新问题

### ISSUE THREAD

**Issue by Paper-Folding** [Chuyu-Team/Dism-Multi-language#772]
问题描述：Dism++x64 10.1.1001.10版本在空间回收中，若勾选清理以前的Dism++组件并清理，在Dism++下次启动的时候，会提示更新版本。

**Comment by mingkuang-Chuyu** [comment]
无法重现，请提供更多信息。

以前的Dism++组件的扫描结果是什么，能否提供详细的列表 或者截图……。

**Comment by Paper-Folding** [comment]
这是很小的问题。根据你提供的 #770 ， 我发现确实是这个原因，前提1：当config\languages\目录下存在多语种翻译包（我曾切换过英文版）；前提2：勾选清理以前的Dism++组件并清理。此时Dism++总会删除其它语言的语言文件包，导致下次启动时提示更新。

> 无法重现，请提供更多信息。
> 
> 以前的Dism++组件的扫描结果是什么，能否提供详细的列表 或者截图……。
