### ISSUE TITLE
旧版本10.1.1000.70无法自动升级

### ISSUE THREAD

**Issue by TurnOffNOD** [Chuyu-Team/Dism-Multi-language#779]
Dism++ 的版本：10.1.1000.70
放置路径：D：\Programs\Dism++
Windows 的版本：Win10 64bit，中间时间很长，小版本经历过升级。
SKU： 专业版（一直都是）
架构： AMD64，UEFI。

本软件本来是启动的时候自动检查更新自动升级的，之前是在win7上用，一路自动升级到都没问题，后来入手新电脑，这时候开始就是同时在win7和win10上面用，当然因为一直正常，并没有多留意是从什么版本开始同时使用的。
之前一直自动更新都很正常，更新到10.1.1000.70版本并且一直使用了，到今天也都一直没有自动提示有更新。
然而因为搜索“过期驱动清理出错”这个问题到了这里，这才发现已经有了好几个新版本了，中间全都没有提示过有更新，也没有自动更新过。
应该不是我这边的网络问题，中间时间跨度这么大，网络环境变换过不知道多少，公司、咖啡馆、租的房子、家里都用过，都没有提示过更新。

**Comment by mingkuang-Chuyu** [comment]
请删除 `Config\UpdateInfo.zip` 然后重启Dism++看看。，中间版本确实出了一点缓存问题，但是后来修复了。

未来新版本如果依然有此问题，请重新打开此问题。
