### ISSUE TITLE
win7专业版64，空间回收报无法启动服务

### ISSUE THREAD

**Issue by Nicky-he** [Chuyu-Team/Dism-Multi-language#78]
无法启动服务，原因可能是已被禁用或与其相关联的设备没有启动。
可能是哪个服务或者设备？

**Comment by mingkuang-Chuyu** [comment]
需要 TrustedInstaller 服务正常工作，如果这个服务无法正常工作 那么部分功能无法使用。

**Comment by mingkuang-Chuyu** [comment]
关闭此问题，如果有疑问 你可以重新打开此问题
