### ISSUE TITLE
允许在正常模式下开启S模式

### ISSUE THREAD

**Issue by Windowsist** [Chuyu-Team/Dism-Multi-language#787]
设置注册表项重启后就可以进入S模式
但是只有一次机会，如果修改注册表进入S模式后退出S模式，之后再修改注册表也不能进入S模式
希望添加这项优化规则，为需要的用户开启一次S模式
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CI\Policy]
"SkuPolicyRequired"=dword:00000001

**Comment by mingkuang-Chuyu** [comment]
这样的用户还是自己开启吧……

要不然下一个问题就是……怎么弄回来……
