### ISSUE TITLE
Dism++的WinSxS清理无效

### ISSUE THREAD

**Issue by myheartorz** [Chuyu-Team/Dism-Multi-language#789]
Dism++ 的版本：10.1.1000.100 & 10.1.1001.10 均有尝试
放置路径：E盘
截图：
![image](https://user-images.githubusercontent.com/63791468/79456663-785f2980-8021-11ea-9b26-f791f89b2e48.png)
![image](https://user-images.githubusercontent.com/63791468/79456710-8e6cea00-8021-11ea-840c-5b4d000f24fc.png)
Windows 的版本：Windows10家庭64位（我猜应该在1803？）

问题详细：扫出来194MB。前一段时间曾出现过扫描没问题，清理就显示操作出错，后来在刚开机时操作发现问题自动就好了，就什么都没搞。
现在是扫描没问题，清理后也不会显示操作出错，但其实dism++并没有清理成功，这些文件并没有被删除。我再次扫描还是能扫出清理前的垃圾。也试过单独扫描清理，清理后没弹出提示清理了多少空间，再次扫描发现没清。

谢谢你们💗

**Comment by myheartorz** [comment]
![image](https://user-images.githubusercontent.com/63791468/79457083-2a96f100-8022-11ea-92c2-adbb744b4e92.png)
我把鼠标放在界面左上角的蓝框里，显示10.0.17134.1130，这个才是版本吗？

**Comment by myheartorz** [comment]
[Dism++.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/4487161/Dism%2B%2B.log)
这是单独扫描清理winsxs的

**Comment by SituChengxiang** [comment]
WinSxS文件夹内大部分文件都属于TrustedInstaller，因此用TrustedInstaller的权限应该可以清理过期的WinSxS

**Comment by mingkuang-Chuyu** [comment]
请无视这个问题，问题根源是，扫描结果是DIsm++推断的一个扫描结果。

但是清理是微软CBS本身进行的，所以发生了一些不一致的情况。
简单说就是，扫描的多，清理的少。

无视吧，我也不太可能仅仅为了追求结果的完全一致而在这里花费大力气。

警告！！扫描出来的文件不要手工去处理……
