### ISSUE TITLE
win10 15063.250 仅启动re无法使用，但在re中运行时可以用的

### ISSUE THREAD

**Issue by zlx42** [Chuyu-Team/Dism-Multi-language#79]
恢复功能中的问题
点完仅启动RE后自动重启正常进入系统，但是re环境是正常的，点系统的高级启动就没有问题。。。。
而且在RE中运行这个功能也正常

**Comment by mingkuang-Chuyu** [comment]
此功能正常，我猜测是触发了 文件校验逻辑。你是不是曾经在BCD里添加过Dism++

如果是这样，那么先在设置中  关闭此功能，然后在重新打开此功能。最后重新尝试……此操作

**Comment by zlx42** [comment]
我手动设过winre。其他没动过。

在 2017年5月22日 下午3:04，mingkuang <notifications@github.com>写道：

**Comment by mingkuang-Chuyu** [comment]
建议远程看看此问题，谢谢……
我的QQ是 343183163

**Comment by zlx42** [comment]
用bcdedit -enum all
命令查看也是正常的，因为之前win10默认是450m恢复区结果默认安装是认为450不够用直接将re放在了c盘。后来我调整了分区大小后重新用reagentc设置了winre到恢复盘。对了是uefi启动模式。现在自己点高级启动是可以进入re。reagentc
/info 也是完全正常，bcdedit -enum all 查看发现描述是dism++的那项的bcdid也跟我手动设置的那个相同，那项貌似是
在re中启动的添加项。感觉一切都正常，就是那项 仅启动re是正常开启系统。

在 2017年5月25日 上午6:12，周立鑫 <zhoulixin42@gmail.com>写道：

**Comment by zlx42** [comment]
还有之前引导修复过，导致winre环境丢失还特地重设过一次re。

在 2017年5月30日 上午4:26，周立鑫 <zhoulixin42@gmail.com>写道：

**Comment by mingkuang-Chuyu** [comment]
可能你添加信息导致混乱了，建议加我好友，远程看看吧

**Comment by mingkuang-Chuyu** [comment]
用户长时间无应答，并且在本地一切正常……  暂时关闭此问题。
