### ISSUE TITLE
建议重新搬回10.1.1000.70中的“让任务栏更透明”功能

### ISSUE THREAD

**Issue by AduitSSH** [Chuyu-Team/Dism-Multi-language#796]
经过验证，1000.70版本中的“让任务栏更透明”功能在最新2004版Windows 10中能够正常使用 所以建议将此功能搬回

**Comment by mingkuang-Chuyu** [comment]
暂时不搞了，搞了后某些人说可以。某些人说不可以。其实我完全没有看出来开了有啥效果……
