### ISSUE TITLE
反馈一个BUG，win10 点更新管理-点扫描后提示 系统找不到指定文件

### ISSUE THREAD

**Issue by ellx98** [Chuyu-Team/Dism-Multi-language#797]
反馈一个BUG，win10 点更新管理-点扫描后提示 系统找不到指定文件

**Comment by baronv5** [comment]
![image](https://user-images.githubusercontent.com/7010266/84386351-c52b3f00-ac23-11ea-9a82-0e2a97eb2772.png)
**链接：[https://github.com/Chuyu-Team/Dism-Multi-language/releases](url)**

**Comment by mingkuang-Chuyu** [comment]
请手工下载wsuscan3。

**Comment by saodis** [comment]
Dism++ 10.1.1002.2 没有提供 wsuscan3 吗？
我下载这个，还是提示 系统找不到指定文件
![image](https://github.com/Chuyu-Team/Dism-Multi-language/assets/51149477/ceddc496-088a-4a98-bc10-b6775e27e407)

命名有要求吗？
我试了重命名和不重名 wsuscan3 
![image](https://github.com/Chuyu-Team/Dism-Multi-language/assets/51149477/a0074cf9-b548-4ed8-bb56-357f67530224)
![image](https://github.com/Chuyu-Team/Dism-Multi-language/assets/51149477/e9bf5a3c-0fb0-49bb-bfb2-63f6dbb3ed76)

**Comment by saodis** [comment]
![image](https://github.com/Chuyu-Team/Dism-Multi-language/assets/51149477/34ad4854-64ca-4977-a7e3-b4035de2c9eb)

得用这个，这个可以。

**Comment by fengchunchao** [comment]
> ![image](https://github.com/Chuyu-Team/Dism-Multi-language/assets/51149477/34ad4854-64ca-4977-a7e3-b4035de2c9eb)
> 
> 得用这个，这个可以。

我遇到的问题和你一样，也是找不到指定文件，现在的版本如图，和你的WimGAPI不一样，你是在哪下载的

<img width="531" height="330" alt="Image" src="https://github.com/user-attachments/assets/024139bb-28e2-4517-a694-cb1a6dd7a638" />
