### ISSUE TITLE
windows安全中心

### ISSUE THREAD

**Issue by lishige** [Chuyu-Team/Dism-Multi-language#799]
使用完Dism++之后，使用windows安全中心扫描文件出现win10系统 页面不可用 你的IT管理员已经限制对此应用一些区域的访问，这个问题怎么解决?

**Comment by lishige** [comment]
是我误会dism++了
是因为我装了火绒，与windows defender相冲突的结果
对此，我深表歉意
Dism++的体验感极好
希望开发者可以继续完善
支持Dism++

**Comment by mingkuang-Chuyu** [comment]
好吧，记得关闭问题。谢谢
