### ISSUE TITLE
备份系统出现句柄错误

### ISSUE THREAD

**Issue by chen842081173** [Chuyu-Team/Dism-Multi-language#804]
Windows 10 2004  19041.264
备份系统到一半发生句柄错误，然后结束，PE下操作会有同样的错误。
![Uploading 微信图片_20200606183313.png…]()

**Comment by mingkuang-Chuyu** [comment]
图片看不了，这个问题 可以打开Config/DIsm++.log 看看 应该是硬盘里某些文件出了点逻辑问题。

排除后 应该就好了（可以在设置 - 文件过滤列表里添加规则）。

**Comment by chen842081173** [comment]
感谢回复，排除之后就是另一个文件有问题，重装系统后解决了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mingkuang"<notifications@github.com&gt;; 
发送时间: 2020年8月13日(星期四) 下午4:50
收件人: "Chuyu-Team/Dism-Multi-language"<Dism-Multi-language@noreply.github.com&gt;; 
抄送: " "<842081173@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Chuyu-Team/Dism-Multi-language] 备份系统出现句柄错误 (#804)





 
图片看不了，这个问题 可以打开Config/DIsm++.log 看看 应该是硬盘里某些文件出了点逻辑问题。
 
排除后 应该就好了（可以在设置 - 文件过滤列表里添加规则）。

**Comment by mingkuang-Chuyu** [comment]
这样的问题一般都磁盘受损，暂时关闭吧。
