### ISSUE TITLE
删除临时WinSxS文件时出现问题

### ISSUE THREAD

**Issue by JaegerFox** [Chuyu-Team/Dism-Multi-language#805]
清除临时WinSxS文件时，这样做不正确，为此，必须停止“受信任的安装程序”服务。 (TrustedInstaller)

**Comment by wanrufang** [comment]
删除WinSxS和过期驱动都出错。系统是最新版win10

**Comment by JaegerFox** [comment]
不，我認為在Windows 8.1和Windows 10中，要刪除“ WinSxS Temporary”，必須首先停止“ TrustedInstaller”服務，然後再清理

**Comment by mingkuang-Chuyu** [comment]
你说的没有错，但是这个问题无法解决。因为CBS服务会占用那些文件……而Dism++本身运行需要CBS服务……

因此删除那些临时文件将是困难的……
