### ISSUE TITLE
建议在Dism++的主界面中添加"发送反馈"链接

### ISSUE THREAD

**Issue by realYulin** [Chuyu-Team/Dism-Multi-language#806]
为了方便用户发送Issues时自动收集系统信息，建议添加"发送反馈"链接。
点击此链接后进入new issue页面，并展示以下草稿内容：

[在此处输入反馈]

---
### 操作系统详细信息

⚠ *请勿编辑此部分。Dism++ ➟ GitHub 问题链接必须具有此部分。*

* Dism++ Version: [Dism++版本]
* Install Path: [Dism++放置路径]
* OS Version: [操作系统版本]
* SKU: [操作系统SKU]
* Build: [操作系统架构]

其中Dism++版本、Dism++放置路径、操作系统版本、操作系统SKU、操作系统架构由Dism++自动收集并放置到这个草稿中。

**Comment by mingkuang-Chuyu** [comment]
抱歉，臣妾不会做……你知道怎么做吗？
