### ISSUE TITLE
HyperV 2019 在RE中运行不了

### ISSUE THREAD

**Issue by pegasusplus** [Chuyu-Team/Dism-Multi-language#807]
Dism++ 的版本 10.1.1001.10
Windows 的版本 HyperV 2019，10.0.17763.1282、
架构：Intel x64

点在RE中运行，处理了一会儿，报错对话框：
The file name, directory name, or volume label syntax is incorrect.

log文件最后一行：
2020-06-13 17:03:12, Error	PID=2544 TID=3780, NativeDism	无法获取Dism++所在分区ID，0x8007007B

//我是放在网络盘上运行的，哎。我换个方式看看是不是就好了。不能假设Dism++和要处理的分区是在一起吧，获取自己的分区ID干什么用呢？

**Comment by mingkuang-Chuyu** [comment]
设计如此，在RE中运行 就需要设置当前Dism++的路径，因为会在RE中启动Dism++。
