### ISSUE TITLE
系统备份：无法完成操作，因为文件包含病毒或潜在的垃圾文件

### ISSUE THREAD

**Issue by Sasukejf** [Chuyu-Team/Dism-Multi-language#808]
Dism++版本: 10.1.1001.10
Windows版本: 10.0.18363 
Dism++放置路径: 非系统盘，非中文路径内。

![Dism++无法完成操作，因为文件包含病毒或潜在的垃圾文件](https://user-images.githubusercontent.com/40699421/84588639-c5ae1a80-ae5b-11ea-89ac-8a2ebcadb186.png)

**Comment by ChanWunsam** [comment]
关闭Winodws defender的实时保护试试

**Comment by mingkuang-Chuyu** [comment]
WD拦截所致，你关闭WD就可以了。
