### ISSUE TITLE
右键菜单管理-禁用播放到设备怎么找不到了

### ISSUE THREAD

**Issue by operammm** [Chuyu-Team/Dism-Multi-language#810]
Dism_v10.1.1001.10
win10专业版2004
记得以前有这个功能的，怎么找不到了？
搜索了下，以前也有人提交过这个规则。https://github.com/Chuyu-Team/Dism-Multi-language/issues/355
测试了下，效果也OK啊。为什么不加到Dism里呢？

**Comment by mingkuang-Chuyu** [comment]
收到
