### ISSUE TITLE
是否可提供批次命令呼叫执行 空间回收 ？

### ISSUE THREAD

**Issue by AlexChen0128** [Chuyu-Team/Dism-Multi-language#811]
空间回收设定、效能 非常棒！
在周期维护需求下(每月)，希望与硬碟重组、工作排程...程序执行！
如果可以提供 批次命令呼叫执行 一定更加方便

**Comment by mingkuang-Chuyu** [comment]
#https://github.com/Chuyu-Team/Dism-Multi-language/issues/815

重复反馈。
