### ISSUE TITLE
更新功能无法使用

### ISSUE THREAD

**Issue by tianlng** [Chuyu-Team/Dism-Multi-language#812]
![QQ截图20200625231817](https://user-images.githubusercontent.com/65796859/85748050-5d541880-b73a-11ea-9765-dd309b1c6cd9.png)
点击更新功能，提示无法找到指定文件，这是我哪里操作有问题吗？系统还是刚装好的

**Comment by tianlng** [comment]
没有人回的吗？我的是windows 10 系统

**Comment by woshoxxx** [comment]
到群里下载wsusscn3.cab复制到config文件夹里

**Comment by josways** [comment]
https://github.com/Chuyu-Team/Dism-Multi-language/releases

**Comment by mingkuang-Chuyu** [comment]
到群里下载wsusscn3.cab复制到config文件夹里
