### ISSUE TITLE
清除被取代的WinSXS组件报错 找不到元素

### ISSUE THREAD

**Issue by rmwxxwmr** [Chuyu-Team/Dism-Multi-language#814]

**Comment by rmwxxwmr** [comment]
[Dism++.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/4903213/Dism%2B%2B.log)
win10 19041.329

**Comment by 2563173357** [comment]
替换了没有用

**Comment by 2563173357** [comment]
> [Dism+.log win10](https://github.com/Chuyu-Team/Dism-Multi-language/files/4903213/Dism%2B%2B.log)
> 19041.329

替换了没有用

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/Dism-Multi-language/issues/816

重复反馈
