### ISSUE TITLE
清除被取代的WinSXS组件报错 找不到元素 

### ISSUE THREAD

**Issue by 2563173357** [Chuyu-Team/Dism-Multi-language#816]
![QQ截图20200715094212](https://user-images.githubusercontent.com/68309194/87493617-bbac5100-c67f-11ea-91cf-966ee0c1f227.png)
![QQ截图20200715094320](https://user-images.githubusercontent.com/68309194/87493619-bc44e780-c67f-11ea-91e6-2781e9e31705.png)
[Dism++.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/4922384/Dism%2B%2B.log)

**Comment by LeslieYon** [comment]
可以试试手动执行指令：
`Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase`

**Comment by 2563173357** [comment]
cmd命令还是什么



---原始邮件---
发件人: "LeslieYon"<notifications@github.com&gt;
发送时间: 2020年7月27日(周一) 凌晨1:29
收件人: "Chuyu-Team/Dism-Multi-language"<Dism-Multi-language@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"2563173357"<2563173357@QQ.COM&gt;;
主题: Re: [Chuyu-Team/Dism-Multi-language] 清除被取代的WinSXS组件报错 找不到元素  (#816)




 
可以试试手动执行指令：
 Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase

**Comment by LeslieYon** [comment]
> cmd命令还是什么
> […](#)
> ---原始邮件--- 发件人: "LeslieYon"<notifications@github.com&gt; 发送时间: 2020年7月27日(周一) 凌晨1:29 收件人: "Chuyu-Team/Dism-Multi-language"<Dism-Multi-language@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"2563173357"<2563173357@QQ.COM&gt;; 主题: Re: [Chuyu-Team/Dism-Multi-language] 清除被取代的WinSXS组件报错 找不到元素 (#816) 可以试试手动执行指令： Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

随意 管理员的cmd或者powershell都行
我在虚拟机测试没问题  但是我实体机直接蓝屏了。。

**Comment by 2563173357** [comment]
蓝屏？？！！ 实体机不敢试了



---原始邮件---
发件人: "LeslieYon"<notifications@github.com&gt;
发送时间: 2020年7月27日(周一) 凌晨1:42
收件人: "Chuyu-Team/Dism-Multi-language"<Dism-Multi-language@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"2563173357"<2563173357@QQ.COM&gt;;
主题: Re: [Chuyu-Team/Dism-Multi-language] 清除被取代的WinSXS组件报错 找不到元素  (#816)




  
cmd命令还是什么
 …
 ---原始邮件--- 发件人: "LeslieYon"<notifications@github.com&gt; 发送时间: 2020年7月27日(周一) 凌晨1:29 收件人: "Chuyu-Team/Dism-Multi-language"<Dism-Multi-language@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"2563173357"<2563173357@QQ.COM&gt;; 主题: Re: [Chuyu-Team/Dism-Multi-language] 清除被取代的WinSXS组件报错 找不到元素 (#816) 可以试试手动执行指令： Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
随意 管理员的cmd或者powershell都行
 我在虚拟机测试没问题  但是我实体机直接蓝屏了。。

**Comment by LeslieYon** [comment]
> 蓝屏？？！！ 实体机不敢试了
> […](#)
> ---原始邮件--- 发件人: "LeslieYon"<notifications@github.com&gt; 发送时间: 2020年7月27日(周一) 凌晨1:42 收件人: "Chuyu-Team/Dism-Multi-language"<Dism-Multi-language@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"2563173357"<2563173357@QQ.COM&gt;; 主题: Re: [Chuyu-Team/Dism-Multi-language] 清除被取代的WinSXS组件报错 找不到元素 (#816) cmd命令还是什么 … ---原始邮件--- 发件人: "LeslieYon"<notifications@github.com&gt; 发送时间: 2020年7月27日(周一) 凌晨1:29 收件人: "Chuyu-Team/Dism-Multi-language"<Dism-Multi-language@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"2563173357"<2563173357@QQ.COM&gt;; 主题: Re: [Chuyu-Team/Dism-Multi-language] 清除被取代的WinSXS组件报错 找不到元素 (#816) 可以试试手动执行指令： Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 随意 管理员的cmd或者powershell都行 我在虚拟机测试没问题 但是我实体机直接蓝屏了。。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

虚拟机没有任何问题 你执行这条指令之后重启 Winsxs已经清理 而且Dism++中的Winsxs清理也不报错了

**Comment by LeslieYon** [comment]
> 蓝屏？？！！ 实体机不敢试了
> […](#)
> ---原始邮件--- 发件人: "LeslieYon"<notifications@github.com&gt; 发送时间: 2020年7月27日(周一) 凌晨1:42 收件人: "Chuyu-Team/Dism-Multi-language"<Dism-Multi-language@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"2563173357"<2563173357@QQ.COM&gt;; 主题: Re: [Chuyu-Team/Dism-Multi-language] 清除被取代的WinSXS组件报错 找不到元素 (#816) cmd命令还是什么 … ---原始邮件--- 发件人: "LeslieYon"<notifications@github.com&gt; 发送时间: 2020年7月27日(周一) 凌晨1:29 收件人: "Chuyu-Team/Dism-Multi-language"<Dism-Multi-language@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"2563173357"<2563173357@QQ.COM&gt;; 主题: Re: [Chuyu-Team/Dism-Multi-language] 清除被取代的WinSXS组件报错 找不到元素 (#816) 可以试试手动执行指令： Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 随意 管理员的cmd或者powershell都行 我在虚拟机测试没问题 但是我实体机直接蓝屏了。。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我测试了半天 这个应该是安装KB4565503之后才有的问题
不清楚是这个补丁的bug 还是dism++的bug

**Comment by macintosh123456** [comment]
i get the same issue as he has.
i had left comment on next post.

**Comment by mingkuang-Chuyu** [comment]
此问题已知，不兼容2004系统

**Comment by Mc-Snake** [comment]
请问‘’不兼容2004‘’这个问题现在修复了吗

**Comment by macintosh123456** [comment]
> 请问‘’不兼容2004‘’这个问题现在修复了吗

hi ... Mc-Snake.

Please refer to the article [the solution of undeletable WinSxS](https://github.com/Chuyu-Team/Dism-Multi-language/issues/821)

it **MIGHT** be helpful **BUT** it does not mean that it works for everyone.
take the RISK by yourself.

**Comment by Edward-Yeung** [comment]
> 请问‘’不兼容2004‘’这个问题现在修复了吗
亲测2004 build19041.546可以使用 @LeslieYon 的方法实现

**Comment by Edward-Yeung** [comment]
> 请问‘’不兼容2004‘’这个问题现在修复了吗

亲测2004 build 19041.546可以采用 @LeslieYon 的方法实现

**Comment by piggy9999** [comment]
亲测2004 build 19041.572可以采用 @LeslieYon 的方法实现

**Comment by DustinWin** [comment]
版本19042.662，一样的问题。

**Comment by DustinWin** [comment]
> 可以试试手动执行指令：
> `Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase`

19042.662 亲测可行，感谢！

**Comment by dA-lizi** [comment]
19042.746 亲测可行 采用@LeslieYon  的方法

**Comment by b4imetu** [comment]
> 可以试试手动执行指令：
> `Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase`

谢谢，`21H1`  `19043.985`实测有效，希望 @mingkuang-Chuyu 尽快跟进，Thx

**Comment by mingkuang-Chuyu** [comment]
已经确认，微软的早期CBS存在Bug，他就将报告可选功能为取代，目前已知Win11 已经没有此问题了。

同时删除历史版本会导致整个组件被移除，因为，未来版本Dism++针对Windows 10或者更高平台禁用过期更新删除逻辑。

代码已经完毕

**Comment by mingkuang-Chuyu** [comment]
10.1.2002.111发布

**Comment by starobots** [comment]
我在虚拟机上的win11 22000.100也有这个问题。

![image](https://user-images.githubusercontent.com/10796457/126913689-9747463b-c71f-4314-80b4-c215d82db00a.png)

请问是等Dism++软件更新就可以么？

谢谢！

**Comment by mingkuang-Chuyu** [comment]
@starobots 你可以试试 10.1.2002.111 Beta（只能群文件）。

另外注意我的回复，老版本存在的问题，不需要重复提醒我一遍……

**Comment by starobots** [comment]
那就等等，不着急用。

谢谢老板为大家做这么多O/

**Comment by snow212-cn** [comment]
10.1.1001一年半没更新了，10.1.2002无处下载，求分享！

**Comment by b4imetu** [comment]
> 10.1.1001一年半没更新了，10.1.2002无处下载，求分享！

> mingkuang-Chuyu commented 9 days ago • 
@starobots 你可以试试 10.1.2002.111 Beta（只能群文件）。
