### ISSUE TITLE
“关闭锁屏是的windows聚焦推广（by、Cloud）”不起作用了

### ISSUE THREAD

**Issue by MrWait11** [Chuyu-Team/Dism-Multi-language#819]
使用平台信息：Dism++x64 10.1.1001.10，windows10pro 2004 19041.388。本人想关闭锁屏时windows聚焦的推广和相关文字，用Dism++系统优化内的相关选线操作，现在发现不起作用了。。。

**Comment by Franinc** [comment]
应该是失效挺久了，win store下个dynamic theme作为替代吧

**Comment by MrWait11** [comment]
> 应该是失效挺久了，win store下个dynamic theme作为替代吧

好的，谢谢你的回复

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/Dism-Multi-language/issues/690

反馈类似
