### ISSUE TITLE
扫描被取代的winsxs组件提示我 指定的服务未安装

### ISSUE THREAD

**Issue by aimei54** [Chuyu-Team/Dism-Multi-language#82]
http://wx2.sinaimg.cn/large/610d7e36ly1ffdtg9oq26j20rs0jggmz.jpg 
图片地址
邮箱 aimei54@qq.com

**Comment by mingkuang-Chuyu** [comment]
请确认 TrustedInstaller 服务是否存在，你的问题应该就是TrustedInstaller服务被删除所致
