### ISSUE TITLE
挂载的系统映像无法打补丁

### ISSUE THREAD

**Issue by lincicong** [Chuyu-Team/Dism-Multi-language#820]
挂载的系统映像无法打补丁。补丁下载失败，但是仍提示操作成功。用的wsusscn3.cab 2020-06-24。操作系统是cn_windows_10_enterprise_ltsc_2019_x64

![捕获](https://user-images.githubusercontent.com/46524237/87897464-fe09cf80-ca7d-11ea-8f48-64db670426d8.PNG)

**Comment by mingkuang-Chuyu** [comment]
因为是直接使用的微软服务器，建议你先灵魂出境试试。另外也可以使用导出地址功能，然后用迅雷下载。在放到Config/UpdateCache里面

**Comment by mingkuang-Chuyu** [comment]
考虑到微软服务器本身比较差，下载失败类不做考虑。
