### ISSUE TITLE
An error occurs after upgrading windows 10 from 1909 to 2004

### ISSUE THREAD

**Issue by macintosh123456** [Chuyu-Team/Dism-Multi-language#821]
DISM++ X64 10.1.1001.10
WINDOWS 10 PRO VERSION 2004
BUILD 19041.388
INTEL X64

the error occurs on attempting to clean replaced WinSxS components.
it is showed as the screen shot.

![AN ERROR OCCURS AFTER UPGRADING WINDOWS 10 FROM 1909 TO 2004](https://user-images.githubusercontent.com/43736952/88470611-12901100-cf31-11ea-867d-e81567fe0d7f.png)
[Dism++.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/4977086/Dism%2B%2B.log)
[UpdateInfo.zip](https://github.com/Chuyu-Team/Dism-Multi-language/files/4977088/UpdateInfo.zip)
[WINDOWS LOG.zip](https://github.com/Chuyu-Team/Dism-Multi-language/files/4977089/WINDOWS.LOG.zip)

**Comment by caspertone2003** [comment]
same here.
Solved executing under CMD/Admin - Dism.exe /online /Cleanup-Image /StartComponentCleanup
Afterwards DISM++ goes ok again on WinSXS.

**Comment by macintosh123456** [comment]
Hi... caspertone2003
Your solution works pretty well !!!!!!
how did you find out the solution?

**Comment by caspertone2003** [comment]
@macintosh123456 

you know, the ants move up and down and find some seeds... so, I was finding a way to reduce WinSXS size, and found that DISM command. After that I tried DISM++ and saw it worked...
CT

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/Dism-Multi-language/issues/816

重复反馈，所以关闭。
