### ISSUE TITLE
20H2 (19042.421) 中，Appx应用不能彻底清除掉，还会通过Microsoft Store更新下载回来

### ISSUE THREAD

**Issue by b4imetu** [Chuyu-Team/Dism-Multi-language#824]
更新了 `20H2 (19042.421)` 后，内置Appx应用不能彻底清除，会通过Microsoft Store更新下载回来
![image](https://user-images.githubusercontent.com/41535001/89018696-d3a5f500-d34e-11ea-9d26-99e9eea690ef.png)
![image](https://user-images.githubusercontent.com/41535001/89018637-bf61f800-d34e-11ea-959d-4a0113a21fc7.png)
也许是个例，但是我现在通过强行删除 `C:\Program Files\WindowsApps\Microsoft.XXXXXX_8wekyb3d8bbwe` 和 `C:\ProgramData\Microsoft\Windows\AppRepository\Packages\Microsoft.XXXXXX_8wekyb3d8bbwe` 文件解决了

**Comment by MouriNaruto** [comment]
你需要提供这方面的 DISM++ 日志文件

**Comment by b4imetu** [comment]
暂时复现不了，而且算是解决了，就先Close了
