### ISSUE TITLE
chuyu：“开源是一种美德，也是一种实力的象征”

### ISSUE THREAD

**Issue by b4imetu** [Chuyu-Team/Dism-Multi-language#825]
### 初雨团队[DIsm++主页](https://www.chuyu.me)写着：

- Open source is not only a spirit, but also a symbol of strength. [Check here](https://github.com/Chuyu-Team) to view Chuyu Team's Github.
- 开源是一种美德，也是一种实力的象征，查看初雨团队的开源项目[点我](https://github.com/Chuyu-Team)。

### 但是Dism++本身并不开源

请问初雨团队什么时候有时间回复 `Issue` 和维护 `Dism++` ，或者将 `Dism++` **开源**让开发者自行开发。

一人血书 `Dism++` 开源

**Comment by MouriNaruto** [comment]
在没有妥当的防止恶意商用的方案之前，Dism++ 不会开源

**Comment by mingkuang-Chuyu** [comment]
是啊 没错啊，查看初雨团队的开源项目点我。

写的很明白 就是查看初雨团队的开源项目。没说Dism++的开源代码。

按你的理解，微软的主页上 有个 微软开源，里面点进去就是WIndows的源代码咯？

**Comment by apkqiu** [comment]
> 在没有妥当的防止恶意商用的方案之前，Dism++ 不会完全开源
> 
> 其实 Dism++ 有部分设施是开源的，详情参阅 Chuyu Team 的 GitHub 组织

呵呵，改一下许可证，在README中写一下声明就好了呀
