### ISSUE TITLE
建议增加任务栏透明功能

### ISSUE THREAD

**Issue by asmydream** [Chuyu-Team/Dism-Multi-language#829]
我想把任务栏透明一下，结果发现没有直接可用的工具，按照网上方法改了注册表，重启后也没有变，所以想请你们加上此功能，谢谢！

**Comment by GDWGH** [comment]
去应用商店下translucentTB然后右键工具栏TB图标 菜单 常规 然后选择毛玻璃

**Comment by GDWGH** [comment]
毛玻璃是 模糊 效果（补充）

**Comment by Geeyun-JY3** [comment]
不是有吗：
![image](https://user-images.githubusercontent.com/49396421/97948189-c58ec700-1dca-11eb-9499-9dfdbf1e2566.png)

**Comment by asmydream** [comment]
> 不是有吗：
> ![image](https://user-images.githubusercontent.com/49396421/97948189-c58ec700-1dca-11eb-9499-9dfdbf1e2566.png)
> 
> 不过我个人也是比较推荐使用 [TranslucentTB](https://github.com/TranslucentTB/TranslucentTB)。我一直和这个设置项混着用，不过好像有 bug（

我刚用了 translucentTB 这个效果是很好，但是我需要的是translucentTB点击菜单时候的透明效果，能应用到所有，希望大神搞一下。

**Comment by Geeyun-JY3** [comment]
> 我刚用了 translucentTB 这个效果是很好，但是我需要的是translucentTB点击开始菜单时候的透明效果，能应用到所有，希望大神搞一下。

我也就是个用户🤣

**Comment by mingkuang-Chuyu** [comment]
感谢你的理解，但是这种东西做的好就需要注入explorer写插件实现，但是Dism++但是都不会考虑这样的功能。

目前仅使用系统现有的设置。
