### ISSUE TITLE
win10下补丁更新管理近期失效

### ISSUE THREAD

**Issue by wangzongle** [Chuyu-Team/Dism-Multi-language#83]
软件版本为 10.1.27.1 ，在win10 1703最新版下扫描补丁更新扫描不出，实际上官方已经发布了补丁。
而且就算是刚安装的系统，也只能够扫描到 flashplayer 这一个补丁。

**Comment by mingkuang-Chuyu** [comment]
Hi,数据库 会在 双休日更新。另外Dism++的数据库均统一到双休日更新。谢谢
