### ISSUE TITLE
有个更新补丁一直出现，但是一直无法安装成功，但是 windows update 显示没有补丁可以安装

### ISSUE THREAD

**Issue by Wesly-Zhang** [Chuyu-Team/Dism-Multi-language#830]
如图所示，最新版本 2020年9月15日版本的 DISM++，我是第一次用这个软件，之前一个版本也检测出这个补丁，但是与 windows update 检测的不一致，所以到这个来问问情况。

![2020-09-16_091507](https://user-images.githubusercontent.com/33350770/93281207-34559800-f7fe-11ea-89da-62136931b1ee.png)

系统版本：Windows 10 build 1909

**Comment by Wesly-Zhang** [comment]
我好像知道了问题的答案了：https://github.com/Chuyu-Team/Dism-Multi-language/issues/747

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/Dism-Multi-language/issues/747
重复反馈
