### ISSUE TITLE
系统分区MBR，启动分区GPT时无法成功修复系统引导

### ISSUE THREAD

**Issue by huangsijun17** [Chuyu-Team/Dism-Multi-language#831]
问题：
引导修复功能对于VHD系统的兼容性欠佳。

详细情况：
DISM++不回去识别VHD文件所在分区的分区格式，而是会去识别VHD系统内系统所在分区的分区格式。
从而会导致GPT的磁盘，建了一个VHD文件使用MBR分区表，DISM++修复时会根据VHD文件使用的MBR分区表而运行BIOS的引导修复，而非运行VHD文件所在GPT磁盘的UEFI引导修复。

修复方法：
对于VHD以及VHDX内的操作系统，自动识别VHD或VHDX文件所在的分区的分区格式，进行判断。

**Comment by mingkuang-Chuyu** [comment]
不仅仅是VHD，跨硬盘也存在此问题。

**Comment by mingkuang-Chuyu** [comment]
但是我不认为这样有什么问题。

系统盘是GPR，引导盘是MBR，这显然是不符合标准的。
如果是新安装的系统，那么也将卡死在OOBE。

然后反过来说，当前系统是MBR（并且没有使用UEFI），VHD用了GPT，这样的修复又有什么意义？

所以我认为这个问题不需要修复，最多，Dism++进行弹窗提示，启动分区与系统分区，类型不一致。

**Comment by huangsijun17** [comment]
> 但是我不认为这样有什么问题。
> 
> 系统盘是GPR，引导盘是MBR，这显然是不符合标准的。
> 如果是新安装的系统，那么也将卡死在OOBE。
> 
> 然后反过来说，当前系统是MBR（并且没有使用UEFI），VHD用了GPT，这样的修复又有什么意义？
> 
> 所以我认为这个问题不需要修复，最多，Dism++进行弹窗提示，启动分区与系统分区，类型不一致。

主要是某些VHD/WTG工具等会不询问就直接选择MBR/GPT作为分区表格式，然后拿DISM++来修复引导就无效了。

**Comment by mingkuang-Chuyu** [comment]
@huangsijun17 那我可以调整一些逻辑。

这样？

| 系统分区类型  |  启动分区类型              | 目标修复方式 
| ---------------- | ------------------------ | ---------------
| GPT                 |  GPT/MBR                     | UEFI
| MBR                | GPT                               | UEFI
| MBR                | MBR                              | 传统BIOS

**Comment by huangsijun17** [comment]
> @huangsijun17 那我可以调整一些逻辑。
> 
> 这样？
> 
> 系统分区类型	启动分区类型	目标修复方式
> GPT	GPT/MBR	UEFI
> MBR	GPT	UEFI
> MBR	MBR	传统BIOS
> 但是会有人 使用MBR + MBR 然后UEFI启动吗？其实我不想过多讨论这个问题，考虑到非标准的场景处理会很麻烦。
> 
> 或者说，简单的处理，当发现系统分区类型 与启动分区类型不一致时，直接返回错误。

使用启动分区所在硬盘的硬盘分区格式就行。VHD文件还存在二次分发的情况，以及各种工具自动新建时自动使用GPT或则MBR，未知数太多了。

**Comment by mingkuang-Chuyu** [comment]
你说的这样的处理那不是更加不合理吗？

启动分区 MBR，系统分区GPT。按你的说法就变成  传统BIOS启动了，这显然是无法正常启动的。

**Comment by huangsijun17** [comment]
> 你说的这样的处理那不是更加不合理吗？
> 
> 启动分区 MBR，系统分区GPT。按你的说法就变成 传统BIOS启动了，这显然是无法正常启动的。
> 
> 搞了一个逻辑，反而导致无法修复，你这个又有什么意义？
> 
> 解决问题，不仅仅要解决你的问题，而且还要不新引入问题。明白？
> 
> 否则，你的问题解决了，另外的人遇到问题了。

VHD的Windows在Legacy+MBR的引导顺序是：
1. 按BIOS的加载顺序设置顺序加载硬盘的MBR。
2. MBR按照活动的主分区加载PBR。
3. PBR引导`bootmgr`文件。
4. `bootmgr`文件按照BCD配置加载VHD并引导里面的`\WINDOWS\system32\winload`来启动系统。

VHD的Windows在UEFI+GPT的引导顺序：
1. 按照UEFI的加载顺序设置，加载EFI文件`bootmgr.efi`。
2. `bootmgr.efi`按照BCD配置加载VHD并引导里面的`\WINDOWS\system32\winload.efi`来系统。

----
不论Legacy+MBR，亦或者UEFI+GPT，都**只会**想WIM那样**直接加载**VHD里的`\WINDOWS\system32\winload`，或者`\WINDOWS\system32\winload.efi`，而不会管你VHD里面的分区格式是啥。

----
至于你说启动分区 MBR，系统分区GPT的，如果在不支持UEFI的传统BIOS上，你按照GPT去修复，也是不能启动的。最主要的是MBR扇区、PBR扇区、引导分区的活动标签都没有，你写个efi在那里，BIOS是不会认的。

**Comment by mingkuang-Chuyu** [comment]
所以你说的有啥意义？

**Comment by mingkuang-Chuyu** [comment]
改动需要满足二个条件：
1. 修改不引入新的问题。
2. 可以解决现在遇到的问题。

按照你的提议，确实解决了你遇到的问题，但是也同时给其他场景的用户制造了其他问题。

如果需要改，我目前支持以下二种

## 修改方式一
| 系统分区类型  |  启动分区类型              | 目标修复方式 
| ---------------- | ------------------------ | ---------------
| GPT                 |  GPT/MBR                     | UEFI
| MBR                | GPT                               | UEFI
| MBR                | MBR                              | 传统BIOS

## 修改方式二
修复逻辑不变，但是对于非标准的场景，统一进行警告弹窗处理，提醒用户。

**Comment by huangsijun17** [comment]
> 所以你说的有啥意义？

如果PC是UEFI引导，那么引导分区应该是ESP。但如果VHD是MBR的，DISM++就会LegacyBIOS的引导方式进GPT分区。引导程序写的是/bootmgr，BCD也是/boot/BCD。这在纯UEFI是无法引导的。
同理，如果PC是传统引导，引导分区应该是活动分区。而如果VHD是GPT的，DISM++也就会写UEFI的引导方式进活动扇区。引导程序写的是/efi/bootx64.efi等，BCD则是/efi/boot/BCD。这在legacyBIOS下也是无法引导的。

----
所以说，照着VHD里面的分区表来修复外面的引导分区，不小的概率会出问题。（不考虑主板对于双重引导方式兼容的情况下）

**Comment by mingkuang-Chuyu** [comment]
双 MBR 这是可以引导的，只需要放入 efi 文件，即可启动，这点并没有问题，但是这不在标准中。

**Comment by mingkuang-Chuyu** [comment]
所以新的逻辑增加了启动分区的权值，每一种情况的组合我不是已经罗列了？

| 系统分区类型  |  启动分区类型              | 现有逻辑    | 我的预期    |  你的预期
| ---------------- | ------------------------ | -----------    | --------     | ---------
| GPT                 |  MBR                            |    UEFI          |         UEFI   | 传统BIOS
| GPT                 | GPT                               |  UEFI             | UEFI          | UEFI
| MBR                | GPT                               | 传统BIOS      |UEFI           | UEFI
| MBR                | MBR                             | 传统BIOS      | 传统BIOS | 传统BIOS


我做了一个新的表格，你可以明白吧？我们处理方式，第一项我们二个人的预期是不同的。

但是很显然，按照我的预期去修复，那么很大概率，系统将可以启动，但是按照你的需求

**Comment by mingkuang-Chuyu** [comment]
但是如果按照你的要求的做，一条的行为将发生改变，而且这必然是无法正常使用的路径。

**Comment by mingkuang-Chuyu** [comment]
由于你的修改方式会引入新的问题，所以我不接受你的提议，另外你的回答中也显然对于UEFI启动MBR存在误解，所以我想在过多的讨论这个问题。


我会用我的逻辑去修改，增加启动分区的权值，而不仅仅考虑系统分区的情况。

**Comment by mingkuang-Chuyu** [comment]
| 系统分区类型  |  启动分区类型              | 现有逻辑    | 新的逻辑    | 
| ---------------- | ------------------------ | -----------    | --------     | ---------
| GPT                 |  MBR                            |    UEFI          |         UEFI   |
| GPT                 | GPT                               |  UEFI             | UEFI          |
| MBR                | GPT                               | 传统BIOS      |UEFI           |
| MBR                | MBR                             | 传统BIOS      | 传统BIOS |

**Comment by mingkuang-Chuyu** [comment]
10.1.2002.112生效
