### ISSUE TITLE
关闭软件的时候窗口卡死，显示正在取消任务。

### ISSUE THREAD

**Issue by ImViper** [Chuyu-Team/Dism-Multi-language#833]
发布问题的时候请删掉以上内容，我们也不通过格式来限制你们。
Dism++10.1.1001.10版本，在 Windows10 2004 [版本 10.0.19041.508]中，打开的时候没有执行任何操作，
关闭的时候却显示正在执行任务，点击确认后并不能关闭，而是窗口与程序卡死。一直在正在取消现有任务。

![image](https://user-images.githubusercontent.com/60597225/95161609-38aa1b00-07d6-11eb-88c6-4ea4825d4bd8.png)
![image](https://user-images.githubusercontent.com/60597225/95161630-452e7380-07d6-11eb-9460-96f2554b6528.png)

**Comment by uukongjian** [comment]
是的，目前关闭程序都提示这个

**Comment by ImViper** [comment]
> 是的，我也碰到了这个问题，不过需要把提供的 wsusscn3.cab 文件放入 dism 的 Config 目录下就没问题了

这个文件在哪里呢

**Comment by uukongjian** [comment]
> > 是的，我也碰到了这个问题，不过需要把提供的 wsusscn3.cab 文件放入 dism 的 Config 目录下就没问题了
> 
> 这个文件在哪里呢

![image](https://user-images.githubusercontent.com/57243412/95711840-2e849280-0c96-11eb-97db-bd11a8627ca2.png)
