### ISSUE TITLE
dism++ x86 使用wsusscn3.cab将崩溃

### ISSUE THREAD

**Issue by keneahuang** [Chuyu-Team/Dism-Multi-language#836]
dism++ x86 10.1.1001.10 使用wsusscn3.cab扫描WIN7X86系统更新时会崩溃重新打开，X64版本不会
beta版本也是这样的情况

**Comment by mingkuang-Chuyu** [comment]
已知，因为新的库将所有系统的数据放在了一起，导致x86 进程无法承受。

**Comment by mingkuang-Chuyu** [comment]
10.1.2002.111
