### ISSUE TITLE
黑暗主题

### ISSUE THREAD

**Issue by wangshanghai240** [Chuyu-Team/Dism-Multi-language#840]
添加黑暗主题支持。
![dism++](https://user-images.githubusercontent.com/59947306/99875875-c24e6480-2c2d-11eb-9224-07d1f248949f.png)

**Comment by kkqqd** [comment]
> 添加黑暗主题支持。
> ![dism++](https://user-images.githubusercontent.com/59947306/99875875-c24e6480-2c2d-11eb-9224-07d1f248949f.png)

**Comment by mingkuang-Chuyu** [comment]
不考虑此问题，因为Dism++只处理Bug。
