### ISSUE TITLE
无法在锁屏界面显示天气

### ISSUE THREAD

**Issue by shifu0456** [Chuyu-Team/Dism-Multi-language#845]
你好，我想问下，如何恢复在锁屏时候的天气显示呢？我在优化面板禁用了Windows聚焦之后，再打开就无法显示了。麻烦指引一下，谢谢

**Comment by mingkuang-Chuyu** [comment]
不太清楚，Windows聚焦是一个策略，理论上应该跟你这个没有关系。

暂时也没有其他用户反馈。暂时关闭处理。
