### ISSUE TITLE
wimgapi 版本检测的问题

### ISSUE THREAD

**Issue by fuchanghao** [Chuyu-Team/Dism-Multi-language#846]
似乎wimgapi版本检测的时候只会检测系统目录(system32/sysWOW64)下的和文件目录自带的。

如果自带的版本高于系统

而并不会使用ADK中的wimgapi.dll

举例：

Windows Server 2019安装"Windows ADK for Windows 10, version 2004"为例：

其中安装目录会在path的环境变量中自动添加，例如默认路径安装后，环境变量的数值为：

> “C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\”

此时Windows ADK的wimgapi.dll路径为：

> "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\<arch>\DISM\wimgapi.dll"

而此时Dism++依旧显示使用的为内置的18362.1的api，手动替换dll又会在每次开启时无限提示更新。

希望Dism++能在检测wimgapi.dll的时候添加此路径。

附Windows ADK安装地址：https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install

**Comment by mingkuang-Chuyu** [comment]
目前似乎没有实际需求支撑这个新特性，因为wimgapi.dll的版本变化几乎没有实际有用的新功能。

值得一提的是，Dism++保持在18362.1是因为更高版本的API不兼容Windows 10 10240……

**Comment by mingkuang-Chuyu** [comment]
请提供实际这样的使用场景，否则无视此问题。
