### ISSUE TITLE
资源管理器占用异常，桌面图标变成白纸（使用功能：清除小箭头与小盾牌）

### ISSUE THREAD

**Issue by KevinWBlack** [Chuyu-Team/Dism-Multi-language#847]
Windows10家庭中文版x64 Dism++10.1.1001.10（之前用的老版出了问题，换了最新版还是没办法解决）
存放目录 D:\Dism++ 日志内容只有成功启动

问题描述：我下载Dism++只是为了清除小箭头和小盾牌（杀鸡焉用牛刀），使用了一年多没有什么大问题，偶尔会出现桌面快捷方式图标丢失的情况（变成白纸），只需要打开Dism++把那两个选项关掉再打开就可以解决。12月5号的时候微软推送了一个CPU驱动程序的更新，安装完之后就出现了现在的这个无法解决的问题了（不太清楚这个驱动程序与问题的出现是否有必然联系，但是在问题发生前后对电脑所做出的唯一一个改动就是安装了这次更新）具体问题如下：
1.资源管理器占用CPU达30%左右（正常情况感觉是10%以下），导致电脑一启动风扇就一直运转，续航变为之前的三分之二不 
   到。
2.桌面图标变成白纸，包括文件夹里的word等文档图标都变成了白纸，刷新桌面可以概率复原，再刷新又会变回白纸。
3.前面提到了以前出现问题时（只有桌面图标变成白纸，资源管理器异常没有遇到过）会通过关闭开关再打开的方式解决问题，但 
   是这次不同，关闭 小盾牌消失的开关 小盾牌会出现，但是无论打开还是关闭 小箭头消失的开关 小箭头都不会出现。

谢谢大家的帮助，感觉要是能够重置DIsm++对资源管理器的更改应该能解决问题，但是我实在不知道怎么操作了。恳请大家帮助我，十分感谢！
（第一次在GitHub发帖，如有做得不好之处敬请原谅）
![1](https://user-images.githubusercontent.com/75724381/101609463-f43f3380-3a41-11eb-9d13-e5ac202128fc.png)
图1：CPU占用异常的资源管理器（打开电脑就是这么高，不去管它也是这么高）
![2](https://user-images.githubusercontent.com/75724381/101609487-facdab00-3a41-11eb-8184-8fa98b873deb.png)
图2：桌面图标变白纸
![4](https://user-images.githubusercontent.com/75724381/101609913-7f202e00-3a42-11eb-95dc-2e8cb92c4593.png)
图3：关闭开关小箭头也不会出现

**Comment by KevinWBlack** [comment]
不知道怎么上传图片，图似乎裂掉了

**Comment by mingkuang-Chuyu** [comment]
你的图片我能看到，但是我不认为与Dism++有什么联系……

暂时可以观望

**Comment by KevinWBlack** [comment]
谢谢你，问题目前已经解决了，是系统的图标缓存文件出现了问题，现在重设了一个。







------------------ 原始邮件 ------------------
发件人: mingkuang <notifications@github.com&gt;
发送时间: 2021年2月8日 10:34
收件人: Chuyu-Team/Dism-Multi-language <Dism-Multi-language@noreply.github.com&gt;
抄送: KevinWBlack <1036572489@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Chuyu-Team/Dism-Multi-language] 资源管理器占用异常，桌面图标变成白纸（使用功能：清除小箭头与小盾牌） (#847)





 
你的图片我能看到，但是我不认为与Dism++有什么联系……
 
暂时可以观望

**Comment by mingkuang-Chuyu** [comment]
感谢反馈。
