### ISSUE TITLE
win10升级 20H2版本后，清理被替换掉的winsxs失败

### ISSUE THREAD

**Issue by ClaudiusGitHub** [Chuyu-Team/Dism-Multi-language#849]
**windows版本：**
版本	Windows 10 专业版
版本号	20H2
安装日期	‎2020/‎11/‎18
操作系统版本	19042.685
体验	Windows Feature Experience Pack 120.2212.551.0

**问题：**
  win10升级 20H2版本后，清理被替换掉的winsxs失败， 尝试手动删除winsxs内的无效sxs,提示需要trustedInstaller权限，更改winsxs目录所有者为administrators，并且给administrators增加完全控制的执行权限后，使用管理员运行dism++仍旧提示清理失败（此时可以手动删除无效的winsxs目录成功）

**DISM log:**

[Dism++.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/5682882/Dism%2B%2B.log)

**CBS log:**
[CBS.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/5682880/CBS.log)

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/Dism-Multi-language/issues/816

重复反馈
