### ISSUE TITLE
unable to install Dism++ to my boot with windows 7 ?

### ISSUE THREAD

**Issue by j0k3335** [Chuyu-Team/Dism-Multi-language#851]
﻿If you are not a Chinese, please use translator.

如果是清理规则、优化规则、多语言改善的提议，建议直接发布 Pull Request 直接为 
Dism++ 添加，不明白的可以直接通过邮箱或者 QQ 群直接联系鸭子；当然你发 Issue 也
没问题，只是开发者们没法处理，需要等待有志者帮你发 Pull Request 了。

如果是除此之外的问题，发 Issues 即可。

发 Issue 需要注意你当前使用的环境信息描述清楚，譬如 Dism++ 的版本、放置路径和截
图，Windows 的版本（完整版本，例如 10.0.18362.10014）、SKU（例如 专业版）、架构
（例如 AMD64），当然如果能提供 Dism++ 目录下 Config 内的日志文件和 Windows\Logs
目录内有关 CBS 和 DISM 的相关日志我们会更加高兴。

发布问题的时候请删掉以上内容，我们也不通过格式来限制你们。

**Comment by j0k3335** [comment]
Hi,

I can't install Dism++ on my boot in my Windows 7 ( path not found ...  during the process ???)

thanks for some help ... I appreciate so much this utility Program !

José

**Comment by j0k3335** [comment]
any help ?

**Comment by j0k3335** [comment]
or how to install a Dism++ entry on my BCD ?

**Comment by j0k3335** [comment]
Using Windows 7 SP1, 
I get this on Dism++.log when i try ti install Dism++ on the BCD : 

 Info	PID=5560 TID=5764, Dism++	成功启动，程序版本: 10.1.1001.10，CBS抽象层: 10.1.1001.10，Host版本：6.1.7601.24545

**Comment by mingkuang-Chuyu** [comment]
Please decompress and run.

**Comment by j0k3335** [comment]
> Please decompress and run.

Thanks for your answer BUT :+1: 
I mean : I want to install Dism++ ON THE BOOT and get this error ??? what can I do ?

thanks

**Comment by mingkuang-Chuyu** [comment]
If there is an error, please provide a screenshot of the error. The loss of `WinRE.wim` files of the system may have caused this problem.

**Comment by j0k3335** [comment]
Hi,
When I try to install Dism++ on my w7 pro 64 bits, i got this result :

![dism1](https://user-images.githubusercontent.com/76258671/107322039-f9e9e180-6aa3-11eb-8a17-2e53d3911573.jpg)
![dism2](https://user-images.githubusercontent.com/76258671/107322057-00785900-6aa4-11eb-9345-90c70cc47b71.jpg)

I already do the same thing on my other PC with success ( and so I have a "Multi-boot" : W7/Dism++  when I start my PC.

Thanks a lot for your help

**Comment by mingkuang-Chuyu** [comment]
@j0k3335 The WinRE.wim file has been lost. You must restore it to use this feature.
