### ISSUE TITLE
Cpu利用率问题

### ISSUE THREAD

**Issue by Toothpick-overlord** [Chuyu-Team/Dism-Multi-language#852]
![3](https://user-images.githubusercontent.com/31361750/104531278-c8b6f680-5648-11eb-9f71-8fd5ead2eccf.jpg)
![2](https://user-images.githubusercontent.com/31361750/104531282-c9e82380-5648-11eb-9a19-6c4a9df776e8.jpg)

Dism版本：10.1.1001.10
Win版本	10.0.14393 版本 14393 Server16-standard-X64
Cpu：Gold5118X2
问题：在win转esd时Cpu占用低
[CBS.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/5811807/CBS.log)
[dism.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/5811809/dism.log)

**Comment by mingkuang-Chuyu** [comment]
Dism++调用的是微软的wimagapi，除非你能给图证明微软的Dism利用率高……

否则将不予受理。
