### ISSUE TITLE
系统备份报错

### ISSUE THREAD

**Issue by AlexRager** [Chuyu-Team/Dism-Multi-language#855]
Dism++ 的版本、
![image](https://user-images.githubusercontent.com/46938788/106376288-ce456800-63ce-11eb-8089-c0399e41a80f.png)

放置路径和截
图，
![image](https://user-images.githubusercontent.com/46938788/106376296-eb7a3680-63ce-11eb-9001-295706b42c1e.png)

Windows 的版本（完整版本，例如 10.0.18362.10014）、
![image](https://user-images.githubusercontent.com/46938788/106376307-0e0c4f80-63cf-11eb-8aa0-7d6f20040a64.png)

SKU（例如 专业版）、专业版
问题：恢复 系统备份出错
![image](https://user-images.githubusercontent.com/46938788/106376398-e5d12080-63cf-11eb-9aaa-cfaf2c39ab3c.png)

**Comment by mingkuang-Chuyu** [comment]
VSS故障，你的系统应该本身就无法创建快照吧

可以先试试 创建快照
