### ISSUE TITLE
挂载镜像后另存WIM异常

### ISSUE THREAD

**Issue by leoxxx** [Chuyu-Team/Dism-Multi-language#859]
程序版本: 10.1.1001.10，CBS抽象层: 10.1.1001.10
尝试环境为WIN7 X64 SP1 U版和WIN7PE X86。
挂载和卸载镜像到是没问题。修改WIM里面的数据后点另存为WIM映像，压缩率为默认的最大压缩映像。速度异常的慢，且无论经过多少时间生成的WIM只有4K大小，硬盘读写声音很大。挂载目录为G:\W7。另存为的WIM目录为G:。
直接备份C盘的系统时并无异常，硬盘读写声音也正常，生成的WIM也正常。

**Comment by mingkuang-Chuyu** [comment]
符合预期。请使用保存，因为你的挂载的映像。
