### ISSUE TITLE
无法安装 可选功能  Exchange Active Sync和 Internet邮件同步引擎

### ISSUE THREAD

**Issue by icrazt** [Chuyu-Team/Dism-Multi-language#863]
版本
Dism++ ：Dism++ 10.1.1001.10 年度更新 20:46 2020/1/18
win10     ：Windows 10 专业版 20H2

win10 的默认邮箱应用出现无法添加账户的问题，在按此处 [link](https://www.zhihu.com/question/264641120/answer/1156933456)
回答使用Dism++解决时，发现系统的 **Exchange Active Sync和 Internet邮件同步引擎** 已经安装，且卸载后无法重新安装。错误图片如下：
![屏幕截图 2021-02-26 233907](https://user-images.githubusercontent.com/29837321/109321244-e1dbd580-788b-11eb-89e3-16f6eba7d46d.png)

**Comment by mingkuang-Chuyu** [comment]
这个错误代码一般都是系统精简所致。请认真的想想 是否精简了系统（Dism++没有精简功能）。

**Comment by AstridTrj** [comment]
请问最后怎么解决的呢
