### ISSUE TITLE
【bug 提交】首次进行空间回收时勾选“被取代的WinSxS组件”会清理两个重要的可选功能，如记事本

### ISSUE THREAD

**Issue by DustinWin** [Chuyu-Team/Dism-Multi-language#867]
**系统版本：** Windows 10 19042/19043

**软件版本：** 10.1.1001.10

**复现步骤：**
1. 进入系统 Windows 10 19042/19043;
2. **首次**安装并使用 Dism++ 的“空间回收”功能，勾选“被取代的WinSxS组件”，如图：
![Snipaste_2021-04-10_23-09-13](https://user-images.githubusercontent.com/45238096/114508579-1e5e6780-9c67-11eb-9429-85415a15cace.png)
3. 点击“清理”，清理结束后可以发现“被取代的WinSxS组件”显示“出错”，如图：
![Snipaste_2021-04-10_23-09-46](https://user-images.githubusercontent.com/45238096/114508711-43eb7100-9c67-11eb-8e92-4d5e1d1c9849.png)
4. 重启电脑，再次打开 Dism++，进入“可选功能”，查看项目。

**预期结果：**
显示有“记事本”和“Windows 功能体验包”，文本文档可以正常打开。

**实际结果：**
“记事本”和“Windows 功能体验包”缺失，文本文档没有关联程序，无法打开。
![Snipaste_2021-04-10_23-10-00](https://user-images.githubusercontent.com/45238096/114508864-6f6e5b80-9c67-11eb-8b85-a3f53060e82f.png)

**备注：**
1. 必须是安装系统后首次使用 Dism++ 进行空间回收，该 bug 才能触发；
2. bug 已经被触发后，在 Dism++ 的“可选功能”安装“记事本”和“Windows 功能体验包”，再次进行空间回收，重启后“记事本”和“Windows 功能体验包”不会缺失；
3. 其实该 bug 在比较久之前，也许是 Windows 10 19042 刚发布的时候就出现过，只不过今天才提交。

**Comment by DustinWin** [comment]
把电脑重装了 n 次，终于定位到具体的问题，并成功复现。

**Comment by 0x558** [comment]
> 把电脑重装了 n 次，终于定位到具体的问题，并成功复现。

牛逼，我也遇到了同样的问题，记事本没有了。但是后来一直没复现。

**Comment by DustinWin** [comment]
> > 把电脑重装了 n 次，终于定位到具体的问题，并成功复现。
> 
> 牛逼，我也遇到了同样的问题，记事本没有了。但是后来一直没复现。

系统首次使用 Dism++ 勾选“被取代的WinSxS组件”进行空间回收，才会触发。清理后出现“出错”，还以为没有进行任何清理，哪知道实际上清理了“记事本”和“Windows 功能体验包”。😂

**Comment by b4imetu** [comment]
确实是这样，自从系统自带Notepad变成可卸载组件之后，就会被Dism++卸载

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/Dism-Multi-language/issues/816
重复问题，关闭。
