### ISSUE TITLE
扫描系统更新时出现奔溃，无法使用该功能

### ISSUE THREAD

**Issue by mintiandeniwo** [Chuyu-Team/Dism-Multi-language#869]
Dism++ 的版本：10.1.1001.10
wsusscn3.cab版本：2021-1-18
windows版本：win7 sp1 x86 和 win8.1 x86

**Comment by mingkuang-Chuyu** [comment]
重复问题
https://github.com/Chuyu-Team/Dism-Multi-language/issues/836
