### ISSUE TITLE
Dism++ 扫描更新时出现闪退、软件重启

### ISSUE THREAD

**Issue by xFelino** [Chuyu-Team/Dism-Multi-language#870]
Dism++ 版本为 x86 10.1.1001.10
放置路径为 D:\Program Files\Dism++
Windows7 版本 6.1 内部版本 7601 SP1 专业版
同样的 Dism++ 使用新版 wsusscn3.cab 会出现闪退、软件重启，而此前使用的一个版本（88D0DFF7DC44B1B787A37F9A61D6439A）则可正常扫描更新并安装。

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/Dism-Multi-language/issues/836

重复问题
