### ISSUE TITLE
为什么除了备份能用，其他的功能全是出现这个？

### ISSUE THREAD

**Issue by zbxuling** [Chuyu-Team/Dism-Multi-language#873]
![360截图20210429085458015](https://user-images.githubusercontent.com/83380585/116489935-bb0c4080-a8c8-11eb-9987-da52b27c9694.jpg)
![360截图20210429085626743](https://user-images.githubusercontent.com/83380585/116489968-cc554d00-a8c8-11eb-9cb8-a29266164ab7.jpg)
已经解压缩了

**Comment by mingkuang-Chuyu** [comment]
你的系统RE被精简，吃功能需要RE完好。
