### ISSUE TITLE
更新到Win10 20H2后， 使用最新版本DISM++清理过期WinSXS组件出错

### ISSUE THREAD

**Issue by TrueZhuangJia** [Chuyu-Team/Dism-Multi-language#879]
![image](https://user-images.githubusercontent.com/78474576/119076360-01b30d80-ba25-11eb-9ae4-1f7778e30d89.png)
![image](https://user-images.githubusercontent.com/78474576/119076201-ba2c8180-ba24-11eb-958b-1779ebf22f16.png)
Win10 1909 不维护了，微软推送20H2我就更新了一下。更新完WinSXS清理出错，请大佬研究一下谢谢

**Comment by 2563173357** [comment]
可以试试手动执行指令：
Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase

**Comment by TrueZhuangJia** [comment]
> 可以试试手动执行指令：
> Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase

感谢大佬， 看起来可以了
