### ISSUE TITLE
WEPE下无法给运行中的PE本身打驱动和补丁 但是给已经安装的系统打补丁和驱动就没问题

### ISSUE THREAD

**Issue by daiaji** [Chuyu-Team/Dism-Multi-language#88]
这看起来像是一个BUG
详情
http://wuyou.net/forum.php?mod=redirect&goto=findpost&ptid=372482&pid=3375838&fromuid=551745

**Comment by mingkuang-Chuyu** [comment]
这个不是BUG，而是本身就是这样设计的。PE往往是在内存中运行的。如果你需要修改PE，那么请离线修改。

**Comment by daiaji** [comment]
@mingkuang-Chuyu 如果有临时给PE加驱动的家伙存在呢？比如带网络浏览器的PE这样

**Comment by mingkuang-Chuyu** [comment]
这样的人不考虑，虽然我确实能做到。微软本身也不考虑这样的奇葩的用户。如果需要修改PE，请直接修改WIM文件，而不是在运行时修改，那个奇葩的人还想出这样奇葩的事情，难道他还想添加后，然后直接捕获当前PE系统为WIM文件吗？

我还是那句话，如果要修改PE，请直接修改对应的WIM文件…… 请不要把一个PE当真正常系统来使用。
