### ISSUE TITLE
即使没有执行任何任务，Dism++也提示正在执行任务

### ISSUE THREAD

**Issue by HanHan233** [Chuyu-Team/Dism-Multi-language#880]
# 图片：
![image](https://user-images.githubusercontent.com/64469437/119162718-483c5280-ba8d-11eb-95d0-75f59d4002b8.png)
 
https://user-images.githubusercontent.com/64469437/119163168-b84ad880-ba8d-11eb-8b4a-72fedc3d3b68.mp4

# 环境信息：
![image](https://user-images.githubusercontent.com/64469437/119162070-8ab15f80-ba8c-11eb-94cc-6d1ff1d59170.png)

# Dism++版本：
![image](https://user-images.githubusercontent.com/64469437/119163314-e0d2d280-ba8d-11eb-9025-5c1fddd4f181.png)

**Comment by DustinWin** [comment]
同样的问题，正准备来反馈的。
系统版本 Windows 10 19043.1023 也可以复现此问题，打开 Dism++ 后不进行任何操作，点击“关闭”就会提示“正在执行任务”。
![QQ截图20210531012713](https://user-images.githubusercontent.com/45238096/120131628-60ce0a80-c1fb-11eb-89c6-68a57f05b83f.png)

**Comment by HanHan233** [comment]
我19042也有问题，现在PE里也有问题（优启通最新）

**Comment by mingkuang-Chuyu** [comment]
后台网络请求一直没有返回

**Comment by HanHan233** [comment]
（换个服务器吧）（暴论

**Comment by GrimmYun** [comment]
我也遇到这情况了，以前没出现过，点击空间回收扫描了下，然后点退出程序就出现这个了

**Comment by mingkuang-Chuyu** [comment]
先应该好了吧？
CDN运营商出了点问题。

**Comment by pein0saga** [comment]
> 先应该好了吧？ CDN运营商出了点问题。

最新版，再次复现了啊
