### ISSUE TITLE
不是反馈，只是问一下软件还有更新吗

### ISSUE THREAD

**Issue by ThunderPanther5** [Chuyu-Team/Dism-Multi-language#881]
一直很喜欢用这个软件，不过官网首页还停留在去年1月份的版本，之后再也没见发布，不知道后面有没有什么新功能或者新改进

**Comment by miao-2021-5-28** [comment]
I got the same question.

**Comment by MouriNaruto** [comment]
按照现阶段来看的话，估计最多修复 Bug 吧

**Comment by mingkuang-Chuyu** [comment]
如果是提问可以来群里。

应该会有一些Bug修复吧。
