### ISSUE TITLE
开启专家模式与compactos的问题

### ISSUE THREAD

**Issue by masktao** [Chuyu-Team/Dism-Multi-language#882]
开启专家模式后,空间回收默认会开启勾选compactOS的功能
扫描的时候不会开启compactos功能
但扫描完成后,清理空间后
compactos会被自动的开启
![image](https://user-images.githubusercontent.com/13614353/120019742-62d97300-c01b-11eb-88c7-b0bc85174fdf.png)
所以关闭compactos,也能扫描占用的空间?
但清理空间,ccompactos会默认开启这个功能?
我只想关闭compactos功能,清理空间,每次却自动开启compactos

**Comment by mingkuang-Chuyu** [comment]
跟它有什么关系？

如果你不想使用他，那么不要在清理选项中选择 compactos。

如果你需要取消，那么在恢复功能，撤销CompactOS。
