### ISSUE TITLE
清理“被取代的WinSxS组件时”提示"无法执行该操作，因为另一事务取决于此属性将不会更改的事实。"

### ISSUE THREAD

**Issue by HanHan233** [Chuyu-Team/Dism-Multi-language#884]
发布问题的时候请删掉以上内容，我们也不通过格式来限制你们。
# 错误提示
![image](https://user-images.githubusercontent.com/64469437/123037749-c2ac1980-d421-11eb-90b5-3a3a25f56872.png)
# Windows版本
![image](https://user-images.githubusercontent.com/64469437/123037767-ce97db80-d421-11eb-9915-10596b32e0ea.png)
![image](https://user-images.githubusercontent.com/64469437/123037802-dfe0e800-d421-11eb-9e3e-e8b952063969.png)
# 架构信息（AMD64 ）
![image](https://user-images.githubusercontent.com/64469437/123038009-3817ea00-d422-11eb-8e07-7f3108239727.png)

# Logs
[Dism++.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/6698986/Dism%2B%2B.log)
[CBS.log](https://github.com/Chuyu-Team/Dism-Multi-language/files/6698987/CBS.log)

**Comment by HanHan233** [comment]
我在执行
```cmd
Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase
```
之后发现此问题已经解决（可以正常清理）
希望团队能够继续跟进

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/Dism-Multi-language/issues/816

在这个问题中同样被修复，此修改是通用的。
