### ISSUE TITLE
不兼容Windows11

### ISSUE THREAD

**Issue by huangsijun17** [Chuyu-Team/Dism-Multi-language#888]
最新版的11，不论离线还是在线，Windows Update功能的扫描新更新都不用，提示找不到文件。

**Comment by diaosiqz** [comment]
win11 和 win10 结构不太一样  等待开发者适配

**Comment by mingkuang-Chuyu** [comment]
Windows Update功能的扫描新更新都不用，提示找不到文件

这不是一直如此吗？wsuscan库已经停止在线分发了。

参考Release页面


还有其他什么问题吗？如果没有实际的问题我会关闭
