### ISSUE TITLE
Dism++卸载更新时显示操作系统已被严重精简，请放弃该系统

### ISSUE THREAD

**Issue by Igronemyk** [Chuyu-Team/Dism-Multi-language#89]
系统为Windows7 64位旗舰版，安装更新KB4012212过程中出现蓝屏，进入PE使用Dism++卸载更新时显示操作系统已被严重精简，请放弃该系统。

**Comment by EMLVIRUS** [comment]
正如提示所说

> 操作系统已被严重精简，请放弃该系统

**Comment by mingkuang-Chuyu** [comment]
对于6B蓝屏问题 我已经提供了 一键修复工具，你可以加QQ群获取200783396。
另外无法卸载 是因为系统精简过度，这个问题 无解。  谢谢
