### ISSUE TITLE
win11系统  挂载映像失效

### ISSUE THREAD

**Issue by tongshengliule** [Chuyu-Team/Dism-Multi-language#892]
win11系统下 打开软件会提示“C:\MountUUP” 已损坏  按照提示修复 提示“句柄无效”  可以进入软件  常规优化操作以及iso操作都可以正常使用。

右侧会显示“C:\MountUUP” 挂在映像 已经失效。

Diss++x64&x86均会报此错误。

最新下载的官网版本亦无法使用。

**Comment by mingkuang-Chuyu** [comment]
与Dism++无关。
如果需要移除它，可以使用Dism或者wim的强制Cleanup命令（作用就是强制删除所有挂载点）。
