### ISSUE TITLE
無法進行更新掃描

### ISSUE THREAD

**Issue by necro-wbj** [Chuyu-Team/Dism-Multi-language#894]
Windows 10 企業版LTSC x64 更新按下掃描 顯示錯誤:系統找不到指定的檔案
![系統找不到指定的檔案](https://user-images.githubusercontent.com/36947211/126087846-101533f9-1431-4f2d-8ae8-9c96942ddd54.png)

**Comment by mingkuang-Chuyu** [comment]
手工下载wsuscan库。自动更新已经停止维护，因为负担太大了。

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/Dism-Multi-language/issues/899
