### ISSUE TITLE
繁體中文的更新介面變了中東文字

### ISSUE THREAD

**Issue by mic4126** [Chuyu-Team/Dism-Multi-language#90]
![-8](https://cloud.githubusercontent.com/assets/4671533/26110022/a4e99224-3a83-11e7-9e65-aa64699f3e52.PNG)

**Comment by mingkuang-Chuyu** [comment]
谢谢，我跟踪下此问题

**Comment by mingkuang-Chuyu** [comment]
感谢 支持，已经修复。今晚发布新的Beta版解决此问题
