### ISSUE TITLE
检测更新补丁一直失败，校验SHA1发现和提供不符合

### ISSUE THREAD

**Issue by blizzardster** [Chuyu-Team/Dism-Multi-language#901]
wsusscn3.cab 2021-7-14
SHA1： DBC61DE0C8B077655F780BF9EDF103888B3CC2AD
89, 324, 164 Bytes

多次下载，科学和不科学的下载核验的SHA1:SHA1: 5B2F8072918AD6E8FAE6FC323C791CE1AA7F7AF4

**Comment by mingkuang-Chuyu** [comment]
Sha1忘记更新了，你的是对的。5b2f8072918ad6e8fae6fc323c791ce1aa7f7af4
