### ISSUE TITLE
删除nahimic相关驱动及完全禁用

### ISSUE THREAD

**Issue by 957176113** [Chuyu-Team/Dism-Multi-language#903]
win20H2
自动更新一直会打上nahimic驱动无法卸载，无法删除。暴力删除文件也无用，自动会下载。
已知会和腾讯游戏启冲突（判定外挂第三方辅助工具）

**Comment by mingkuang-Chuyu** [comment]
如果DIsm++去删除，那么这属于系统精简。

建议你反馈给腾讯，让他们修复。
