### ISSUE TITLE
Cant mount install.wim it says "no such interface supported" and not exist

### ISSUE THREAD

**Issue by McGuim** [Chuyu-Team/Dism-Multi-language#91]
Here the error "No Such Interface Supported" and not exist

http://i.imgur.com/4zPZMCZ.png

Thats the Install.wim from en_windows_7_ultimate_with_sp1_x64_dvd_u_677332 who i have tested and worked fine in the command line and other soft that opens images

That's just for images, in the operate system that works well.

**Comment by mingkuang-Chuyu** [comment]
Please close rt7lite, then restart Dism++
Best

**Comment by McGuim** [comment]
the rt7 was closed at time, i was just using the same folder for every work to find things faster. But i've restarted the machine, cleared all mounted images and traces by command and now it works flawlessly. Ty for tha answer bt. :D
