### ISSUE TITLE
未来如有大更新的话，建议考虑添加CBS package处理功能

### ISSUE THREAD

**Issue by chrovex** [Chuyu-Team/Dism-Multi-language#913]
最近的开发者，我是DISM++的忠实用户，使用非常顺手，感谢。但是目前DISM++似乎没有显示并操作隐藏的CBS包功能。最近发现一个小软件cbsenum可以填补这方面的空白，功能包括：1.结构化显示所有隐藏的CBS包；2.将CBS包标记可见；3.解除CBS包依赖关联；4.关键词搜索功能。我不知道DISM++是否处于停止开发状态。如果未来大更新的话，可以考虑整合类似功能，该功能极大的减少精简的难度，而且不影响系统完整性，而且我相信你一定可以做的更好！
一下为cbsenum的repo链接：https://github.com/himselfv/cbsenum

**Comment by mingkuang-Chuyu** [comment]
很久以前Dism++的前身（Dism管理器有过类似的功能，但是……做了以后，系统会存在某些问题，即使只是标记为隐藏）

那时更新清理后自动隐藏被固化的更新……

所以这个功能不会跟进，如果更近 那不就是开历史的倒车，重新把问题引入软件。

**Comment by chrovex** [comment]
感谢大佬回复，没有不信，果然是走了各种弯路才有了今天的Dism++
