### ISSUE TITLE
win10更新参数错误

### ISSUE THREAD

**Issue by dtldtt** [Chuyu-Team/Dism-Multi-language#93]
错误提示只有参数错误，其他的都没有，我用win10自动更新好几次了都是安装更新失败，今天用这个软件提示参数错误，到底是怎么回事啊，求解答！！

**Comment by mingkuang-Chuyu** [comment]
WIndows 10 BUG,修复办法 我已经分享到了知乎：
https://zhuanlan.zhihu.com/p/25994994

自己修复吧……
