### ISSUE TITLE
引导修复 不支持NTFS

### ISSUE THREAD

**Issue by msg7086** [Chuyu-Team/Dism-Multi-language#945]
Dism++x64 10.1.1002.1 UEFI
Windows 10 21H1 Pro

系统盘GPT，就一个系统分区 C:，NTFS。
引导分区也是C:。

对C:做引导修复时，手动选中C:，提示「UEFI启动需要FAT16/FAT32分区」。

替代方法是新建一个VHD虚拟磁盘，建立一个ESP分区，然后做修复引导，最后把虚拟磁盘中的文件复制到C盘。

**Comment by mingkuang-Chuyu** [comment]
不支持NTFS作为UEFI的启动分区那不是很正常吗？你需要创建一个esp分区

**Comment by msg7086** [comment]
现在只能创建一个ESP分区，做引导修复，然后再复制到C盘去。

我是不太懂为什么「不支持NTFS作为UEFI启动分区」是很正常的事情。
明明只要把限制去掉就可以支持，偏要加上奇怪的限制不让人从NTFS引导么。
