### ISSUE TITLE
QQ群2个都炸了

### ISSUE THREAD

**Issue by alexblair** [Chuyu-Team/Dism-Multi-language#953]
DISM++ 2个群都找不到了。。。

![image](https://user-images.githubusercontent.com/4616320/146050851-64c5d4f8-232d-4019-8bda-b540e812fab7.png)

**Comment by yinzhefuyun** [comment]
莫名其貌没了

**Comment by tangchuqi** [comment]
官网也打不开了，软件内的官方群按钮也点不了了。包过查看帮助，问题反馈

**Comment by VistaQvQ** [comment]
建议tg备用

**Comment by yinzhefuyun** [comment]
> 建议tg备用

没提供过吧

**Comment by tangchuqi** [comment]
回去找一下那啥玩意。现在没环境

**Comment by AngusChiang** [comment]
？昨天有人举报了？因为吃狗吃鸡？鸭子还有telegram啊？

**Comment by ReadChart** [comment]
到底发生了什么，有无避难所？

**Comment by hijkzzz** [comment]
E 群是什么？有 Telegram 链接吗？

**Comment by mingkuang-Chuyu** [comment]
E群：361689191

Telegram目前在中国无法注册

**Comment by wonchong** [comment]
> 

E 群是什么？有 Telegram 链接吗？

**Comment by lmfreedom** [comment]
整个discord群吧

**Comment by Acpear** [comment]
有无新消息

**Comment by hunandy14** [comment]
為什麼整個網站消失了

**Comment by Acpear** [comment]
https://github.com/Chuyu-Team/Dism-Multi-language/releases/tag/v10.1.1002.1

**Comment by Acpear** [comment]
E群！361689191

**Comment by littlekan-gitee** [comment]
> E 群是什么？有 Telegram 链接吗？

Telegram都进不去[捂脸]

**Comment by XDRSZYHRL** [comment]
走

![00381A7C](https://user-images.githubusercontent.com/59906163/151091547-30b8ba7f-c589-45e6-829b-ecdf53fbf9ec.gif)

或者坐

![0038706C](https://user-images.githubusercontent.com/59906163/151091572-0ee16483-185f-464e-9b37-aa8a4958c202.png)

进Telegram进行资料搜集和知识学习，在中国可以注册，只能在手机App上端注册，可以使用中国手机号码。。。前提先要科学上网。（就跟进谷歌搜索进行资料搜集和知识学习一样）

**Comment by littlekan-gitee** [comment]
> 在Telegram进行资料搜集和知识学习，在中国可以注册，只能在手机App上端注册，可以使用中国手机号码。前提先要科学上网。（就跟进谷歌搜索进行资料搜集和知识学习一样）

怪不得我装的iGG谷歌学术助手没法正常访问Telegram（或许我没开通VIP）
手机用个v2rayNG来科学上网
[教程](https://nice456.com/index.php/2021/07/24/v2rayng/) & [下载链接](https://github.com/2dust/v2rayNG/releases)

**Comment by mingkuang-Chuyu** [comment]
有人乱发消息，群自然就没了。管理员不可能每时每刻都在
