### ISSUE TITLE
空间回收中损坏的AppX，不支持接口能在列表中显示么，出错好难看

### ISSUE THREAD

**Issue by wsldb97532** [Chuyu-Team/Dism-Multi-language#96]
空间回收中损坏的AppX，不支持接口能在列表中显示么，出错好难看

**Comment by mingkuang-Chuyu** [comment]
明白……

**Comment by mingkuang-Chuyu** [comment]
已经调整规则文件，今晚发布新的规则文件

**Comment by wsldb97532** [comment]
ok




发自网易邮箱大师


在2017年05月21日 14:39，mingkuang<notifications@github.com> 写道：

Closed #96.
