### ISSUE TITLE
[安装包]最新版的安装包

### ISSUE THREAD

**Issue by Colin130716** [Chuyu-Team/Dism-Multi-language#965]
最新版安装包(用的是InstallShield):
[Dism++_setup.zip](https://github.com/Chuyu-Team/Dism-Multi-language/files/7868108/Dism%2B%2B_setup.zip)

**Comment by yuyangyi** [comment]
好奇怪，您提供的x64安装包点击安装时出现严重系统故障，无法打开网页，无法打开任务管理器，甚至无法关机，只能强制重启，我的电脑是Microsoft Windows 10 Pro

**Comment by mingkuang-Chuyu** [comment]
不要到这里来发布安装包……

**Comment by layerfsd** [comment]
这种工具还要来制作安装包是什么心态

> 最新版安装包(用的是InstallShield): [Dism++_setup.zip](https://github.com/Chuyu-Team/Dism-Multi-language/files/7868108/Dism%2B%2B_setup.zip)
