### ISSUE TITLE
Command line for VHD cleaning

### ISSUE THREAD

**Issue by Hunter23071985** [Chuyu-Team/Dism-Multi-language#966]
﻿Hey!
Thanks for the great program!
I'll support the [request from FizzyHana](https://github.com/Chuyu-Team/Dism-Multi-language/issues/815).
Many users would like to use VHD cleanup from the command line.
Can this be done in the next release of DISM++?

**Comment by mingkuang-Chuyu** [comment]
我们从 https://github.com/Chuyu-Team/Dism-Multi-language/issues/815 统一的跟踪问题。
