### ISSUE TITLE
[问题] www.chuyu.me 官网无法打开    [Problem] Can't open www.chuyu.me

### ISSUE THREAD

**Issue by littlekan-gitee** [Chuyu-Team/Dism-Multi-language#967]
不知道为什么，官网（www.chuyu.me）没法访问
能帮忙解决这个问题吗？
附：截图：
![image](https://user-images.githubusercontent.com/75866787/149894914-8d7fc9a1-253a-46dc-952e-6835260e5551.png)

English ver:
I don't know why, the official website (www.chuyu.me) cannot be accessed
Can anyone help with this issue?
Attached: Screenshot:
![image](https://user-images.githubusercontent.com/75866787/149895448-08cb261d-94df-4204-82b3-444e9028f800.png)

**Comment by Lemonawa** [comment]
不看release的吗？  
```
由于不可抗力因素 chuyu.me 网站的备案掉了，因此无法访问。
```

**Comment by littlekan-gitee** [comment]
> 不看release的吗？
> 
> ```
> 由于不可抗力因素 chuyu.me 网站的备案掉了，因此无法访问。
> ```

az，我都不常看release
不过因为备案问题，IP被改成localhost专属IP了（GitHub的raw也是127.0.0.1）
