### ISSUE TITLE
［What's your Problem（精神错乱）］初雨官网挂了

### ISSUE THREAD

**Issue by dontknowhy** [Chuyu-Team/Dism-Multi-language#968]
初雨的鸭子网GG了
走的很安详(悲
把鸭子搬github吧，直接拿github.io的服务器当家(

**Comment by dontknowhy** [comment]
PS.cab干嘛用？要把ta放在config下吗？
似乎不放也没什么问题…

**Comment by mingkuang-Chuyu** [comment]
没什么问题，那个只是个数据库

**Comment by littlekan-gitee** [comment]
> > 初雨的鸭子网GG了 走的很安详(悲 把鸭子搬github吧，直接拿github.io的服务器当家(
> 
> 官网备案过期了，IP被改成了127.0.0.1

准确的说备案是gg了

**Comment by lzpong** [comment]
Dism++ 版本还有更新么???

**Comment by dontknowhy** [comment]
> Dism++ 版本还有更新么???

有回复就是有更新，方便面包装写卡路里是包装袋，面饼妹说就是柠卡…
