### ISSUE TITLE
dism++10.1.28.2 Windows Update patch bug

### ISSUE THREAD

**Issue by zerozerone** [Chuyu-Team/Dism-Multi-language#97]
windows 7 x86/x64 sp1
dism++10.1.28.2 Windows Update patch
\system32\drivers
drivers sys files date time Created /modified/accessed was wrong time
time is patching time.

**Comment by mingkuang-Chuyu** [comment]
这个是微软BUG所致，只能等下个大版本进行绕开才能修复。
暂时建议关闭此差异传输引擎解决此问题。

**Comment by mingkuang-Chuyu** [comment]
这个是微软自生BUG，建议反馈给微软。

由于不是Dism++所致，另外Dism已经msu 也统统中枪。另外这个不影响使用，所以就这样去吧……
