### ISSUE TITLE
Win11 Dev 22567.1 备份系统失败

### ISSUE THREAD

**Issue by Doddddd** [Chuyu-Team/Dism-Multi-language#975]
<img width="733" alt="{9B45FDC7-AD05-439B-B673-901C0BA7ABFE}" src="https://user-images.githubusercontent.com/88972478/156571817-f67023fa-176a-4da5-9887-77ce563cc93f.png">

**Comment by mingkuang-Chuyu** [comment]
开启了Linux子系统？提供一下DIsm++的日志看看把，DIsm++目录/Config/Dism++.log

**Comment by Doddddd** [comment]
> 开启了Linux子系统？提供一下DIsm++的日志看看把，DIsm++目录/Config/Dism++.log

已经更换了系统，日志也丢失了
