### ISSUE TITLE
介面顯示問題回報

### ISSUE THREAD

**Issue by kulaLin** [Chuyu-Team/Dism-Multi-language#99]
![sshot-2017-05-22- 6](https://cloud.githubusercontent.com/assets/17091825/26290798/c2fb14ce-3edc-11e7-9a9b-88ad050b4f7f.png)
這裡顯示為簡體。
![sshot-2017-05-22- 7](https://cloud.githubusercontent.com/assets/17091825/26290820/e5434c9a-3edc-11e7-90b6-1993d0f8a2e1.png)
對話框顯示不全。
![sshot-2017-05-22- 8](https://cloud.githubusercontent.com/assets/17091825/26291007/05e8b452-3ede-11e7-9547-355e80845e2d.png)
![sshot-2017-05-22- 9](https://cloud.githubusercontent.com/assets/17091825/26291008/05ef3110-3ede-11e7-9de2-88bd0dd76fec.png)
缺字問題，"像"沒法顯示。

**Comment by mingkuang-Chuyu** [comment]
谢谢……

**Comment by mingkuang-Chuyu** [comment]
Dism++ Beta 10.1.2000.10已经修正此问题
